<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bell</name>
   <tag></tag>
   <elementGuidId>d11f5b04-8e98-4ad6-ad2a-9c74b901eb10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navbar-notification']/li/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.update-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c186308e-2ef7-409c-aba4-46bc2b433c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>update-icon</value>
      <webElementGuid>2eeaddb2-c1bb-4970-a045-40228d4d291e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-notification&quot;)/li[1]/a[@class=&quot;cursor-pointer&quot;]/span[@class=&quot;update-icon&quot;]</value>
      <webElementGuid>e12965de-a999-4bce-ad3a-7d3c7c3b8e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navbar-notification']/li/a/span[2]</value>
      <webElementGuid>497e024a-f69c-4315-a074-8d6c58ad2a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, BOLLORE LOGISTICS HOROZ EDI'])[1]/preceding::span[1]</value>
      <webElementGuid>90968991-1b19-4a2d-bc7b-9adab05c996b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/preceding::span[2]</value>
      <webElementGuid>dc0e747c-fc46-4b6e-b2fb-f2f94f259fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>62dfb5bd-94ab-4ce0-8dc3-88160ddc06b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
