<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notification</name>
   <tag></tag>
   <elementGuidId>5de7aefc-46eb-49cc-80c5-5a597bad3446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navbar-notification']/li/a/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.total-indicateur.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0e625136-ed8f-4646-bdb1-12e0997cafa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total-indicateur ng-star-inserted</value>
      <webElementGuid>0746ab3d-efd5-48da-b89b-3e6dd5234196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>99324b6d-9fc9-43d6-887f-18d8c86ce303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-notification&quot;)/li[1]/a[@class=&quot;cursor-pointer&quot;]/span[@class=&quot;update-icon&quot;]/span[@class=&quot;total-indicateur ng-star-inserted&quot;]</value>
      <webElementGuid>31347558-8882-461d-ab15-539fdb13bc29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navbar-notification']/li/a/span[2]/span</value>
      <webElementGuid>6a4c9a86-ff3a-43de-9eeb-0d6d9b301d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, BOLLORE LOGISTICS HOROZ EDI'])[1]/preceding::span[1]</value>
      <webElementGuid>fe3c9a04-c8b3-4be9-b47f-c8b996030a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/preceding::span[2]</value>
      <webElementGuid>a64d8a3c-bf5b-4589-bc75-396e4fb86cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>1ff3dc82-114f-4ca0-afcf-f0ae712ae845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>e3f92836-521d-40af-9fdf-875da82978bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>1d970784-ad45-4498-9253-020ff105ee13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
