<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description</name>
   <tag></tag>
   <elementGuidId>81cb3556-8495-4fe7-a976-1c7be554ca90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--consolidation-rule-form--description > #dfc-item--consolidation-rule-form--description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--consolidation-rule-form--description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a07d610-fd0a-4165-ab50-43f10b9821eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>a84ab5af-399c-4a18-a7b1-82bac9e786bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--consolidation-rule-form--description</value>
      <webElementGuid>d3967d99-4d9c-45b7-a08c-09102944d2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>6a7c864f-523d-4642-9341-cf3fcd4be512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96a57168-24fc-4ecd-8e28-c021fb41815c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>c4126533-9703-4575-9d0e-acfb9a16f432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--consolidation-rule-form--description&quot;)/div[@id=&quot;dfc-item--consolidation-rule-form--description&quot;]/input[@id=&quot;dfc-item--consolidation-rule-form--description&quot;]</value>
      <webElementGuid>70219d52-0bc9-40ec-8fcb-4ef7256570f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--consolidation-rule-form--description']</value>
      <webElementGuid>120d861f-6711-4a94-98cc-da3660d69020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--consolidation-rule-form--description']/input</value>
      <webElementGuid>713880cb-2776-4d8a-85a6-7adc7fe75afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[20]/div/div/input</value>
      <webElementGuid>8842c061-9dad-46a8-8865-b38ebb1345be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--consolidation-rule-form--description' and @name = 'description' and @type = 'text']</value>
      <webElementGuid>874f3f92-9b42-42fd-ab3b-347fc65151b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
