<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Optimize costs No</name>
   <tag></tag>
   <elementGuidId>5507285c-667f-433f-9f2f-ab850c96b42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--consolidation-rule-form--optimizeCosts--false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--consolidation-rule-form--optimizeCosts--false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41a7401c-4926-4980-8534-c0d37efbf6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>190aee7e-98c1-4abf-bded-be10024dcaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--consolidation-rule-form--optimizeCosts--false</value>
      <webElementGuid>6c313e22-324e-4587-9dc0-80dd8b071547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>0c0e2ce8-fc60-46c6-9ee9-dc87efaeec60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--consolidation-rule-form--optimizeCosts--false&quot;)</value>
      <webElementGuid>ff921b1d-1d9e-4f50-a215-e2bfcc516c65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--consolidation-rule-form--optimizeCosts--false']</value>
      <webElementGuid>d623f094-ce90-4434-b59d-24be17edd0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--consolidation-rule-form--optimizeCosts']/div[2]/input</value>
      <webElementGuid>dc2bbb01-63d0-42b2-b150-d87e03af4fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/df-form-control/div/div/div[2]/input</value>
      <webElementGuid>2d265bc1-36fd-4e37-add9-8df468a4da64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--consolidation-rule-form--optimizeCosts--false']</value>
      <webElementGuid>e4ccb1bb-194e-421d-87d5-92d5a57271cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
