<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Optimize costs Yes</name>
   <tag></tag>
   <elementGuidId>7827d28f-9c7a-4488-950e-7418a7f74e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--consolidation-rule-form--optimizeCosts--true</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--consolidation-rule-form--optimizeCosts--true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef565ed8-dbcb-4b17-8d1c-a296d6957f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6d4fb493-6eda-4ec8-b94d-d74e3c462350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--consolidation-rule-form--optimizeCosts--true</value>
      <webElementGuid>8ee402a4-149f-4272-8461-052aa62bb27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>370fc3e4-5ef7-439c-af70-b0920321c898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--consolidation-rule-form--optimizeCosts--true&quot;)</value>
      <webElementGuid>a8e9ea4d-6b6c-442b-a421-d5a285f7c05b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--consolidation-rule-form--optimizeCosts--true']</value>
      <webElementGuid>075a2794-1547-4bcf-a11f-6eb894dd918e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--consolidation-rule-form--optimizeCosts']/div/input</value>
      <webElementGuid>c0b3051d-f900-4b5d-9abc-5430b1bd9009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/df-form-control/div/div/div/input</value>
      <webElementGuid>2df67218-366b-4014-8047-e4fb1f347403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--consolidation-rule-form--optimizeCosts--true']</value>
      <webElementGuid>12bf0873-e8ab-4c12-9587-1268bd0ec2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
