<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enable Yes</name>
   <tag></tag>
   <elementGuidId>261c8021-a4b6-4634-b37f-eae8d5ee75d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--consolidation-rule-form--enabled--true</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--consolidation-rule-form--enabled--true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01a8ef2d-bfbd-4092-84c9-271106a09fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>53dbf3eb-c8f0-4ef2-b3dc-39dea53dd7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--consolidation-rule-form--enabled--true</value>
      <webElementGuid>3cb60c07-259e-47e5-a69d-27aaf29ea200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-dirty ng-touched</value>
      <webElementGuid>f49661cf-8652-4761-9271-cf3812be3392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--consolidation-rule-form--enabled--true&quot;)</value>
      <webElementGuid>56915535-d30d-4a6a-9e66-b80e44d68f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--consolidation-rule-form--enabled--true']</value>
      <webElementGuid>612bb48d-c239-419f-b3f4-095cee055515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--consolidation-rule-form--enabled']/div/input</value>
      <webElementGuid>8c0eab84-72d7-4936-ae5f-1a134ee9c6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[19]/div/div/div/input</value>
      <webElementGuid>37a2107b-0e90-425e-912f-27f0a45bdc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--consolidation-rule-form--enabled--true']</value>
      <webElementGuid>d46c0b06-a23f-467d-a3b0-40564760f9b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
