<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title</name>
   <tag></tag>
   <elementGuidId>1f0c6c23-ba1e-43fb-b538-b4604d89dac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--consolidation-rule-form--title > #dfc-item--consolidation-rule-form--title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--consolidation-rule-form--title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00ff3b7b-eba5-4b37-a6fa-0024277fdb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>4ad6ae9a-d223-4dad-9cec-d32c0f0e0722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--consolidation-rule-form--title</value>
      <webElementGuid>e08e5cb1-c24e-4f6c-a268-4a99d0b1828f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>a26d7156-beb2-49f8-bed4-f68325f8cd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>897d0402-985c-4c2e-9f07-7fad09cb2ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>0a59d23a-8f03-49b0-a410-f7103f6fed9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--consolidation-rule-form--title&quot;)/div[@id=&quot;dfc-item--consolidation-rule-form--title&quot;]/input[@id=&quot;dfc-item--consolidation-rule-form--title&quot;]</value>
      <webElementGuid>d3513a43-7d38-46e2-b8f1-f2cc4714d4ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--consolidation-rule-form--title']</value>
      <webElementGuid>91d59a5a-48f2-4846-a22d-0fa209dee843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--consolidation-rule-form--title']/input</value>
      <webElementGuid>0e454109-8d77-4d14-9d0a-0c7468939800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[17]/div/div/input</value>
      <webElementGuid>5493cfe2-3d8e-4b67-a377-2819857cb2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--consolidation-rule-form--title' and @name = 'title' and @type = 'text']</value>
      <webElementGuid>3935f9dc-f84d-43fe-afad-58fff92bc516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
