<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Export</name>
   <tag></tag>
   <elementGuidId>2f38c1b8-d57d-47d3-b725-d818992d9509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='actionbutton-export']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionbutton-export</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32b74f49-89f3-4cb7-b284-2ab7245d2846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-primary ng-star-inserted</value>
      <webElementGuid>e29839c3-ffaf-4b17-93e9-bbf0ccdc872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionbutton-export</value>
      <webElementGuid>7a43f9bc-563e-4d99-b14d-99535438d56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export</value>
      <webElementGuid>b04680de-8a55-453b-8f8d-ad82dd45a02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionbutton-export&quot;)</value>
      <webElementGuid>114cec65-2b5b-4f52-bebe-b4997a803b79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='actionbutton-export']</value>
      <webElementGuid>61465408-85d0-4c88-a649-e94d329dac1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/div/app-action-bar/div/div[3]/app-action-buttons/div/div[2]/button</value>
      <webElementGuid>26898967-0aee-4cdb-b8ad-b4d2002a98bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESC-S16845 (test060904, test060905)'])[1]/following::button[1]</value>
      <webElementGuid>01cb9ef5-7500-49bc-b371-a2f0bc12c5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::button[1]</value>
      <webElementGuid>d87cb4ba-15c6-4ede-b56d-3d1261d330a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm pending'])[1]/preceding::button[1]</value>
      <webElementGuid>333842b0-f2e8-4ed8-b881-a30ae3681d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3cb1470a-4376-40a1-8d4e-171c1a3583d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'actionbutton-export' and (text() = 'Export' or . = 'Export')]</value>
      <webElementGuid>65ad3b71-71c1-4c2b-af8e-f7353a40efe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
