<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Download</name>
   <tag></tag>
   <elementGuidId>cd44f138-b446-4ec0-be54-ccc9f5b53889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='actionDownload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;actionDownload&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29e3a305-7aeb-4c11-8ad0-15978b54ec5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52efbaf2-1e0a-4426-a143-541edd41a943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionDownload</value>
      <webElementGuid>a080bffa-8d3a-44f7-bd4d-5260c6f669fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-effect ng-pristine ng-valid ng-touched</value>
      <webElementGuid>28d4d4b9-bb9b-495b-b7b6-03f1ce15714c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-modal-export-doc-by-template[1]/div[@class=&quot;modal modal-backdrop modal-export-doc-tpl-root loader-content-container transparent-dark-loader&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;modal-body overflow-visible&quot;]/div[@class=&quot;row margin-top-10&quot;]/div[@class=&quot;col-xs-9 col-md-8 text-left&quot;]/div[1]/input[@class=&quot;no-effect ng-pristine ng-valid ng-touched&quot;]</value>
      <webElementGuid>3c3ff768-347f-4ca0-85e1-87a727590290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='actionDownload']</value>
      <webElementGuid>3bcd84d2-4bc2-4b84-bee0-668b50ac95e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-details/div[2]/app-modal-export-doc-by-template/div/div/div/div/form/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>3d20f2eb-877c-4efb-97ae-e1f731f0a2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>2d6eba8e-8065-434f-93ca-2db4b284e6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'actionDownload']</value>
      <webElementGuid>4a572244-37a0-460e-bb5c-b4e217cf3d9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
