<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_Exported</name>
   <tag></tag>
   <elementGuidId>d78c012d-252a-420b-a710-a191a38355a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'ellipsis-item text-center') and contains(@title, 'ESC')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>993c41d7-7099-47f0-b275-6ca2e592d627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ellipsis-item text-center</value>
      <webElementGuid>2a14d476-48df-4ed6-95ff-88255995e3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ESC-S16845_BC_14.pdf</value>
      <webElementGuid>3dc67f64-a793-47a1-a212-23955110b339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ESC-S16845_BC_14.pdf </value>
      <webElementGuid>d4f0492b-e8d3-4465-a0ff-563d05123ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileDropContainer-147&quot;)/div[@class=&quot;col-md-12 padding-0&quot;]/div[@class=&quot;col-md-12 padding-0 document-zone&quot;]/div[@class=&quot;padding-0 margin-0 col-md-12&quot;]/div[@class=&quot;padding-0 col-md-12&quot;]/div[@class=&quot;col-md-12 col-xs-12 padding-0-important uploaded-files ng-star-inserted&quot;]/div[@class=&quot;existed-items&quot;]/div[@class=&quot;existed-item ng-star-inserted&quot;]/span[@class=&quot;filename d-flex-ai-c&quot;]/div[@class=&quot;ellipsis-item text-center&quot;]</value>
      <webElementGuid>85c5c2b4-e29d-4748-a171-015821097fd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fileDropContainer-147']/div/div/div[2]/div/div/div/div[2]/span/div</value>
      <webElementGuid>677d4c81-9b8a-48c4-b990-93bb3cec79d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testChanel.txt'])[1]/following::div[2]</value>
      <webElementGuid>209d3820-2d13-4257-93cf-22e0631332ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/following::div[8]</value>
      <webElementGuid>2938ac98-ada1-4024-b27c-674ce33c2b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Restriction Visibility'])[1]/preceding::div[2]</value>
      <webElementGuid>cb29eaf0-6a28-44bd-aaa5-fae1d43bae22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[2]/preceding::div[3]</value>
      <webElementGuid>098e398c-1a08-4854-90c9-75f7f0127738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESC-S16845_BC_14.pdf']/parent::*</value>
      <webElementGuid>cdda6c27-d6b6-4c42-96e7-f7c7e068c5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div</value>
      <webElementGuid>180343b7-e377-4583-b33c-46a6ae161988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'ESC-S16845_BC_14.pdf' and (text() = ' ESC-S16845_BC_14.pdf ' or . = ' ESC-S16845_BC_14.pdf ')]</value>
      <webElementGuid>b74eeb22-145f-4d7a-8a43-259c98b877f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
