<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PDF_formatPDF</name>
   <tag></tag>
   <elementGuidId>6781dec8-e8c8-41a1-ac7c-7a025b7979f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='formatPDF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;formatPDF&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2efd9b04-10ce-4793-950d-fd9ff3ed9b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>12c147a0-b130-4b0e-a605-d4ff8e0e541b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formatPDF</value>
      <webElementGuid>8f5f7754-7775-43ef-a5fe-7208f8e1f1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-effect ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>35a9a05d-895a-4c5f-8c90-9e1702c19d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-modal-export-doc-by-template[1]/div[@class=&quot;modal modal-backdrop modal-export-doc-tpl-root loader-content-container transparent-dark-loader&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;modal-body overflow-visible&quot;]/div[@class=&quot;row margin-top-10&quot;]/div[@class=&quot;col-md-8 col-xs-9 text-left&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-xs-5&quot;]/label[1]/input[@class=&quot;no-effect ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>24349ab4-2fda-4890-91ee-cd3a16c3cd95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='formatPDF']</value>
      <webElementGuid>23d35764-77c0-400c-bba7-d84541b84fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-details/div[2]/app-modal-export-doc-by-template/div/div/div/div/form/div[2]/div[2]/div[2]/div/div/label/input</value>
      <webElementGuid>c91f1c8d-0722-4e97-aa18-132f519a2566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>ba5b065f-5b51-411c-a770-96df2cbeeb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'formatPDF']</value>
      <webElementGuid>82a3ee34-7793-404a-a67a-794bdd917f4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
