<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Word (.docx)_formatWORD</name>
   <tag></tag>
   <elementGuidId>b5536ad8-713f-4e89-ab6b-43c439d61782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='formatWORD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;formatWORD&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4d5fbf8-655f-4ef1-b5b5-34d448b0dbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3370ce8e-c67d-4d56-a071-e0c16ed9e99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formatWORD</value>
      <webElementGuid>1524e6bd-1f4f-4345-839d-fc0d6c4b6972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-effect ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b45fe5af-4550-4b0d-846e-5dcebeb32bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-modal-export-doc-by-template[1]/div[@class=&quot;modal modal-backdrop modal-export-doc-tpl-root loader-content-container transparent-dark-loader&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[1]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;modal-body overflow-visible&quot;]/div[@class=&quot;row margin-top-10&quot;]/div[@class=&quot;col-md-8 col-xs-9 text-left&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-xs-7&quot;]/label[1]/input[@class=&quot;no-effect ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>1ccc4850-8ea9-4a48-bc4c-07ea92b77f02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='formatWORD']</value>
      <webElementGuid>7adff050-f579-4c62-acb1-af23311bbd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-details/div[2]/app-modal-export-doc-by-template/div/div/div/div/form/div[2]/div[2]/div[2]/div/div[2]/label/input</value>
      <webElementGuid>a1abb181-e7ca-4013-a53e-c09974739ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>a28b5c8c-929d-4a81-b64b-16bd14843d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'formatWORD']</value>
      <webElementGuid>86b60c53-3582-4e4d-96d6-29b767d57778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
