<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Template</name>
   <tag></tag>
   <elementGuidId>f01a1684-d69b-44e9-ab56-d4f010456f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;ng-option ng-star-inserted&quot;][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ae102b403be0-2 > div.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f70f75c-5582-4e47-87f9-7d3f321acebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>fbd74da9-494e-427b-9f6f-3bc9c4e45e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Bon de Chargement </value>
      <webElementGuid>a1754237-cac6-4b25-ac33-ccccb87ceb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ae102b403be0-2&quot;)/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>0a0f25b1-8845-4146-b1e6-b436fc988155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ae102b403be0-2']/div</value>
      <webElementGuid>7467711c-0d77-4b22-8802-7c894acad3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attestation de Vente'])[1]/following::div[2]</value>
      <webElementGuid>1e75e2d3-9d73-4e84-810b-dd06906f617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATR'])[1]/following::div[4]</value>
      <webElementGuid>06e40f61-0e79-4fb6-9e2a-1777ffb23aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Certificat d', &quot;'&quot;, 'origine')])[1]/preceding::div[1]</value>
      <webElementGuid>deffba50-5e39-4ff2-a189-8e04e2c9d183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DDT EU'])[1]/preceding::div[3]</value>
      <webElementGuid>9bdb3a7d-4cf7-440d-822f-89cc6d94ee43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bon de Chargement']/parent::*</value>
      <webElementGuid>3963d481-34d0-4562-bbd0-4a6a9ace7f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[3]/div</value>
      <webElementGuid>01c65abe-1974-4dff-8461-28e294b7ec62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Bon de Chargement ' or . = ' Bon de Chargement ')]</value>
      <webElementGuid>518c2b52-b77b-42b6-aded-26510df3932d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
