<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BC</name>
   <tag></tag>
   <elementGuidId>6aea0df6-3ef0-4cd1-9d66-78bcc6ee02f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;ng-option ng-option-marked ng-star-inserted&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a049642afe2d-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d30c95e7-bcbc-4209-b3d4-d0f4fbe490d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>6fd0d407-0e79-4950-8a15-1a0f72313386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>469751bb-a006-4a56-b4c7-cb0b4803e12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>93799626-9450-4b4c-8dae-077a8d606b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a049642afe2d-0</value>
      <webElementGuid>d99502c8-f62d-45a4-82d5-412e7ed95415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BC</value>
      <webElementGuid>f0e1ddbc-ea3b-45c7-8dc0-c8481e6de922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a049642afe2d-0&quot;)</value>
      <webElementGuid>a2afb903-3d2d-437a-b874-3aaa9a96a975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a049642afe2d-0']</value>
      <webElementGuid>908b31c1-e58a-4d9a-94a9-03fcb17a937b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a049642afe2d']/div/div[2]/div</value>
      <webElementGuid>1ddd21a9-d65d-4de1-b8be-19e071e391dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select documents type...'])[1]/following::div[5]</value>
      <webElementGuid>522e1fa8-66ca-4c6d-b091-3b1823249866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::div[1]</value>
      <webElementGuid>4c141765-fb02-41fc-bd3e-3a4b93ed9dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>ad5d822d-8937-4709-9364-8e60fda83440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a049642afe2d-0' and (text() = 'BC' or . = 'BC')]</value>
      <webElementGuid>0955f90e-43bb-48dd-8961-15555ba37c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
