<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add_Transportation plans</name>
   <tag></tag>
   <elementGuidId>ee122123-5a81-4910-bea7-90ba136e4c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='header-button-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-button-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8fc7e667-509d-423a-b4a4-3f24b5709fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>b795910c-1b4e-4571-ad38-a16e4d3df5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-button-0</value>
      <webElementGuid>e11f763b-4466-4730-afc2-09d3cf859e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-square-o ng-star-inserted</value>
      <webElementGuid>b65f2ab8-54ab-41ce-bbf4-4cc842b8965a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-button-0&quot;)</value>
      <webElementGuid>91f0893a-b647-4db5-b022-d3d6cc0e7576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='header-button-0']</value>
      <webElementGuid>eca4bd7f-76ff-4cb8-adce-ead1cfd03406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-transport-plans/div/app-list-header-buttons/div/div/div/i</value>
      <webElementGuid>dc1c8fc2-c1fc-4bb2-93f4-171f3e69d494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>01188adf-7c54-46f0-9ac2-75a76af14a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Add' and @id = 'header-button-0']</value>
      <webElementGuid>8a2977a9-3de8-42d8-9db5-d5a13eabc422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
