<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Seconde Field Output</name>
   <tag></tag>
   <elementGuidId>e4255407-2aca-4ce2-b8d6-41dc2082c57f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//app-create-transport-plans//app-ng-select-form//ng-select//input)[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afad214c-a1ae-4c43-bc6a-b9de0292bc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>40b61869-07a8-4592-b6af-30c81f09fb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7822cf46-ae1a-48b4-9db7-8e1d310e8e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ea83e87b-5ebc-4621-98db-20355b1a053e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>338f68c6-7222-44c9-a870-3f4ed0d5ad94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a83a4dbe459b</value>
      <webElementGuid>a1b59b35-e604-4708-bbd6-da5de2eba2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>453a413c-a75f-4fc6-8f8a-7eb352594ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a83a4dbe459b</value>
      <webElementGuid>bd33c0c8-3ecb-45f8-9d0d-254e17cc8caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a83a4dbe459b-0</value>
      <webElementGuid>71b61294-3963-4885-bda9-a6c53934b6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;aurora-theme&quot;]/body[@class=&quot;background app-wrapper aurora-theme modal-open&quot;]/ngb-modal-window[@class=&quot;d-block fade modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/app-create-transport-plans[1]/div[@class=&quot;m-ngb-modal&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;margin-5&quot;]/app-fill-field-form[1]/div[@class=&quot;margin-10 row ng-star-inserted&quot;]/div[@class=&quot;col-md-11 row&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-6 ng-star-inserted&quot;]/app-ng-select-form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/ng-select[@class=&quot;m-fz-s ng-select ng-select-single ng-select-searchable ng-select-clearable ng-untouched ng-pristine ng-valid ng-select-opened ng-select-top ng-select-focused&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>ab0fab86-de03-460d-8e19-d81ab0d74630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[10]</value>
      <webElementGuid>3e0c0295-ef1a-40b8-bcaf-9afcaccacd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div/div/div[2]/input</value>
      <webElementGuid>9c5c61a7-31b2-46ca-968e-2754d17673c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>8dd72a32-d4f9-42d0-bcc8-546791ce8825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
