<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference Transportations Plans Dashboard</name>
   <tag></tag>
   <elementGuidId>1149c3d2-7ed4-4836-b46b-26cbe869aa38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@class=&quot;ag-input-field-input ag-text-field-input&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-768-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36f369c5-a4c7-4fd7-b0f8-fff06185436d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>02706946-348b-4a89-8971-9218173f66ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>269476d2-252b-4e34-9cbd-80ffb53570db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80133a1b-a66e-4606-9d43-6be479fc64cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-768-input</value>
      <webElementGuid>7f18cc7d-1ac2-49f3-aa5a-7d309a9a7c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Reference Filter Input</value>
      <webElementGuid>e7b750b7-175a-4950-885c-3d78e02185a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-768-input&quot;)</value>
      <webElementGuid>e4e2a9df-b587-49dd-a432-2faafe2cb83a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@class=&quot;ag-input-field-input ag-text-field-input&quot;])[1]</value>
      <webElementGuid>098a329d-e5ca-485c-a870-5a3afc50e88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-transport-plans/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>1fabc148-3e0c-4fb5-a491-6438b77ef98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>1387bf6b-1b71-4948-963e-089cf368d312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-768-input']</value>
      <webElementGuid>f4f0f386-dc59-428a-8966-7f9f2a005d53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
