<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__First Field Input</name>
   <tag></tag>
   <elementGuidId>e3710288-6518-46af-b449-691a2a2afe8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//app-create-transport-plans//app-ng-select-form//ng-select//input)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.ng-star-inserted > app-ng-select-form > div.row > div.col-md-8 > ng-select[name=&quot;selectForm&quot;] > div.ng-select-container > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>260b343e-3373-4e51-978e-c7218ae487cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>94cfbe6e-74a0-47a3-8cf0-e516fcd22cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>805cf707-c0ed-45cf-a955-95d5f4693b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>06d1ceea-823a-4fba-b5f8-700ceb332cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4bd3ac15-a426-411d-be60-01d38ad9b68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a8093d7ed96c</value>
      <webElementGuid>cc170cd9-6136-4215-9469-c4fbf72cf4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4cce13bd-cc0c-4969-b593-909536c80dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a8093d7ed96c</value>
      <webElementGuid>bd2b2075-ebe1-41af-9d98-01ee9396a3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a8093d7ed96c-0</value>
      <webElementGuid>5c84e1a7-9929-4d0e-82a2-395052ccb075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;aurora-theme&quot;]/body[@class=&quot;background app-wrapper aurora-theme modal-open&quot;]/ngb-modal-window[@class=&quot;d-block fade modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/app-create-transport-plans[1]/div[@class=&quot;m-ngb-modal&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;margin-5&quot;]/app-fill-field-form[1]/div[@class=&quot;margin-10 row ng-star-inserted&quot;]/div[@class=&quot;col-md-11 row&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-6 ng-star-inserted&quot;]/app-ng-select-form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/ng-select[@class=&quot;m-fz-s ng-select ng-select-single ng-select-searchable ng-select-clearable ng-pristine ng-valid ng-select-focused ng-select-top ng-touched ng-select-opened&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>fa6611b8-f876-4ee8-a58c-8e2c8e356e3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>5b16d872-4dfa-4b93-8f0b-3c3ab85be2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div/div/div[2]/input</value>
      <webElementGuid>067360ae-03f1-48d3-9076-953523828db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>3e8f82a4-f074-432b-ae00-518c8b0c8491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
