<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Value Output</name>
   <tag></tag>
   <elementGuidId>b4b8c4f3-d138-4bd3-97e0-2f221d11585a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//app-create-transport-plans//app-ng-select-form//ng-select//input)[5]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d89499ea-d786-45a3-b23e-6d2ce05399a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>d2f050bd-f9ad-4af9-8b7d-326e96a2d996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c6e2c70-fbc0-451e-92e4-171e6bbb1b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c69aaecf-ad79-41ea-8cc2-1c76edd25ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b423b2a-5a3b-44df-9d7f-3bd141817f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a0c459ebe165</value>
      <webElementGuid>4ac17b63-be33-4fb3-abef-b9d9f2a3f395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a559b89f-bd19-4d8f-9fb3-e427f469c4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a0c459ebe165</value>
      <webElementGuid>b3bb6403-b7c6-44dc-a1c3-24c9067f570a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;aurora-theme&quot;]/body[@class=&quot;background app-wrapper aurora-theme modal-open&quot;]/ngb-modal-window[@class=&quot;d-block fade modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/app-create-transport-plans[1]/div[@class=&quot;m-ngb-modal&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;margin-5&quot;]/app-fill-field-form[1]/div[@class=&quot;margin-10 row ng-star-inserted&quot;]/div[@class=&quot;col-md-11 row&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-6 ng-star-inserted&quot;]/app-ng-select-form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/ng-select[@class=&quot;m-fz-s ng-select ng-select-multiple ng-select-taggable ng-select-searchable ng-select-clearable ng-untouched ng-pristine ng-valid ng-select-opened ng-select-bottom ng-select-focused&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>9c3ed8a8-fa4b-41a1-b3f7-35f49392fd54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//app-create-transport-plans//app-ng-select-form//ng-select//input)[5]</value>
      <webElementGuid>77596a5b-b4a3-448c-b277-f1fcf928e8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/app-ng-select-form/div/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>273a2f63-7eb9-4f83-a90d-a4685ad17e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>1bb22f53-e287-4410-b2f7-840f524b140c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
