<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pending</name>
   <tag></tag>
   <elementGuidId>bdaef185-027e-4d43-8eb9-e16bf748c9e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formStatusBar-chip-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formStatusBar-chip-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff585932-a6eb-42fc-a99f-b08f953c9c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formStatusBar-chip-text</value>
      <webElementGuid>8b44d601-7ad7-4951-ba21-56efecb1b36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chip ng-star-inserted</value>
      <webElementGuid>3f636d8a-87e3-4832-b35a-a91b8165ad44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pending </value>
      <webElementGuid>ce818ea3-70b4-4a61-ba58-2d3cfe62cc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formStatusBar-chip-text&quot;)</value>
      <webElementGuid>2cbbb1ea-d17d-4a75-9b45-08d55e9be6cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='formStatusBar-chip-text']</value>
      <webElementGuid>cc26f7ba-c013-44bb-b132-7b72cab18fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formStatusBar-chip']/div</value>
      <webElementGuid>ec634b93-531b-47b4-8daf-79c388a4a3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/following::div[9]</value>
      <webElementGuid>8d5f84d4-df2e-40f2-bf6f-676433cd6de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alerts'])[1]/following::div[9]</value>
      <webElementGuid>3135f87c-d65c-436e-9166-8a39a3d6a59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate pending or confirm quote file to start process'])[1]/preceding::div[1]</value>
      <webElementGuid>74f427e0-0ffb-4b66-b524-b2aceb6977df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping informations'])[1]/preceding::div[3]</value>
      <webElementGuid>bd51a0ee-f2e6-4d34-a35f-72f9553b24c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pending']/parent::*</value>
      <webElementGuid>ec35684a-c77f-4d4e-bfb2-4f3a5e6b77f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-form-statusbar/div/div/div</value>
      <webElementGuid>cc626b0c-4965-43fc-b69a-c93dc74f1dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'formStatusBar-chip-text' and (text() = ' Pending ' or . = ' Pending ')]</value>
      <webElementGuid>3b60df70-821a-4676-bbf2-becaf764d9c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
