<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Module</name>
   <tag></tag>
   <elementGuidId>7c3bb0f3-311c-42b4-bc9e-adf862f99841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--edit-status-transition-form--module > #dfc-item--edit-status-transition-form--module</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--edit-status-transition-form--module']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0bcb1762-5600-4970-86bd-4eb77f20a1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--edit-status-transition-form--module</value>
      <webElementGuid>3ef7a3f4-3e57-49cc-aefe-653325ef364c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>module</value>
      <webElementGuid>5a8356b5-35a7-4a80-a84e-4f206eb52857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>505d0f4d-41ef-4a0d-89a5-013342cbeacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transport requestPricingDeliveryOrder</value>
      <webElementGuid>3e5afa7f-97a0-4d8a-9218-fd49745a04b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--edit-status-transition-form--module&quot;)/div[@id=&quot;dfc-item--edit-status-transition-form--module&quot;]/select[@id=&quot;dfc-item--edit-status-transition-form--module&quot;]</value>
      <webElementGuid>a565d2da-f787-4aef-9498-19aacb97416a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--edit-status-transition-form--module']</value>
      <webElementGuid>273dcc28-fda8-46f5-94bd-c7919ae5e642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--edit-status-transition-form--module']/select</value>
      <webElementGuid>82de367b-d2f4-455d-99bb-189be8727dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module'])[2]/following::select[1]</value>
      <webElementGuid>63a3b704-b81b-484d-9b7f-44ee2d7e4962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ce champs est obligatoire'])[1]/following::select[1]</value>
      <webElementGuid>371e0e65-bff5-4eca-8240-31c21e2e5cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination Status'])[2]/preceding::select[1]</value>
      <webElementGuid>c6340351-1b9e-4be6-be83-10e87c8cfc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::select[2]</value>
      <webElementGuid>caee4690-bc69-4c2f-8568-41d8cc023d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ab5918ea-8e6d-4630-ab0c-477b9343b77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--edit-status-transition-form--module' and @name = 'module' and (text() = 'Transport requestPricingDeliveryOrder' or . = 'Transport requestPricingDeliveryOrder')]</value>
      <webElementGuid>62839e1c-b9d5-4a67-a7cf-82f041b0d460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
