<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Volume</name>
   <tag></tag>
   <elementGuidId>c5500ef8-f919-475a-a4b4-fdcfb050311b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--totalVolume > #dfc-item--transport-packaging-content-form--totalVolume</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--totalVolume']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fea2d12-861b-42d8-89a4-6931ee401f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>5b88e72e-72e7-4b86-820b-33140ed78701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--totalVolume</value>
      <webElementGuid>52e38fd3-3411-47e8-8088-023b5b6140a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a9664108-cf01-42d5-89b9-423214177431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>totalVolume</value>
      <webElementGuid>8a6d13d0-2945-4008-9afd-2ec87b6d6207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Total volume (m3)</value>
      <webElementGuid>f939d303-9278-4205-afe6-6927ba8227f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6e074d1b-5681-4d4e-ad8f-3f0c38482110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>48921455-b887-4dfa-8621-16f485d9c095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--totalVolume&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--totalVolume&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--totalVolume&quot;]</value>
      <webElementGuid>7069907f-b39a-4e17-9248-9b76b94ab995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--totalVolume']</value>
      <webElementGuid>a033b607-e4d1-4d3b-8432-f1570b26047e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--totalVolume']/input</value>
      <webElementGuid>7df12da8-71dd-4fd0-ad04-8456ab417219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[15]/div/div/input</value>
      <webElementGuid>a783cdcb-3538-4056-8bfd-190e36029fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--totalVolume' and @name = 'totalVolume' and @placeholder = 'Total volume (m3)' and @type = 'number']</value>
      <webElementGuid>eec4471d-8566-4a7c-9596-05685a4489dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
