<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Final ShipTo Zip Code</name>
   <tag></tag>
   <elementGuidId>56c37584-c961-4b3a-a79e-5383e7295a1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging > #dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc004205-7486-4baa-a1e0-9d7051a84dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>81f7247a-370d-48a9-a380-19ec0636f687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging</value>
      <webElementGuid>e9b7e2b6-8ecc-4a83-8e39-58ff1c74198e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_final_shipto_zip_code_packaging</value>
      <webElementGuid>5c0756c7-c1be-4c58-849c-33d32086ee50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Final ShipTo Zip Code</value>
      <webElementGuid>6cf843ef-5be1-4639-8cb8-04e49b156f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a27d324-cdd2-4ccd-b866-e165c27bfcac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>8fdd5a6e-137e-412b-979b-cc977a7c4411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging&quot;]</value>
      <webElementGuid>5002068a-6c35-47da-a0bb-040b883484c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging']</value>
      <webElementGuid>011f8f41-7268-4f38-9808-fe944a95c83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging']/input</value>
      <webElementGuid>5acac6eb-31bd-44da-a35a-3da541d41609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[47]/div/div/input</value>
      <webElementGuid>719fcc3b-8ff7-40af-be85-6c05be377067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_final_shipto_zip_code_packaging' and @name = 'parcel_final_shipto_zip_code_packaging' and @placeholder = 'Parcel Final ShipTo Zip Code' and @type = 'text']</value>
      <webElementGuid>0e905dce-08a7-41c3-a64f-0f677b231ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
