<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice Total Gross Weight KG</name>
   <tag></tag>
   <elementGuidId>a7813239-13e3-4c0d-919f-9d04be7f77c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging > #dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e93743b-5fb7-4869-8e52-8c2ecec393e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>95ca7d29-6f0c-43f2-b9b9-d3b58e2e3589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging</value>
      <webElementGuid>f73e61d6-1a15-427f-a836-1d12eeab5baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_total_gross_weight_kg_packaging</value>
      <webElementGuid>2e5a6338-f99e-4097-a56c-dbdc285e984a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice Total Gross Weight KG</value>
      <webElementGuid>fa7d367e-41f0-480a-a69d-3538b6f8f9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b480ea9e-be02-4d3f-9ff0-ca0050cbe2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>138cc3af-0cf7-41e6-aa25-6c47b2ecb374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging&quot;]</value>
      <webElementGuid>9356f103-6860-4e5d-a65d-f0fbdf4a69a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging']</value>
      <webElementGuid>15f3538d-cfa3-4aaf-89e6-5f395ca33969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging']/input</value>
      <webElementGuid>4a283a8c-58c5-4a9e-b405-859d9d48b9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[72]/div/div/input</value>
      <webElementGuid>a66639da-567a-499b-a513-d6b45434e8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--invoice_total_gross_weight_kg_packaging' and @name = 'invoice_total_gross_weight_kg_packaging' and @placeholder = 'Invoice Total Gross Weight KG' and @type = 'number']</value>
      <webElementGuid>72441b4d-6865-42f0-a8aa-e652aa99b48a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
