<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Final Ship To Company Code</name>
   <tag></tag>
   <elementGuidId>8cfcff4c-3a65-4e71-aa3d-7933d2535105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging > #dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>030770a8-5cfe-4b11-b920-a13d5a65274b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>0847391a-4c2e-4761-9ed8-2285764582a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging</value>
      <webElementGuid>132ca7aa-5d86-49e3-b3b0-81f853611a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_final_ship_to_company_code_packaging</value>
      <webElementGuid>7a1c1842-7e8e-4ac6-a4b9-f96cf0350f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Final Ship To Company Code </value>
      <webElementGuid>b9d63d94-2b22-414c-94a1-acfda824047d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b226c69d-639c-4cf4-acbd-2957a03bcf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>e7b9dad0-8327-4649-be1a-dbae1a8d1678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging&quot;]</value>
      <webElementGuid>59d6bbe1-2fb1-4dc6-b59b-bced3c55be53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging']</value>
      <webElementGuid>eea3faf9-38d8-430c-9f7c-68e7fc4e91d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging']/input</value>
      <webElementGuid>5370afc0-3b15-4ec2-8105-3b12ab141e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[41]/div/div/input</value>
      <webElementGuid>3f299f63-3b5a-4fe1-87c9-c0a15713a046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_final_ship_to_company_code_packaging' and @name = 'parcel_final_ship_to_company_code_packaging' and @placeholder = 'Parcel Final Ship To Company Code ' and @type = 'text']</value>
      <webElementGuid>89a78403-7f88-4fef-b02c-31a010d5443f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
