<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delivery Note</name>
   <tag></tag>
   <elementGuidId>d946e5da-5b5b-45af-843d-1596055b2f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--delivery_note_packaging > #dfc-item--transport-packaging-content-form--delivery_note_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--delivery_note_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c044e583-a78d-4dae-8904-9eef7a29689b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>597f5e11-4754-4036-93c6-0c74480efd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--delivery_note_packaging</value>
      <webElementGuid>98f6c2bf-5676-474d-81e8-76273564b3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_note_packaging</value>
      <webElementGuid>1ad0cbe8-308d-49a0-9be5-1daadf2bfecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Delivery Note</value>
      <webElementGuid>91d739b8-61d4-4554-9b5a-6d1785be8757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>606aca9e-82d9-444a-b51d-f5fdbbbdfa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>c660731d-7a0c-4aba-8404-6b5b208ae656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--delivery_note_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--delivery_note_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--delivery_note_packaging&quot;]</value>
      <webElementGuid>bbe9b3a1-fc76-4bfd-a4b2-86453609bed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--delivery_note_packaging']</value>
      <webElementGuid>87eb027b-224d-4e80-a72b-37fce516c306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--delivery_note_packaging']/input</value>
      <webElementGuid>76b4bda8-2d13-405f-b59b-13c2a69c3017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[31]/div/div/input</value>
      <webElementGuid>cec466bf-4307-469c-851d-d0a229298978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--delivery_note_packaging' and @name = 'delivery_note_packaging' and @placeholder = 'Delivery Note' and @type = 'text']</value>
      <webElementGuid>4f12f78f-094b-41ed-ac41-fe8c116dc5c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
