<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Sold To City</name>
   <tag></tag>
   <elementGuidId>6e9856a1-4e60-4e16-870e-45858261c6b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging > #dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88723d48-96ae-4a79-941e-68a20dfedb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>181125ac-b3dc-48ba-9951-bcc2105ae3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging</value>
      <webElementGuid>d0ae13bf-dab0-4c16-b82d-c18e5c1e36b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_sold_to_city_packaging</value>
      <webElementGuid>919a43b3-b712-4684-9f65-328dec55b2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Sold To City</value>
      <webElementGuid>4b91aa1b-af84-43a2-8184-a80cf15ef0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a2e8fcc-2da3-4141-aef5-6a216e075e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>88a0c18a-8b22-4e88-a2d4-dbe93d303e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_sold_to_city_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging&quot;]</value>
      <webElementGuid>8e6417dd-2087-414a-b037-525adabd68e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging']</value>
      <webElementGuid>4122cdf8-9d92-4ce6-bbab-6643fae31d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging']/input</value>
      <webElementGuid>68fd9dee-209b-4128-8183-b10eed00e32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[60]/div/div/input</value>
      <webElementGuid>e1968047-cc3d-469e-9925-5a74b46a0f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_sold_to_city_packaging' and @name = 'parcel_sold_to_city_packaging' and @placeholder = 'Parcel Sold To City' and @type = 'text']</value>
      <webElementGuid>efd49dad-dd96-4e87-b081-344bd86899d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
