<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice Total Net Amount HT</name>
   <tag></tag>
   <elementGuidId>2c20d8ad-87f9-4611-b910-d2ba01b22c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging > #dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1d27d9d-5d71-4c8e-a1e4-ae752c3215ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>6a46b7a2-cb63-47db-8f3f-18c664dc7edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging</value>
      <webElementGuid>64591776-85d6-4eb1-9eb4-6d11215f6405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_total_net_amount_ht_packaging</value>
      <webElementGuid>87917d74-08e2-4b74-9d3d-f5ea7ee9f193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice Total Net Amount HT</value>
      <webElementGuid>2366bf35-bb71-4ecd-8a94-bcf100b3c969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e14688ee-c585-47bf-930a-ae898104a010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>cf101f9a-6325-4916-8e69-5bb49628ac7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_total_net_amount_ht_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging&quot;]</value>
      <webElementGuid>26240e74-fa6d-4f3f-8009-44ccf1e97a40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging']</value>
      <webElementGuid>312a916f-ac6e-47c3-a9f8-522a6d64baf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging']/input</value>
      <webElementGuid>839040a8-c6f5-45b9-9f1d-77280651bb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[67]/div/div/input</value>
      <webElementGuid>1e9626bc-1e56-4580-928b-51629f5482f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_total_net_amount_ht_packaging' and @name = 'parcel_total_net_amount_ht_packaging' and @placeholder = 'Invoice Total Net Amount HT' and @type = 'number']</value>
      <webElementGuid>9fd71015-817d-4ac5-a834-cd0d4719a367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
