<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice date</name>
   <tag></tag>
   <elementGuidId>5f0a1753-9798-446c-80b1-aa6bda3881d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#invoice_date_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='invoice_date_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ceafc49b-c27b-491c-906a-8b6a18aa9e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invoice_date_packaging</value>
      <webElementGuid>4197c950-e770-49a2-b3f7-818a5b90093b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2200-02-01T00:00:00</value>
      <webElementGuid>1cfefac8-11d8-4ede-b6a9-0a861005a662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900-02-01T00:00:00</value>
      <webElementGuid>ec8edad2-9f27-45ce-8622-c2186b09d879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_date_packaging</value>
      <webElementGuid>33717188-aabd-47f9-b8dd-f44f848cc4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice date</value>
      <webElementGuid>c93af9a1-a5c1-4665-bb5f-983a9247184b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>6b3c886c-4bed-45a3-9f7c-d02bad8dc087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>729898c9-3a0f-4d46-afbb-7c3d422a051a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice_date_packaging&quot;)</value>
      <webElementGuid>d1c4a745-648c-438d-8666-95dd53fc50fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='invoice_date_packaging']</value>
      <webElementGuid>d2dc1d0c-cc5d-4c55-96b5-8aa65a3f2aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--invoice_date_packaging']/df-date-form/div/input</value>
      <webElementGuid>c0e0c29a-f1a9-430d-a97f-e6cbc19d4ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[37]/div/div/df-date-form/div/input</value>
      <webElementGuid>00d81edf-2ba2-4e48-b04c-3a0c33d3e64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'invoice_date_packaging' and @name = 'invoice_date_packaging' and @placeholder = 'Invoice date' and @type = 'datetime-local']</value>
      <webElementGuid>0dbece59-23a8-411f-9f3f-442cdcff0307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
