<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Document type code</name>
   <tag></tag>
   <elementGuidId>8a45669e-06f4-4bd5-992f-816ef70b8a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--document_type_code_packaging > #dfc-item--transport-packaging-content-form--document_type_code_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--document_type_code_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1f9c4f7-3b59-49db-8b11-2de0b2f0ddd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>1aae1590-9b5f-4363-81ec-99f1ea28b908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--document_type_code_packaging</value>
      <webElementGuid>c59feba8-029e-4d1d-b66a-8251abda658a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>document_type_code_packaging</value>
      <webElementGuid>8876a2ec-641f-4b75-a5e4-c7cc6c40b05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Document type code </value>
      <webElementGuid>747d1f58-2846-40b5-8f20-0f8707bde99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a690336-556b-4570-8f90-812f7254d2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>184134b6-76e3-4dfe-a577-af59df1dec05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--document_type_code_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--document_type_code_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--document_type_code_packaging&quot;]</value>
      <webElementGuid>cb5152d3-359f-4849-9d40-c87842042981</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--document_type_code_packaging']</value>
      <webElementGuid>49825ca4-e473-429f-ab11-79dc857d5a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--document_type_code_packaging']/input</value>
      <webElementGuid>2906b7d5-51ff-4731-8385-cf30d05f77b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[34]/div/div/input</value>
      <webElementGuid>024cbd8d-3650-4715-852a-8aca8c1a85cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--document_type_code_packaging' and @name = 'document_type_code_packaging' and @placeholder = 'Document type code ' and @type = 'text']</value>
      <webElementGuid>0ab12552-79b5-463a-90a4-eeea170e2a0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
