<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Net weight</name>
   <tag></tag>
   <elementGuidId>76ea2738-cd91-43d3-8746-c50fea033062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--unitaryNetWeight > #dfc-item--transport-packaging-content-form--unitaryNetWeight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--unitaryNetWeight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df8722ab-729c-4cf4-93f4-a75f5bdfd425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>86b45f1e-49e3-4c39-9689-0b1ad54f88dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--unitaryNetWeight</value>
      <webElementGuid>b94cae8b-bd02-49d1-8a7b-8c463c35a973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25f07283-39cf-40a1-9720-2769268c9b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitaryNetWeight</value>
      <webElementGuid>af921699-63c9-4936-89d2-2f4340a498e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Net weight (Kg)</value>
      <webElementGuid>06d64cea-e461-4a86-918d-0dec827cd9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7a43c098-abd1-4070-8ca5-a60eaeee1c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>8815e583-4233-48c0-bcce-fe1c35bdb335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--unitaryNetWeight&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--unitaryNetWeight&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--unitaryNetWeight&quot;]</value>
      <webElementGuid>8d001625-2785-4695-a182-29d8509790a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--unitaryNetWeight']</value>
      <webElementGuid>cbb86ffc-5612-4c9a-89de-c128cf4aeab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--unitaryNetWeight']/input</value>
      <webElementGuid>a2d26fef-ab02-4279-8ef0-ca02e2cdb1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[16]/div/div/input</value>
      <webElementGuid>bea2dd83-8d7d-4909-a2d9-614161f93f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--unitaryNetWeight' and @name = 'unitaryNetWeight' and @placeholder = 'Net weight (Kg)' and @type = 'number']</value>
      <webElementGuid>96f6de5a-ad09-4d83-8fbe-0000612f051a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
