<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SRI number</name>
   <tag></tag>
   <elementGuidId>948ecca0-7b49-41fb-b3b4-c799d7578835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--sri_number_packaging > #dfc-item--transport-packaging-content-form--sri_number_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--sri_number_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4407223a-0df7-4f3c-a888-df448d490407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>9e8a7ef7-9267-43e3-9b77-f5610a9b4981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--sri_number_packaging</value>
      <webElementGuid>7520bd20-1646-4640-b621-de4430cce2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sri_number_packaging</value>
      <webElementGuid>9e1b4aaf-9bee-4046-b66f-cce24ee9138d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SRI number </value>
      <webElementGuid>1291cf8c-ec75-4665-a687-bba508c1d8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>faa7fb22-f79a-4cac-b3c8-f8d5d80096cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>93fcbb29-ada5-4d11-8965-b7eccc239718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--sri_number_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--sri_number_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--sri_number_packaging&quot;]</value>
      <webElementGuid>4e629553-9d94-4e3a-8ec5-7539c5a0f9c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--sri_number_packaging']</value>
      <webElementGuid>0ade18ea-8d02-45ce-89ac-bbec8d00d12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--sri_number_packaging']/input</value>
      <webElementGuid>3d57b4e2-cea7-4a70-a67b-771be0d13a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[38]/div/div/input</value>
      <webElementGuid>a39c9a5c-a473-45e7-a2fc-7f5b85b1f2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--sri_number_packaging' and @name = 'sri_number_packaging' and @placeholder = 'SRI number ' and @type = 'number']</value>
      <webElementGuid>15fc1bdf-1047-47eb-acd5-2b08f6fb5471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
