<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Final ShipTo City</name>
   <tag></tag>
   <elementGuidId>97a379e7-3354-43f9-baaa-1afe2d23ce1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging > #dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b6c502c-0ce8-4d5e-a203-82a8e4835310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>06a8db7e-93fa-4691-a259-9a5dacca1fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging</value>
      <webElementGuid>2f48618e-7e51-4bbf-81b4-00103ffeac25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_final_shipto_city_packaging</value>
      <webElementGuid>720d21d8-9df6-4dbf-8825-0930a758b7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Final ShipTo City</value>
      <webElementGuid>d32968cc-b6e8-4700-932d-9137220330a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cfba1390-1c6f-4c9e-8887-ac1a8e327a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ddb6e40a-aea5-47fb-9b52-74753bee8380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_final_shipto_city_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging&quot;]</value>
      <webElementGuid>6971cd7c-d615-41cd-9250-72eea4f7aa57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging']</value>
      <webElementGuid>0d06d88b-0f4d-4ace-97fe-836d62ddd04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging']/input</value>
      <webElementGuid>551b5427-d445-428c-8a7c-cc8261bb216d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[48]/div/div/input</value>
      <webElementGuid>fecc6415-d9d9-4b85-b99f-3409a631e3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_final_shipto_city_packaging' and @name = 'parcel_final_shipto_city_packaging' and @placeholder = 'Parcel Final ShipTo City' and @type = 'text']</value>
      <webElementGuid>11a00ecd-1e98-4a8b-ad41-1c4adfab651b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
