<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Sold To Post Code</name>
   <tag></tag>
   <elementGuidId>84ad140d-7309-4017-a8f8-c949ffc59e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging > #dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dbff52e-d6eb-427b-ac7a-585231b25e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>e943501b-47e1-47b4-a2fc-36a9a639c9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging</value>
      <webElementGuid>36324482-40f6-4f36-9fcc-bd6c0dc24fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_sold_to_post_code_packaging</value>
      <webElementGuid>deecd407-96b6-4b40-b836-13b4ee41a41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Sold To Post Code</value>
      <webElementGuid>821c0447-8f9e-4f84-a14a-35a6357c03be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c1dce71-fa26-492d-b5ca-1cf9f7869ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>fa0eb1f2-0c81-4af6-8159-429056ea885d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_sold_to_post_code_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging&quot;]</value>
      <webElementGuid>8b64d6ee-53cc-487e-8d6f-425d9ba5c7b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging']</value>
      <webElementGuid>21375a76-9673-4c11-9034-2ce3e7204e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging']/input</value>
      <webElementGuid>ffafb9a1-d8de-4bc3-bfa9-f0fc9b724a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[61]/div/div/input</value>
      <webElementGuid>250fa640-b0bc-4d43-9602-9f5a5cc778d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_sold_to_post_code_packaging' and @name = 'parcel_sold_to_post_code_packaging' and @placeholder = 'Parcel Sold To Post Code' and @type = 'text']</value>
      <webElementGuid>3b84b262-7e87-401f-b685-e4a6e8c1d522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
