<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Bill To Code</name>
   <tag></tag>
   <elementGuidId>bc8cbdd4-b6e5-432c-a7fb-2f0f892b14de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging > #dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>953fd20b-3df7-4bf4-8790-7bd24fccc217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>b865bc86-bc36-4ca8-a18e-204a2634a2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging</value>
      <webElementGuid>b72a447b-22ee-4592-be26-65f2be5e1fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_bill_to_code_packaging</value>
      <webElementGuid>cbc0c43c-7d58-4b6e-bf68-a11361b018ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Bill To Code</value>
      <webElementGuid>364606bb-785b-4f3b-bfb6-73b86519203c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>694f5278-3823-4612-a1f9-34039437ca64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>638d7ea4-2a42-4ce2-9f68-85b6fe743ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_bill_to_code_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging&quot;]</value>
      <webElementGuid>87affa79-e69a-4e94-9326-c6b6cc644499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging']</value>
      <webElementGuid>ed53ba6d-ba74-4b7d-8377-992495955581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging']/input</value>
      <webElementGuid>d8227b3e-3479-499d-9da6-339c6d7d6acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[66]/div/div/input</value>
      <webElementGuid>044fd15f-ac15-4b3b-9e59-fd888884cdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_bill_to_code_packaging' and @name = 'parcel_bill_to_code_packaging' and @placeholder = 'Parcel Bill To Code' and @type = 'text']</value>
      <webElementGuid>44c5c4b9-9545-4812-a91f-18e90d7dffc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
