<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gross weight</name>
   <tag></tag>
   <elementGuidId>7033fe91-42b9-486f-b3d3-44a64bbf79c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--unitaryGrossWeight > #dfc-item--transport-packaging-content-form--unitaryGrossWeight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--unitaryGrossWeight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed55e8b4-d7c7-4cf2-93f0-cf1cd9c677de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>7df99c07-38ea-4bb6-bd9c-01f121fe0a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--unitaryGrossWeight</value>
      <webElementGuid>838815db-6fec-44e6-841c-8329cca3473a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>72b8afe0-3843-4807-924f-df888f8915db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitaryGrossWeight</value>
      <webElementGuid>9b698dc6-05d3-442b-9d77-39a4ba2075bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Gross weight (Kg)</value>
      <webElementGuid>32baed35-e407-4fb9-9d81-4d62660ffefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3055d413-a5dd-42d6-ac50-fc47e18c08f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>b0fa1195-1581-453e-8c2e-3a90d61b16d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--unitaryGrossWeight&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--unitaryGrossWeight&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--unitaryGrossWeight&quot;]</value>
      <webElementGuid>b4fbdd63-810d-4b07-a523-1a02af829328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--unitaryGrossWeight']</value>
      <webElementGuid>662234cc-3cc7-4a66-89c1-f6806b45c1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--unitaryGrossWeight']/input</value>
      <webElementGuid>5e421d01-b8b9-4418-a118-d1139d5f6344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[18]/div/div/input</value>
      <webElementGuid>d7fa9782-d2cd-49f6-9e94-c3436590dc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--unitaryGrossWeight' and @name = 'unitaryGrossWeight' and @placeholder = 'Gross weight (Kg)' and @type = 'number']</value>
      <webElementGuid>32acd7f1-45b3-4db0-b3cb-921fcbac289a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
