<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice VAT Bill To</name>
   <tag></tag>
   <elementGuidId>a6f0ce31-acd4-4db0-b880-3f2ba3a4a582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging > #dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6daf5e1a-970a-4ee1-aeba-45493a1b79c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>658af5e0-0f7f-4c73-a60d-13786b5e29b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging</value>
      <webElementGuid>40b8b33e-9447-434a-9e5d-ff2749ea18d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_vat_bill_to_packaging</value>
      <webElementGuid>b46ccbc0-0515-49c9-95bc-9e7b685e66b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice VAT Bill To</value>
      <webElementGuid>5e136056-72e9-493d-afd1-aee866d0e7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ffeeab0-fd72-4e2c-b786-b0c9ceee2d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>baaca53f-a469-4714-9024-fbab519cedf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--invoice_vat_bill_to_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging&quot;]</value>
      <webElementGuid>08144c62-c449-417a-8a7e-f4c9c7b97fb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging']</value>
      <webElementGuid>5049e511-3502-4ded-b379-39ff91e053ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging']/input</value>
      <webElementGuid>ef2195d4-bb8f-46a9-bcde-1c735e79fddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[70]/div/div/input</value>
      <webElementGuid>51c717d6-aa47-4a1f-9108-be19671ce4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--invoice_vat_bill_to_packaging' and @name = 'invoice_vat_bill_to_packaging' and @placeholder = 'Invoice VAT Bill To' and @type = 'text']</value>
      <webElementGuid>3c48ce99-3e1e-479e-b35e-d470be747443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
