<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Total Amount</name>
   <tag></tag>
   <elementGuidId>914fdd23-4230-4789-9428-d994ec32155e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_total_amount_packaging > #dfc-item--transport-packaging-content-form--parcel_total_amount_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_total_amount_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>513b83a2-11ad-4b28-b971-235eb7e342ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>fd8157b2-4a38-4329-b41a-4e1ef3f02045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_total_amount_packaging</value>
      <webElementGuid>12061275-41bc-4452-ba78-12c22b9a2673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_total_amount_packaging</value>
      <webElementGuid>4db51b02-ea2e-4e96-a2ea-db0713587c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Total Amount</value>
      <webElementGuid>2c9d73cf-4382-47f2-8523-0e2d453d50d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>079b9cc7-92f5-41ba-8018-71468fee317c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>26b41eec-59af-4aad-af9c-4329e6b281fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_total_amount_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_total_amount_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_total_amount_packaging&quot;]</value>
      <webElementGuid>cb497feb-1b40-41c9-bc09-db89c713804d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_total_amount_packaging']</value>
      <webElementGuid>878b8c0a-bbe5-41d1-add2-8edea141d8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_total_amount_packaging']/input</value>
      <webElementGuid>4a97637f-a779-4c28-97f5-8ba4b14e18cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[76]/div/div/input</value>
      <webElementGuid>fd5116ae-496d-4d7f-822c-5acde15368e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_total_amount_packaging' and @name = 'parcel_total_amount_packaging' and @placeholder = 'Parcel Total Amount' and @type = 'number']</value>
      <webElementGuid>c39df056-e2ea-4f41-b72d-42bebd79c47c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
