<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice Total Gross Amount TTC</name>
   <tag></tag>
   <elementGuidId>d3732505-d7e8-4456-beee-7b12ab3f2f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging > #dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e6d4ad7-85f1-4a5c-bb55-ba1bf0ccd829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>1df9d926-7f1b-46a1-9af5-db36ee0ac80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging</value>
      <webElementGuid>019ed83b-42ec-4442-83d7-2339da58c655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_total_gross_amount_ttc_packaging</value>
      <webElementGuid>1ad6c8f9-ef4e-4ed9-adf0-8a66b56e4a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice Total Gross Amount TTC</value>
      <webElementGuid>9d950208-1955-4c12-a8e7-aaf1e82a03b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>68b41453-d537-4802-bee0-db77cab72332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>9c15fb1f-4ad7-4196-bc09-7016a20179f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging&quot;]</value>
      <webElementGuid>8391c169-4f22-457c-bb24-5c3a78c24cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging']</value>
      <webElementGuid>9f2743a0-53d7-423e-8051-14e5255b4ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging']/input</value>
      <webElementGuid>e5fb71f3-10c4-4aaf-8628-bf056e3d7b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[68]/div/div/input</value>
      <webElementGuid>e86ebc7b-73f6-4fbd-9e52-d4af396bf870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_total_gross_amount_ttc_packaging' and @name = 'parcel_total_gross_amount_ttc_packaging' and @placeholder = 'Invoice Total Gross Amount TTC' and @type = 'number']</value>
      <webElementGuid>9ef56334-074f-40f7-9aa9-e7653ec24b9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
