<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SRI Date</name>
   <tag></tag>
   <elementGuidId>41c9ef18-e71c-4176-8006-23562b3db980</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sri_date_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sri_date_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5897e75-0daa-4a5e-b87f-2851eee96748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sri_date_packaging</value>
      <webElementGuid>acf8a63d-2de8-4937-919d-b790e7301e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2200-02-01T00:00:00</value>
      <webElementGuid>842fa6f0-50ce-49df-b938-90a03cb6cd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900-02-01T00:00:00</value>
      <webElementGuid>f52d6f81-8977-40ce-9fe1-6de7dd65c6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sri_date_packaging</value>
      <webElementGuid>4e4d5bbc-fa3d-471f-a560-165e3497783b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SRI Date</value>
      <webElementGuid>597112a5-a437-4fd5-80f8-61d293b2c9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>4633dccf-dd7c-41a0-973f-7061c638ef78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7468c861-e786-486e-be17-39d47165dc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sri_date_packaging&quot;)</value>
      <webElementGuid>009f1886-0581-4ac3-b4cd-dec009eb43aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sri_date_packaging']</value>
      <webElementGuid>022ffae8-7618-4107-b83d-40f3ae4575ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--sri_date_packaging']/df-date-form/div/input</value>
      <webElementGuid>d3a02660-1345-4b67-a25a-6c2ac29ced16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[39]/div/div/df-date-form/div/input</value>
      <webElementGuid>db26dc0d-ce42-4eba-a8ce-09bed4f4cfe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sri_date_packaging' and @name = 'sri_date_packaging' and @placeholder = 'SRI Date' and @type = 'datetime-local']</value>
      <webElementGuid>f7bafe10-464a-48e2-b316-b85b11b60c98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
