<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ColHous</name>
   <tag></tag>
   <elementGuidId>6eeab37b-09e1-440b-b6bd-ed0e042ccee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--col_hous_packaging > #dfc-item--transport-packaging-content-form--col_hous_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--col_hous_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d5557ab-167d-428e-9401-086856f1e061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>a0116243-f24d-4c92-90c3-c2cf164a8078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--col_hous_packaging</value>
      <webElementGuid>541164ba-b1e5-47c9-a471-bdf0157bad31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>col_hous_packaging</value>
      <webElementGuid>09cf5db1-921f-449f-838b-307b29da143e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Col/Hous</value>
      <webElementGuid>25e60c27-ebcd-4313-8326-9e3d6cfed87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63829e96-20d0-4293-8d63-62c9833c63f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>78bab4fb-c692-48d1-8f77-3d7f89187aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--col_hous_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--col_hous_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--col_hous_packaging&quot;]</value>
      <webElementGuid>07e901e7-82ee-47f1-a64d-e17935075631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--col_hous_packaging']</value>
      <webElementGuid>a32d3995-1f2e-421d-a3ec-f24f1512b470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--col_hous_packaging']/input</value>
      <webElementGuid>5983dc48-07f0-4332-b8ae-cee03ac9af32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[79]/div/div/input</value>
      <webElementGuid>46d38dc6-d075-47c7-a545-e4e32020d803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--col_hous_packaging' and @name = 'col_hous_packaging' and @placeholder = 'Col/Hous' and @type = 'text']</value>
      <webElementGuid>13c9ab9a-4c14-4ae4-83ac-eb45eecf1ef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
