<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice Total Number of Parcel</name>
   <tag></tag>
   <elementGuidId>5fbe7d08-1c3c-4465-b9ff-d2b80d30989b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging > #dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae2de2b8-c055-406d-a5ad-ac92143ca712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>b5aa8a1f-11e5-4f86-931d-37b389706e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging</value>
      <webElementGuid>54372af1-4086-494b-962b-5da2fe2d9ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_total_number_of_parcel_packaging</value>
      <webElementGuid>87b8646a-9cc2-40cb-9896-a56abca8424d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice Total Number of Parcel</value>
      <webElementGuid>13bccbad-c059-4d93-be0b-bc6db8ff47dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9b6ea7b2-0053-49be-90b4-09b6938eb71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>6fd96655-46ad-4383-a51d-52584a6a0b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--invoice_total_number_of_parcel_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging&quot;]</value>
      <webElementGuid>7e319c90-b1c2-40ce-bfed-d6141a691d8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging']</value>
      <webElementGuid>fd65587b-ffe4-45b2-8ad4-8f4e53599f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging']/input</value>
      <webElementGuid>ffbfbced-8f0d-4ee9-866f-1470f2ddd01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[71]/div/div/input</value>
      <webElementGuid>7c9bf549-602a-4d68-b3ac-cf8f23985f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--invoice_total_number_of_parcel_packaging' and @name = 'invoice_total_number_of_parcel_packaging' and @placeholder = 'Invoice Total Number of Parcel' and @type = 'number']</value>
      <webElementGuid>0f86ca2f-409d-4e0e-aea5-7f9c51401d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
