<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Gross weight</name>
   <tag></tag>
   <elementGuidId>f04b1d96-bd5c-4e9e-a400-2c5f1f63efee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--totalGrossWeight > #dfc-item--transport-packaging-content-form--totalGrossWeight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--totalGrossWeight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>105fc63c-ad69-4ec5-807f-af35137dca38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>fcc903c2-59fa-42f4-920f-c82ca63b41c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--totalGrossWeight</value>
      <webElementGuid>914b3224-2ed5-4613-8a97-ae43834fe5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>027cad9d-a489-4180-965f-4f9df029c8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>totalGrossWeight</value>
      <webElementGuid>eb1316d7-0019-4f30-97c0-d9f94104a475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Total Gross weight (Kg)</value>
      <webElementGuid>4388f5c4-96ba-4ab3-afa1-0703963b45dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0e5d7404-48b3-43ce-b4d5-266477626cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>82f9ff86-03ac-48d1-ae47-dbad3eeb235b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--totalGrossWeight&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--totalGrossWeight&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--totalGrossWeight&quot;]</value>
      <webElementGuid>d87cdb22-9895-479b-b3dc-45de6aedfa3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--totalGrossWeight']</value>
      <webElementGuid>47e9a1ce-0a5b-4bb0-b231-ed4a707f8b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--totalGrossWeight']/input</value>
      <webElementGuid>a8d88676-de4b-41d1-ac40-a2119e626d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[19]/div/div/input</value>
      <webElementGuid>831a2684-c9af-4428-b7e7-bc0174d4fe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--totalGrossWeight' and @name = 'totalGrossWeight' and @placeholder = 'Total Gross weight (Kg)' and @type = 'number']</value>
      <webElementGuid>b1f41bfd-ad19-4f0c-907f-102645bcd764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
