<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice  VAT Ship From</name>
   <tag></tag>
   <elementGuidId>4ba1a60a-d1d1-4dcc-8791-d8db26abedd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging > #dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0c195e2-2da3-46d9-abd6-bb02857b3842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>f962d69e-fd66-492e-9da5-67cb5ad857b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging</value>
      <webElementGuid>b6ab2f14-0ee7-45a9-99e6-e0e20c7c3963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_vat_ship_from_packaging</value>
      <webElementGuid>e5e374e5-9994-4de5-9a0c-cf8cfb7a4d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice  VAT Ship From</value>
      <webElementGuid>3a31b38f-a56c-4a7b-845e-31d61f6fdcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31383574-6ac9-437c-8a25-e461eb3d71b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>48e70bec-5118-4cc6-8bdf-0bae212175a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--invoice_vat_ship_from_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging&quot;]</value>
      <webElementGuid>16882ada-bb29-440e-918d-34ab4d7d3373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging']</value>
      <webElementGuid>a8617d5b-8e70-464b-ae08-3c68d8dab60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging']/input</value>
      <webElementGuid>bad6a023-90b9-48db-9b11-94cd910daace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[69]/div/div/input</value>
      <webElementGuid>f26f73e9-0be3-4ef7-90f1-c2184077f45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--invoice_vat_ship_from_packaging' and @name = 'invoice_vat_ship_from_packaging' and @placeholder = 'Invoice  VAT Ship From' and @type = 'text']</value>
      <webElementGuid>09b15df0-8a73-4eaf-a4c3-889f9c1b4cd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
