<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Final ShipTo District</name>
   <tag></tag>
   <elementGuidId>8fed631a-dcd9-48fa-b168-16e0c9e8b0e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging > #dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>999d0626-54f5-4fd9-87e0-a876f4a02b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>32fa072d-0ab0-4cf8-ac2d-ae1dbdfb6943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging</value>
      <webElementGuid>06d26b4e-70ec-4434-8656-6c30623a868d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_final_shipto_district_packaging</value>
      <webElementGuid>23cb7b3e-91da-4417-b4b2-cb16b633480d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Final ShipTo District</value>
      <webElementGuid>ef263e55-c7f0-448b-99fa-dda430c1144e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>025c7241-4ff3-4933-9b0e-c1795016a4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>b15b0754-7a70-4338-9746-1715b202bff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_final_shipto_district_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging&quot;]</value>
      <webElementGuid>dcc4ccf7-4597-4359-888c-edc03b20ec32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging']</value>
      <webElementGuid>06457b7b-896c-4c09-b8f8-9c2cfaf39ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging']/input</value>
      <webElementGuid>a45f2b8d-731e-4bcc-940e-4969b52b9911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[50]/div/div/input</value>
      <webElementGuid>d21aff4b-c80f-45f0-8c2a-5f84ec2563f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_final_shipto_district_packaging' and @name = 'parcel_final_shipto_district_packaging' and @placeholder = 'Parcel Final ShipTo District' and @type = 'text']</value>
      <webElementGuid>e92f1b29-01e1-4467-b599-6a8b707d6575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
