<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Package Reference</name>
   <tag></tag>
   <elementGuidId>71fd5ab9-e713-4cad-a7b8-f230ae0068e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--packageReferenceView > #dfc-item--transport-packaging-content-form--packageReferenceView</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--packageReferenceView']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>511e8fe3-746c-45ea-af63-b4c11df4564e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>856df2b4-3624-4d43-a634-5b27c226613a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--packageReferenceView</value>
      <webElementGuid>884b40e5-63f8-4004-8ffb-7d7f2fc03561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageReferenceView</value>
      <webElementGuid>e0c1dd22-dacc-470a-8897-00098720122a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Package Reference</value>
      <webElementGuid>55f10137-d51e-417f-b772-160879f6c677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>050fa397-c356-4112-881c-c3c93c6978fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>cbbb3a96-7c5c-444e-9283-4f7ac255ed03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--packageReferenceView&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--packageReferenceView&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--packageReferenceView&quot;]</value>
      <webElementGuid>d1aaa67f-2a27-4198-b435-9530e4df89a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--packageReferenceView']</value>
      <webElementGuid>90b4ee50-79ad-4472-aa08-05b8ab1c96b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--packageReferenceView']/input</value>
      <webElementGuid>b0a0b93a-3c97-4074-8328-0d01bb1a818b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[6]/div/div/input</value>
      <webElementGuid>a12afb5b-2b84-420e-93de-5d0dbe003b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--packageReferenceView' and @name = 'packageReferenceView' and @placeholder = 'Package Reference' and @type = 'text']</value>
      <webElementGuid>099b14af-fce3-439c-8b2d-0b4188481ba3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
