<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice Total Quantity of Item</name>
   <tag></tag>
   <elementGuidId>dacae5b5-768f-4919-81f7-991dcbce590a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging > #dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a57febaf-95c0-4797-b519-f9a9d1c24058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>1d94a857-84fc-4d7d-8f04-da276fda03f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging</value>
      <webElementGuid>e4b7e6ed-c100-4abc-a80f-f2a60911f07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_total_quantity_of_item_packaging</value>
      <webElementGuid>aa28877a-069e-43e9-b86f-6b97cf2c5e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice Total Quantity of Item</value>
      <webElementGuid>16df730a-1b19-4aad-8b4f-7800bc79d01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>03c56c16-ea90-484b-a720-5a7a06692ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>2a6834bc-f21a-4a95-b15e-0a51185ed05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--invoice_total_quantity_of_item_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging&quot;]</value>
      <webElementGuid>e6e69eaa-bf7c-4ec5-97c8-bdab56726374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging']</value>
      <webElementGuid>9bf4a054-ddd4-40ea-81bd-f57ab52d3ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging']/input</value>
      <webElementGuid>9a243b0e-feb6-4a3a-ad98-df33d27cfa65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[75]/div/div/input</value>
      <webElementGuid>844f8419-5464-4636-8e2a-6050c795572e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--invoice_total_quantity_of_item_packaging' and @name = 'invoice_total_quantity_of_item_packaging' and @placeholder = 'Invoice Total Quantity of Item' and @type = 'number']</value>
      <webElementGuid>83fdef39-9d67-4137-a05c-12787d68f97a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
