<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice number</name>
   <tag></tag>
   <elementGuidId>06ea6b29-0f3b-420b-a5b8-ffc802e385b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--invoice_number_packaging > #dfc-item--transport-packaging-content-form--invoice_number_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_number_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ece3efb-1b2f-4f74-b4ae-9f3a70af694b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>136235dd-68b4-41c7-8bfd-52d1684072f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--invoice_number_packaging</value>
      <webElementGuid>e8799e3a-57e4-44ff-84ab-88b14bd02e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_number_packaging</value>
      <webElementGuid>21d82705-c32c-4958-8b3c-37ac8afa0432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Invoice number </value>
      <webElementGuid>de497d14-2b49-495f-b8c4-798a48416e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b8aec53-1d3b-48eb-b544-cced1fd15236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>6a682e38-f0f0-426e-88c4-c055b5362dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--invoice_number_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--invoice_number_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--invoice_number_packaging&quot;]</value>
      <webElementGuid>4b3f5823-1322-4abb-8277-e3c6e168b298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--invoice_number_packaging']</value>
      <webElementGuid>4045b9ed-52ec-4be5-b296-de4112ee556a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--invoice_number_packaging']/input</value>
      <webElementGuid>672df63a-bfb8-4dd0-a351-e99d20ddbe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[33]/div/div/input</value>
      <webElementGuid>611e53fb-dd2c-4f4d-9acc-8711de83ec5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--invoice_number_packaging' and @name = 'invoice_number_packaging' and @placeholder = 'Invoice number ' and @type = 'text']</value>
      <webElementGuid>d4298307-db3e-4c41-9617-bfff519f6949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
