<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Final ShipTo Code</name>
   <tag></tag>
   <elementGuidId>4b0b8147-e35c-438e-aa98-8232fce1de64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging > #dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42dfd167-2604-4e6b-8140-51896acaac0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>3e4ab140-3d88-4f53-887c-f2291865d66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging</value>
      <webElementGuid>3db9d356-9254-4201-bf35-c206e92bf864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_final_shipto_code_packaging</value>
      <webElementGuid>11a7b867-9789-4f07-9f3f-0218b6324449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Final ShipTo Code</value>
      <webElementGuid>c3ef2785-1171-4003-9014-ff7863d375f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73b4b271-9a4c-4066-b668-9756f640bebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>bd51514f-2d27-46a4-a654-c113f51f78f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_final_shipto_code_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging&quot;]</value>
      <webElementGuid>0b4b723e-d47f-49ed-a54b-30e31cb27d6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging']</value>
      <webElementGuid>bddc0d35-2417-4165-bcf9-0d05cb736f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging']/input</value>
      <webElementGuid>bffb4c8d-2da2-4945-8003-d23c8ce9912f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[40]/div/div/input</value>
      <webElementGuid>d490488f-8b13-4c0a-a546-56a7b26d222c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_final_shipto_code_packaging' and @name = 'parcel_final_shipto_code_packaging' and @placeholder = 'Parcel Final ShipTo Code' and @type = 'text']</value>
      <webElementGuid>7e48c57d-036e-4f3c-ba02-0b949b012c48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
