<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Sold To Adress 4_</name>
   <tag></tag>
   <elementGuidId>fa22804e-4264-4055-820d-800f9de7fb4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging > #dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15c160d2-8729-4856-b341-5ba51bfda49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>b764630f-a61c-4575-b6ac-632b2dbce712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging</value>
      <webElementGuid>6ca568a0-c26a-4550-a0df-322bcb29e20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_sold_to_adress_4_packaging</value>
      <webElementGuid>09fb65fa-5503-484f-b0f1-69cfce977bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Sold To Adress 4</value>
      <webElementGuid>2ed6a6df-7d1e-4700-b03f-a0897771363a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>487316b5-5b31-4cd0-a0a0-c41dddb35c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>d0425d71-70f1-46c7-bf0a-3f34303b8306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_sold_to_adress_4_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging&quot;]</value>
      <webElementGuid>c0c20f3c-74c1-46b4-b07e-4eb080e3d3b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging']</value>
      <webElementGuid>d6627fae-4a8d-440a-8a10-ac0cad2bfe1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging']/input</value>
      <webElementGuid>9a35b5f8-394e-4e3f-8bd2-117fadc38313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[58]/div/div/input</value>
      <webElementGuid>17b7d863-a9f5-4ce0-a6ab-90cb99fae77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_sold_to_adress_4_packaging' and @name = 'parcel_sold_to_adress_4_packaging' and @placeholder = 'Parcel Sold To Adress 4' and @type = 'text']</value>
      <webElementGuid>a4a14d98-c55d-4b65-ba64-4aff9fb291a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
