<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Sold To Company Code</name>
   <tag></tag>
   <elementGuidId>1fee3ccd-446c-47fd-a16b-23d84959b1fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging > #dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd49eb70-523b-4e29-9464-9b69b40bd3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>4f3548d2-a889-4a26-9a54-3f313b8741f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging</value>
      <webElementGuid>bc35283f-62f2-4b1b-b16d-3f356db9e654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_sold_to_company_code_packaging</value>
      <webElementGuid>306e4146-dc66-4dca-a671-70af71556c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Sold To Company Code</value>
      <webElementGuid>d425ff0c-c2b2-4132-bfdb-f2dff4ceccd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41d7e46f-7df0-4f70-bf8f-441f8e017141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>5cb75ba3-10c2-43d4-9efa-5eadbb9e1d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_sold_to_company_code_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging&quot;]</value>
      <webElementGuid>60a6f8b7-83e8-4cca-b28f-fb9dd23a5cca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging']</value>
      <webElementGuid>a5ff15aa-163d-4618-b0ae-ae9037847f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging']/input</value>
      <webElementGuid>c2aea88b-9ec4-4188-8e6c-edc839c7ff3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[54]/div/div/input</value>
      <webElementGuid>bf72efa6-cbda-4d71-be30-493ae0f1d0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_sold_to_company_code_packaging' and @name = 'parcel_sold_to_company_code_packaging' and @placeholder = 'Parcel Sold To Company Code' and @type = 'text']</value>
      <webElementGuid>0bfad7c7-5f62-4699-ab26-bf5b4af94ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
