<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Sold To Admin Sub</name>
   <tag></tag>
   <elementGuidId>790fea52-a91d-436f-b4c9-ae77c59cb76e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging > #dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d5590e2-f2e4-4af1-9555-ab2001122451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>bcc554ea-f750-46de-8639-cb3d24b7dcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging</value>
      <webElementGuid>e294f391-e07f-45f0-984e-3884741ba0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_sold_to_admin_sub_packaging</value>
      <webElementGuid>43d22f3f-170a-47d3-ae61-4b296a334dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Sold To Admin Sub</value>
      <webElementGuid>8ef33038-7b8d-4206-b861-b74e725deb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c63d4eff-d6bb-4e57-bf0a-b9dc90083cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>3baeeafd-53a7-4e66-b3a6-ba34e42dc1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging&quot;]</value>
      <webElementGuid>069bbda8-1fd0-4380-8bbf-9e5b6e5ff3a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging']</value>
      <webElementGuid>5fc999c3-eac2-4219-8cbb-b87885adebf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging']/input</value>
      <webElementGuid>593f25cf-def0-4f26-928f-145c062f5f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[63]/div/div/input</value>
      <webElementGuid>cdbd60ac-6bdb-4bbc-aaf6-dddb93afe72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_sold_to_admin_sub_packaging' and @name = 'parcel_sold_to_admin_sub_packaging' and @placeholder = 'Parcel Sold To Admin Sub' and @type = 'text']</value>
      <webElementGuid>b34649cd-1591-48b6-a0ee-c36866c70689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
