<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SSCC Parcel ID</name>
   <tag></tag>
   <elementGuidId>79304aab-69ca-4d13-9c84-0309b9820c70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging > #dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e869d439-44f3-4180-bfe0-913ced2b5c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>cbe833ce-1f85-46f3-868f-81379cf9d0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging</value>
      <webElementGuid>ca42c87e-bbe2-4c06-892e-663ba1dd199d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sscc_parcel_id_packaging</value>
      <webElementGuid>50ba2e32-3faa-4478-b256-3f1a4b1b53e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SSCC Parcel ID</value>
      <webElementGuid>ee60179a-1a48-4c4c-9b8b-c32b957e1acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f636a95b-543d-4633-bf4c-946a6fa3fb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>5adb0285-cb6b-4325-a369-f43b98c62358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--sscc_parcel_id_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging&quot;]</value>
      <webElementGuid>3e2c52cf-7a07-45fc-9d56-ea740d46ac66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging']</value>
      <webElementGuid>610e83f9-7e16-48d8-9dfb-525d881cec65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging']/input</value>
      <webElementGuid>2b8230b9-ec6f-40d4-bf17-a968434a0d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[29]/div/div/input</value>
      <webElementGuid>586ae6a5-12fe-4bb9-920b-92c716094d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--sscc_parcel_id_packaging' and @name = 'sscc_parcel_id_packaging' and @placeholder = 'SSCC Parcel ID' and @type = 'text']</value>
      <webElementGuid>90cbd0f0-8f03-4287-b72e-08a18bdc1e09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
