<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unitary Quantity</name>
   <tag></tag>
   <elementGuidId>506bc68c-8790-4372-a8be-a3a3835f9314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--unitaryQuantity > #dfc-item--transport-packaging-content-form--unitaryQuantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--unitaryQuantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88a4b447-50cf-46d0-a434-cfa1489c80be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>4adc5093-646c-404e-ab84-127d7923a92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--unitaryQuantity</value>
      <webElementGuid>a733f469-620e-4541-8339-5c201bf732e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>104d4be8-c900-4612-8f98-d16fde5ec5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitaryQuantity</value>
      <webElementGuid>ac2c48bf-67d0-4518-b1b3-f5e5f1bdbf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unitary Quantity</value>
      <webElementGuid>7d7cf013-1dad-460d-87c5-c4968f12e127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a6bbdf56-4469-4ec6-b92d-1d0ee3cfd200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>51f00898-169f-458d-8b3d-e96c78c988b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--unitaryQuantity&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--unitaryQuantity&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--unitaryQuantity&quot;]</value>
      <webElementGuid>f11bb8f8-5e94-43b0-b664-da53bb035947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--unitaryQuantity']</value>
      <webElementGuid>0bb7f861-2bbf-4e3f-a3a5-76c5ac93f363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--unitaryQuantity']/input</value>
      <webElementGuid>86547eba-ed59-4ad0-ac53-8d65e8914070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-packaging-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[9]/div/div/input</value>
      <webElementGuid>fd2c0c12-3b8e-4ac6-a046-01e98693260b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--unitaryQuantity' and @name = 'unitaryQuantity' and @placeholder = 'Unitary Quantity' and @type = 'number']</value>
      <webElementGuid>915f886d-e59c-48ea-a339-baf7538891ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
