<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parcel Final ShipTo Name</name>
   <tag></tag>
   <elementGuidId>325cf326-509c-4e1a-bb69-034412b80420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging > #dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>751caed8-6fff-47cd-a181-6d95033f6024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>a3c0eb70-18cd-48de-85fb-9b1e2f6fe4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging</value>
      <webElementGuid>0592683a-0055-431d-aa56-b7c1b29a02ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parcel_final_shipto_name_packaging</value>
      <webElementGuid>0fd1cc30-954a-48be-9983-b714877ceeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parcel Final ShipTo Name</value>
      <webElementGuid>d358f26f-868c-4356-9e30-b16e9127f0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b0cff86-04ca-4ee9-9862-a0ebdb7c31e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>34fc5d2d-960d-424a-94dd-fcb2c4d37d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--parcel_final_shipto_name_packaging&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging&quot;]/input[@id=&quot;dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging&quot;]</value>
      <webElementGuid>87388f32-aa70-4b5a-853b-b2c945789702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging']</value>
      <webElementGuid>cc0e0e53-61c4-4ec7-9a5e-2c64f81e5857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging']/input</value>
      <webElementGuid>45118a41-281b-496d-a190-93d537d2cd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[42]/div/div/input</value>
      <webElementGuid>5c0e2616-068b-4907-af25-b18fe415c250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-packaging-content-form--parcel_final_shipto_name_packaging' and @name = 'parcel_final_shipto_name_packaging' and @placeholder = 'Parcel Final ShipTo Name' and @type = 'text']</value>
      <webElementGuid>5a6f24a9-6b9b-47de-a080-44bff4310a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
