<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Package Category</name>
   <tag></tag>
   <elementGuidId>ab0c571b-511f-46b4-a208-97571f85a495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--packageCategory > #dfc-item--transport-packaging-content-form--packageCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--transport-packaging-content-form--packageCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>86326975-8c69-4d6d-8a1a-7397c09438ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--packageCategory</value>
      <webElementGuid>6ba53c8e-a5c1-4938-9767-24103da68cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageCategory</value>
      <webElementGuid>c2f2635e-b2cf-49f0-9459-cebfc2f6871e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>68226273-8548-49ef-8779-37bc8c6a1676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PalletParcel</value>
      <webElementGuid>399cd165-5958-4580-b74a-421f0d8af8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--packageCategory&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--packageCategory&quot;]/select[@id=&quot;dfc-item--transport-packaging-content-form--packageCategory&quot;]</value>
      <webElementGuid>4c76dd9d-43a9-4974-ba78-1153487648f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--transport-packaging-content-form--packageCategory']</value>
      <webElementGuid>7b9a2949-de45-4474-86ab-321c5441fc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--packageCategory']/select</value>
      <webElementGuid>8ba8a2fe-8109-4496-8676-b1f833ea8b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[2]/following::select[1]</value>
      <webElementGuid>739d1c36-df79-4527-b1c1-6475ffb30550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package Reference'])[3]/following::select[1]</value>
      <webElementGuid>b85a99f1-cacd-4706-badc-3cd391864e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unitary Quantity'])[2]/preceding::select[2]</value>
      <webElementGuid>5075d80a-d4a0-4e66-9aac-2d884ffd518b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Quantity'])[2]/preceding::select[2]</value>
      <webElementGuid>fcaf2144-5bfd-4ae2-8943-e44c838fc500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[7]/div/div/select</value>
      <webElementGuid>3b2e1684-8e62-4e31-b7ab-e160157bbb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--transport-packaging-content-form--packageCategory' and @name = 'packageCategory' and (text() = 'PalletParcel' or . = 'PalletParcel')]</value>
      <webElementGuid>2338887b-a13f-43a8-8267-9660487cdb0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
