<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select Unit Type</name>
   <tag></tag>
   <elementGuidId>61560a41-521b-410e-8e25-0e3d71fb1cff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=&quot;dfc-item--transport-packaging-content-form--unitPackageTypeCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d8e90f0d-e16e-4dee-90d2-e0cfa44bb8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1668523788741</value>
      <webElementGuid>92b7ca5f-a49d-4b39-be08-ffd0a4fa063f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
