<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Parcel</name>
   <tag></tag>
   <elementGuidId>3e784425-fd3c-4f85-9876-d8dbe446bdd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-packaging-content-form--unitPackageTypeCode > #dfc-item--transport-packaging-content-form--unitPackageTypeCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--transport-packaging-content-form--unitPackageTypeCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a0656d51-cb7f-4cea-b29d-d4a58942e6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-packaging-content-form--unitPackageTypeCode</value>
      <webElementGuid>8943e2e3-66c6-4a69-adc4-128d3f70566b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitPackageTypeCode</value>
      <webElementGuid>3f05c701-a4d7-49b7-b3fa-c00769d4e52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>24cdb4d8-b54e-468b-a070-664b16c00637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parcel</value>
      <webElementGuid>4a0a61dc-2919-41ab-b667-cfee696b7da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-packaging-content-form--unitPackageTypeCode&quot;)/div[@id=&quot;dfc-item--transport-packaging-content-form--unitPackageTypeCode&quot;]/select[@id=&quot;dfc-item--transport-packaging-content-form--unitPackageTypeCode&quot;]</value>
      <webElementGuid>f8488f3d-ca41-427b-b96f-ebd5045cd998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--transport-packaging-content-form--unitPackageTypeCode']</value>
      <webElementGuid>e1272dea-26e5-4e58-82f7-3b490c3535ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-packaging-content-form--unitPackageTypeCode']/select</value>
      <webElementGuid>aaaf8e41-b02f-4e51-96f0-314c0d8410cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Type'])[2]/following::select[1]</value>
      <webElementGuid>d0712ea4-053b-46b5-b39b-40cf88c76fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package Type'])[3]/following::select[1]</value>
      <webElementGuid>b9bbd865-0a80-4890-a81d-5a7a0e11c876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taxable weight (Kg)'])[1]/preceding::select[1]</value>
      <webElementGuid>f7bff230-35f8-4eea-9626-ac11d11fce38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total taxable weight (Kg)'])[1]/preceding::select[1]</value>
      <webElementGuid>928fea95-3008-43c3-bf3e-644d6dfc5bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[21]/div/div/select</value>
      <webElementGuid>09708338-b12e-4ab8-8a03-93f3c259f2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--transport-packaging-content-form--unitPackageTypeCode' and @name = 'unitPackageTypeCode' and (text() = 'Parcel' or . = 'Parcel')]</value>
      <webElementGuid>f6a951f5-c835-46da-9ded-8642d6b7f905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
