<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Visible</name>
   <tag></tag>
   <elementGuidId>54574933-d86a-40b2-ada8-6d99a7fa0eda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-inputswitch-slider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='dfc-dyn-root--field-configuration-form--visibility']/app-visibility-section//p-inputswitch//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1903822e-4a5d-44a8-8a69-3eb26e78871a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputswitch-slider</value>
      <webElementGuid>8f8ed88a-9fb3-48e0-9a40-bd5eb1f13bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--field-configuration-form--visibility&quot;)/app-visibility-section[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;df-form-control-root big-content&quot;]/div[@class=&quot;df-form-control-item&quot;]/div[@class=&quot;switch-row ng-star-inserted&quot;]/div[@class=&quot;switch-label&quot;]/p-inputswitch[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ui-inputswitch ui-widget&quot;]/span[@class=&quot;ui-inputswitch-slider&quot;]</value>
      <webElementGuid>877589af-0235-4faa-ad14-54182ccc70ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--field-configuration-form--visibility']/app-visibility-section/div/div/div/div/p-inputswitch/div/span</value>
      <webElementGuid>0003bbee-8060-4c9f-8173-1f8e972aab7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-inputswitch/div/span</value>
      <webElementGuid>a5a83018-4a62-4b87-820f-ca74b12cc9f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
