<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name EN</name>
   <tag></tag>
   <elementGuidId>7a3ca36f-eaea-4994-8200-7b423d890813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--i18nLabelEN > #dfc-item--field-configuration-form--i18nLabelEN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--field-configuration-form--i18nLabelEN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07eeb344-11ba-4563-9686-7c94bd827412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>e0004e8b-81c2-4534-830b-4109a6adc125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--i18nLabelEN</value>
      <webElementGuid>efcbec42-2474-4b4b-87ff-c6ec5b591593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>i18nLabelEN</value>
      <webElementGuid>ed0d5ace-ab39-4c26-afdc-83510ea1e497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name EN</value>
      <webElementGuid>c9b59b35-8e3c-4601-92be-a555c86ab817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5858f71-0931-4a9d-b11d-5072d85801e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>b1969ce8-0155-4e3d-9b8d-d69759f7456a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--field-configuration-form--i18nLabelEN&quot;)/div[@id=&quot;dfc-item--field-configuration-form--i18nLabelEN&quot;]/input[@id=&quot;dfc-item--field-configuration-form--i18nLabelEN&quot;]</value>
      <webElementGuid>47381dce-1a6f-4595-aec6-c147a6d4896b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--field-configuration-form--i18nLabelEN']</value>
      <webElementGuid>c6aaeb97-bcea-45bd-b7c6-95495bf476a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--i18nLabelEN']/input</value>
      <webElementGuid>6f315687-5899-4aab-ad6c-aa3dd7fdffd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[2]/div/div/input</value>
      <webElementGuid>d1ceff7c-bc8b-47a6-8264-3abb8e3a9856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--field-configuration-form--i18nLabelEN' and @name = 'i18nLabelEN' and @placeholder = 'Name EN' and @type = 'text']</value>
      <webElementGuid>f9cae38f-8d70-451d-a964-e1a7a57dfc1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
