<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Concatenate values in consolidation Yes</name>
   <tag></tag>
   <elementGuidId>cc1751d4-3aa6-406e-86e0-e04050782b8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--consolidationConcatenateValues--true</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--field-configuration-form--consolidationConcatenateValues--true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69801f10-5b20-494d-b5d6-5f484ca07922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4b3af9aa-a8a0-4cb9-86e8-2f6c38092632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--consolidationConcatenateValues--true</value>
      <webElementGuid>33aa0ef0-e071-422a-a2de-6a0f98d236a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e9525de2-9045-4ec2-9aa8-25244f5f94f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--field-configuration-form--consolidationConcatenateValues--true&quot;)</value>
      <webElementGuid>07a52589-1fb1-40d5-a658-8511b9d62431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--field-configuration-form--consolidationConcatenateValues--true']</value>
      <webElementGuid>67b642f4-d5d7-4907-93a6-3bc2e672d7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--consolidationConcatenateValues']/div/input</value>
      <webElementGuid>d300b967-be14-4a2c-a15a-7ebb08edcf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[7]/div/div/div/input</value>
      <webElementGuid>35807282-61a9-4339-8331-1ad86b8ea63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--field-configuration-form--consolidationConcatenateValues--true']</value>
      <webElementGuid>da6e7a55-a8ed-4f19-8bc7-575595baccd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
