<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dropdown list Yes</name>
   <tag></tag>
   <elementGuidId>6083fa12-758b-452d-b2eb-0edc96c1bcf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--isDropDown--true</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--field-configuration-form--isDropDown--true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>671d2a64-b2c6-4764-90f9-97862e03b5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>24e13c78-3eb6-4ba6-abb6-cbc66fadaef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--isDropDown--true</value>
      <webElementGuid>52b00d88-7d0d-412e-b73e-3b2741d61e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c5ceea45-7c42-4a05-8118-1f6bc976975e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--field-configuration-form--isDropDown--true&quot;)</value>
      <webElementGuid>3f3794df-f2a8-41ea-8604-84e19ccb8686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--field-configuration-form--isDropDown--true']</value>
      <webElementGuid>1fbe2e3b-7e56-4005-9793-9e81c3bbc855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--isDropDown']/div/input</value>
      <webElementGuid>a89db113-b6ca-4c98-9f66-4587fc6cad10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[8]/div/div/div/input</value>
      <webElementGuid>3e71e81b-d9fc-4191-807d-d88f74230a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--field-configuration-form--isDropDown--true']</value>
      <webElementGuid>0bfa58f8-5712-4e0d-9945-63d017f74300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
