<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Concatenate values in consolidation No</name>
   <tag></tag>
   <elementGuidId>80aaaac5-0cfb-46ee-bbec-ef640a82f594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--consolidationConcatenateValues--false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--field-configuration-form--consolidationConcatenateValues--false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e585137-ed97-4d18-9544-02fee37467e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ff71b91e-8187-4bcf-bdff-75cbee1a2aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--consolidationConcatenateValues--false</value>
      <webElementGuid>d83be2d6-2557-4847-9014-89aac38f547a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>639c1d3b-bd14-4d1b-94c1-8c0ac30ba32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--field-configuration-form--consolidationConcatenateValues--false&quot;)</value>
      <webElementGuid>abe3b71d-5611-4a90-bad8-f8b54347ed61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--field-configuration-form--consolidationConcatenateValues--false']</value>
      <webElementGuid>3ef26489-8b94-4596-a60e-38d767d6ddc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--consolidationConcatenateValues']/div[2]/input</value>
      <webElementGuid>aa2aa34b-5e2b-4f0e-8a46-fc89e4d17538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[7]/div/div/div[2]/input</value>
      <webElementGuid>51be832d-6bb7-4200-8048-6d4c9c9c8197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--field-configuration-form--consolidationConcatenateValues--false']</value>
      <webElementGuid>fe4fa6d8-fc48-4a9c-8d18-23a994df8571</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
