<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Setting type</name>
   <tag></tag>
   <elementGuidId>6f006582-2b9c-4b83-b6e7-28bd41a94524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--settingType > #dfc-item--field-configuration-form--settingType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--field-configuration-form--settingType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d975fc5-7202-4cad-a8da-9b7c264736fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>5691b3b6-c8c7-423a-a1b6-c1a164db477f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--settingType</value>
      <webElementGuid>4d3bda15-a022-41c5-9db8-75f3da141500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>settingType</value>
      <webElementGuid>18030cf0-afbc-4cb2-bdb0-fdac39d34f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Setting type</value>
      <webElementGuid>a79e87fd-c4dd-4f10-9c15-1647c18b859a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7524d3d7-c924-4a49-8110-b5e34f00cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>84313788-1b3f-48fe-a458-72cc27a3a3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--field-configuration-form--settingType&quot;)/div[@id=&quot;dfc-item--field-configuration-form--settingType&quot;]/input[@id=&quot;dfc-item--field-configuration-form--settingType&quot;]</value>
      <webElementGuid>be6aec0c-7deb-4364-a7e1-90cc202ce01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--field-configuration-form--settingType']</value>
      <webElementGuid>47820f58-3aa0-4a9a-b86f-c7b106ba809e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--settingType']/input</value>
      <webElementGuid>8191c683-79ad-4914-b823-6a9857cff7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[15]/div/div/input</value>
      <webElementGuid>c9389575-602b-4a05-a7b4-4e91132c465d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--field-configuration-form--settingType' and @name = 'settingType' and @placeholder = 'Setting type' and @type = 'text']</value>
      <webElementGuid>a8fc658b-b751-4192-8e05-f3a7151e4e26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
