<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dropdown list No</name>
   <tag></tag>
   <elementGuidId>5893baeb-218b-4de7-881c-21e2ed54b216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--isDropDown--false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--field-configuration-form--isDropDown--false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>700cfcc0-6fa3-4567-aee5-ccd8016e142b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>919de973-2aa3-4be4-a31f-b0022d2fc795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--isDropDown--false</value>
      <webElementGuid>2e5ae1a3-0c67-44b9-b1f4-ab45ea02bf12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>784ae803-1e5e-4df3-9204-321395b57664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--field-configuration-form--isDropDown--false&quot;)</value>
      <webElementGuid>60dca8d3-5481-43d0-8766-20c016a03873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--field-configuration-form--isDropDown--false']</value>
      <webElementGuid>006709ee-3be2-431f-b65e-c31bce081879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--isDropDown']/div[2]/input</value>
      <webElementGuid>e1c993ff-2029-404f-acdd-ad0986fcadd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[8]/div/div/div[2]/input</value>
      <webElementGuid>44cb6e04-1259-4502-9380-3f5726b1d8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--field-configuration-form--isDropDown--false']</value>
      <webElementGuid>dc6df3b8-b00b-4293-8997-4009066450c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
