<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name FR</name>
   <tag></tag>
   <elementGuidId>01d18d25-1c85-4b5e-8939-75968608f584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--i18nLabelFR > #dfc-item--field-configuration-form--i18nLabelFR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--field-configuration-form--i18nLabelFR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3bb7c9e-9fec-40c9-9214-573c7ac23943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>cd7311ab-4bd9-4ef0-82ff-63835c8e3b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--i18nLabelFR</value>
      <webElementGuid>12eca52c-8099-470e-882f-d1aa508979c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>i18nLabelFR</value>
      <webElementGuid>c646b71f-7a56-48c4-80a4-40eb928c3acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name FR</value>
      <webElementGuid>f57a0e2b-9d97-40d1-8980-cea86252e5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>132c8ce3-acfc-4245-ad62-2463f1058ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>c6d5d5d8-ad10-4ba7-9228-5add3993a8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--field-configuration-form--i18nLabelFR&quot;)/div[@id=&quot;dfc-item--field-configuration-form--i18nLabelFR&quot;]/input[@id=&quot;dfc-item--field-configuration-form--i18nLabelFR&quot;]</value>
      <webElementGuid>090dbd3c-a0dc-4528-ae57-e5e564b4f568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--field-configuration-form--i18nLabelFR']</value>
      <webElementGuid>67831f29-3feb-4e4b-b3aa-fbfe47dab4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--i18nLabelFR']/input</value>
      <webElementGuid>f3ab02af-b50c-4df4-ac81-3954aa45fc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control/div/div/input</value>
      <webElementGuid>08ae49e1-c627-4458-b420-4e0243f2a576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--field-configuration-form--i18nLabelFR' and @name = 'i18nLabelFR' and @placeholder = 'Name FR' and @type = 'text']</value>
      <webElementGuid>63a5d6ae-c550-4c59-a327-6cb893a14c52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
