<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Type</name>
   <tag></tag>
   <elementGuidId>406a2354-9f6d-4083-914a-2acd83e7a76b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--fieldType > #dfc-item--field-configuration-form--fieldType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--field-configuration-form--fieldType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>94589c57-e130-472f-95e7-814ffc902a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--fieldType</value>
      <webElementGuid>1310b38f-6d58-484d-810b-b6e33a2cb8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldType</value>
      <webElementGuid>1461c3b9-ad94-4364-849c-99eab68b7c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ba59eb87-ba06-4f93-a6c4-f02155d3e6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IntegerDecimalTextMailYes / NoDateDate &amp; timeOther</value>
      <webElementGuid>49f5086f-5c98-4ecc-a5b2-0e837e30d723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--field-configuration-form--fieldType&quot;)/div[@id=&quot;dfc-item--field-configuration-form--fieldType&quot;]/select[@id=&quot;dfc-item--field-configuration-form--fieldType&quot;]</value>
      <webElementGuid>05c25bd4-f0ef-4b77-bdff-efcceac30cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--field-configuration-form--fieldType']</value>
      <webElementGuid>af48020b-a1e0-4523-9dd2-fa3e9d577056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--fieldType']/select</value>
      <webElementGuid>8511dc83-4641-4ee3-a7b7-825742e0813f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[1]</value>
      <webElementGuid>1445aed7-485b-49f6-9c6c-7601a19056f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ce champs est obligatoire'])[2]/following::select[1]</value>
      <webElementGuid>f4a4a18c-4778-4b02-a6f5-4ec2c6962df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Date can', &quot;'&quot;, 't be in the past')])[1]/preceding::select[1]</value>
      <webElementGuid>1f3cfcbb-1a74-46ea-b141-122aad979109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::select[1]</value>
      <webElementGuid>81d188d7-123b-47b6-ad6a-9c7c2c0438b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1f479cae-94f2-4010-a880-0b3369a4f8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--field-configuration-form--fieldType' and @name = 'fieldType' and (text() = 'IntegerDecimalTextMailYes / NoDateDate &amp; timeOther' or . = 'IntegerDecimalTextMailYes / NoDateDate &amp; timeOther')]</value>
      <webElementGuid>2c2567ee-dc09-456c-bf90-a81223438a1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
