<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Step</name>
   <tag></tag>
   <elementGuidId>a09ace7d-7edc-4b20-a1f9-cd7cd0972847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--step > #dfc-item--field-configuration-form--step</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--field-configuration-form--step']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eeace960-679e-4288-8391-e45253fe91d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--step</value>
      <webElementGuid>1abd9724-0957-4207-97f7-97ba505f7db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>step</value>
      <webElementGuid>4409948d-403f-4b5e-8389-d7e0f86f690c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>d5d58255-d72d-4303-bd7b-a3a2f8c708b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EXPEDITIONREFERENCESUNITSPRICINGCONSOLIDATIONINFOS_ABOUT_TRANSPORT</value>
      <webElementGuid>65fd122c-6ee4-4025-9b65-463859d80a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--field-configuration-form--step&quot;)/div[@id=&quot;dfc-item--field-configuration-form--step&quot;]/select[@id=&quot;dfc-item--field-configuration-form--step&quot;]</value>
      <webElementGuid>f2c9db12-cca5-47c8-9d89-533d50d71c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--field-configuration-form--step']</value>
      <webElementGuid>710df5c1-e208-48d6-8897-d51de5bbbc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--step']/select</value>
      <webElementGuid>d0e4fecd-3d45-45f0-9f3e-91593b6ca051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step'])[2]/following::select[1]</value>
      <webElementGuid>eb1020fd-3a91-4831-bcc4-1e028516d4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='field-configuration-view.data-table.columns.companyCode'])[1]/following::select[1]</value>
      <webElementGuid>3472ce1c-7e23-4327-8145-53698ad687cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section'])[1]/preceding::select[1]</value>
      <webElementGuid>7dac00a4-9ee1-4a87-9f9e-c71e01d7f79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[2]/preceding::select[2]</value>
      <webElementGuid>7a01578b-2baf-4c31-bdde-f7ba3bf9dc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[4]/div/div/select</value>
      <webElementGuid>07e4a9a9-758d-46d8-b65a-f2783619365f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--field-configuration-form--step' and @name = 'step' and (text() = 'EXPEDITIONREFERENCESUNITSPRICINGCONSOLIDATIONINFOS_ABOUT_TRANSPORT' or . = 'EXPEDITIONREFERENCESUNITSPRICINGCONSOLIDATIONINFOS_ABOUT_TRANSPORT')]</value>
      <webElementGuid>05e56e14-90a8-49f3-897d-0b8a6a721b21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
