<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Section</name>
   <tag></tag>
   <elementGuidId>7c0b3fe5-3eb8-4317-8e67-f5571ebf5d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--section > #dfc-item--field-configuration-form--section</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--field-configuration-form--section']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48471e16-53eb-47a1-b5eb-0f318e7c527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--section</value>
      <webElementGuid>3cee33fb-9df4-401a-81b3-89f6c25f8ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>6d2f31a8-a180-41c5-bc9c-5948b9ed2a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>bc86f719-eede-44bb-844e-9e40ac51857d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DESCRIPTION_EXPEDITIONREQUESTED_DATESCONTACT</value>
      <webElementGuid>fd3fe1a9-b69b-433a-8c37-115998db4c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--field-configuration-form--section&quot;)/div[@id=&quot;dfc-item--field-configuration-form--section&quot;]/select[@id=&quot;dfc-item--field-configuration-form--section&quot;]</value>
      <webElementGuid>714d5dfb-1f06-412b-8cec-0cc63f4b4938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--field-configuration-form--section']</value>
      <webElementGuid>680494f7-b522-4b7c-aecf-863dce8d798e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--section']/select</value>
      <webElementGuid>03f569d9-87ac-4c8c-80d3-dc72bab2745f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section'])[1]/following::select[1]</value>
      <webElementGuid>d28c7ff7-a91b-4ca5-a0ad-5a737ed20613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step'])[2]/following::select[2]</value>
      <webElementGuid>2eebc902-1b0c-4cba-bbc2-f5a2afd6ba36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[2]/preceding::select[1]</value>
      <webElementGuid>aa46bbe1-25b9-493d-8311-862b56698f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibility'])[2]/preceding::select[1]</value>
      <webElementGuid>ff0190af-8c82-48e5-aa94-c2e9898a2e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/df-form-control[5]/div/div/select</value>
      <webElementGuid>91c506b7-84ab-4e20-b6b6-953682f6d991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--field-configuration-form--section' and @name = 'section' and (text() = 'DESCRIPTION_EXPEDITIONREQUESTED_DATESCONTACT' or . = 'DESCRIPTION_EXPEDITIONREQUESTED_DATESCONTACT')]</value>
      <webElementGuid>9c1df0fb-2892-4f10-9c3e-6c1d71778ccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
