<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Component</name>
   <tag></tag>
   <elementGuidId>79ce7d1e-8661-4159-a53d-677190d1b1a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--field-configuration-form--businessType > #dfc-item--field-configuration-form--businessType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--field-configuration-form--businessType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34d147f1-52df-4d5f-a2e8-4808f5b2e441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--field-configuration-form--businessType</value>
      <webElementGuid>df3a1850-35a7-48d8-8b20-f20e40561ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessType</value>
      <webElementGuid>763b4fdf-bbbc-4b7c-8e16-cc57b8f6760a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>d5370553-b664-4b51-9f3d-235ae8491c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase OrderUnitsPackagingDeliveryTransportadditional-attribute-view.enums.business_type.ADDRESS_PARTYContactPricingTrackingadditional-attribute-view.enums.business_type.ROOT_CAUSEadditional-attribute-view.enums.business_type.FREIGHT_AUDITQuality management</value>
      <webElementGuid>87c3ec00-0eac-4c6e-8610-895721b10856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--field-configuration-form--businessType&quot;)/div[@id=&quot;dfc-item--field-configuration-form--businessType&quot;]/select[@id=&quot;dfc-item--field-configuration-form--businessType&quot;]</value>
      <webElementGuid>aded77f6-ebde-4bcb-82e7-97f66f40810e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--field-configuration-form--businessType']</value>
      <webElementGuid>dccfb233-9348-4808-b0ed-a7319ca5a8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--field-configuration-form--businessType']/select</value>
      <webElementGuid>df60461a-0154-4373-9641-eb4303965655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Component'])[2]/following::select[1]</value>
      <webElementGuid>05d08812-2294-4363-b549-7e4b4efbc116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column size'])[1]/following::select[1]</value>
      <webElementGuid>02a19458-a779-4c9e-ad18-199aea56d80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibility component'])[2]/preceding::select[1]</value>
      <webElementGuid>8e37f6a0-1bc7-4b3c-b124-5480103ab6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibility component'])[3]/preceding::select[1]</value>
      <webElementGuid>366da375-053e-4469-9f17-01b58d77c61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/df-form-control/div/div/select</value>
      <webElementGuid>b434279d-6b76-44d3-b0f1-e4419b5b524d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--field-configuration-form--businessType' and @name = 'businessType' and (text() = 'Purchase OrderUnitsPackagingDeliveryTransportadditional-attribute-view.enums.business_type.ADDRESS_PARTYContactPricingTrackingadditional-attribute-view.enums.business_type.ROOT_CAUSEadditional-attribute-view.enums.business_type.FREIGHT_AUDITQuality management' or . = 'Purchase OrderUnitsPackagingDeliveryTransportadditional-attribute-view.enums.business_type.ADDRESS_PARTYContactPricingTrackingadditional-attribute-view.enums.business_type.ROOT_CAUSEadditional-attribute-view.enums.business_type.FREIGHT_AUDITQuality management')]</value>
      <webElementGuid>96165fa7-335e-467a-9955-493a2a44073a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
