<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TypeOfDoc - BC</name>
   <tag></tag>
   <elementGuidId>e150ee7d-7ab7-4634-8e5b-16f8ee1c8568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-documents//div[contains(@class, 'type-doc_wrapper') and .//div[text()[normalize-space() = &quot;BC&quot;]]]//input[@type=&quot;file&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.upload-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b2ec983-f2f0-4597-83da-6bb1e1c98e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a500e3a9-f1db-4c81-934a-e6ead0aea223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-input</value>
      <webElementGuid>15c0694c-08aa-44c9-888e-c20e2f25a6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileDropContainer-147&quot;)/div[@class=&quot;col-md-12 padding-0&quot;]/div[@class=&quot;col-md-12 padding-0 expected-doc&quot;]/div[@class=&quot;margin-0-important col-md-12 text-doc-title ellipsis-item&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/input[@class=&quot;upload-input&quot;]</value>
      <webElementGuid>87e36eb9-c112-4978-8d69-f940d5ba7a6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fileDropContainer-147']/div/div/div/div[2]/input</value>
      <webElementGuid>e7de2234-c0c1-4f9c-9744-1704faf3d442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fileDropContainer-147']/div/div/div/div[2]/input</value>
      <webElementGuid>c372edbe-197d-4ff9-9541-3f9e1c1dff5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-documents/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>190c65ac-4822-4809-869a-7d99482f5123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file']</value>
      <webElementGuid>e911676d-339e-4a31-b8ff-4cccdd0f5a4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
