<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TypeOfDoc - CITES</name>
   <tag></tag>
   <elementGuidId>e203d66d-969b-408d-a381-afcb697f2019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-documents//div[contains(@class, 'type-doc_wrapper') and .//div[text()[normalize-space() = &quot;CITES&quot;]]]//input[@type=&quot;file&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.upload-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cb8d394-f881-4c3b-95a7-c0f2e4f39511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>b6a39ea3-cf05-4c5a-8acb-225d2859134a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-input</value>
      <webElementGuid>58b4411a-a5cc-4a28-b97e-c7b79f27a4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileDropContainer-147&quot;)/div[@class=&quot;col-md-12 padding-0&quot;]/div[@class=&quot;col-md-12 padding-0 expected-doc&quot;]/div[@class=&quot;margin-0-important col-md-12 text-doc-title ellipsis-item&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/input[@class=&quot;upload-input&quot;]</value>
      <webElementGuid>d305135c-049f-4d49-aebc-36c0e7046986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fileDropContainer-147']/div/div/div/div[2]/input</value>
      <webElementGuid>0011354d-a4c7-4c1e-b83a-42e929fa491a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fileDropContainer-147']/div/div/div/div[2]/input</value>
      <webElementGuid>a438545e-2b5c-4470-abb3-5d7a9c031249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-documents/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>e0e73559-49a9-426b-9bba-2c26d8aeac00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file']</value>
      <webElementGuid>d3f80c5c-52e7-41a0-93c2-849bf0d5ba92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
