<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attach to folder Yes</name>
   <tag></tag>
   <elementGuidId>39516a38-d81d-46d9-a86b-a57311292bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--type-document-template-form--attachChecked--true</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--type-document-template-form--attachChecked--true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>918d2965-71ec-4869-9dee-01941bf20424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>298ddf71-ce2f-4121-ba76-29d48fc9333f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--type-document-template-form--attachChecked--true</value>
      <webElementGuid>1c106463-de8e-4e71-bb00-8008a7dfd663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-dirty ng-touched</value>
      <webElementGuid>ee907e10-1662-4498-bebf-2cbd5368be97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--type-document-template-form--attachChecked--true&quot;)</value>
      <webElementGuid>ff542c08-9f70-413a-bb55-15afbb2737b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--type-document-template-form--attachChecked--true']</value>
      <webElementGuid>ac43a2bb-bd0e-42a7-a97c-d81d6e8e7dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--type-document-template-form--attachChecked']/div/input</value>
      <webElementGuid>69e3f8c2-a23e-4fd8-8574-6d8fe304aee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[2]/div/div/div/input</value>
      <webElementGuid>245dab06-5806-43de-bd50-74d4d8553681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--type-document-template-form--attachChecked--true']</value>
      <webElementGuid>496f0608-06e9-44f0-8301-dda36de5e88e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
