<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Default Document Type</name>
   <tag></tag>
   <elementGuidId>ae6f457c-0283-4400-8020-30c68bf899f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select.ng-select-single.ng-select-searchable.ng-select-clearable.ng-pristine.ng-valid.ng-select-bottom.ng-touched.ng-select-opened.ng-select-focused > div.ng-select-container > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;dfc-dyn-root--type-document-template-form--defaultTypeDocumentNum&quot;]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a409e355-88d0-45d6-8929-4df9708a21ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>a0a35495-5b38-4a2e-8d7e-a53ecbe6773f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a92897e-6902-4ee1-ae49-3e0eb715b2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>de6904c7-3530-4722-86ce-1ef22a803385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b252db12-c0cb-47d9-aab1-67e108766561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a9a97cdd1016</value>
      <webElementGuid>c46b5a13-a1be-457d-8ff5-402620faf9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad14535f-db9d-440b-922e-10754c1086e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a9a97cdd1016</value>
      <webElementGuid>335f0d46-f4cb-410f-a318-991122b72012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--type-document-template-form--defaultTypeDocumentNum&quot;)/app-ng-select-type-document[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;df-form-control-root&quot;]/div[@class=&quot;df-form-control-item&quot;]/ng-select[@class=&quot;ng-select ng-select-single ng-select-searchable ng-select-clearable ng-pristine ng-valid ng-select-bottom ng-touched ng-select-opened ng-select-focused&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>8c497a20-a270-441f-9e2e-2dad341d2aa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[16]</value>
      <webElementGuid>a9d06628-fad9-46c0-9c44-77281f5aec3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--type-document-template-form--defaultTypeDocumentNum']/app-ng-select-type-document/div/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>fffc9f96-3b56-4e76-9af5-09f9dd00c160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-ng-select-type-document/div/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>a963e221-110f-4c08-8a5f-9334a70c59a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>2c69ffde-d44f-4f6e-97a5-b27abda789d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
