<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose file to Upload</name>
   <tag></tag>
   <elementGuidId>66f24456-332e-4771-bd52-c71dcc317974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;file&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;dfc-dyn-root--type-document-template-form--cheminDocument&quot;]//input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>848ab77c-212f-48eb-ab05-5f1f385893f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>f8f3b42f-65e5-46b8-96f9-eaa3bf9fc0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.docx</value>
      <webElementGuid>b0b2edf3-d1d3-41f1-a355-c8f61d842b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--type-document-template-form--cheminDocument&quot;)/app-file-upload[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-12 col-sm-4 col-xs-12 form-group doc_upload&quot;]/p-fileupload[1]/div[@class=&quot;ui-fileupload ui-widget ng-star-inserted&quot;]/div[@class=&quot;ui-fileupload-buttonbar ui-widget-header ui-corner-top&quot;]/span[@class=&quot;ui-fileupload-choose ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left ui-state-focus&quot;]/input[1]</value>
      <webElementGuid>cab4f05a-4019-4534-8dac-5a6a02947437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='file']</value>
      <webElementGuid>ea7e6e68-935e-4a8d-b338-a795a23dec1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--type-document-template-form--cheminDocument']/app-file-upload/div/div/p-fileupload/div/div/span/input</value>
      <webElementGuid>2f4ed483-0347-4ed4-9b25-b5355f89ae04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>21d11414-355c-430e-b9ec-65aa4b9384fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file']</value>
      <webElementGuid>6bbfa5cd-d7f9-417a-854a-77913a9f09e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
