<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label</name>
   <tag></tag>
   <elementGuidId>717b4709-5dd3-4ccc-8724-42fb790d57a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--type-document-template-form--libelle > #dfc-item--type-document-template-form--libelle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--type-document-template-form--libelle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bb0896d-cae3-44be-b3c9-72830aae32aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>7d227af0-1219-4f22-ad6d-9418e00ea3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--type-document-template-form--libelle</value>
      <webElementGuid>05320a4c-3682-4257-84ad-ec0434c00ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>libelle</value>
      <webElementGuid>8bf7bd6a-7549-4f8c-ba7d-484cdbfa8026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>bbcbe8dc-ebb8-41e7-8378-0fb49ec0dd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be29d0dc-1c66-45c7-962b-75003070fd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>cae0dfe7-4a67-450d-ab51-da83acb326d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--type-document-template-form--libelle&quot;)/div[@id=&quot;dfc-item--type-document-template-form--libelle&quot;]/input[@id=&quot;dfc-item--type-document-template-form--libelle&quot;]</value>
      <webElementGuid>5144fb07-ac58-4b3d-a785-d255a28b562e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--type-document-template-form--libelle']</value>
      <webElementGuid>0424cd07-37ea-437c-9ed3-f9496124a72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--type-document-template-form--libelle']/input</value>
      <webElementGuid>f2a44f2d-01f5-4de1-974b-d647d58a2886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/input</value>
      <webElementGuid>92e8f793-4c1d-455c-bfe5-87318cd63223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--type-document-template-form--libelle' and @name = 'libelle' and @placeholder = 'Label' and @type = 'text']</value>
      <webElementGuid>c52c7152-6e97-48b0-a357-e90b86a5f432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
