<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Means Of Transport (AIR)</name>
   <tag></tag>
   <elementGuidId>b67525e7-267a-4f48-b1d6-f52467b30d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;padding-right-5 ng-star-inserted&quot;][1]//div[@class=&quot;ui-chkbox ui-widget&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9539c9a2-197d-4b7f-8897-6fabe43dd8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>043f7ab5-536a-4d14-9611-329c9a0d093d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-box ui-widget ui-corner-all ui-state-default</value>
      <webElementGuid>29161254-db96-403c-93f6-8fcd5b405955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac28e7e7-1066-4212-a431-e1bae77c5e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-costs-items[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;config-type-flux&quot;]/form[@class=&quot;generic-default ng-pristine ng-valid ng-star-inserted ng-touched&quot;]/div[@class=&quot;form-content col-sm-12 margin-top-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-sm-4 col-xs-12 form-group&quot;]/div[@class=&quot;col-md-12 d-flex-w checkbox-primeng padding-right-0 padding-left-0&quot;]/div[@class=&quot;padding-right-5 ng-star-inserted&quot;]/div[@class=&quot;new-formcontrol&quot;]/p-checkbox[@class=&quot;col-md-12 padding-0 ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ui-chkbox ui-widget&quot;]/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default&quot;]</value>
      <webElementGuid>509eed5e-6701-4d90-be11-bb2ed5884286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-costs-items/div/form/div[2]/div/div[2]/div/div/div/p-checkbox/div/div[2]</value>
      <webElementGuid>f6f67a6d-1cbe-4bba-8bce-9e8d977953e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Means of transport'])[1]/following::div[6]</value>
      <webElementGuid>4e37de65-6510-4117-a088-2f18282b1337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select category ...'])[1]/following::div[8]</value>
      <webElementGuid>ac643b64-99e4-4e22-be05-ac92990f2e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AIR'])[1]/preceding::div[1]</value>
      <webElementGuid>9fad6da9-f97f-4096-8b6d-d2b84296d093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEA'])[1]/preceding::div[4]</value>
      <webElementGuid>1ea73d66-0506-4c60-865b-bb5152b53d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-checkbox/div/div[2]</value>
      <webElementGuid>cec27f70-5377-48d9-8dab-1b3815c4830f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
