<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Designation</name>
   <tag></tag>
   <elementGuidId>cfefa514-a00f-4aea-8afb-56aa3ea00cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--unit-measure-form--designation > #dfc-item--unit-measure-form--designation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--unit-measure-form--designation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>549ea01e-bc36-4db0-8e53-b63de17b4dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>6f0e85ca-a3cd-40a1-83e8-9b7b7d713173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--unit-measure-form--designation</value>
      <webElementGuid>e45953a2-dab6-4749-b8c4-5935f10f31af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>designation</value>
      <webElementGuid>4965b777-59ee-4acb-ac98-9b0573ed844b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Designation</value>
      <webElementGuid>83fcf26f-6c20-43c2-ab49-3a058c922734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>987e79e7-ee5a-4537-8e37-f171cd7c82c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>d198f1da-3fc9-4741-966f-4f50285febb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--unit-measure-form--designation&quot;)/div[@id=&quot;dfc-item--unit-measure-form--designation&quot;]/input[@id=&quot;dfc-item--unit-measure-form--designation&quot;]</value>
      <webElementGuid>fa50adac-ea19-40cc-8990-4bc1e003cead</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--unit-measure-form--designation']</value>
      <webElementGuid>0f64bc0c-ee6c-4776-bf52-2f4b503befba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--unit-measure-form--designation']/input</value>
      <webElementGuid>89b7af80-5aae-4409-bb13-7c1d1e47bf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control/div/div/input</value>
      <webElementGuid>5c78d70b-ce06-4084-bd9a-1152d0232524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--unit-measure-form--designation' and @name = 'designation' and @placeholder = 'Designation' and @type = 'text']</value>
      <webElementGuid>c2de0f9b-7c7b-49b3-894e-99f318629ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
