<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Symbol</name>
   <tag></tag>
   <elementGuidId>bf6dec5b-9617-4d53-b440-21473bbe3c47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--unit-measure-form--symbol > #dfc-item--unit-measure-form--symbol</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--unit-measure-form--symbol']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98c03c50-7287-4bb8-ad83-7185dd965a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>4db5795e-ab7d-41a1-b862-924b06b1ce24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--unit-measure-form--symbol</value>
      <webElementGuid>0ab479dd-c336-4e64-93bd-4cda4ac6e052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>symbol</value>
      <webElementGuid>1b8193bc-7786-494d-8e0f-9237820ea8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Symbol</value>
      <webElementGuid>75fbc3d1-bef2-4f03-9340-d485ed945400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8553459-1c4b-4312-a33f-842175a4c0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>2408637f-3c5c-4187-b29a-5014732a9c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--unit-measure-form--symbol&quot;)/div[@id=&quot;dfc-item--unit-measure-form--symbol&quot;]/input[@id=&quot;dfc-item--unit-measure-form--symbol&quot;]</value>
      <webElementGuid>27a8cb00-3665-4ab7-b773-4e7dec44b82a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--unit-measure-form--symbol']</value>
      <webElementGuid>447c7756-0444-4e0e-b636-93a03b913df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--unit-measure-form--symbol']/input</value>
      <webElementGuid>46b05dd7-5efa-48e6-b480-b28ff6c11c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[2]/div/div/input</value>
      <webElementGuid>8b5c7b76-17ea-41c9-9026-71233b49eb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--unit-measure-form--symbol' and @name = 'symbol' and @placeholder = 'Symbol' and @type = 'text']</value>
      <webElementGuid>4cd925f4-46a4-4e07-b4f6-1521a305c723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
