<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field - Customer Reference</name>
   <tag></tag>
   <elementGuidId>9ca81104-209e-4587-a596-4897fc0668df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--customerReference > #dfc-item--transport-form--customerReference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--customerReference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c60294b3-16de-40ec-9635-f7f2147982fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>515b4db7-6f7e-4e18-8fc8-69b87eaa6c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--customerReference</value>
      <webElementGuid>99a56d1f-903a-4291-903f-9587acd3d7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerReference</value>
      <webElementGuid>29c15e42-8e8d-4d81-9d2f-5f2e4d0edb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Customer Reference</value>
      <webElementGuid>5227e940-6ede-426f-be32-0e12f65bbcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a22bc5ab-a2cb-40f7-acc9-2aa3002cd00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>86ade49b-ad9c-4327-87df-0d8a93b007e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--customerReference&quot;)/div[@id=&quot;dfc-item--transport-form--customerReference&quot;]/input[@id=&quot;dfc-item--transport-form--customerReference&quot;]</value>
      <webElementGuid>263291cd-ff52-4ab2-b253-44caa373857f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--customerReference']</value>
      <webElementGuid>ee454c02-2175-4a08-96cb-d1ebe417caf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--customerReference']/input</value>
      <webElementGuid>80ca8924-210a-4c5f-a710-6860c20cb88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[4]/div/div/input</value>
      <webElementGuid>2130e1f5-1274-45fd-a03c-6dde1072d319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--customerReference' and @name = 'customerReference' and @placeholder = 'Customer Reference' and @type = 'text']</value>
      <webElementGuid>f91972fe-66e3-4722-b5da-c69a16c344f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
