<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field - Type Of Shipment</name>
   <tag></tag>
   <elementGuidId>3b038980-2b4f-4b54-b8e3-0d282e47f41a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--type_of_shipment_transport_request']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--type_of_shipment_transport_request > #dfc-item--transport-form--type_of_shipment_transport_request</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90967e62-a02b-463a-9e95-8edfddd32e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>3676b0d5-5909-46a0-9835-fe2e25f58554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--type_of_shipment_transport_request</value>
      <webElementGuid>3b984397-a45e-47be-83b3-db8d2cf2859a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type_of_shipment_transport_request</value>
      <webElementGuid>dbaf1cb0-f55f-4e41-8041-5fe48df81ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type of Shipment</value>
      <webElementGuid>2d93e660-3178-4c51-9d1d-e770b3cae308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43fb5792-7261-4fa1-a53a-6f6bcc6e282f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>8925be7b-a58b-4867-b607-62bf3014cb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--type_of_shipment_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--type_of_shipment_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--type_of_shipment_transport_request&quot;]</value>
      <webElementGuid>6845c5b4-6745-4ee4-910f-330b8f9dcdaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--type_of_shipment_transport_request']</value>
      <webElementGuid>dc2bfdae-3e2a-41b2-bfca-d199f6dbc881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--type_of_shipment_transport_request']/input</value>
      <webElementGuid>f9b59c25-3b41-4278-8c54-cbc96607a3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[10]/div/div/input</value>
      <webElementGuid>b0204706-a6a8-4b3c-ac1a-91e022cb8938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--type_of_shipment_transport_request' and @name = 'type_of_shipment_transport_request' and @placeholder = 'Type of Shipment' and @type = 'text']</value>
      <webElementGuid>3b257172-21ad-4cab-91dd-063c3a0ddf07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
