<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field - Consolidated - Yes</name>
   <tag></tag>
   <elementGuidId>3a32c903-fa9b-421a-90c8-3fede4983119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--consolidated--true']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--consolidated--true</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4114d2cf-425a-4c03-a479-b77c1e620fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5ea98c85-7dd8-4904-baa4-6b3973af348f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--consolidated--true</value>
      <webElementGuid>5abda5dc-0264-4638-9473-61e8e06191a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>9db47295-af35-4a02-80c5-f128050d32d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--transport-form--consolidated--true&quot;)</value>
      <webElementGuid>a118777c-0eff-419a-b68a-e939317bf8c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--consolidated--true']</value>
      <webElementGuid>2c223ed3-b7a4-426c-8c99-f72e248fe5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--consolidated']/div/input</value>
      <webElementGuid>5893587e-28bc-4d3b-bb6c-840ae48befb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[51]/div/div/div/input</value>
      <webElementGuid>116d7aa4-cbf8-43aa-8e3c-c501715099de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--transport-form--consolidated--true']</value>
      <webElementGuid>73b7eaac-c945-4e08-be8b-729a6346f3d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
