<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo MyTower</name>
   <tag></tag>
   <elementGuidId>b9517723-1494-4a55-8bbc-8a235e82c223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/app-header//*//a[@routerlink=&quot;/home&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87324cb9-50ec-4fdc-9ecd-caaa4bd08cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../assets/images/mytower-logo-text.png</value>
      <webElementGuid>cbe1ac4c-07e4-4f8f-a5fa-655a3ee30365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c2058f99-c90e-4dd0-8e05-6d680b8aea23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>c89c1acc-6a8d-42ca-8f61-83a282ec6d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-header&quot;)/app-header[1]/nav[@class=&quot;opened d-flex-ai-c animated fadeInDown navbar-header navbar-fixed-top navbar-shadow ng-star-inserted&quot;]/ul[@class=&quot;navb navbar-left&quot;]/li[1]/a[1]/img[1]</value>
      <webElementGuid>53fb7785-66d0-4bf2-826a-111357ed4b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/nav/ul/li/a/img</value>
      <webElementGuid>a00d95a5-8a70-4464-805d-eeed327bd438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>363613f3-979b-45c0-8b81-bf5e86d938a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../assets/images/mytower-logo-text.png']</value>
      <webElementGuid>6b8e7e78-68ce-4e9f-bc20-1d7d3c59ff01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
