<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First valorized quote - Select for confirmation</name>
   <tag></tag>
   <elementGuidId>5634e1ec-e6ef-4f2c-b91f-e76193a9bfc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class, 'vignette')]//div[contains(@class, 'actions') and button[i[contains(@class, 'fa-info')]]])[1]//button[i[contains(@class, 'fa-check')]]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>185de88e-b471-4a9a-a077-b79524c459c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>909b616b-f6cb-4c80-b903-169eff9640d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check</value>
      <webElementGuid>99bfd064-1941-4ddd-bdc5-6588f2ac53af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quote-view-22-actions&quot;)/button[@class=&quot;btn btn-xs ng-star-inserted&quot;]/i[@class=&quot;fa fa-check&quot;]</value>
      <webElementGuid>01beb403-195f-4638-84a6-347734d486c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quote-view-22-actions']/button[2]/i</value>
      <webElementGuid>d358e413-bd36-4262-90bb-e77e197d1e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>bf3496ad-4670-4787-bfc5-f824e2b97cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
