<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First valorized quote - Checkbox</name>
   <tag></tag>
   <elementGuidId>ce2e2ea5-9e31-4efc-a3a5-188c99c479f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class, 'vignette')]//div[contains(@class, 'actions') and button[i[contains(@class, 'fa-info')]]])[1]//input[@type = 'checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quote-view-22-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01e265dc-2173-41ef-a0da-88f43e84ca96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>274471e4-2564-4ec3-b496-15ef7bb4966e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quote-view-22-check</value>
      <webElementGuid>3a72880f-63db-4b11-af9a-1f63ab9cf4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>a966185d-7891-4a52-bee5-3d8c8a8956e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quote-view-22-check&quot;)</value>
      <webElementGuid>6c69d9b0-6de8-419f-b0f8-03ecd90a42f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quote-view-22-check']</value>
      <webElementGuid>dac9acb8-424e-42e3-a43c-642ef6d89af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quote-view-22-actions']/input</value>
      <webElementGuid>ecc003c4-b5f7-4e7c-b118-4dfae51b0b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/div[2]/input</value>
      <webElementGuid>8196a4af-ec7d-42c8-bf78-21101d8d8f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'quote-view-22-check']</value>
      <webElementGuid>19f42561-ffca-4ad2-a54b-2a88d40bee47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
