<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Designation Dashboard</name>
   <tag></tag>
   <elementGuidId>3bfba59a-ba02-4522-a4b8-8686e7a98ed3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-405-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label=&quot;Designation Filter Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ac8c6b6-a0c8-4952-b1cc-b3b2006c7a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>11a05032-1352-4b6d-805c-16a8c8e791c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>850f2717-bc91-4393-8a62-c7fedac3908e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84555163-7da5-4500-b1bf-961bf8255ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-405-input</value>
      <webElementGuid>68c69ffa-4565-47d2-8ea8-bc5e4abc6d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Designation Filter Input</value>
      <webElementGuid>5a7ff424-dcf2-4090-851d-a2a4b68ebfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-405-input&quot;)</value>
      <webElementGuid>da112748-af50-43f2-8bf0-77b9bc141864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-405-input']</value>
      <webElementGuid>c1e1b301-ec38-45a1-b33f-60b4b5954a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-config-type-flux/div/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>4ee0cc11-5968-4d2b-b7ed-08d7d527eaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>dbf5ef25-d3e6-43e7-9c6f-eaa57e9470dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-405-input']</value>
      <webElementGuid>e2d69283-6023-4c3e-8a52-17387def5ce1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
