<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Schemas psl</name>
   <tag></tag>
   <elementGuidId>71a07bde-f17a-4517-b94f-c3524daa35ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select.ng-select-multiple.ng-select-searchable.ng-select-clearable.ng-untouched.ng-pristine.ng-valid.ng-select-focused.ng-select-opened.ng-select-top > div.ng-select-container > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-autocomplete[@name=&quot;selectedListEbTtSchemaPsl&quot;]//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>849cce03-9ae3-47b8-80fd-0f8a20155161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2f045715-3219-46b2-b788-6282024f3e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c6c3ec2-ea7a-432f-906c-1b95a91a9eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d78b36f5-9c5f-4699-8d73-d0162159e89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ac0927cb-a296-4c8c-a211-0030cfd1deca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a7b61b5ffd1b</value>
      <webElementGuid>d22d7808-7aaa-4ebe-bb87-7fb5f16033a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d053af7-aaa8-41c3-95a6-8d98bc92e535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a7b61b5ffd1b</value>
      <webElementGuid>998aad77-9212-4073-9b5e-40d43fdc83e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a7b61b5ffd1b-0</value>
      <webElementGuid>9826a974-ad21-41e9-9002-2e2ea860d59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-config-type-flux[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;config-incoterm ng-star-inserted&quot;]/div[@class=&quot;trpl-zone-settings-root ng-star-inserted&quot;]/form[@class=&quot;generic-default ng-pristine ng-valid ng-star-inserted ng-touched&quot;]/div[@class=&quot;form-content col-sm-6&quot;]/div[@class=&quot;list-psl col-md-12 col-sm-12 col-xs-12 form-group padding-top-10&quot;]/div[@class=&quot;col-md-12 col-sm-12 col-xs-12 padding-0&quot;]/app-autocomplete[1]/ng-select[@class=&quot;ng-select ng-select-multiple ng-select-searchable ng-select-clearable ng-untouched ng-pristine ng-valid ng-select-focused ng-select-opened ng-select-top&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>93533f01-5f5b-4fef-bfa5-481dbcb67e22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>3c7d173c-2971-4cf9-8e9f-cd0ff9e7083a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-config-type-flux/div/div/form/div[2]/div/div/app-autocomplete/ng-select/div/div/div[2]/input</value>
      <webElementGuid>4e766d78-211c-4228-ae48-245095a0f586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/app-autocomplete/ng-select/div/div/div[2]/input</value>
      <webElementGuid>02c7309d-91a6-48db-90cf-8b5bff535514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>33a4e22e-c5cf-4eeb-bac1-d0118ad2ab53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
