<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Designation</name>
   <tag></tag>
   <elementGuidId>dd162a08-043b-4743-9e2c-7344bca6cdde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;designation&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='designation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>668b209f-0c62-4e76-b228-15dd106977df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7c2fe75-7ed1-4dc1-bec3-880426fef861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>designation</value>
      <webElementGuid>8b5ac2b8-2fb7-4da7-81d4-bd831c5cf151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-underline input-xs ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b22a98cd-1452-43d9-94bc-e645e1dd87a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-config-type-flux[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;config-incoterm ng-star-inserted&quot;]/div[@class=&quot;trpl-zone-settings-root ng-star-inserted&quot;]/form[@class=&quot;generic-default ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;form-content col-sm-6 margin-top-10&quot;]/div[@class=&quot;col-md-6 col-sm-12 col-xs-12 form-group&quot;]/div[1]/input[@class=&quot;form-control input-underline input-xs ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>d3be40db-c83a-42e4-8419-deea51377858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='designation']</value>
      <webElementGuid>a9e81650-7956-4a99-9f1a-b70e9de5aa9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-config-type-flux/div/div/form/div/div/div/input</value>
      <webElementGuid>3db2c3b6-f805-4edc-834e-b9c5ec1f34f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c2b91d8d-e76f-4189-b8a0-5f0cd726f567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'designation']</value>
      <webElementGuid>df4008bb-82a0-4533-8e6a-20aa010d6b1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
