<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_Quotation</name>
   <tag></tag>
   <elementGuidId>fbb75a12-b65e-43f0-9595-4c9930d6757c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='quote-view-0-actions']/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-xs.ng-star-inserted > i.fa.fa-pencil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1d056adb-a113-483d-a0ed-7968fd29ee8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b03e62b7-f4fb-48d5-9c23-2a37847a6930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-pencil</value>
      <webElementGuid>dbb3a428-2eaa-4f9c-a8db-d0cc595dd31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quote-view-0-actions&quot;)/button[@class=&quot;btn btn-xs ng-star-inserted&quot;]/i[@class=&quot;fa fa-pencil&quot;]</value>
      <webElementGuid>63e7e9a8-bcea-4138-89c0-ce43f81c67d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quote-view-0-actions']/button/i</value>
      <webElementGuid>5c3fad81-0965-4b1b-857b-4a7194955cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>9fb9c5cd-bd7c-43e4-9fce-09f9e424fe58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
