<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pricing</name>
   <tag></tag>
   <elementGuidId>d8f37ae2-bb2b-411f-ab62-3718499195ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-details/div/div/div[2]/div/app-panel-left/div/div[2]/div[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3af9eade-5545-4512-97ca-dfb52b4a4fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing</value>
      <webElementGuid>97bdecb9-72db-413e-bc16-3351c6586830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;transport-details-root loader-content-container transparent-dark-loader&quot;]/div[@class=&quot;m-details-form ng-star-inserted&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;left&quot;]/app-panel-left[1]/div[@class=&quot;panel-root details-form-overview opened&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;section clickable&quot;]/span[1]</value>
      <webElementGuid>1ee92499-e11e-448e-aaa4-9ec5c71b81ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-details/div/div/div[2]/div/app-panel-left/div/div[2]/div[5]/span</value>
      <webElementGuid>4a420742-0c7a-4067-9fd1-e5793e9388ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articles'])[1]/following::span[1]</value>
      <webElementGuid>96934a6e-2421-4800-91c9-ebbbb0e9cd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STANDARD'])[1]/following::span[2]</value>
      <webElementGuid>48cab1e5-42ed-4987-9aa0-728b15898a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informations about transport'])[1]/preceding::span[1]</value>
      <webElementGuid>b3f52c7b-38d9-46d9-b32f-7219e557e87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping informations'])[2]/preceding::span[2]</value>
      <webElementGuid>42e04638-5eed-4481-8625-673b81034ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span</value>
      <webElementGuid>6a4aa5bf-ad81-4ddf-921e-6219c17b9211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pricing' or . = 'Pricing')]</value>
      <webElementGuid>41aefdeb-8ff5-4546-89ed-a7a804029254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
