<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total_Time</name>
   <tag></tag>
   <elementGuidId>65cff6a9-238e-444c-806d-f8dfa845aad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--quote-edit-form--transitTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--quote-edit-form--transitTime > #dfc-item--quote-edit-form--transitTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57ee75be-84a3-48d9-9bf8-71503f7c3316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>15c69eb2-4d86-483e-afaf-4789bc6bea36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--quote-edit-form--transitTime</value>
      <webElementGuid>822a5362-4cd4-4a5b-a0f5-17713c7cf943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transitTime</value>
      <webElementGuid>38072e79-3bf9-4b0c-bddf-3ac9eaf0dd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Total transit time (hours)</value>
      <webElementGuid>9f71830a-b5f5-43f5-8b0b-8263c690f813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>614e2d96-0ab7-4f7c-9fcf-ea149da1566d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-star-inserted ng-dirty ng-invalid</value>
      <webElementGuid>39ca9c55-6c96-4c0e-92f0-617dd7211165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--quote-edit-form--transitTime&quot;)/div[@id=&quot;dfc-item--quote-edit-form--transitTime&quot;]/input[@id=&quot;dfc-item--quote-edit-form--transitTime&quot;]</value>
      <webElementGuid>5e02cf7a-9471-49b2-a410-eaad7594a290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--quote-edit-form--transitTime']</value>
      <webElementGuid>44c1463d-d240-4ab1-b625-01f7cd6eb3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--quote-edit-form--transitTime']/input</value>
      <webElementGuid>2e15b6ec-d43e-4a35-bc4a-180145bfa386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[10]/div/div/input</value>
      <webElementGuid>91e97744-1d96-4ae6-bcd5-2f1a7efdbab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--quote-edit-form--transitTime' and @name = 'transitTime' and @placeholder = 'Total transit time (hours)' and @type = 'number']</value>
      <webElementGuid>fcd9e7c3-eaf1-4ff1-b639-4627b928aeb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
