<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total_Price</name>
   <tag></tag>
   <elementGuidId>8474f390-e7db-4377-8586-106b365a3d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--quote-edit-form--totalPrice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--quote-edit-form--totalPrice > #dfc-item--quote-edit-form--totalPrice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0082bdf-ca4b-4bbd-bee2-d03968cfb432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>76446a41-75d5-4167-952c-0fc76e87d08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--quote-edit-form--totalPrice</value>
      <webElementGuid>a1b8754b-b857-40ed-b33e-f3a2eb38110d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>totalPrice</value>
      <webElementGuid>824721d7-baa3-43bf-b109-3737b8919b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Total price</value>
      <webElementGuid>f37e3326-8c8a-4447-9ade-f7451704d36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>98e12dc0-cf51-4d8a-83d0-935ce354da6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>b43c05ad-b0b9-4f24-b9ba-24eca033c96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--quote-edit-form--totalPrice&quot;)/div[@id=&quot;dfc-item--quote-edit-form--totalPrice&quot;]/input[@id=&quot;dfc-item--quote-edit-form--totalPrice&quot;]</value>
      <webElementGuid>d33409c2-6af1-4592-952f-9ae899ba2248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--quote-edit-form--totalPrice']</value>
      <webElementGuid>623670d4-8e1f-4f48-aebb-988dbee548b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--quote-edit-form--totalPrice']/input</value>
      <webElementGuid>ac42dffc-7ad0-44cc-9fc2-1a117e201c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/df-form-control[2]/div/div/input</value>
      <webElementGuid>de677671-228d-414f-b065-da3a7310a11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--quote-edit-form--totalPrice' and @name = 'totalPrice' and @placeholder = 'Total price' and @type = 'number']</value>
      <webElementGuid>4dff6e9e-92e2-4bca-8991-54128c15005c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
