<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Column filter text input</name>
   <tag></tag>
   <elementGuidId>4833919a-2d56-47fb-b356-50ec8c5291f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-8718-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@class, 'ag-filter-wrapper')]//*[contains(@class, 'ag-set-filter')]//*[contains(@class, 'ag-input-wrapper')]//input[@ref = 'eInput' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>128087d0-a873-4bcb-bc2d-46a2e4b543e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>333474f9-210e-431b-9e74-c1de90604e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>1726570f-5a96-4033-a040-51913db3e7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>194f3201-109d-4dc5-9635-94c33e1c5bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-8718-input</value>
      <webElementGuid>63689d12-4522-4ac7-8029-66a1924bd90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search filter values</value>
      <webElementGuid>a2d049c6-727f-43c6-ab4d-2e9c377648bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>561076ae-841c-45d7-9ef0-a9e9565197b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-8718-input&quot;)</value>
      <webElementGuid>d9bae3a4-9c6a-4045-b7a0-b7a6bc25e2c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-8718-input']</value>
      <webElementGuid>2cc033ff-df5b-407a-b1dc-a79c1100181e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-pricing-list/app-transport-common-list/div/ag-grid-angular/div/div[6]/div/div[2]/div/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>00dbc735-7c1b-461e-9b35-187c92820bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>c94ef9dc-f6bb-4279-8e0b-75686e367b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-8718-input' and @placeholder = 'Search...']</value>
      <webElementGuid>99944a5c-a291-4e99-ad5e-6c22ff9df1d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
