<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action Button - Ask quotation</name>
   <tag></tag>
   <elementGuidId>f192333e-f86c-4c01-a93d-54b84b90d33c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='actionbutton-ask-quotation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionbutton-ask-quotation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>925dfe7f-7c48-4880-b4a1-fd6a1886044a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-primary ng-star-inserted</value>
      <webElementGuid>a764a555-19ce-4f27-b2f5-272449bce868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionbutton-ask-quotation</value>
      <webElementGuid>fdcd7066-fa43-45be-830c-fea483f252c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ask quotation</value>
      <webElementGuid>82496479-37ab-48b2-b2be-31c97e0dc6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionbutton-ask-quotation&quot;)</value>
      <webElementGuid>c664cf81-095b-47d4-9a06-b5788ae04acf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='actionbutton-ask-quotation']</value>
      <webElementGuid>1465284c-48c6-4250-9231-fbff0b6f9ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/div/app-action-bar/div/div[3]/app-action-buttons/div/div[3]/button</value>
      <webElementGuid>5e5d98cd-1af2-4907-ab56-f7c9a671815f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save as pending'])[1]/following::button[1]</value>
      <webElementGuid>0291af66-c1f3-42af-88fd-a37c9bc1c53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New transport request'])[1]/following::button[2]</value>
      <webElementGuid>fb060816-7a4e-4f97-97cf-2361253f3fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm quote'])[1]/preceding::button[1]</value>
      <webElementGuid>782dee24-7cde-44ed-a5c6-c8e2c05f4716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>357a7fb8-f055-4db8-ab4e-e6d81d33b977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'actionbutton-ask-quotation' and (text() = 'Ask quotation' or . = 'Ask quotation')]</value>
      <webElementGuid>dc3fb01a-f329-423d-8d5c-7747ad362a3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
