<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pre-carriage</name>
   <tag></tag>
   <elementGuidId>45f8f459-b172-4702-b147-4fc770a107ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id=&quot;dfc-dyn-root--multi-modal-form--segments&quot;]//button)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5301243-03b2-4abe-b38f-f5156d70548c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c773c73-10e2-45fb-bc69-391eef4bdc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary</value>
      <webElementGuid>92455861-18d5-4795-8b97-8da58514a0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pre-carriage </value>
      <webElementGuid>bf73bffd-ad5a-4c55-8510-538f0a81b4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--multi-modal-form--segments&quot;)/app-multi-modal-selector[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;df-form-control-root&quot;]/div[@class=&quot;df-form-control-item&quot;]/div[@class=&quot;add-segment-buttons ng-star-inserted&quot;]/button[@class=&quot;btn btn-outline-primary&quot;]</value>
      <webElementGuid>74588f63-d7d3-4b5f-bf37-b4237f994e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>0c344b98-e5f1-4462-b21b-46d9f7cab934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--multi-modal-form--segments']/app-multi-modal-selector/div/div/div/button</value>
      <webElementGuid>213b6c73-d5de-4059-aa84-54bd4a4759fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a segment type'])[1]/following::button[1]</value>
      <webElementGuid>8dd271ae-17ab-4bd8-b8f7-d26adca74365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ce champs est obligatoire'])[2]/following::button[1]</value>
      <webElementGuid>8612d0ac-f17c-438d-9fae-e1ee5260a51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main transport'])[1]/preceding::button[1]</value>
      <webElementGuid>2fcb078e-bb1a-4a14-8628-6ecc56424b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post-carriage'])[1]/preceding::button[2]</value>
      <webElementGuid>8233cedd-f7e8-4845-a581-511a416def1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pre-carriage']/parent::*</value>
      <webElementGuid>bf0acbf3-2d61-45e2-9b6c-4a329a42197b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-multi-modal-selector/div/div/div/button</value>
      <webElementGuid>b8655e3b-71c2-4836-bb42-8e2a32e6c427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Pre-carriage ' or . = ' Pre-carriage ')]</value>
      <webElementGuid>40a3f8c2-49a1-43f8-97ac-03d7705c5658</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
