<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_label</name>
   <tag></tag>
   <elementGuidId>0e152e85-35d4-4391-b05a-61dcfc7c4bc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--multi-modal-form--label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--multi-modal-form--label > #dfc-item--multi-modal-form--label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3f65077-ba46-4847-9ef2-c87b4bac9593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>a9a77d44-445d-497c-ab2d-c3d321b647c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--multi-modal-form--label</value>
      <webElementGuid>40244260-3868-44b1-8494-8fbc863508f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9c08dcb4-334a-47b1-b473-377cce2b913f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f9c2843c-2943-446d-8b7f-268850b63a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>918007d6-d5f4-4a85-b006-8c52ef18d4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>9cb0acf9-f101-487d-a7d6-833bdbe2f3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--multi-modal-form--label&quot;)/div[@id=&quot;dfc-item--multi-modal-form--label&quot;]/input[@id=&quot;dfc-item--multi-modal-form--label&quot;]</value>
      <webElementGuid>8933f38c-f606-47be-bd5e-bdce7f5446fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--multi-modal-form--label']</value>
      <webElementGuid>79bfa354-f4c9-4ad2-8463-3c97582829b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--multi-modal-form--label']/input</value>
      <webElementGuid>9469b5ea-71e7-45ec-aac4-1e299363707f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/input</value>
      <webElementGuid>629137c7-9bba-47d0-ba22-65eb4aa4b0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--multi-modal-form--label' and @name = 'label' and @placeholder = 'label' and @type = 'text']</value>
      <webElementGuid>3c551e79-41c5-41ea-b31b-cb5dda0ed9db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
