<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active false</name>
   <tag></tag>
   <elementGuidId>7f71d0e2-c401-4be0-acbc-93c77c5f5749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--type-of-variant-form--active--false']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--type-of-variant-form--active--false</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54c48383-2d3a-4dc9-b036-71c0e0a988d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cbcdeb40-2dc7-493b-86e9-04add4559098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--type-of-variant-form--active--false</value>
      <webElementGuid>8e431820-4709-4bbf-89a8-b46629aab224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>91233d20-b1f5-47ac-93a1-50f0c290a106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--type-of-variant-form--active--false&quot;)</value>
      <webElementGuid>66c9fd2d-df56-47a9-9949-2bbe4ed9a742</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--type-of-variant-form--active--false']</value>
      <webElementGuid>cb622abd-83e4-419b-a447-95297e4cde85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--type-of-variant-form--active']/div[2]/input</value>
      <webElementGuid>0da8afcb-7003-430c-af35-797e89161077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/div[2]/input</value>
      <webElementGuid>2bf043ce-9967-4561-93e1-4135b7787150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--type-of-variant-form--active--false']</value>
      <webElementGuid>559af1f9-dd3e-4f94-96dd-6ab40de3332f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
