<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active true</name>
   <tag></tag>
   <elementGuidId>436755f5-102b-4929-ae23-05593cb80e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--type-of-variant-form--active--true']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--type-of-variant-form--active--true</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>963ac8a0-3b10-475d-8517-04839265bacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9aba1e6f-b197-433e-91b3-db8379eeafa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--type-of-variant-form--active--true</value>
      <webElementGuid>f22f2ca3-7503-4280-ac1a-869ab0a68dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>79601fc3-68a1-494c-9978-3bc4018958d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--type-of-variant-form--active--true&quot;)</value>
      <webElementGuid>88afff1d-db46-4af3-a41d-1e86b9c9cd68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--type-of-variant-form--active--true']</value>
      <webElementGuid>7fccc795-90e4-4ccd-8db0-05becf1c8fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--type-of-variant-form--active']/div/input</value>
      <webElementGuid>317fcb04-c9cb-48a4-bd56-de310910c74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/div/input</value>
      <webElementGuid>7cb13b51-01c9-4fbf-8192-cb011a7ab738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--type-of-variant-form--active--true']</value>
      <webElementGuid>e2ee594b-1b16-477a-8e35-718d03c4422f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
