<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type of variants Code Dashboard</name>
   <tag></tag>
   <elementGuidId>65186bf5-9877-4937-84c7-394bea845b35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label=&quot;Code Filter Input&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-45-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9af46fd9-d388-47eb-a61b-b088c0ba2d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>fb09541e-1121-4c8e-97e4-3c333f599dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>416d51f0-0291-4e7d-9cb3-a5b9dbbe7475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5410337f-cc85-48d7-9df4-71dcf4739867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-45-input</value>
      <webElementGuid>dc4d39f8-8106-4802-b5ba-687d32565445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Code Filter Input</value>
      <webElementGuid>64918109-f552-4b8e-b07f-dd92689dd3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-45-input&quot;)</value>
      <webElementGuid>10d22914-764c-4c7f-9683-9e1f207b1236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-45-input']</value>
      <webElementGuid>36b259ce-8d86-489f-ba4c-e30c640c4057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-list-type-of-variants/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>bb63a6df-8683-4ba5-bd54-357358789a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>e6d7816a-285a-4453-9445-8da6189817c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-45-input']</value>
      <webElementGuid>12dc4417-2026-4c27-9f01-435d5bac5905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
