<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Module_Tracking</name>
   <tag></tag>
   <elementGuidId>d2cda6aa-9007-4056-add0-eff32c7f11c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='module_tracing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.my-icon-track</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ca4e990-f41a-46f6-8a6c-23d2a9999d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-icon-track</value>
      <webElementGuid>1fcac3b8-66d4-454a-b501-3c71e03d4511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module_tracing&quot;)/span[@class=&quot;my-icon-track&quot;]</value>
      <webElementGuid>eac67733-d6b7-49a7-8b42-0d29ed13ae7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='module_tracing']/span</value>
      <webElementGuid>b3476459-3ca5-4826-934b-d670896cf3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span</value>
      <webElementGuid>6d35c712-3ded-414e-9d9c-a0afbc132e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
