<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Module_Transport</name>
   <tag></tag>
   <elementGuidId>8bc10bff-cd7a-4808-8abb-e2f1a4f3834b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='module_transport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.my-icon-trans-management</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b66530e-a3e3-4be5-b806-4d004a37e024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-icon-trans-management</value>
      <webElementGuid>5bf91812-b933-49cf-95e0-201b6f055b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module_transport&quot;)/span[@class=&quot;my-icon-trans-management&quot;]</value>
      <webElementGuid>244fe6bc-4b3e-44c8-b0ac-b551eb1c92f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='module_transport']/span</value>
      <webElementGuid>889da37d-2fd4-413d-bc58-5de29fb583ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>e6b50b50-387b-47cf-afb5-154c67acc876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
