<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Module</name>
   <tag></tag>
   <elementGuidId>482be2b2-02f0-4477-8270-b4a45b3b47a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='modules-wrapper__btn']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>91bd2361-df0a-4921-b14c-7ed22b6bc955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-th</value>
      <webElementGuid>014f7980-a9e1-417f-bea8-746353c6ce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modules-wrapper__btn&quot;)/i[@class=&quot;fa fa-th&quot;]</value>
      <webElementGuid>e2144fcc-2e6c-4166-87d6-dec6955d6bfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='modules-wrapper__btn']/i</value>
      <webElementGuid>abb15405-cd46-4bfd-bc8f-08d6694cd7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/i</value>
      <webElementGuid>0282125a-ee22-4c80-a33d-cc2fb608b4d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
