<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of reason code</name>
   <tag></tag>
   <elementGuidId>c77d476f-f071-441f-9c66-d203713b1378</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='numCodeRaison']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;numCodeRaison&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a703088-39cd-4dba-a50c-d571ca813760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>39b6ce81-05c0-4e2d-92eb-0d9bdf29c9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numCodeRaison</value>
      <webElementGuid>1f1a0dc2-d5dc-437d-ba96-47b405625a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a13696a3-1011-41be-81e3-b50c17c6b21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-mapping-code-psl-details[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;col-md-12 form-mappingcodepsl__wrapper padding-10 ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;padding-bottom-10 d-flex-ai-c padding-right-0 generic-inputs__style col-md-6 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-md-9 col-sm-12 col-xs-12 input-wrapper padding-right-0&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>cde7d795-4c88-4866-800c-a61bc022ac5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='numCodeRaison']</value>
      <webElementGuid>34d86ac2-2cf2-4065-9604-eedf07f9300c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-mapping-code-psl-details/form/div/div/div[7]/div/input</value>
      <webElementGuid>1175cea2-cfb7-4159-a448-fc353ba39dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>adc11df3-2532-4fef-a288-a68efc0e2ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'numCodeRaison']</value>
      <webElementGuid>9713a5f5-cc14-4056-88e8-66556bfbd398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
