<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descriptive reason code</name>
   <tag></tag>
   <elementGuidId>aca7fe7f-27e9-4b01-800c-e1e2b9f666e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='descriptiveCodeRaison']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;descriptiveCodeRaison&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee937697-3b39-4d97-ba65-80ca586267c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f1ce045-609c-4797-b711-e7ffc7285d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>descriptiveCodeRaison</value>
      <webElementGuid>63c97e5a-0e34-4edd-a4d8-e0f9dc42c8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1124c4e2-3e0e-420e-9314-ee1c4810e5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-mapping-code-psl-details[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;col-md-12 form-mappingcodepsl__wrapper padding-10 ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;padding-bottom-10 d-flex-ai-c padding-right-0 generic-inputs__style col-md-6 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-md-9 col-sm-12 col-xs-12 input-wrapper padding-right-0&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>1e49a9a2-9033-4373-bfef-aa586ff15715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='descriptiveCodeRaison']</value>
      <webElementGuid>48f5996d-3ccf-4499-bed9-b97e1596a7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-mapping-code-psl-details/form/div/div/div[10]/div/input</value>
      <webElementGuid>7593abcb-2169-4b4f-b8d0-a077f3db4eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>39d2036e-8eb7-4eff-acd7-a8c7b8613ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'descriptiveCodeRaison']</value>
      <webElementGuid>016bb74a-8a3c-435f-a64c-0b4678988a16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
