<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Normalized psl code</name>
   <tag></tag>
   <elementGuidId>174e86b6-ec51-474c-9680-f486e3ba31ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='codePslNormalise']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;codePslNormalise&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d04a341c-2024-49f2-8af7-d01b02cc3588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b02ac94-45de-49d2-b52a-b81eca02c8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>codePslNormalise</value>
      <webElementGuid>6cbfc17d-bc8a-4f9b-8b3c-ec7f53bca1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0028be1a-da51-4a8c-bdd8-cc6006cfc440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-mapping-code-psl-details[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;col-md-12 form-mappingcodepsl__wrapper padding-10 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;padding-bottom-10 d-flex-ai-c padding-right-0 generic-inputs__style col-md-6 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-md-9 col-sm-12 col-xs-12 input-wrapper padding-right-0&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>c90efa21-aed7-4f90-845c-15e74dea3d68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='codePslNormalise']</value>
      <webElementGuid>318ec6cc-e8e0-47d4-a887-8cb93359eb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-mapping-code-psl-details/form/div/div/div/div/input</value>
      <webElementGuid>a284a692-cfce-4fd0-a1d7-c1ca7bb74bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6db98d54-0c5a-4d34-9ec5-7c050c9b7e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'codePslNormalise']</value>
      <webElementGuid>4b7148ea-fc01-4fbe-9271-3a26d4d4f677</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
