<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Event Type</name>
   <tag></tag>
   <elementGuidId>2065a251-84a0-4e4b-bc73-ec95d993e86c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='typeEvent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;typeEvent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ab92d32-f27b-4216-9d06-4f4e7166bd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeEvent</value>
      <webElementGuid>fd7232f6-5555-405e-9f98-c8ce1ce0c767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>197fe8c0-2830-4fd3-9715-099dae93ed60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New event New incident  Unconformity </value>
      <webElementGuid>afa19a6f-8084-4d21-a50e-3b669bb89888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-mapping-code-psl-details[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;col-md-12 form-mappingcodepsl__wrapper padding-10 ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;padding-bottom-10 d-flex-ai-c padding-right-0 generic-inputs__style col-md-6 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-md-9 col-sm-12 col-xs-12 input-wrapper padding-right-0&quot;]/select[@class=&quot;form-control ng-pristine ng-invalid ng-touched&quot;]</value>
      <webElementGuid>4cfdcba4-f690-4746-b9fc-a4b64bc6b147</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='typeEvent']</value>
      <webElementGuid>a3a65423-662c-4e0f-b15f-dfd572576b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-mapping-code-psl-details/form/div/div/div[3]/div/select</value>
      <webElementGuid>3ae753ef-428a-41b9-bed5-be0f4c73e497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event type'])[1]/following::select[1]</value>
      <webElementGuid>699ce5a1-cbc3-44bc-993f-d634dec19664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrier psl code'])[1]/following::select[1]</value>
      <webElementGuid>d88739c6-6136-43e8-80b8-221b5cce3035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipper'])[1]/preceding::select[1]</value>
      <webElementGuid>3786dd2a-a1d3-40d7-b3a5-7e5a2ed95252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select shipper'])[1]/preceding::select[1]</value>
      <webElementGuid>05857d97-e4a7-4a5c-8aae-853685fe9675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>172a539e-f703-4e85-98ed-b79d88d567ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'typeEvent' and (text() = 'New event New incident  Unconformity ' or . = 'New event New incident  Unconformity ')]</value>
      <webElementGuid>4269c756-eefa-47a3-930d-01b7925b524b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
