<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header - Filter - Value - Cancelled</name>
   <tag></tag>
   <elementGuidId>4d0d8f32-cf0a-49c3-b1c1-18346c9d7cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-8796-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'ag-set-filter-item')]//div[@ref = 'eCheckbox' and div[text() = 'Cancelled'] ]//input[@type = 'checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3863cad0-9b8c-479c-aa9e-fd4cb3a67ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eLabel</value>
      <webElementGuid>10c3a481-8da4-4384-a44e-7d79fece4d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-label ag-label ag-checkbox-label</value>
      <webElementGuid>9d4f8ade-f055-4b1c-bbf8-44def75f2032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-8796-label</value>
      <webElementGuid>f8d82fba-8462-4f47-9078-1d2e540b6742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelled</value>
      <webElementGuid>11afcba6-194a-4c96-9022-5acf246c7322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-8796-label&quot;)</value>
      <webElementGuid>20bbf57d-7252-4258-9724-161bdb6bf2ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ag-8796-label']</value>
      <webElementGuid>fd05f353-7b1f-4d6e-b391-593e6af597fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-pricing-list/app-transport-common-list/div/ag-grid-angular/div/div[6]/div/div[2]/div/div/div/div/div[4]/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>9936814c-7a4b-4591-a7c7-8d863945a779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Select All)'])[1]/following::div[5]</value>
      <webElementGuid>84c50b10-3a24-4f7b-b5e7-2276c0e21d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No matches.'])[1]/following::div[13]</value>
      <webElementGuid>c1e268ae-c75f-4173-bd30-43f5ae29491d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelled for consolidation'])[1]/preceding::div[2]</value>
      <webElementGuid>c860dd2d-ba89-4850-bcef-aa7e55fc45c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[9]</value>
      <webElementGuid>a4fdad4f-d252-455c-8c5e-a25cc2723158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancelled']/parent::*</value>
      <webElementGuid>7e2d2d3e-34cd-426e-832f-a4bb337fdcf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>38e04b37-a505-46c2-ac4b-be8d17ba26a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ag-8796-label' and (text() = 'Cancelled' or . = 'Cancelled')]</value>
      <webElementGuid>38c37b82-9982-4a73-bf78-10094eca9ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
