<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status_TR_Cancelled</name>
   <tag></tag>
   <elementGuidId>de16b999-2a83-4bff-b1ab-f15c796a8d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formStatusBar-chip-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formStatusBar-chip-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>849a9857-14eb-47e2-8a57-20135b5d168e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formStatusBar-chip-text</value>
      <webElementGuid>a875b359-c65f-4801-9f75-46ef6a4cf704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chip ng-star-inserted</value>
      <webElementGuid>d6410b8b-2968-406b-b763-da5b19962123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancelled </value>
      <webElementGuid>2bc95795-99be-4a78-94ca-e7293c9397ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formStatusBar-chip-text&quot;)</value>
      <webElementGuid>8f52b9d1-5ec5-4d0d-82f5-a599c9410602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='formStatusBar-chip-text']</value>
      <webElementGuid>e01e9912-1075-4c72-885b-b47c123071a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formStatusBar-chip']/div</value>
      <webElementGuid>161d0220-5afa-4cb1-bb68-e4a850b084a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/following::div[9]</value>
      <webElementGuid>0fa7907f-301f-4223-ac75-e47b13cc8298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alerts'])[1]/following::div[9]</value>
      <webElementGuid>a6f5ff98-fe23-4d71-81fb-9f3ff57d19d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelled at 10/10/2022 by f.salaheddine@mytower.fr'])[1]/preceding::div[1]</value>
      <webElementGuid>09e53e4e-6a8f-4963-b11b-bda39a8d7f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicated from : ESC-A17150'])[1]/preceding::div[3]</value>
      <webElementGuid>9ae8d5bf-b277-4bdc-93fc-02e11461883b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancelled']/parent::*</value>
      <webElementGuid>5c61d925-ee78-4e10-a637-c384e5f27a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-form-statusbar/div/div/div</value>
      <webElementGuid>3ceff2b4-030a-4da2-a6d1-061edd885e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'formStatusBar-chip-text' and (text() = ' Cancelled ' or . = ' Cancelled ')]</value>
      <webElementGuid>8ac43a83-2e12-4aa0-9ea8-52c247ad2ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
