<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code</name>
   <tag></tag>
   <elementGuidId>8bebc0ad-af6f-4b7d-9682-b7602d30fd0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--type-of-packaging-form--code > #dfc-item--type-of-packaging-form--code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--type-of-packaging-form--code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cc191a1-abdb-413f-96d8-4012ca25268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>c08dd6d8-792a-46ce-b641-423fb83ad073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--type-of-packaging-form--code</value>
      <webElementGuid>816af5f4-95ff-479b-853b-cc9dd2e04f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>5ee04823-9995-470d-b04b-81c193735a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>4c22a3fd-63ed-4eb9-b402-70685388c5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa98bd1d-dbe8-4dff-9265-6e5d991ddc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>7f4816b5-f9c1-4a75-82b8-d0b4adb8ce4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--type-of-packaging-form--code&quot;)/div[@id=&quot;dfc-item--type-of-packaging-form--code&quot;]/input[@id=&quot;dfc-item--type-of-packaging-form--code&quot;]</value>
      <webElementGuid>d6b4cbdc-7170-41ef-bfa3-27569ee5f356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--type-of-packaging-form--code']</value>
      <webElementGuid>d12116a1-06c4-4c44-b53b-7c20d2f680c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--type-of-packaging-form--code']/input</value>
      <webElementGuid>2f3d7354-b4a1-45ae-818c-596f8dbad8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/input</value>
      <webElementGuid>12381372-4bc4-4a1b-933d-b5f84e9741c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--type-of-packaging-form--code' and @name = 'code' and @placeholder = 'Code' and @type = 'text']</value>
      <webElementGuid>f9efa4f3-2468-4953-8bff-cde16d3ac95a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
