<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label</name>
   <tag></tag>
   <elementGuidId>ad011295-7330-47fd-80b7-49fa9e18271d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--type-of-packaging-form--label > #dfc-item--type-of-packaging-form--label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--type-of-packaging-form--label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f127a23-b510-42ec-878a-173eced9a238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>125c871f-251f-42cf-8b35-0237192f99ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--type-of-packaging-form--label</value>
      <webElementGuid>76c91272-6df5-4c39-bf88-34b0f3d970e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>56defb02-0ed4-4953-80c8-dc49e1dee915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>d51b7873-641f-4379-bb68-ab6e817aa7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1caea30e-c726-4c6c-ae17-68f31c65d3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>78faf037-18bd-4161-8a35-adca219c6858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--type-of-packaging-form--label&quot;)/div[@id=&quot;dfc-item--type-of-packaging-form--label&quot;]/input[@id=&quot;dfc-item--type-of-packaging-form--label&quot;]</value>
      <webElementGuid>9bda8ad2-8067-45b6-8e82-0caef94aefd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--type-of-packaging-form--label']</value>
      <webElementGuid>b1db16c7-41fb-479d-925e-8f668cb7906e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--type-of-packaging-form--label']/input</value>
      <webElementGuid>981cad22-0851-45ea-8667-bb8a33685611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[2]/div/div/input</value>
      <webElementGuid>4a8f6d0c-28d7-44b5-b094-b0ba0c8a6d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--type-of-packaging-form--label' and @name = 'label' and @placeholder = 'Label' and @type = 'text']</value>
      <webElementGuid>597607a8-4f0d-4b9f-8dc7-ad9a71bee782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
