<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Created by</name>
   <tag></tag>
   <elementGuidId>7237d2c9-5aa2-4f29-a45b-1dc86d2fd2d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--type-of-packaging-form--createdByName > #dfc-item--type-of-packaging-form--createdByName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--type-of-packaging-form--createdByName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a384886a-6b3e-43fa-b55c-840dc6eed7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>1ecb45e4-173c-4752-805a-97c1f68ded53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--type-of-packaging-form--createdByName</value>
      <webElementGuid>3b73aca1-efc0-4c25-8134-f1ad2b27c1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>createdByName</value>
      <webElementGuid>ade9f739-b526-4578-a5c4-315858a45612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Created by</value>
      <webElementGuid>203a64d2-5617-49e3-8b08-fe64a575d0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5f9e2ab-45b2-4acb-a56c-3bf70f3a2fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>07dc21db-a054-437a-ad61-315364ed83df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--type-of-packaging-form--createdByName&quot;)/div[@id=&quot;dfc-item--type-of-packaging-form--createdByName&quot;]/input[@id=&quot;dfc-item--type-of-packaging-form--createdByName&quot;]</value>
      <webElementGuid>003de3f9-c8ce-47c7-b74a-c4bb04652d59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--type-of-packaging-form--createdByName']</value>
      <webElementGuid>97f0b34a-6cd9-43f6-8d29-6e7a7db30b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--type-of-packaging-form--createdByName']/input</value>
      <webElementGuid>8d693a54-b9c1-4f74-84d6-019094686fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[4]/div/div/input</value>
      <webElementGuid>92e8d907-f0df-41b7-9d2b-5854a7515137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--type-of-packaging-form--createdByName' and @name = 'createdByName' and @placeholder = 'Created by' and @type = 'text']</value>
      <webElementGuid>86b5b875-4514-4369-8b23-24ac43ea993e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
