<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OriginDestination user</name>
   <tag></tag>
   <elementGuidId>9d8938db-bad2-455b-8efc-e45b765c4799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-creation-form--xEbUserVisibility > #dfc-item--address-creation-form--xEbUserVisibility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-creation-form--xEbUserVisibility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b0329af-72f1-4509-b9c5-8b8a067fc4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>ee7acb38-e3d5-4f23-bc0f-461d9de15a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-creation-form--xEbUserVisibility</value>
      <webElementGuid>3c86f520-103d-4c07-91e7-506a2b2f948a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>xEbUserVisibility</value>
      <webElementGuid>14d668f2-63b9-4c89-80e5-7b7519cfe4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Origin/Destination user</value>
      <webElementGuid>83800cb1-2b32-4710-9f79-c774b1891634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ef695e3-b7ac-4ef2-81d9-f7b58fcb8122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>eec4b9da-c2f0-48ee-a562-5f37f1bfe2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-creation-form--xEbUserVisibility&quot;)/div[@id=&quot;dfc-item--address-creation-form--xEbUserVisibility&quot;]/input[@id=&quot;dfc-item--address-creation-form--xEbUserVisibility&quot;]</value>
      <webElementGuid>590e81ca-b1fe-4d67-8fca-aa75d686738f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-creation-form--xEbUserVisibility']</value>
      <webElementGuid>24c95c6c-df08-4a80-adc7-b583d944dc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-creation-form--xEbUserVisibility']/input</value>
      <webElementGuid>88d46cc4-3e9e-4fbf-bb98-e2335b8d14b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[19]/div/div/input</value>
      <webElementGuid>8f16fcb1-5656-44dd-9dba-1aa1028285e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-creation-form--xEbUserVisibility' and @name = 'xEbUserVisibility' and @placeholder = 'Origin/Destination user' and @type = 'text']</value>
      <webElementGuid>7e3ad084-66d4-409e-9e8a-7d1ad356d0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
