<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Additional address 2_secondaryAdditionalAddress</name>
   <tag></tag>
   <elementGuidId>e2668a4d-b95c-425b-a548-aff85316abbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-creation-form--secondaryAdditionalAddress > #dfc-item--address-creation-form--secondaryAdditionalAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-creation-form--secondaryAdditionalAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e387ad17-e680-4c1c-8d6f-bcc3c1f5dc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>9479882c-d081-4faf-a62d-f618341d09f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-creation-form--secondaryAdditionalAddress</value>
      <webElementGuid>bf343377-b9ec-46ea-992d-c21f2ae21350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondaryAdditionalAddress</value>
      <webElementGuid>274ee171-35ef-48ca-926e-9b19b5892a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional address 2</value>
      <webElementGuid>0fbdecb7-3b52-4cbc-bccb-6fd520d42767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>162bd5ab-315b-46a5-83ab-e65d6928c56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>93d8476c-ae41-447c-99f4-20f0555a0605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-creation-form--secondaryAdditionalAddress&quot;)/div[@id=&quot;dfc-item--address-creation-form--secondaryAdditionalAddress&quot;]/input[@id=&quot;dfc-item--address-creation-form--secondaryAdditionalAddress&quot;]</value>
      <webElementGuid>c00d9464-f979-4394-981d-f804d58f31d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-creation-form--secondaryAdditionalAddress']</value>
      <webElementGuid>7f973c20-b30e-49af-86f6-7f7fff3c1f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-creation-form--secondaryAdditionalAddress']/input</value>
      <webElementGuid>99b3f52b-5912-4272-b500-f00100745097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[7]/div/div/input</value>
      <webElementGuid>99ecc2ed-0ab6-4cde-a90e-e885c711fdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-creation-form--secondaryAdditionalAddress' and @name = 'secondaryAdditionalAddress' and @placeholder = 'Additional address 2' and @type = 'text']</value>
      <webElementGuid>d15aec98-434c-45fa-81af-8b77848c0a2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
