<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recipients identity</name>
   <tag></tag>
   <elementGuidId>d7e7c005-e54b-4732-8790-12ed9c541cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-creation-form--recipientIdentification > #dfc-item--address-creation-form--recipientIdentification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-creation-form--recipientIdentification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70759617-f47f-4e2d-917e-c4f827f84cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>47db8332-9829-42e2-8e22-ca93cdde7d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-creation-form--recipientIdentification</value>
      <webElementGuid>846f97dc-5dd1-4319-abbd-bc995ded7fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>recipientIdentification</value>
      <webElementGuid>9b9c84ad-8fb9-4336-a615-ae2699619c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Recipient’s identity</value>
      <webElementGuid>6f4b6b92-53a2-4c33-9411-db4bf02c94e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ddedfd4-a22d-409e-820d-dd72611ff35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>77c6dab6-93fd-4a73-8434-5ec8c1503ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-creation-form--recipientIdentification&quot;)/div[@id=&quot;dfc-item--address-creation-form--recipientIdentification&quot;]/input[@id=&quot;dfc-item--address-creation-form--recipientIdentification&quot;]</value>
      <webElementGuid>085144f0-c22e-40e1-b9df-e1578bae18f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-creation-form--recipientIdentification']</value>
      <webElementGuid>9238d0d3-4e1d-4e83-b28f-c0d519d3adc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-creation-form--recipientIdentification']/input</value>
      <webElementGuid>1a286837-f13b-4891-ba5d-857c46d399ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[4]/div/div/input</value>
      <webElementGuid>48995dac-f414-4cdd-9145-7a49fcb72a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-creation-form--recipientIdentification' and @name = 'recipientIdentification' and @placeholder = 'Recipient’s identity' and @type = 'text']</value>
      <webElementGuid>d2930adf-dc24-4f2c-a945-07838b401743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
