<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference</name>
   <tag></tag>
   <elementGuidId>cb0ef2b1-f013-42b6-a9d9-9aa88791edd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-creation-form--reference > #dfc-item--address-creation-form--reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-creation-form--reference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1de7fe8e-146f-47e5-b105-4a6465ab672a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>48faaa2a-2d8f-4a2a-951d-f7749b0d83d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-creation-form--reference</value>
      <webElementGuid>5444fd52-7c29-4861-babd-a0a93e9e83ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>7aa5788a-f773-4f8e-8cd2-6763a799d488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>62953e1a-49a1-4898-ac35-7f5ab5f2f208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de940e5b-959e-43fa-8d03-fb256c3bcd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>a2ac5819-d9d4-41ac-988f-80f714734e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-creation-form--reference&quot;)/div[@id=&quot;dfc-item--address-creation-form--reference&quot;]/input[@id=&quot;dfc-item--address-creation-form--reference&quot;]</value>
      <webElementGuid>0d8d2004-225f-478c-bd69-e8b37c37b7e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-creation-form--reference']</value>
      <webElementGuid>e3e5c2ca-7677-4241-960d-d5825a37f8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-creation-form--reference']/input</value>
      <webElementGuid>00726344-d928-4720-aee7-7d505eece05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[2]/div/div/input</value>
      <webElementGuid>c5504c37-c9c7-4f8e-882e-7ae1a43fa2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-creation-form--reference' and @name = 'reference' and @placeholder = 'Reference' and @type = 'text']</value>
      <webElementGuid>d91cca67-ecdd-48ac-8d57-03e8c9955558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
