<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Additional address_secondaryStreet</name>
   <tag></tag>
   <elementGuidId>9719a4ec-aa26-450b-89b9-272790a2a7d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-creation-form--secondaryStreet > #dfc-item--address-creation-form--secondaryStreet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-creation-form--secondaryStreet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9076bc31-5114-4c81-954e-5527665c79a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>2edd1101-f438-473d-840d-3659e24d8034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-creation-form--secondaryStreet</value>
      <webElementGuid>a5351e09-1156-457e-8ae3-46d838f4226d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondaryStreet</value>
      <webElementGuid>2a5e8abe-9b28-4bc1-9d72-e9a405c73779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Additional address</value>
      <webElementGuid>8875c9fa-22ff-4a66-80ca-30dfb691bbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc53833f-ac33-45cc-aa05-1a17fe693641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>e8b083e7-3fa6-4af6-bb03-b1da9810a8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-creation-form--secondaryStreet&quot;)/div[@id=&quot;dfc-item--address-creation-form--secondaryStreet&quot;]/input[@id=&quot;dfc-item--address-creation-form--secondaryStreet&quot;]</value>
      <webElementGuid>b4733cc9-4719-4060-882a-fa053b9eec99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-creation-form--secondaryStreet']</value>
      <webElementGuid>4c527943-1760-4bc9-9b1b-79d71e5f2389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-creation-form--secondaryStreet']/input</value>
      <webElementGuid>0662a6fc-037f-4150-a174-94d9ab76782c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[6]/div/div/input</value>
      <webElementGuid>8f1ac457-e91d-4034-8fd4-09c89dfdffba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-creation-form--secondaryStreet' and @name = 'secondaryStreet' and @placeholder = 'Additional address' and @type = 'text']</value>
      <webElementGuid>bdbefe90-f640-4eb3-9f88-31b658429547</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
