<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Opening hours</name>
   <tag></tag>
   <elementGuidId>3362b9a4-fc4b-484c-bca5-4b0f4df148bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-creation-form--openingHoursFreeText > #dfc-item--address-creation-form--openingHoursFreeText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-creation-form--openingHoursFreeText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>481f61fa-20a4-41b1-b56c-b7aaea011450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>fced07b3-2fa7-42e4-91c5-1078a5421af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-creation-form--openingHoursFreeText</value>
      <webElementGuid>0b06aa0a-8f8f-4f32-bb80-7e49275a9ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>openingHoursFreeText</value>
      <webElementGuid>104a85b9-6c9d-4bd2-bfb7-e0bdfe0160b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Opening hours</value>
      <webElementGuid>de6913e1-bd59-419b-a811-f9656a2c3f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7ab8a9f-eb3f-48f5-9a23-c03b27aca452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>d9eb36ed-99f0-4767-8c98-0599957c522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-creation-form--openingHoursFreeText&quot;)/div[@id=&quot;dfc-item--address-creation-form--openingHoursFreeText&quot;]/input[@id=&quot;dfc-item--address-creation-form--openingHoursFreeText&quot;]</value>
      <webElementGuid>c0d481e8-1fce-4872-88d1-c7bbde761665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-creation-form--openingHoursFreeText']</value>
      <webElementGuid>04fd971e-ee1b-4633-ab24-def7961d245c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-creation-form--openingHoursFreeText']/input</value>
      <webElementGuid>a4fd178e-03cd-416d-9418-8aa9ad144f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[15]/div/div/input</value>
      <webElementGuid>96415ce5-7fe1-4aa1-9ffd-f5a8e4e63118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-creation-form--openingHoursFreeText' and @name = 'openingHoursFreeText' and @placeholder = 'Opening hours' and @type = 'text']</value>
      <webElementGuid>3f1182dc-39ba-4f7f-b16e-806aed3afbf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
