<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AirportPort</name>
   <tag></tag>
   <elementGuidId>f559cc79-d613-4f5d-b474-f47dc43f2e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-creation-form--airport > #dfc-item--address-creation-form--airport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-creation-form--airport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da0a8b52-9d93-460e-aa33-b5c00b55bcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>69e4cf93-fba7-4901-af64-cf90490ec6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-creation-form--airport</value>
      <webElementGuid>eff90671-dcac-4593-9c0f-e0ae5447efdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>airport</value>
      <webElementGuid>6d8c90fe-7eab-4d04-bdfb-b129e73b35ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Airport/Port</value>
      <webElementGuid>69d50a38-2c3a-43e9-9145-caacb521ae56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a791fa8-e520-4fa6-bff7-c9d94a4994a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>2206adc2-abfc-4b17-8c7c-575b93b96119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-creation-form--airport&quot;)/div[@id=&quot;dfc-item--address-creation-form--airport&quot;]/input[@id=&quot;dfc-item--address-creation-form--airport&quot;]</value>
      <webElementGuid>783a0776-df8f-4744-a0c8-b11cf2cb6d06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-creation-form--airport']</value>
      <webElementGuid>e66e80d0-f018-40c2-8ad1-f34c904350d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-creation-form--airport']/input</value>
      <webElementGuid>b22656b8-04e4-4f70-8e2d-6e6c431d2103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[12]/div/div/input</value>
      <webElementGuid>2d9d2ed5-812c-4db5-93c3-73e56f054b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-creation-form--airport' and @name = 'airport' and @placeholder = 'Airport/Port' and @type = 'text']</value>
      <webElementGuid>ace95316-3c7f-4756-8244-a1efeefe90bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
