<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Latitude</name>
   <tag></tag>
   <elementGuidId>e8af5437-c302-4718-b323-0cb4fd422b52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-creation-form--latitude > #dfc-item--address-creation-form--latitude</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-creation-form--latitude']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b225a13c-8f24-4a30-9139-dd078514b88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>9ea13105-2bc2-46cd-bb27-e5e54cdc99a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-creation-form--latitude</value>
      <webElementGuid>08bc283f-e01c-4e1e-9f44-5134d8c075ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>latitude</value>
      <webElementGuid>494fd643-f853-4f77-8dcb-a6321a8d70e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Latitude</value>
      <webElementGuid>f7d81580-7c7b-4428-bfac-77df1bc5fbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>101b9b5e-a3c0-427d-a56c-8f71c563c672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-star-inserted ng-dirty</value>
      <webElementGuid>8d274aba-6e10-4e34-a861-b5158837da05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-creation-form--latitude&quot;)/div[@id=&quot;dfc-item--address-creation-form--latitude&quot;]/input[@id=&quot;dfc-item--address-creation-form--latitude&quot;]</value>
      <webElementGuid>473bfed4-aec1-47f9-9f9f-e4b151e38f9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-creation-form--latitude']</value>
      <webElementGuid>357ee1a6-608d-4929-a611-76c3f5aaad6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-creation-form--latitude']/input</value>
      <webElementGuid>bbbc4974-8652-4f92-bd8b-5a0be75acb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[24]/div/div/input</value>
      <webElementGuid>599f12e2-b31b-4f6a-b925-1ba01ff78c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-creation-form--latitude' and @name = 'latitude' and @placeholder = 'Latitude' and @type = 'number']</value>
      <webElementGuid>f9488c63-dae4-4688-834f-5f92b2db3381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
