<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Key Dashboard</name>
   <tag></tag>
   <elementGuidId>fbf512f3-2a68-4daf-8526-89ae7c9a683e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label=&quot;Key Filter Input&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-30-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49ee6649-55d2-4329-86d2-16f28962eaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>01819ad9-874a-4320-9be0-2a7bdb394bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>84e3d91d-5ea7-4b03-8cc9-1cf8f9d735d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24a8ee71-7ce8-4279-b69c-8d121873e93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-30-input</value>
      <webElementGuid>a09f2826-ad58-4829-abdc-fcd0bd4ffc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Code Filter Input</value>
      <webElementGuid>39fd15b8-833a-447b-9941-04790e9a8556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-30-input&quot;)</value>
      <webElementGuid>ffd0169b-5bd5-4a11-b51d-48c1f0b08744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-30-input']</value>
      <webElementGuid>76bba16e-3b8d-4c7a-bb5f-b192c4cb9578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-refusal-reason-list/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>26cf19a6-57dc-4520-bfbd-ab8f6fb18f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>d259a07c-572d-4fca-8bd5-10536f05c4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-30-input']</value>
      <webElementGuid>9e52e233-09da-4580-b579-447428e350d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
