<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description</name>
   <tag></tag>
   <elementGuidId>f99a4330-77a0-42ac-95a9-cec81393a027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--refusal-reason-form--reasonDescription > #dfc-item--refusal-reason-form--reasonDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--refusal-reason-form--reasonDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f943dd4f-2b3a-45ef-9c2a-5e6ba020ed3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>eb38db4a-e6ed-45c5-aa68-e70e978ae324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--refusal-reason-form--reasonDescription</value>
      <webElementGuid>1c48c17a-aecf-4010-b369-f32df02d1a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reasonDescription</value>
      <webElementGuid>9e2b6f24-f08c-4cdb-8cf6-7a6059e2a1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>6c027962-8674-4479-a72c-f5cf4b3fa723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e925bd23-7df2-4ebd-9e67-3a9e21004e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>2c44d5b8-7be2-4590-9da6-c929509b584c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--refusal-reason-form--reasonDescription&quot;)/div[@id=&quot;dfc-item--refusal-reason-form--reasonDescription&quot;]/input[@id=&quot;dfc-item--refusal-reason-form--reasonDescription&quot;]</value>
      <webElementGuid>48510deb-2017-4c06-be8a-eb94377fef6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--refusal-reason-form--reasonDescription']</value>
      <webElementGuid>2a480dc3-92cb-43b9-a5cc-cd2cdece5363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--refusal-reason-form--reasonDescription']/input</value>
      <webElementGuid>85a4f27b-8aa8-49a2-8cc1-d8a8e0700710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/input</value>
      <webElementGuid>9fbb095c-9f9e-470c-afd2-411809d1391f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--refusal-reason-form--reasonDescription' and @name = 'reasonDescription' and @placeholder = 'Description' and @type = 'text']</value>
      <webElementGuid>d40b56f2-d343-4c56-bacc-e5e4658f6730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
