<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Key</name>
   <tag></tag>
   <elementGuidId>b0aa84ca-1407-4001-9ada-3ea12e396231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--refusal-reason-form--reasonKey > #dfc-item--refusal-reason-form--reasonKey</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--refusal-reason-form--reasonKey']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e447b75-bab6-4481-b61b-e39492f40a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>7d9c5e92-f743-445f-b87a-b2d8955427a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--refusal-reason-form--reasonKey</value>
      <webElementGuid>c1c75483-7dc2-4d5c-ad87-43f13011fbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reasonKey</value>
      <webElementGuid>75e81867-c453-4aab-bbd6-cfbecdee08e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>78a82722-36fc-4e43-b158-1364524e5ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f553208b-f872-4ea1-9773-194fd5d3a7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>78972b5a-7504-4e02-9405-ef51b3dee661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--refusal-reason-form--reasonKey&quot;)/div[@id=&quot;dfc-item--refusal-reason-form--reasonKey&quot;]/input[@id=&quot;dfc-item--refusal-reason-form--reasonKey&quot;]</value>
      <webElementGuid>cfb4cd26-0fb9-4caa-9671-5624a9b37a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--refusal-reason-form--reasonKey']</value>
      <webElementGuid>3abe461e-960f-49cd-9ae6-3061ea6bd4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--refusal-reason-form--reasonKey']/input</value>
      <webElementGuid>1e0e299f-44bd-4605-8158-7cc802d4cd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[2]/div/div/input</value>
      <webElementGuid>80b15c92-18bd-4f27-9cc5-f45df1183dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--refusal-reason-form--reasonKey' and @name = 'reasonKey' and @placeholder = 'Code' and @type = 'text']</value>
      <webElementGuid>12bbe84f-abb2-4a53-ba02-14d929fc1476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
