<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code</name>
   <tag></tag>
   <elementGuidId>9ae89aef-9a63-43a7-a3e7-32f1a65c7c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--incident-category-form--code > #dfc-item--incident-category-form--code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--incident-category-form--code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d46f855-2498-45aa-a68b-ad9fad959737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>aef196a2-5077-4894-8dac-801f046744e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--incident-category-form--code</value>
      <webElementGuid>0e7b19de-5368-4769-b828-d56a70b59e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>964971cf-8d34-4b6f-a42f-c86174832579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>3fc695bc-09ed-451f-8d8c-66fb257ea9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>598a5a4c-2b2f-42ba-9990-7ffd9b749a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>40b75028-0fd1-492b-80f8-1d05e66aa549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--incident-category-form--code&quot;)/div[@id=&quot;dfc-item--incident-category-form--code&quot;]/input[@id=&quot;dfc-item--incident-category-form--code&quot;]</value>
      <webElementGuid>905ad620-cb2d-4f94-9808-52d01290013e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--incident-category-form--code']</value>
      <webElementGuid>00fb56e4-4b5b-49fa-aa64-f4a449c7b2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--incident-category-form--code']/input</value>
      <webElementGuid>051b0e86-ce6f-48af-bcd5-4e3e309154de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/input</value>
      <webElementGuid>5b967cbe-9403-4a58-bc0e-93111bab8caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--incident-category-form--code' and @name = 'code' and @placeholder = 'Code' and @type = 'text']</value>
      <webElementGuid>bf7af46d-161e-4b68-9bd1-79eb8d1343b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
