<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label</name>
   <tag></tag>
   <elementGuidId>540cfdcf-361a-4483-a87e-fbf99d7499c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--incident-category-form--label > #dfc-item--incident-category-form--label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--incident-category-form--label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>412da58a-3ce2-4c17-90fa-d75ba0865185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>c8f5ac58-5204-460e-b925-0295df3ad721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--incident-category-form--label</value>
      <webElementGuid>7f61fc72-b12b-43d4-aff7-56fdf71f1a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9076bd45-5135-4725-8785-dbf634ddeb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>8e3b2213-0b9a-4bfa-9f99-606e1296acd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0ad5781-eedd-448e-97f6-da000e826803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>ee7745c0-6fbb-444f-a4d7-150016b8c7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--incident-category-form--label&quot;)/div[@id=&quot;dfc-item--incident-category-form--label&quot;]/input[@id=&quot;dfc-item--incident-category-form--label&quot;]</value>
      <webElementGuid>05c2b4f6-8405-40a0-a9b7-ddc68106a99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--incident-category-form--label']</value>
      <webElementGuid>5c31facc-f252-4416-bfb6-556b1c02b190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--incident-category-form--label']/input</value>
      <webElementGuid>cf522ed8-1967-48db-b97c-9fb63553ea3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[4]/div/div/input</value>
      <webElementGuid>3e470a07-5ed5-4035-b419-a62bd2129678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--incident-category-form--label' and @name = 'label' and @placeholder = 'Label' and @type = 'text']</value>
      <webElementGuid>3ca5cc63-4b33-43f4-8afd-84a2ed99a04f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
