<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code Incident category Dashboard</name>
   <tag></tag>
   <elementGuidId>bc684a00-f595-4305-9c22-0e020278e7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-1745-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label=&quot;Code Filter Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08e71694-abe1-43ab-ba4d-41e5e050670c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>7d21d45e-f2a8-4046-aad2-f9f2c1dcb300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>bbf76456-a886-4364-9862-102fb1de9969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6dfe748-b9e1-4fa9-88ed-7f7f7b346b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-1745-input</value>
      <webElementGuid>2a2d465d-88bc-4bda-83c0-2502a33b22f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Code Filter Input</value>
      <webElementGuid>bd3767a2-5ffc-4746-8f4b-a2bc4b29831e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-1745-input&quot;)</value>
      <webElementGuid>2caa6ddc-f832-4a3a-838f-dc9f2416835d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-1745-input']</value>
      <webElementGuid>8ff83d3d-0237-4ad7-a4a5-bec61e012ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-list-incident-category/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>47ffc0e7-453d-4dd1-a134-dd34a4818a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>ac46b809-46af-4a1e-819e-00a57aef2096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-1745-input']</value>
      <webElementGuid>558b9f4b-0ae4-428e-8f8e-eedf24927839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
