<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order</name>
   <tag></tag>
   <elementGuidId>78a135cc-9576-466d-896f-1c82154d3144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--incident-category-form--order > #dfc-item--incident-category-form--order</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--incident-category-form--order']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>147cc707-1ba3-4806-86b6-bee406f1436f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>721e3dd5-b703-4d20-a321-1532eb11454e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--incident-category-form--order</value>
      <webElementGuid>3897e6ac-ea8c-400f-973a-0c23d1354087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order</value>
      <webElementGuid>5ed06185-1275-4dc7-b096-5b814c8b51d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Order</value>
      <webElementGuid>8b01b120-7165-493c-9df8-8358de3f370a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>db1dbbbe-8fbf-4259-90a9-721b92e31372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>ea4d29b0-0eda-4071-a6a0-4bdafcaf66ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--incident-category-form--order&quot;)/div[@id=&quot;dfc-item--incident-category-form--order&quot;]/input[@id=&quot;dfc-item--incident-category-form--order&quot;]</value>
      <webElementGuid>15bac344-5e9f-477d-9962-2ec6f16802fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--incident-category-form--order']</value>
      <webElementGuid>a37c0c78-7d6e-4e72-adf8-6add4cae1719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--incident-category-form--order']/input</value>
      <webElementGuid>0f77102c-86f6-4f72-936a-0c68741b5b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[5]/div/div/input</value>
      <webElementGuid>566fa03e-833d-4046-90eb-4a3b9adf9a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--incident-category-form--order' and @name = 'order' and @placeholder = 'Order' and @type = 'number']</value>
      <webElementGuid>e86cc3f9-a248-4cec-834c-9b272df77b5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
