<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select the first option</name>
   <tag></tag>
   <elementGuidId>e93cff06-229f-445a-9691-db7f7a413708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--incident-category-form--incidentType']/option[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a12bd38e-3417-4c7f-a44b-8afac863bc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1670431466905</value>
      <webElementGuid>56836429-88a0-4670-8abe-7a1312db02ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
