<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Incident type</name>
   <tag></tag>
   <elementGuidId>943d8be1-c73e-4fb5-b7c3-2492b285b6ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--incident-category-form--incidentType > #dfc-item--incident-category-form--incidentType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--incident-category-form--incidentType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e5ac7b1e-740b-42da-8c0f-66d8a864d1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--incident-category-form--incidentType</value>
      <webElementGuid>c99c6a32-1b9a-46ba-b97c-64bc4d3dfb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>incidentType</value>
      <webElementGuid>bbdeb930-20bc-423e-a9c1-03a501fc12a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-invalid ng-star-inserted ng-touched</value>
      <webElementGuid>77ebb786-7e75-44c5-983e-1a9d7de3b614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INCIDENTUNCONFORMITY</value>
      <webElementGuid>981ac1f7-aded-4589-acfd-83d5b4cc6fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--incident-category-form--incidentType&quot;)/div[@id=&quot;dfc-item--incident-category-form--incidentType&quot;]/select[@id=&quot;dfc-item--incident-category-form--incidentType&quot;]</value>
      <webElementGuid>558f23c3-8e56-4ec6-955f-0c3304658f87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--incident-category-form--incidentType']</value>
      <webElementGuid>c0879cba-b2a2-48b7-93af-d553605d8bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--incident-category-form--incidentType']/select</value>
      <webElementGuid>c7874006-230e-4235-baf6-0b848f1f48b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident type'])[2]/following::select[1]</value>
      <webElementGuid>eef8b033-716a-4816-a853-d37f6540b8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Category'])[3]/following::select[1]</value>
      <webElementGuid>a38e1e4e-a145-43ed-93f5-04454a97ea2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ce champs est obligatoire'])[4]/preceding::select[1]</value>
      <webElementGuid>07bd0e04-00e7-4eaa-a942-a0f53b97d91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>79da18e5-79fe-4430-8d03-3d43956b407d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>319e7c18-eb55-4a08-ada1-c9d533b5459b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--incident-category-form--incidentType' and @name = 'incidentType' and (text() = 'INCIDENTUNCONFORMITY' or . = 'INCIDENTUNCONFORMITY')]</value>
      <webElementGuid>e1223838-cd79-4450-8f97-1101e9e41a96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
