<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>9a7f84d3-75da-493c-844d-bb503738f6e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-toastitem//a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ui-toast-close-icon.pi.pi-times.ng-tns-c331-35.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61fdcc54-96b2-4efc-b206-5885afc47944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d61055ee-80ad-4e85-a235-cff3720d25a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-toast-close-icon pi pi-times ng-tns-c331-35 ng-star-inserted</value>
      <webElementGuid>0a32319e-9a16-41be-b468-c1955c4f838f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;aurora-theme&quot;]/body[@class=&quot;background app-wrapper aurora-theme&quot;]/app-root[1]/p-toast[@class=&quot;ng-tns-c332-0&quot;]/div[@class=&quot;ng-tns-c332-0 ui-toast ui-widget ui-toast-top-right&quot;]/p-toastitem[@class=&quot;ng-tns-c331-35 ng-trigger ng-trigger-toastAnimation ng-tns-c332-0 ng-star-inserted&quot;]/div[@class=&quot;ui-toast-message ui-shadow ng-tns-c331-35 ng-trigger ng-trigger-messageState ui-toast-message-info&quot;]/div[@class=&quot;ui-toast-message-content ng-tns-c331-35&quot;]/a[@class=&quot;ui-toast-close-icon pi pi-times ng-tns-c331-35 ng-star-inserted&quot;]</value>
      <webElementGuid>3446fddf-418b-4adf-b6da-3c64caeb927a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>76f47c81-d008-432b-b758-8df4d2a035ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
