<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Delivery Note</name>
   <tag></tag>
   <elementGuidId>40f739b8-2cf3-4993-8aca-d99abf25ac0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_delivery_note_unit > #dfc-item--transport-unit-content-form--item_delivery_note_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_delivery_note_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6f360ba-1c12-4167-b660-95843d86c112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>3b7058b9-c3dc-43ee-ab20-212bce0ccac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_delivery_note_unit</value>
      <webElementGuid>8e98ccaa-4128-4f5f-8374-f470c16b5fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_delivery_note_unit</value>
      <webElementGuid>5d33e999-4e62-4791-a580-10a0601e85df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Delivery Note</value>
      <webElementGuid>e83bc96f-91c4-4311-bc63-dd7b8ce07a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d219a337-48ff-474a-9302-c3eec9b10475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>d11650b8-e1dd-47fe-bccc-02789a002912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_delivery_note_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_delivery_note_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_delivery_note_unit&quot;]</value>
      <webElementGuid>2303d0bd-1319-4d44-9b36-e1e6a0360ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_delivery_note_unit']</value>
      <webElementGuid>69364688-2440-4c8e-b0cf-53c8ad1ae725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_delivery_note_unit']/input</value>
      <webElementGuid>3f4a29f9-64d5-4c04-9796-4ff0e0f5cfc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[33]/div/div/input</value>
      <webElementGuid>ef0c9b2c-8aa4-426e-9237-117d73f06141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_delivery_note_unit' and @name = 'item_delivery_note_unit' and @placeholder = 'Item Delivery Note' and @type = 'text']</value>
      <webElementGuid>27654053-dcc9-43c2-bd3d-502018c6dcc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
