<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Original Warehouse</name>
   <tag></tag>
   <elementGuidId>8a9cf4b4-a95b-4524-b3cd-a025eb308d0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_original_warehouse_unit > #dfc-item--transport-unit-content-form--item_original_warehouse_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_original_warehouse_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46ed3448-3420-4ac3-8af7-e488563faec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>81c20d9d-6feb-4f7c-b674-c1067d0b1bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_original_warehouse_unit</value>
      <webElementGuid>17e5ad52-5179-42c5-a558-81685e383278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_original_warehouse_unit</value>
      <webElementGuid>0364bce6-bb55-4f38-bf2b-e6d8a3cacc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Original Warehouse</value>
      <webElementGuid>218ea08d-cc6e-4a6f-b29d-5bcc42fac302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c11c74cc-c69b-4b93-9a44-ad85d4e138d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>384dcd9a-8f6d-48a6-96b3-3c1e2c898260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_original_warehouse_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_original_warehouse_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_original_warehouse_unit&quot;]</value>
      <webElementGuid>e8a92e4a-713f-4f4f-a6ca-da7f77385986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_original_warehouse_unit']</value>
      <webElementGuid>a129dafb-9c76-46a0-bdb8-0cd1b6bda94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_original_warehouse_unit']/input</value>
      <webElementGuid>f90f41a3-1095-436a-b8ff-b52c75f33f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[57]/div/div/input</value>
      <webElementGuid>4962e0bd-2092-4059-a848-d1be4ed8e2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_original_warehouse_unit' and @name = 'item_original_warehouse_unit' and @placeholder = 'Item Original Warehouse' and @type = 'text']</value>
      <webElementGuid>c8459184-5785-4f6e-a3a4-ab512f42aeb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
