<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Net weight (Kg)</name>
   <tag></tag>
   <elementGuidId>0b0f2163-ae10-4a84-9a9a-b54695ad76b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--unitaryNetWeight > #dfc-item--transport-unit-content-form--unitaryNetWeight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--unitaryNetWeight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3da9559b-2384-40bd-9de0-50d4c78663f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>5b82a3dd-b961-4dce-9747-8e28cfcd9821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--unitaryNetWeight</value>
      <webElementGuid>e49671a4-525f-484c-ade6-9b4ecf403f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>469728f2-c4fd-4b0b-aafc-b457f5af56a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitaryNetWeight</value>
      <webElementGuid>69421b7a-1804-40f8-bc34-156bf8a51bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Net weight (Kg)</value>
      <webElementGuid>be99dfd5-597a-472e-a48b-782607194618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>bf2daeaf-6b36-489d-98e3-5dea9d9e6d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>7720e544-6b0f-4c26-ac03-9e93dad7b4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--unitaryNetWeight&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--unitaryNetWeight&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--unitaryNetWeight&quot;]</value>
      <webElementGuid>eceeeb21-508e-4cfe-8d54-ef383691137a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--unitaryNetWeight']</value>
      <webElementGuid>9c21b068-57ac-4288-9cd4-2883588ab912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--unitaryNetWeight']/input</value>
      <webElementGuid>0ee6fd2e-f0a5-4167-bfe1-8434d01087f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[5]/div/div/input</value>
      <webElementGuid>dfeee8ca-ba41-47ea-91dc-a700c0509883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--unitaryNetWeight' and @name = 'unitaryNetWeight' and @placeholder = 'Net weight (Kg)' and @type = 'number']</value>
      <webElementGuid>7fdcc799-5729-4f54-a818-05ccef32111c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
