<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Net Weight</name>
   <tag></tag>
   <elementGuidId>c1ccc78d-d147-45f8-ba1f-3758b37916f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_net_weight_unit > #dfc-item--transport-unit-content-form--item_net_weight_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_net_weight_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03cfd132-6a44-4606-92ee-c0c9c0706527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>0d0096da-b3b5-47a7-b5ce-63e52520c738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_net_weight_unit</value>
      <webElementGuid>a1901942-bf75-4910-aa22-ba04a542181e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_net_weight_unit</value>
      <webElementGuid>bdae0e37-86e3-476c-8375-2aba67fbe009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Net Weight</value>
      <webElementGuid>d2a2cfac-32b5-497a-bd40-26dc597cc5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c289737-f166-40f6-b23b-e93c2abb5eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>3529b0d2-6a6c-4f82-9166-d53a7a8f4ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_net_weight_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_net_weight_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_net_weight_unit&quot;]</value>
      <webElementGuid>701268f1-b470-4bde-9c9c-0d57937b35c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_net_weight_unit']</value>
      <webElementGuid>1a99eee0-4d59-47f5-bcdf-d08d097b9ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_net_weight_unit']/input</value>
      <webElementGuid>0db0d89d-2e88-4a64-88a8-bebe79995385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[10]/div/div/input</value>
      <webElementGuid>3cf4658c-502e-4d8a-8c8a-f32033bcaf3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_net_weight_unit' and @name = 'item_net_weight_unit' and @placeholder = 'Item Net Weight' and @type = 'text']</value>
      <webElementGuid>2034ae2f-4fa2-4e75-bdad-6f489eb6ea21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
