<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Order Nbr</name>
   <tag></tag>
   <elementGuidId>9ba71796-d35d-4930-8a6d-7b984ff24770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_order_nbr_unit > #dfc-item--transport-unit-content-form--item_order_nbr_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_order_nbr_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d625ab1-780d-4636-8b66-a5ab4fefc166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>c342c8e5-a995-4a23-8a7e-0cda951736bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_order_nbr_unit</value>
      <webElementGuid>d34fe5cb-7f16-4199-84bf-bd59d97715eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_order_nbr_unit</value>
      <webElementGuid>507a52d6-72ff-4111-94d0-e871789c3852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Order Nbr</value>
      <webElementGuid>b4cced9f-769a-46e9-b73b-c902ef9b69ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3176d3a9-f410-4598-8174-88912a50c4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>b9cd258c-cbda-4339-8262-6cb260852360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_order_nbr_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_order_nbr_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_order_nbr_unit&quot;]</value>
      <webElementGuid>8b4345b9-cd12-4962-8d5d-68359bdafe78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_order_nbr_unit']</value>
      <webElementGuid>3961ef98-157d-427c-9652-c80a146f46d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_order_nbr_unit']/input</value>
      <webElementGuid>02138110-ff1d-4b26-9e04-323ecda5e8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[54]/div/div/input</value>
      <webElementGuid>6df1cc10-f7c9-42e0-a717-e13136f33bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_order_nbr_unit' and @name = 'item_order_nbr_unit' and @placeholder = 'Item Order Nbr' and @type = 'text']</value>
      <webElementGuid>fb069222-df7d-48c8-a41c-37df040d8d00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
