<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Unit Price</name>
   <tag></tag>
   <elementGuidId>cc0740ab-dd7f-4bf3-b77d-01ca573a15e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_unit_price_unit > #dfc-item--transport-unit-content-form--item_unit_price_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_unit_price_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca465e84-76f7-4ae7-804e-5ad0575a58f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>6c2fd1e7-c00f-4cf6-93ff-4b457341b4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_unit_price_unit</value>
      <webElementGuid>71e68c41-241f-4af3-be9e-32ef1f96701b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_unit_price_unit</value>
      <webElementGuid>b02bf866-0dbe-4b38-aa9a-d8db2b51e231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Unit Price</value>
      <webElementGuid>8f0b37b1-351a-44b8-99f6-a7cdc6195918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f209ac77-0644-4e7f-8ff9-bcaa95521241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>3d9f8894-ac8a-49a9-b567-8f78b5b4e83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_unit_price_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_unit_price_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_unit_price_unit&quot;]</value>
      <webElementGuid>d2fc7d36-0a7a-4bf6-b9a1-bbae1cbe6f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_unit_price_unit']</value>
      <webElementGuid>3ddab8cc-c9aa-4ada-9433-2da70351e191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_unit_price_unit']/input</value>
      <webElementGuid>c588e7fd-8fd0-4cb7-83ba-b14a0e9a1053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[48]/div/div/input</value>
      <webElementGuid>a7eb9c0c-c9ae-4251-a1ab-305c8696814b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_unit_price_unit' and @name = 'item_unit_price_unit' and @placeholder = 'Item Unit Price' and @type = 'number']</value>
      <webElementGuid>2f0cc377-0102-40a3-af0a-c3c0d07bb07c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
