<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Preferential Origin</name>
   <tag></tag>
   <elementGuidId>35c1294c-6ce7-4938-b2a0-4ba5cc54d2dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_preferential_origin_unit > #dfc-item--transport-unit-content-form--item_preferential_origin_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_preferential_origin_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9df4f1b-9c8f-4f42-9e67-7f9a62f19a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>75c674bd-fe2d-45ff-865c-9c263215e735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_preferential_origin_unit</value>
      <webElementGuid>fadbb8ca-a3ae-4544-88f9-5705ed434193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_preferential_origin_unit</value>
      <webElementGuid>994fd2a1-ac6c-4a42-b950-26cdd24f8c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Preferential Origin</value>
      <webElementGuid>a8603fc5-f961-43fc-8c81-f5800d625126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2635e835-163d-4c7a-a39c-905c2c07f5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>62d167a2-bde4-4200-af37-edc7640f18e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_preferential_origin_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_preferential_origin_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_preferential_origin_unit&quot;]</value>
      <webElementGuid>7438a9e8-3a35-4a20-a420-47bbf10407be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_preferential_origin_unit']</value>
      <webElementGuid>44b890f2-7c48-40bc-86f8-e911a5fc6c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_preferential_origin_unit']/input</value>
      <webElementGuid>386d14ec-c7d4-4c63-84a0-964426cbd0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[62]/div/div/input</value>
      <webElementGuid>a65ef0ac-25ca-4173-baff-a99f2dc838cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_preferential_origin_unit' and @name = 'item_preferential_origin_unit' and @placeholder = 'Item Preferential Origin' and @type = 'text']</value>
      <webElementGuid>ac09cb63-2b3e-43f4-a906-25a77d9f189a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
