<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Customs Value EUR</name>
   <tag></tag>
   <elementGuidId>b0c4bc94-921f-4e80-92df-efc5e92c2453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_customs_value_eur_unit > #dfc-item--transport-unit-content-form--item_customs_value_eur_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_customs_value_eur_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>646ab24b-66dd-4f45-8f37-b2296408793d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>dfb0fd1f-d357-4aaa-88ca-34d3d4b1beba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_customs_value_eur_unit</value>
      <webElementGuid>1134ee30-270c-44b9-80c8-1cf7032a739f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_customs_value_eur_unit</value>
      <webElementGuid>b98975af-9c93-4b02-8931-fc7e71d44689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Customs Value EUR</value>
      <webElementGuid>26a32aad-c1bc-41fa-ae49-378e1c1acf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56a5f973-02e4-4980-934a-b2c63acab1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>0020c263-127a-4aa3-aef3-6cfb31d9a14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_customs_value_eur_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_customs_value_eur_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_customs_value_eur_unit&quot;]</value>
      <webElementGuid>9d499fb6-cc25-4ed0-ba6f-6df1ba9a580d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_customs_value_eur_unit']</value>
      <webElementGuid>de919d67-30e3-4201-b642-1d3e16098c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_customs_value_eur_unit']/input</value>
      <webElementGuid>8d075b95-b1c4-4209-9f39-dc3a09444ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[29]/div/div/input</value>
      <webElementGuid>ad8c4492-0f53-44a3-abde-448b300365a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_customs_value_eur_unit' and @name = 'item_customs_value_eur_unit' and @placeholder = 'Item Customs Value EUR' and @type = 'text']</value>
      <webElementGuid>1d9f99e9-5807-43b8-9bcc-7a3804787c72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
