<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Manufacture Proces</name>
   <tag></tag>
   <elementGuidId>35a04162-fef8-41fa-b582-b34278189fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_manufacture_proces_unit > #dfc-item--transport-unit-content-form--item_manufacture_proces_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_manufacture_proces_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11616f10-e85f-4427-8857-ef0787b3ced1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>62f80439-7b6b-4149-88d4-4b5f92f2fb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_manufacture_proces_unit</value>
      <webElementGuid>d04f780d-baef-4204-863e-41fd40a98a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_manufacture_proces_unit</value>
      <webElementGuid>ef6600ed-26f9-4db7-b272-ba5560384079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Manufacture Proces</value>
      <webElementGuid>b12fd475-40e3-400f-b0d4-b745f5eacd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14a45c66-7d44-42eb-8a9c-ba9207bff84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>00f18bf2-7a4b-4644-82e6-3f47f6342454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_manufacture_proces_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_manufacture_proces_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_manufacture_proces_unit&quot;]</value>
      <webElementGuid>135518a8-c93e-4cb4-a2c5-9649861314f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_manufacture_proces_unit']</value>
      <webElementGuid>cdf9c280-0b1c-44ea-8ee4-adc0aa85dfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_manufacture_proces_unit']/input</value>
      <webElementGuid>27fdcaa1-f2a3-4c77-bd8e-a6dab65c2726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[46]/div/div/input</value>
      <webElementGuid>53672f21-15ed-469f-93a0-e96a10967762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_manufacture_proces_unit' and @name = 'item_manufacture_proces_unit' and @placeholder = 'Item Manufacture Proces' and @type = 'text']</value>
      <webElementGuid>469bb57a-ae7e-4d2e-b8c9-1dc6d2b3f51f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
