<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Packing Slip</name>
   <tag></tag>
   <elementGuidId>2312b1d9-c08e-47da-9887-c7528db512ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_packing_slip_unit > #dfc-item--transport-unit-content-form--item_packing_slip_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_packing_slip_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afbd156b-1ef7-4c64-a46d-27e2bc6a500c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>326c9511-f255-4854-a3c2-20d73d9ef67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_packing_slip_unit</value>
      <webElementGuid>7e8745b9-6d15-4255-bdfb-b8a1f87e3ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_packing_slip_unit</value>
      <webElementGuid>edf9dea8-d26c-4733-97ee-362568b107b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Packing Slip</value>
      <webElementGuid>c4d99e89-044b-4dd0-baae-97382aadf080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91cd4d2d-c100-496b-95ca-390a5b2b56fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>c8d2b97a-c362-4265-be29-6c16bc84112e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_packing_slip_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_packing_slip_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_packing_slip_unit&quot;]</value>
      <webElementGuid>2d533662-963c-4f1b-98d1-735409812f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_packing_slip_unit']</value>
      <webElementGuid>e8e6dd8f-a03b-4585-a009-3bb3cf9776cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_packing_slip_unit']/input</value>
      <webElementGuid>1a000924-c3a2-408f-958c-4495fa7a1acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[27]/div/div/input</value>
      <webElementGuid>0e712a4f-66f5-4092-be55-ed85db27fc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_packing_slip_unit' and @name = 'item_packing_slip_unit' and @placeholder = 'Item Packing Slip' and @type = 'text']</value>
      <webElementGuid>59a6a197-f82b-4586-b049-0f433eb8b465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
