<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Product Line</name>
   <tag></tag>
   <elementGuidId>1dfc500a-68b1-4332-84b4-7e579703bfa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_product_line_unit > #dfc-item--transport-unit-content-form--item_product_line_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_product_line_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>705d9a85-c0c3-40be-a450-a1940258defa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>be95ccfa-4060-4301-a0e0-c7d890006ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_product_line_unit</value>
      <webElementGuid>c0a83cba-b1e9-45d0-9de3-f909d75b5100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_product_line_unit</value>
      <webElementGuid>a72785be-fb9d-4f0b-90fe-79d3f064ee91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Product Line</value>
      <webElementGuid>3ebf0bba-10bd-41b0-82fc-7116aad94f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36f06a53-f6f5-45fa-9a51-dbb484b67568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>f263bc17-8e54-47f1-bd2d-2028deb323fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_product_line_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_product_line_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_product_line_unit&quot;]</value>
      <webElementGuid>a308d790-f8e5-4d54-b076-1b67cc67aff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_product_line_unit']</value>
      <webElementGuid>3ac4ace2-716e-437a-bda0-d65982037bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_product_line_unit']/input</value>
      <webElementGuid>48cc3743-13fd-4edc-af02-55bdcae8aeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[52]/div/div/input</value>
      <webElementGuid>c4a421c1-0919-4f7f-b766-61fde338b395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_product_line_unit' and @name = 'item_product_line_unit' and @placeholder = 'Item Product Line' and @type = 'text']</value>
      <webElementGuid>8929c520-d14e-4e1c-8366-d79b839b5f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
