<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Customer PO Nbr</name>
   <tag></tag>
   <elementGuidId>f6d36027-6ab2-472f-a2f9-ad271f86bdc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_customer_po_nbr_unit > #dfc-item--transport-unit-content-form--item_customer_po_nbr_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_customer_po_nbr_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58e63f92-abb7-4393-9071-94fdbd3e0272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>c692d0d0-133f-4140-9fbe-9c34136981fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_customer_po_nbr_unit</value>
      <webElementGuid>7e593770-b033-4318-85d4-48cc426298e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_customer_po_nbr_unit</value>
      <webElementGuid>7d9ceeb5-01f2-4ed1-a3b0-a0c278c0ae7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Customer PO Nbr</value>
      <webElementGuid>4b8e8944-b5ef-4fb7-ab2b-538aa82e9e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e2a207a-2048-4153-ae52-745b2596fc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>9867ef5a-6f3f-4faf-8020-92d13544a3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_customer_po_nbr_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_customer_po_nbr_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_customer_po_nbr_unit&quot;]</value>
      <webElementGuid>037a9cab-39ac-47c5-8bfb-8864c320bed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_customer_po_nbr_unit']</value>
      <webElementGuid>5f3aa0d5-6180-48c0-a9a3-1fda03059097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_customer_po_nbr_unit']/input</value>
      <webElementGuid>7e5b77d4-d6ab-4cb5-8a8e-557d82f74ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[56]/div/div/input</value>
      <webElementGuid>1fe65dd7-5578-4952-b1f8-eaa7b67fd2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_customer_po_nbr_unit' and @name = 'item_customer_po_nbr_unit' and @placeholder = 'Item Customer PO Nbr' and @type = 'text']</value>
      <webElementGuid>9000709f-7894-49d1-a607-7f020ef50c35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
