<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item line Invoice comment</name>
   <tag></tag>
   <elementGuidId>a1ed5c08-657e-4039-866f-93eb5ad3be6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_line_invoice_comment_unit > #dfc-item--transport-unit-content-form--item_line_invoice_comment_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_line_invoice_comment_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d25e818-c4df-4e4f-a2c0-1504834d02d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>7e3f98c0-b6ac-4464-a708-c0718612d75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_line_invoice_comment_unit</value>
      <webElementGuid>f8722d8a-94cd-4617-999a-4ef9764539c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_line_invoice_comment_unit</value>
      <webElementGuid>04b045b7-bde9-470c-b75e-0b131520a8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item line Invoice comment</value>
      <webElementGuid>2c912b1f-db8e-44a6-b474-c3ed251141d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95d555bd-142c-4e5f-9072-e8a5f5f543a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ba8cfac3-ae58-4a20-926b-4198ebf19a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_line_invoice_comment_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_line_invoice_comment_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_line_invoice_comment_unit&quot;]</value>
      <webElementGuid>d5c6750d-a577-4673-bbf1-6242eb19f56d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_line_invoice_comment_unit']</value>
      <webElementGuid>9b440c1a-a383-4623-84e4-a4b821514d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_line_invoice_comment_unit']/input</value>
      <webElementGuid>b9d28eaf-e707-48d9-8d37-0703d8c9b488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[32]/div/div/input</value>
      <webElementGuid>19513e83-4a01-4122-a5b0-bcd851e19bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_line_invoice_comment_unit' and @name = 'item_line_invoice_comment_unit' and @placeholder = 'Item line Invoice comment' and @type = 'text']</value>
      <webElementGuid>c8744bc1-d185-4c38-9bc6-dedf83180c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
