<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Line Total Net Amount</name>
   <tag></tag>
   <elementGuidId>c1daf65c-8e23-44d0-87a3-a9d0bb5d72fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_line_total_net_amount_unit > #dfc-item--transport-unit-content-form--item_line_total_net_amount_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_line_total_net_amount_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d9ad676-f6c1-4476-acd9-8f7877f51a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>04899f13-2f56-4188-9d4c-02407781aad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_line_total_net_amount_unit</value>
      <webElementGuid>691be6b3-7cce-48cc-a530-4d613eeca38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_line_total_net_amount_unit</value>
      <webElementGuid>4add06a5-9eb2-4ee1-8ece-b22e119abceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Line Total Net Amount</value>
      <webElementGuid>22144bf4-2484-4106-8289-f3e45023e50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fd857475-a25f-4fc0-93e9-8fe0ebe0f2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>c92fd90c-12f4-4b50-b49f-3b274ce32916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_line_total_net_amount_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_line_total_net_amount_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_line_total_net_amount_unit&quot;]</value>
      <webElementGuid>b1f4d8bb-d4f2-4d20-8cd6-6380dc412df2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_line_total_net_amount_unit']</value>
      <webElementGuid>1289fd9e-8aa7-451d-81a6-2a7a7e6f6148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_line_total_net_amount_unit']/input</value>
      <webElementGuid>ae0dfcef-4621-48ce-b12e-0d6fa02cc9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[61]/div/div/input</value>
      <webElementGuid>27068f22-62bd-40a0-b73a-fce7d45d32ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_line_total_net_amount_unit' and @name = 'item_line_total_net_amount_unit' and @placeholder = 'Item Line Total Net Amount' and @type = 'number']</value>
      <webElementGuid>857ca350-6f86-498b-9091-3b63d133d44b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
