<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Attestation</name>
   <tag></tag>
   <elementGuidId>7fcb89cf-ae8a-40d8-90b1-28ed6b237f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_attestation_unit > #dfc-item--transport-unit-content-form--item_attestation_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_attestation_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff0c0bde-9932-4c3a-91f0-51f541a7314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>04075bb5-6984-4802-add3-e3a664eb1b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_attestation_unit</value>
      <webElementGuid>984cf864-ec58-400a-9e8d-ee74181325af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_attestation_unit</value>
      <webElementGuid>83043f4d-9ff2-4755-844f-227a15d7f2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Attestation</value>
      <webElementGuid>1268ca87-6ccd-40cb-8210-60fc8134f073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81a6aaef-93d8-45bf-9f15-ca1e75b21581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>72d30464-1a9c-4251-9b45-400c6fe1eeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_attestation_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_attestation_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_attestation_unit&quot;]</value>
      <webElementGuid>d1b727d6-fa82-44a5-9d43-4e1f02cb7935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_attestation_unit']</value>
      <webElementGuid>d9d0cb48-d11f-4684-a621-8e71f198d8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_attestation_unit']/input</value>
      <webElementGuid>ef750bfd-cef2-48a2-b25a-61d3fce74152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[51]/div/div/input</value>
      <webElementGuid>de17a767-d147-4ca9-a51f-2b46e6ad5044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_attestation_unit' and @name = 'item_attestation_unit' and @placeholder = 'Item Attestation' and @type = 'text']</value>
      <webElementGuid>4898dbe2-37ac-49a8-8804-371b3cd20a12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
