<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Network</name>
   <tag></tag>
   <elementGuidId>85e245d5-6a36-4c9a-8c59-33b6c46e8ad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_network_unit > #dfc-item--transport-unit-content-form--item_network_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_network_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7eaffb35-1b9b-4b92-8f95-09c7f63910fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>e9eccc1b-40f1-4b0c-9f00-aac20569ce1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_network_unit</value>
      <webElementGuid>3353e9a3-28a3-4da0-99f3-e1f6fa0878c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_network_unit</value>
      <webElementGuid>425040fd-34e2-45d0-b811-7f055751945e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Network</value>
      <webElementGuid>081d22dd-1f67-43a5-867d-0a980edaf8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aaf14ff6-9929-4950-8efd-984b2aad9b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>77bb05a6-b30b-4433-9941-ff7edfcb1110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_network_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_network_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_network_unit&quot;]</value>
      <webElementGuid>676ec107-9a81-407e-8cb1-9f2abb61f519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_network_unit']</value>
      <webElementGuid>b7be34a0-2711-46f3-bc61-703ae99cf89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_network_unit']/input</value>
      <webElementGuid>c43229f4-1835-4097-b3c0-b8458afba664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[36]/div/div/input</value>
      <webElementGuid>7557b627-2624-451c-888d-1d78127c1bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_network_unit' and @name = 'item_network_unit' and @placeholder = 'Item Network' and @type = 'text']</value>
      <webElementGuid>e31def63-4c74-42de-8f38-3e5e69bb34ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
