<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Order Line Nbr</name>
   <tag></tag>
   <elementGuidId>ea6ea589-3d77-4b4e-be6f-b8f147fa8bea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_order_line_nbr_unit > #dfc-item--transport-unit-content-form--item_order_line_nbr_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_order_line_nbr_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0321f479-6297-475c-bdea-1e2241e721dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>c3b36200-4b34-4d05-87c0-934a6bfed7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_order_line_nbr_unit</value>
      <webElementGuid>8c26c5bd-b15e-4ede-8f6a-0cb46856fe60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_order_line_nbr_unit</value>
      <webElementGuid>89040a0e-5d3b-42c7-bf4b-75cf8a493c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Order Line Nbr</value>
      <webElementGuid>2410cef1-5150-4375-bb19-88a180730a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f29747f3-20ad-4a70-aab4-1eb5f78e60f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>7237befb-2d60-4f55-b683-789dca7beb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_order_line_nbr_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_order_line_nbr_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_order_line_nbr_unit&quot;]</value>
      <webElementGuid>6570149e-e5df-4b54-91bc-cf4506573253</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_order_line_nbr_unit']</value>
      <webElementGuid>7ba7583e-eccd-425a-b6be-435e0c2a6bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_order_line_nbr_unit']/input</value>
      <webElementGuid>3bd9abd8-49b3-4fe3-be3e-18c1baf6634c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[55]/div/div/input</value>
      <webElementGuid>8840f76e-2064-415f-96cd-80ba262f8eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_order_line_nbr_unit' and @name = 'item_order_line_nbr_unit' and @placeholder = 'Item Order Line Nbr' and @type = 'text']</value>
      <webElementGuid>3511273e-f8a0-47e2-8ce8-992f14ca48ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
