<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Claim Nbr</name>
   <tag></tag>
   <elementGuidId>57d4b7b9-27e6-430f-8f6f-0a1a16067cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_claim_nbr_unit > #dfc-item--transport-unit-content-form--item_claim_nbr_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_claim_nbr_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7744152b-0f3e-4340-98df-3fb6159065eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>baa2a9ed-1bdb-4969-a8e7-ca126de0699f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_claim_nbr_unit</value>
      <webElementGuid>15a6eaa3-7722-45b2-ada5-26df6e98eec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_claim_nbr_unit</value>
      <webElementGuid>82657e8e-aaac-46de-bf56-1744425c177c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Claim Nbr</value>
      <webElementGuid>63cc59e9-826e-496c-b209-19e26561cc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>234d5a0f-9ee3-4b35-a3b9-eaf39d52eeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>08a95a01-b2e2-443d-9ee7-0cee18ab87fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_claim_nbr_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_claim_nbr_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_claim_nbr_unit&quot;]</value>
      <webElementGuid>9af4414a-d929-4393-8a15-ea37df95b1e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_claim_nbr_unit']</value>
      <webElementGuid>38205591-a404-4163-9df5-48d98f0dc6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_claim_nbr_unit']/input</value>
      <webElementGuid>b2216912-95d2-4688-b077-d98f773e461a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[34]/div/div/input</value>
      <webElementGuid>c0623121-13e6-4505-81e4-d7fc8f0f1e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_claim_nbr_unit' and @name = 'item_claim_nbr_unit' and @placeholder = 'Item Claim Nbr' and @type = 'text']</value>
      <webElementGuid>eea87136-1bc8-4fe7-ac0e-8d3753ac6a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
