<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Itemdescription</name>
   <tag></tag>
   <elementGuidId>7b387828-941e-4371-a21a-ff0607fe7e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--itemdescription_transport_request > #dfc-item--transport-unit-content-form--itemdescription_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--itemdescription_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba45f3c1-310a-4a0a-a9c8-81388b8092d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>1ff96aa2-fc0a-42ff-ad5e-9223a6f7a087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--itemdescription_transport_request</value>
      <webElementGuid>e1b687be-28f5-4251-996e-d69accfe84a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemdescription_transport_request</value>
      <webElementGuid>9474fa5a-18de-4ae3-9089-c1680d02f494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Itemdescription</value>
      <webElementGuid>51f285e4-e349-4391-a830-09838beb37c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fcd211a-a372-4503-907d-430ad9adb983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>1c48470b-9064-4876-bde0-64f83fd3918d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--itemdescription_transport_request&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--itemdescription_transport_request&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--itemdescription_transport_request&quot;]</value>
      <webElementGuid>3c89736d-a981-442e-abef-233253bdd68f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--itemdescription_transport_request']</value>
      <webElementGuid>906d27c3-5f6c-4859-a0ae-a3cfb45430b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--itemdescription_transport_request']/input</value>
      <webElementGuid>8535d8d7-7c38-458f-9334-9e41076e9a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[8]/div/div/input</value>
      <webElementGuid>664300d0-5308-4a31-bdcd-16c2b210ab9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--itemdescription_transport_request' and @name = 'itemdescription_transport_request' and @placeholder = 'Itemdescription' and @type = 'text']</value>
      <webElementGuid>a2774ae4-de84-4dff-a86a-7c14ab0db8d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
