<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item QtySize</name>
   <tag></tag>
   <elementGuidId>b12c5b9b-e7ec-49df-8feb-831455590e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_qty_size_unit > #dfc-item--transport-unit-content-form--item_qty_size_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_qty_size_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b63c6b1b-9b8f-4c65-8e0a-89cd2e794bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>4b80644f-b5ce-4d5c-960d-8fa186f6592b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_qty_size_unit</value>
      <webElementGuid>01fa165e-d2d1-48e9-91cc-cf019c34b9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_qty_size_unit</value>
      <webElementGuid>d5f9b4d0-484c-4c83-8c5c-c60faa4575b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Qty/Size</value>
      <webElementGuid>40dd6025-c4be-4d1e-8c49-f474611793f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40cc9654-e673-48fb-b2d3-eba52557c895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>5a422a19-47ed-49c5-83b4-e29032c71d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_qty_size_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_qty_size_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_qty_size_unit&quot;]</value>
      <webElementGuid>58256b4c-c4fb-423c-83b7-2b0835dfb77b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_qty_size_unit']</value>
      <webElementGuid>f173f895-0a5b-4d00-a702-d013faf4b61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_qty_size_unit']/input</value>
      <webElementGuid>781d58c2-f0d0-495c-b785-860440717f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[39]/div/div/input</value>
      <webElementGuid>66b94659-d701-4e4b-85c6-b18923fcab19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_qty_size_unit' and @name = 'item_qty_size_unit' and @placeholder = 'Item Qty/Size' and @type = 'text']</value>
      <webElementGuid>ad248aba-8564-473b-ad66-551aee7b490c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
