<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Customs Code</name>
   <tag></tag>
   <elementGuidId>136e1fa4-5789-4ba2-a399-be2cb604f291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_customs_code_unit > #dfc-item--transport-unit-content-form--item_customs_code_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_customs_code_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4358142d-3a49-4378-ab3a-d965c121d6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>3e7d8508-2b2f-4896-8455-702a82fc397c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_customs_code_unit</value>
      <webElementGuid>288f0b43-551b-4b4d-87b3-fd5adaf329d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_customs_code_unit</value>
      <webElementGuid>6eb5bae2-2277-436a-b05e-2ae2f411b94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Customs Code</value>
      <webElementGuid>9a0d5851-5ddb-477b-b3a0-241903c3fbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0ec6be1-5648-4652-a669-3805076b88da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>61d39359-c5c1-46a4-9440-c4f4ff90bad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_customs_code_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_customs_code_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_customs_code_unit&quot;]</value>
      <webElementGuid>fe691962-75bc-4fbf-ba30-86f086aad8cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_customs_code_unit']</value>
      <webElementGuid>d1e82e37-dde3-49b7-9e92-580aa3ad2ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_customs_code_unit']/input</value>
      <webElementGuid>9e085c20-982e-40c2-bc8a-e4c797335460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[60]/div/div/input</value>
      <webElementGuid>9251f17b-136b-4fb4-b670-c2e873aa46ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_customs_code_unit' and @name = 'item_customs_code_unit' and @placeholder = 'Item Customs Code' and @type = 'text']</value>
      <webElementGuid>d600884f-858e-4372-bc3a-e87becc45c77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
