<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Made In</name>
   <tag></tag>
   <elementGuidId>330413bb-6f44-4c5f-9194-3b5f569242bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--item_made_in_unit > #dfc-item--transport-unit-content-form--item_made_in_unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--item_made_in_unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a176b521-28f9-405e-a702-bc06a91892f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>05696e82-7d6d-40ec-8217-0962915cef0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--item_made_in_unit</value>
      <webElementGuid>857b42d2-aeae-48b1-aecd-b771292ffee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_made_in_unit</value>
      <webElementGuid>1e0a8f70-88d4-4224-8207-de54ec8dff7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Made In</value>
      <webElementGuid>c22b40ce-3aa9-4263-926c-5953a98697b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3649719d-807d-4452-b906-44f9d92588e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>5a98350f-8db2-42ef-b1ae-fb60c9a49a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--item_made_in_unit&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--item_made_in_unit&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--item_made_in_unit&quot;]</value>
      <webElementGuid>21cfa34b-6fe9-4d40-9eee-effc5463e415</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--item_made_in_unit']</value>
      <webElementGuid>10df4f51-a82d-488c-a62d-14115683a0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--item_made_in_unit']/input</value>
      <webElementGuid>c7c840fb-5ca9-4075-80a6-974b8b0fc33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[45]/div/div/input</value>
      <webElementGuid>ab2aaf43-4588-4df0-b19d-ee5e7ab9de86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--item_made_in_unit' and @name = 'item_made_in_unit' and @placeholder = 'Item Made In' and @type = 'text']</value>
      <webElementGuid>a72d93bd-c357-4bab-aab3-bf6d1f5c272c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
