<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total net weight (Kg)</name>
   <tag></tag>
   <elementGuidId>37b69406-d3f6-4e26-a3c4-338300be602d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--totalNetWeight > #dfc-item--transport-unit-content-form--totalNetWeight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--totalNetWeight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0553eaf-c87a-41c7-b935-6d7b24f29f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>3deb7fe4-c51d-4dd1-a2ce-a4da4d7755a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--totalNetWeight</value>
      <webElementGuid>c6de6c5e-71be-472e-9e7a-572b2e7c2579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61a7e7f1-d81c-458b-ab8c-591703c58f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>totalNetWeight</value>
      <webElementGuid>0583b2ad-0389-4d8f-9c53-67bebbb377a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Total net weight (Kg)</value>
      <webElementGuid>ef31e57a-62f7-4556-ab21-8454f7bb44a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1715a912-55c5-4e85-ae7d-b17d20ff5000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-star-inserted</value>
      <webElementGuid>a2073c3c-8c5e-421e-9c73-6f85628e4954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--totalNetWeight&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--totalNetWeight&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--totalNetWeight&quot;]</value>
      <webElementGuid>a505ab6c-a977-4b70-8063-7cfd1219c7f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--totalNetWeight']</value>
      <webElementGuid>9377a70a-f56d-478e-a532-2ce1fea906b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--totalNetWeight']/input</value>
      <webElementGuid>bd4e53f9-377c-4522-9392-f10d9ea47995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[6]/div/div/input</value>
      <webElementGuid>a085a051-c46b-4aa7-8d79-797edcc88b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--totalNetWeight' and @name = 'totalNetWeight' and @placeholder = 'Total net weight (Kg)' and @type = 'number']</value>
      <webElementGuid>6d9ed864-97fd-4f67-bb7c-24a7d2e2892e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
