<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Transport_Request</name>
   <tag></tag>
   <elementGuidId>2b22d457-dd65-4381-9273-06cc6b832192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='new_option_transport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#new_option_transport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>547b2fea-c022-4d80-88b2-dca11cdde949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/pricing/creation</value>
      <webElementGuid>627ae79b-00c8-4a93-8375-ae4121b2fafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new_option_transport</value>
      <webElementGuid>5b788c88-7f57-4754-b3cf-f249777afa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/pricing/creation</value>
      <webElementGuid>e1f482e6-d4b5-4e84-8c8c-2ef1bc28ef4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Transport request </value>
      <webElementGuid>3417925c-23d8-4c47-9461-e7867f3396ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_option_transport&quot;)</value>
      <webElementGuid>405baf8f-a41c-4fb3-a89f-aea88b76da05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='new_option_transport']</value>
      <webElementGuid>d992410d-e1a3-49e4-b47d-f31772d49e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='new-options__items']/li/a</value>
      <webElementGuid>7f68ade5-c58f-4f34-b782-aa0158b5acf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Transport request')]</value>
      <webElementGuid>b2105f0b-1175-4c34-a97c-48d0e9c2a7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident'])[1]/preceding::a[1]</value>
      <webElementGuid>bd60f872-9700-4026-9fae-537a75abd89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, Salaheddine Fatima Zahra'])[1]/preceding::a[3]</value>
      <webElementGuid>e346bf10-e4b0-4c03-954e-fee9afac24cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transport request']/parent::*</value>
      <webElementGuid>092d70e6-5750-4642-ac7e-d2c7b6a8c91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/pricing/creation')]</value>
      <webElementGuid>a2d552b6-4232-4067-aa86-fa0847617f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li/a</value>
      <webElementGuid>0bf480fd-b5d9-48a1-b949-f4b11a650cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'new_option_transport' and @href = '/app/pricing/creation' and (text() = ' Transport request ' or . = ' Transport request ')]</value>
      <webElementGuid>7cb5cac4-bf5b-410b-87e9-a28ff4471795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
