<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_For_Confirmation</name>
   <tag></tag>
   <elementGuidId>6341069c-9fa5-4bec-a82b-fd78d86b3240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='quote-view-0-actions']/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ffe13e7e-42b1-4a3c-af91-8ad95c303d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64e14a2a-dc64-4a90-970e-6d4919f9e9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check</value>
      <webElementGuid>0bf8467c-1a65-4f1b-9d57-dbffd93e577e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quote-view-0-actions&quot;)/button[@class=&quot;btn btn-xs ng-star-inserted&quot;]/i[@class=&quot;fa fa-check&quot;]</value>
      <webElementGuid>eb2b31c2-0a4f-4987-bf52-6a84bad09a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quote-view-0-actions']/button[2]/i</value>
      <webElementGuid>b748d621-91b6-44b8-b6e5-34fcb1564a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>37614af5-968a-4181-aa6f-4403ec73dd20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
