<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dangerous environment Yes</name>
   <tag></tag>
   <elementGuidId>7f6a877f-5ae1-4334-997b-489df95568dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--settings-ags-form--dangerousEnvironment--true</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--settings-ags-form--dangerousEnvironment--true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b68b43ba-d9bf-4fd6-9c7e-61b4d9b7ef8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>88b5555d-6f13-4178-a3b7-b8ec1e20adf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--settings-ags-form--dangerousEnvironment--true</value>
      <webElementGuid>e9ba660b-3116-4e49-ab52-66718274969a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>248f32e1-9f80-4e63-bbb0-bc62e655c58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--settings-ags-form--dangerousEnvironment--true&quot;)</value>
      <webElementGuid>2d488d4a-95ef-4c90-86ac-c5079b69c0fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--settings-ags-form--dangerousEnvironment--true']</value>
      <webElementGuid>da68806b-a013-486a-8edc-04bf1d6f86e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--settings-ags-form--dangerousEnvironment']/div/input</value>
      <webElementGuid>24e11b3f-43a1-4552-86e3-e3c9674520c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[8]/div/div/div/input</value>
      <webElementGuid>35feb449-d1a0-4882-9c9a-1f5fc71e71c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--settings-ags-form--dangerousEnvironment--true']</value>
      <webElementGuid>bb838fd9-b41e-4f6f-9e84-16f6e2dbe4aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
