<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N.O.S No</name>
   <tag></tag>
   <elementGuidId>aaa77bfd-5f35-4641-a0c7-080e1579e4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--settings-ags-form--notOtherwiseSpecified--false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--settings-ags-form--notOtherwiseSpecified--false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cf43127-8417-4da3-bb02-12534d05b1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8a7f94db-c7a9-4ef1-a185-b3b9c015f7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--settings-ags-form--notOtherwiseSpecified--false</value>
      <webElementGuid>6ec156a9-6179-44b1-afa9-036929466938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>3ec7f984-5f51-4dac-bd2e-d89c92b41bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--settings-ags-form--notOtherwiseSpecified--false&quot;)</value>
      <webElementGuid>c07e8862-0253-40e8-a2dc-e0b4359bfa8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--settings-ags-form--notOtherwiseSpecified--false']</value>
      <webElementGuid>c789f50e-3098-48db-a73c-baca72e33eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--settings-ags-form--notOtherwiseSpecified']/div[2]/input</value>
      <webElementGuid>602eb29e-0e87-40a2-ae3e-1bf896ce7ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[10]/div/div/div[2]/input</value>
      <webElementGuid>1d90f2a3-335b-4d16-aa96-796997bf148d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--settings-ags-form--notOtherwiseSpecified--false']</value>
      <webElementGuid>394cfdc7-d6f0-474c-bdc9-561d2e12f377</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
