<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Onu Number</name>
   <tag></tag>
   <elementGuidId>83a6ac2a-891a-45f0-a892-dcc2c1e65817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--settings-ags-form--onuNumber > #dfc-item--settings-ags-form--onuNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--settings-ags-form--onuNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46994cd7-9d44-48b3-a5c3-a36b0094405f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>04b65af1-f8a3-4100-87d9-56f221df02fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--settings-ags-form--onuNumber</value>
      <webElementGuid>3e612208-94f2-443b-b2ed-376fafc547cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onuNumber</value>
      <webElementGuid>2d7e3334-a05a-4d84-8926-420de627398d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Onu Number</value>
      <webElementGuid>a55538f3-f771-425a-ac0f-5579a23637fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b70939dc-aaef-4093-9301-284de839ce9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>cf632ad1-a7c5-47ab-a113-0f25f5f7ad3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--settings-ags-form--onuNumber&quot;)/div[@id=&quot;dfc-item--settings-ags-form--onuNumber&quot;]/input[@id=&quot;dfc-item--settings-ags-form--onuNumber&quot;]</value>
      <webElementGuid>2ce57519-3ad0-45e3-a403-344baa4a0034</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--settings-ags-form--onuNumber']</value>
      <webElementGuid>a5eda9ee-e2c3-47a4-b81e-22252fa83747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--settings-ags-form--onuNumber']/input</value>
      <webElementGuid>9ddf1deb-fcb3-4439-a160-59534790bb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[5]/div/div/input</value>
      <webElementGuid>d9a07f95-231b-4200-901c-fcc1af4be431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--settings-ags-form--onuNumber' and @name = 'onuNumber' and @placeholder = 'Onu Number' and @type = 'text']</value>
      <webElementGuid>1acd3a18-b852-435b-af86-062f14217a84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
