<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Coef 1.1.3.6</name>
   <tag></tag>
   <elementGuidId>8e0ff48b-8dc9-46e4-825a-86f0aa535aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--settings-ags-form--factor > #dfc-item--settings-ags-form--factor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--settings-ags-form--factor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82b7eeef-2280-4bb9-bf2b-4743a1312631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>a6206dfb-75dd-4af2-aa0c-7cf6eaf8ab1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--settings-ags-form--factor</value>
      <webElementGuid>4c2f3886-957f-4f0d-81fe-74213c237d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>factor</value>
      <webElementGuid>21c62832-c6a1-4815-b04f-729f6fbcabeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Coef 1.1.3.6</value>
      <webElementGuid>161ffc65-c245-4797-97ef-2162b3a21481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05b47209-8ba3-4be0-9f3f-2d8c9a4ca704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>536feeaa-599d-43b1-be3a-280c5bcb5703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--settings-ags-form--factor&quot;)/div[@id=&quot;dfc-item--settings-ags-form--factor&quot;]/input[@id=&quot;dfc-item--settings-ags-form--factor&quot;]</value>
      <webElementGuid>9bcf72d6-caa8-457f-a191-77dffa141edc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--settings-ags-form--factor']</value>
      <webElementGuid>c4b795a7-5f2b-40d9-92f5-ab9ce688e28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--settings-ags-form--factor']/input</value>
      <webElementGuid>8159d0cc-5aac-4aae-ba2c-b623516a02c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[9]/div/div/input</value>
      <webElementGuid>ec4c4490-f946-407b-87d0-b616df80d8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--settings-ags-form--factor' and @name = 'factor' and @placeholder = 'Coef 1.1.3.6' and @type = 'text']</value>
      <webElementGuid>63c28d94-8890-4525-80cb-8e044132afef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
