<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type of dangerous goods (typeOfDangerousGoods)</name>
   <tag></tag>
   <elementGuidId>d7723136-8be2-4cf3-af66-187a3ab47915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--settings-ags-form--typeOfDangerousGoods > #dfc-item--settings-ags-form--typeOfDangerousGoods</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--settings-ags-form--typeOfDangerousGoods']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8918a907-3a16-4579-adcb-e861fb61a1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>9f2bc62d-7391-49dc-84ea-c63ab28f28f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--settings-ags-form--typeOfDangerousGoods</value>
      <webElementGuid>6845edfa-2fca-499c-a4d6-667205eef165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeOfDangerousGoods</value>
      <webElementGuid>2b97a06e-2919-4eb8-b06d-cefa25a1af90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type of dangerous goods</value>
      <webElementGuid>61626b15-5bb1-4139-badd-d6fcb188a9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24346708-c190-435b-bf02-2651304680cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>0d80e8a0-2d63-4403-9134-73718537a1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--settings-ags-form--typeOfDangerousGoods&quot;)/div[@id=&quot;dfc-item--settings-ags-form--typeOfDangerousGoods&quot;]/input[@id=&quot;dfc-item--settings-ags-form--typeOfDangerousGoods&quot;]</value>
      <webElementGuid>dd8b5699-bebb-4752-8f6a-6ed66fe4db85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--settings-ags-form--typeOfDangerousGoods']</value>
      <webElementGuid>f77a87db-c4e5-4af6-aede-132b1f003190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--settings-ags-form--typeOfDangerousGoods']/input</value>
      <webElementGuid>5cc663ff-f3f1-4f16-9085-a0f8b4d2aac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[4]/div/div/input</value>
      <webElementGuid>ca439256-e6bc-4bbb-a616-b607bbd2f52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--settings-ags-form--typeOfDangerousGoods' and @name = 'typeOfDangerousGoods' and @placeholder = 'Type of dangerous goods' and @type = 'text']</value>
      <webElementGuid>be28b3c4-ac0a-41b3-9319-a066b9ee4e81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
