<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>code of the last element in the list</name>
   <tag></tag>
   <elementGuidId>b4e6f4cc-a1af-4015-b252-3895fa3847c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@aria-colindex=&quot;1&quot;])[last()]//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d1c3bf7a-6b66-4275-b25b-55ebee02f610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669821702249</value>
      <webElementGuid>d5d2c735-16da-45d3-975a-328105a34486</webElementGuid>
   </webElementProperties>
</WebElementEntity>
