<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label_description</name>
   <tag></tag>
   <elementGuidId>7c70dd3a-23c7-4223-8c05-fc10f72e67e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5869d9cb-f95c-4862-ad3e-f69d76bee00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>996a3179-8286-479d-a614-2a01c2962889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngcontrol</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>d424d4eb-5d4f-44c9-bf26-4fa1d66f77b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>a1adcfe3-d010-43a3-94a6-69856624f653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-underline input-xs ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ce6ab89c-b755-4e80-8865-9b94c2c05c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-type-goods[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;padding-top-5&quot;]/form[@class=&quot;generic-default ng-pristine ng-star-inserted ng-invalid ng-touched&quot;]/div[@class=&quot;form-content col-sm-12 margin-top-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-4 col-xs-12 form-group&quot;]/div[1]/input[@class=&quot;form-control input-underline input-xs ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>def5a7aa-e18a-4c86-b5e0-4049600a28c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='description']</value>
      <webElementGuid>f8cb5354-c1cc-45b4-83ff-c0a32f6f4b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-type-goods/div/form/div/div/div[2]/div/input</value>
      <webElementGuid>ecffb97b-8fd6-4125-9a38-75b41415bb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5a157e02-35d9-4c18-902d-758fa16715d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'description']</value>
      <webElementGuid>a1a699cd-cd6b-451b-8f2e-0a8e133f31a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
