<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label of the last element in the list</name>
   <tag></tag>
   <elementGuidId>2bf0b30c-448f-4a5c-9704-f4352cf26aed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@aria-colindex=&quot;2&quot;])[last()]//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6ae3af0a-9829-40aa-b5be-1831d9026fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669821776390</value>
      <webElementGuid>c9d18214-eecf-4d48-9dcb-0f3481e5c890</webElementGuid>
   </webElementProperties>
</WebElementEntity>
