<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update consolidation info</name>
   <tag></tag>
   <elementGuidId>4390e445-f25d-4960-a5aa-dc45402822ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-content-step-consolidation//button[@type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.button_update_consolidation_info > button.btn.btn-xs.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2219970-e676-481b-9d7d-cb7c8ca5f4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>142a7513-1238-4162-a8d8-111bd10a14eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs ng-star-inserted</value>
      <webElementGuid>8eabff34-73ef-4ce3-bea0-a729b657d7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Update consolidation info </value>
      <webElementGuid>3ef7b81e-991f-493e-a2f0-80d16fbccc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--transport-form--consolidationInitials&quot;)/app-content-step-consolidation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;step-consolidation-root ng-star-inserted&quot;]/div[@class=&quot;add-tr-container ng-star-inserted&quot;]/div[@class=&quot;button_update_consolidation_info&quot;]/button[@class=&quot;btn btn-xs ng-star-inserted&quot;]</value>
      <webElementGuid>189dff8d-fdbf-4680-9d40-8663cb9e8973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>4c3d471b-89bc-445b-9644-6ac0ffddb93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--transport-form--consolidationInitials']/app-content-step-consolidation/div/div/div/button</value>
      <webElementGuid>23ac2cc6-7735-4e41-a9bc-88f6aada94db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidation'])[2]/following::button[1]</value>
      <webElementGuid>9b4e1283-3e6d-4f32-be98-835814ceecb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exportateur Country'])[1]/following::button[1]</value>
      <webElementGuid>63973336-7429-4a14-986b-bf18aeded4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Not saved)'])[1]/preceding::button[1]</value>
      <webElementGuid>b1d5f402-ba48-4a6c-a65c-76efd2e43c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update consolidation info']/parent::*</value>
      <webElementGuid>2f61b0a0-8817-4fc9-989c-96f02569277c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>e9c4906b-b117-40ae-9650-0a0eef3331dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Update consolidation info ' or . = ' Update consolidation info ')]</value>
      <webElementGuid>f878fb35-0d10-4959-9474-a15413875ebd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
