<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type_Of_Shipment</name>
   <tag></tag>
   <elementGuidId>3a2f047a-86b3-492b-976c-29b05fd79899</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label=&quot;Type of Shipment Filter Input&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-10676-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b814ae4f-5b44-497b-a698-734b8c33d01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>fe8cc31b-4e81-438c-8df4-601998878e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>b5badab5-1882-49ac-9268-c453aa703fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7b0a734-a83d-44d9-88c4-aa1390d3d51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-10676-input</value>
      <webElementGuid>0c1eb66e-3548-4cfe-a840-af35d56a108b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Type of Shipment Filter Input</value>
      <webElementGuid>9f84871c-8867-4b38-9b72-5561ffbe8d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-10676-input&quot;)</value>
      <webElementGuid>01655ad9-ed7a-439d-ba62-6dafd458ff80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-10676-input']</value>
      <webElementGuid>0255b019-b201-4305-9aad-3030debef9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-consolidation-proposition-list/div/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>91e19817-da47-49da-8c8f-be8fefc66a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>ffec6d1f-bc8a-4644-b5f1-f12d2a2bae98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-10676-input']</value>
      <webElementGuid>4304871a-b951-4425-a22d-426162dde623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
