<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_An_Article</name>
   <tag></tag>
   <elementGuidId>53956bd2-0cd6-4234-a9bf-e23ba9ac7750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-details/div/div/div[2]/div[3]/app-panel-right/app-form-dynamic-panel/div/app-transport-unit-form-details/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-icon.fa.fa-floppy-o.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a2a9b88-dae3-4ce4-b221-beb45620b6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon fa fa-floppy-o cursor-pointer</value>
      <webElementGuid>563924ad-6c2f-440f-90e6-ec0f7f779e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1b68cfef-0e74-4402-bf9f-5a2c0f48ea81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;transport-details-root loader-content-container transparent-dark-loader&quot;]/div[@class=&quot;m-details-form ng-star-inserted&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;right&quot;]/app-panel-right[1]/app-form-dynamic-panel[1]/div[@class=&quot;form-dynamic-panel ng-star-inserted&quot;]/app-transport-unit-form-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;side-panel panel-root opened&quot;]/div[@class=&quot;margin-bottom-5 padding-0 justify-content-between side-panel-header&quot;]/div[@class=&quot;panel-buttons&quot;]/button[@class=&quot;btn-icon fa fa-floppy-o cursor-pointer&quot;]</value>
      <webElementGuid>e3a94ae2-e65c-464c-bb5b-80b68152ff97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-details/div/div/div[2]/div[3]/app-panel-right/app-form-dynamic-panel/div/app-transport-unit-form-details/div/div/div/button</value>
      <webElementGuid>1b0c620c-dbd2-4755-a3c3-4c8001bf13ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/div/div/button</value>
      <webElementGuid>4d523bff-aa51-4e70-b0bd-9bf574f21310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Save']</value>
      <webElementGuid>309e4a2a-da2c-4547-825b-74685ffb0a85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
