<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add_Unit</name>
   <tag></tag>
   <elementGuidId>7b77a730-35d0-46dd-a53d-0e991cc9e0f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='header-button-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-button-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>74cbe937-8bbd-45a7-b672-5a03fae7f2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add unit</value>
      <webElementGuid>9cdff20f-0ce5-4d95-99f1-b2ea85b906ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-button-3</value>
      <webElementGuid>cf87b7f6-091a-4989-9742-d066bff429c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-cart-plus ng-star-inserted</value>
      <webElementGuid>f4127dd5-c7ba-4c8d-a45a-664eda7fc966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-button-3&quot;)</value>
      <webElementGuid>2d80e89b-fd29-4cc0-bb81-1c663b556b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='header-button-3']</value>
      <webElementGuid>57b3fc5c-420e-4565-9635-5a4a043cf9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--transport-form--transportPackages']/app-transport-packaging-list/div/app-list-header-buttons/div/div/div/i[4]</value>
      <webElementGuid>ab2843c6-9b6e-43a8-b647-ee38d560571d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[4]</value>
      <webElementGuid>685883da-91db-4195-8a2f-777b2880da69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Add unit' and @id = 'header-button-3']</value>
      <webElementGuid>66899a3d-fcaf-4771-b6ff-ca55be532cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
