<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoterm_DAP</name>
   <tag></tag>
   <elementGuidId>9db0242f-9033-44ef-b1d2-35cd916f1a56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dfc-select-Incoterm-109740-option']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-select-Incoterm-109740-option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1639b5c8-6276-4c69-a97b-0a0d6451cdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-select-Incoterm-109740-option</value>
      <webElementGuid>64e51c91-b602-4109-ae33-97200c9e058f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>fb55223e-e178-4549-9123-7b6a07a456b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAP</value>
      <webElementGuid>f512a442-62ed-4c90-9656-2ea14754a2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-select-Incoterm-109740-option&quot;)</value>
      <webElementGuid>ed59abc9-eb9f-46e3-8d19-73c71e0f3761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dfc-select-Incoterm-109740-option']</value>
      <webElementGuid>d22987a5-0d04-4a07-a53c-f00c41b6e9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aefe4ace2380-0']/div</value>
      <webElementGuid>a355cad1-88bf-463a-ae69-486f38f3ea2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoterm'])[2]/following::div[6]</value>
      <webElementGuid>ff09bedc-a219-4b78-8f5e-01a6904f4344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoterm'])[1]/following::div[10]</value>
      <webElementGuid>5f979eae-ed8c-4547-a8a8-f514a1f5148d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXW'])[1]/preceding::div[1]</value>
      <webElementGuid>41936e9c-b054-4ea4-a897-cbc08af8e32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FCA'])[1]/preceding::div[3]</value>
      <webElementGuid>94e0a96b-4be4-4d7a-9114-d74a97b6fb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAP']/parent::*</value>
      <webElementGuid>1e549256-40c4-4b69-920b-e855a7c9efd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div/div</value>
      <webElementGuid>49500219-df73-4da7-be5c-fcde924692c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dfc-select-Incoterm-109740-option' and (text() = 'DAP' or . = 'DAP')]</value>
      <webElementGuid>50b88e70-e302-4883-99f5-abb2dc9b5a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
