<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BC or DN number</name>
   <tag></tag>
   <elementGuidId>9aecd846-8500-4686-bdde-be13b0e00b47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bc_or_dn_transport_request > #dfc-item--transport-form--bc_or_dn_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bc_or_dn_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7befc311-1ad7-4763-bfb3-2357bb96eda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>1b4c95a2-4001-44ba-bfa4-64486155c966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bc_or_dn_transport_request</value>
      <webElementGuid>2e234a6f-d2cb-4473-82fb-82432ad74313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bc_or_dn_transport_request</value>
      <webElementGuid>2b1eb3cc-c153-47a2-944f-cec3e256591e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>BC or DN number</value>
      <webElementGuid>1bf68709-cc24-4175-95c5-3eeb5b323cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5f46a3a-5ba8-4de1-ab29-d6c606742cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>d966e365-3b59-453d-8289-d0b87fbace97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bc_or_dn_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bc_or_dn_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bc_or_dn_transport_request&quot;]</value>
      <webElementGuid>c7df71b9-005c-47ba-adbd-fb4fd815120b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bc_or_dn_transport_request']</value>
      <webElementGuid>c2d5c60e-ab49-4fae-bd44-90b638c58903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bc_or_dn_transport_request']/input</value>
      <webElementGuid>bf2ad60c-a05f-48b4-a388-b09aa1c8ddf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[5]/div/div/input</value>
      <webElementGuid>825f33a0-4152-4699-975f-177166ff7825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bc_or_dn_transport_request' and @name = 'bc_or_dn_transport_request' and @placeholder = 'BC or DN number' and @type = 'text']</value>
      <webElementGuid>189fdb25-a22d-4f90-886a-231b5646d1c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
