<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Manhattan Shipment ID</name>
   <tag></tag>
   <elementGuidId>380ce38d-1618-474f-8927-072481b6677c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--manhattan_shipment_id_transport_request > #dfc-item--transport-form--manhattan_shipment_id_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--manhattan_shipment_id_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04a88853-94f1-4aae-a757-8eddd0ddc549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>32d1479b-a5cb-4e44-af34-ad54cbeb9a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--manhattan_shipment_id_transport_request</value>
      <webElementGuid>7a95a7ec-054b-48ef-ada2-a01a75127ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>manhattan_shipment_id_transport_request</value>
      <webElementGuid>ff98b005-b5dd-4a17-93e1-19bf6259fb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Manhattan Shipment ID</value>
      <webElementGuid>857458b4-48a4-44dd-a788-685b87f17bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bcd78c6-81b9-4e06-b578-4939e8a24ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>f7c2356c-702b-46ca-a981-355cc2b43e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--manhattan_shipment_id_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--manhattan_shipment_id_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--manhattan_shipment_id_transport_request&quot;]</value>
      <webElementGuid>11679bb0-be3b-4924-a6df-2e3eb38bb844</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--manhattan_shipment_id_transport_request']</value>
      <webElementGuid>fe15f7d6-642e-4155-a3b0-30d62afb5c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--manhattan_shipment_id_transport_request']/input</value>
      <webElementGuid>3457c150-0c37-4ee7-861a-4ba490a1b4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[14]/div/div/input</value>
      <webElementGuid>c65e0a1e-476a-469f-9793-0954e1285e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--manhattan_shipment_id_transport_request' and @name = 'manhattan_shipment_id_transport_request' and @placeholder = 'Manhattan Shipment ID' and @type = 'text']</value>
      <webElementGuid>6a57705c-f727-4b68-b36b-09570e3b4ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
