<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur Address 1</name>
   <tag></tag>
   <elementGuidId>cabba7ba-61dc-4d02-b1b4-00ad661f1709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_address_1_transport_request > #dfc-item--transport-form--exportateur_address_1_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_address_1_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e997e36d-9306-4fcd-80f0-ed8c53277061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>f0951d20-e590-448e-990b-ff236f59fd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_address_1_transport_request</value>
      <webElementGuid>1d2d7398-b399-4bfa-b595-7b08165c3ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_address_1_transport_request</value>
      <webElementGuid>e2c5fd5c-dfe9-466a-bed7-9f45f88d5800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur Address 1</value>
      <webElementGuid>faa7c522-c26a-44a2-b33c-29f9bbd4d412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a8260d1-702c-42b1-94c8-ed81f3179648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>735e4cb1-2b3b-4aa6-bcba-c4f70e840008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_address_1_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_address_1_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_address_1_transport_request&quot;]</value>
      <webElementGuid>840ac90f-12ed-421e-b67e-a88010d8e739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_address_1_transport_request']</value>
      <webElementGuid>e4d6f917-7193-45e4-89ec-33ef9c5df79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_address_1_transport_request']/input</value>
      <webElementGuid>c3597659-5f14-4474-ac2b-f50287ff4587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[27]/div/div/input</value>
      <webElementGuid>0f58d349-598d-4030-aec4-69019cdb192f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_address_1_transport_request' and @name = 'exportateur_address_1_transport_request' and @placeholder = 'Exportateur Address 1' and @type = 'text']</value>
      <webElementGuid>e46893c4-7b22-4545-9480-5c83a5d8bb83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
