<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Address 4</name>
   <tag></tag>
   <elementGuidId>1179c2c7-d573-4ee1-a40a-9e89ccff27ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carrier_address_4_transport_request > #dfc-item--transport-form--carrier_address_4_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carrier_address_4_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8203f82-6422-4059-8bec-42ab51cabab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>5129dca1-f7cf-4940-9951-0277ea6854c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carrier_address_4_transport_request</value>
      <webElementGuid>37bc5ad2-581d-4baa-af85-d51b32ece119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrier_address_4_transport_request</value>
      <webElementGuid>c676efa5-dab9-4bf8-94dd-e8a3ee7cbfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier Address 4</value>
      <webElementGuid>7ba2c748-dd3f-4793-a456-5f6cd66d9cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b890f9da-5065-40c4-827d-d0cc3c714282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>d4b53b39-7eb4-421b-a1fb-476e1ea076c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carrier_address_4_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carrier_address_4_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carrier_address_4_transport_request&quot;]</value>
      <webElementGuid>b088a66f-c92d-4293-b4e2-18f63d954fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carrier_address_4_transport_request']</value>
      <webElementGuid>f1e449f2-234d-4f4a-a10b-4a6ecc233a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carrier_address_4_transport_request']/input</value>
      <webElementGuid>534e7d9c-c5a2-4682-b729-12b65e470926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[18]/div/div/input</value>
      <webElementGuid>7886aac2-c8d7-46e8-bb34-27d204de4409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carrier_address_4_transport_request' and @name = 'carrier_address_4_transport_request' and @placeholder = 'Carrier Address 4' and @type = 'text']</value>
      <webElementGuid>13510cc2-7e79-4181-994c-44f21368b2ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
