<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_Form</name>
   <tag></tag>
   <elementGuidId>161dd71a-2fb4-49d7-bc83-a1cfce68239a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;dfc-dyn-root--transport-form--addressOrigin&quot;]/app-address-picker-form-control//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1e2e879-5328-40a0-a4f1-9d4058612cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c30c91bc-7ca1-4670-bde4-4dda3ce81565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>8dab8630-4978-497f-a339-e0a565efe42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2aa0cdb0-f280-4a4d-8ec8-295a471c3720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search addresses</value>
      <webElementGuid>3bb8e425-e04b-4f55-bf52-5371847c0bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--transport-form--addressOrigin&quot;)/app-address-picker-form-control[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;df-form-control-root ng-star-inserted&quot;]/div[@class=&quot;df-form-control-item&quot;]/div[@class=&quot;d-flex ng-star-inserted&quot;]/div[@class=&quot;flex-grow-1&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>ac6964f4-cabc-4633-ae17-55f737f74a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[8]</value>
      <webElementGuid>a946b709-4579-4250-a8dc-638026feb31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--transport-form--addressOrigin']/app-address-picker-form-control/div/div/div/div/input</value>
      <webElementGuid>23634b95-5529-4ea3-b39c-f2acce9aca35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>b45ab102-9a05-4458-b7ef-e297cea822e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search addresses']</value>
      <webElementGuid>6e4026a5-dafb-4855-9307-8ccac7e83752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
