<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To District</name>
   <tag></tag>
   <elementGuidId>fdacabfe-5ea8-45e0-81a0-74c711c3472b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_district_transport_request > #dfc-item--transport-form--bill_to_district_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_district_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e656e7d-e942-46cb-ab1b-72d143933b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>be1e395d-432e-4742-84e3-256704542f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_district_transport_request</value>
      <webElementGuid>d91366e5-5b7b-4867-9a7b-ae3d0a0ebfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_district_transport_request</value>
      <webElementGuid>73752f7e-0151-4e98-b2b9-1ca7a7d266f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To District</value>
      <webElementGuid>4dd89bfb-500c-4f29-acf7-f1419d5f291c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44caf7d9-a570-447d-b043-5910875540ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>3c9fa2c7-1320-4848-8c8f-fb82d7b75d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_district_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_district_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_district_transport_request&quot;]</value>
      <webElementGuid>ebef137a-32fa-4457-b631-c4ad9b06fb64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_district_transport_request']</value>
      <webElementGuid>b91d835c-66e2-48e4-a8cf-bdb18e255374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_district_transport_request']/input</value>
      <webElementGuid>f77ff756-4882-4435-b8e8-614c0a86660f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[11]/div/div/input</value>
      <webElementGuid>27d40fac-4b9d-400d-8cdb-587b4d2bf39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_district_transport_request' and @name = 'bill_to_district_transport_request' and @placeholder = 'Bill To District' and @type = 'text']</value>
      <webElementGuid>955cbe96-03c0-4aaf-9a86-35c3dd95b391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
