<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier AdminSub</name>
   <tag></tag>
   <elementGuidId>15ff8e2c-6fb9-42e4-b9f6-8fae6058fcb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carrier_adminsub_transport_request > #dfc-item--transport-form--carrier_adminsub_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carrier_adminsub_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>424cbb42-c05c-4e5a-8f3a-c809ec7e7b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>d0af8362-bc71-488e-bd12-2d90b2aeca68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carrier_adminsub_transport_request</value>
      <webElementGuid>12779bd6-2c56-4e82-b845-2d6ff005ecb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrier_adminsub_transport_request</value>
      <webElementGuid>004de437-1a9f-4f2a-a53e-7dd29d6dd27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier AdminSub</value>
      <webElementGuid>3b38e9fe-f4cf-4c3b-8f44-81486d1e62b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ca4f148-4d3f-4d1d-b89c-713fd00979cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>dd590b33-c72e-4cac-8187-4523d525f57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carrier_adminsub_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carrier_adminsub_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carrier_adminsub_transport_request&quot;]</value>
      <webElementGuid>16f2beb5-69ca-40b5-95ea-a7ce545bcfa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carrier_adminsub_transport_request']</value>
      <webElementGuid>218a8f91-53cc-4b5d-b9c5-8fc7efca6860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carrier_adminsub_transport_request']/input</value>
      <webElementGuid>02aa48ba-5e85-489c-babc-8d29724e474f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[23]/div/div/input</value>
      <webElementGuid>1ec88ecc-a8c7-4119-9bed-a57a0e020f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carrier_adminsub_transport_request' and @name = 'carrier_adminsub_transport_request' and @placeholder = 'Carrier AdminSub' and @type = 'text']</value>
      <webElementGuid>a9a1a6cf-9baf-41e7-93a8-db37ce6575b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
