<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur Address 3</name>
   <tag></tag>
   <elementGuidId>440a6930-b58a-49ff-bafb-15668ecaba43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_address_3_transport_request > #dfc-item--transport-form--exportateur_address_3_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_address_3_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91338027-51c3-457c-a65d-ab60eb0852f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>feef9ab7-4902-4d4f-b8dc-ac4643a3ff79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_address_3_transport_request</value>
      <webElementGuid>1916d412-8430-4a4d-b090-0e72eb4a4ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_address_3_transport_request</value>
      <webElementGuid>628c018b-42e9-4be0-b2ba-2a5ca786c93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur Address 3</value>
      <webElementGuid>b8824f7e-e8e3-474e-9f18-21bd91e4d22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72553b2a-9906-49fe-912d-51497b0c98ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>17ea1d63-4238-42bf-a9f0-8992bc396bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_address_3_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_address_3_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_address_3_transport_request&quot;]</value>
      <webElementGuid>049e6c0d-e52b-4577-862d-d76bf55f8aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_address_3_transport_request']</value>
      <webElementGuid>0a2734c1-2a52-44bc-9fc9-70387ca52ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_address_3_transport_request']/input</value>
      <webElementGuid>4584a133-b86b-4e9b-83ae-ba8f0de9789d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[29]/div/div/input</value>
      <webElementGuid>17a78558-9140-4c23-b05f-69a9ad1eda55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_address_3_transport_request' and @name = 'exportateur_address_3_transport_request' and @placeholder = 'Exportateur Address 3' and @type = 'text']</value>
      <webElementGuid>9b63d401-f973-4734-8fad-fac2413c7f7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
