<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To address 4</name>
   <tag></tag>
   <elementGuidId>58912345-b7ec-4fa6-be10-7487989c26e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_address_4_transport_request > #dfc-item--transport-form--bill_to_address_4_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_address_4_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9364d2ad-3358-491f-8be7-30e24ab6cf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>ea26bc8f-4078-4876-b980-0483d780714f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_address_4_transport_request</value>
      <webElementGuid>d40c932f-c9d4-466e-8666-48f5bcb5a99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_address_4_transport_request</value>
      <webElementGuid>2f46e13a-7b07-4e55-a96a-f2ea0f0a0b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To address 4</value>
      <webElementGuid>27caf54d-0b5e-4b59-8ca5-1eed63bfd40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd3a511f-cf05-4923-a711-000cd3f74126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>cb541e82-cfe7-43b7-81cf-307146a19338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_address_4_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_address_4_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_address_4_transport_request&quot;]</value>
      <webElementGuid>8edeed01-b903-4c7e-b5de-c85b05f8b4cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_address_4_transport_request']</value>
      <webElementGuid>ffdf8362-37c2-4ba9-81cf-7eaf9d3b273a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_address_4_transport_request']/input</value>
      <webElementGuid>cf850e10-b757-4a22-a05e-ed50074f9b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[7]/div/div/input</value>
      <webElementGuid>41127f79-ffe3-4d28-8aa3-d3218ceb56c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_address_4_transport_request' and @name = 'bill_to_address_4_transport_request' and @placeholder = 'Bill To address 4' and @type = 'text']</value>
      <webElementGuid>b5271a07-59af-4b5a-b4bc-a5813113f2db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
