<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repair invoice number</name>
   <tag></tag>
   <elementGuidId>5e096332-5a66-42d6-aec5-a811460c89b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--repair_invoice_number_transport_request > #dfc-item--transport-form--repair_invoice_number_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--repair_invoice_number_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0d9be84-aa83-4e1f-8cd2-3f01ced25e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>79398044-9da7-4cdc-826e-0b1a88577e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--repair_invoice_number_transport_request</value>
      <webElementGuid>44a855a7-1df7-4bb1-a66a-0502d3e8939b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repair_invoice_number_transport_request</value>
      <webElementGuid>1a07efda-d49a-4d24-bb73-116f8aecab57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Repair invoice number </value>
      <webElementGuid>ff32dee6-7360-4ceb-9b4c-4cde59bddaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad297f60-164e-4fff-943d-901087f76402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>6da66830-0504-41e2-b2fa-866029c0469b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--repair_invoice_number_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--repair_invoice_number_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--repair_invoice_number_transport_request&quot;]</value>
      <webElementGuid>1c13d32f-5a98-4909-b697-a6ad4ff05cfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--repair_invoice_number_transport_request']</value>
      <webElementGuid>082ed23b-249b-4947-9679-76d978357542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--repair_invoice_number_transport_request']/input</value>
      <webElementGuid>3a92687e-dd0a-4614-b273-8b0945035f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[12]/div/div/input</value>
      <webElementGuid>a9f111f9-8989-480e-8df5-9fa7fef6e049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--repair_invoice_number_transport_request' and @name = 'repair_invoice_number_transport_request' and @placeholder = 'Repair invoice number ' and @type = 'text']</value>
      <webElementGuid>d255471c-4f62-4051-9b28-a0ef99753cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
