<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cumulated invoice number</name>
   <tag></tag>
   <elementGuidId>25f6e5e3-cdaf-41b7-8ac8-a424b4ecfcad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--cumulated_invoice_number_transport_request > #dfc-item--transport-form--cumulated_invoice_number_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--cumulated_invoice_number_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb657f4c-7a48-4352-97ee-b0da1b9c1f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>aaa442ea-74e4-43d9-968e-6eec467af180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--cumulated_invoice_number_transport_request</value>
      <webElementGuid>1ba11e8c-3b4c-44e5-a19e-0f3d1c08c747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cumulated_invoice_number_transport_request</value>
      <webElementGuid>4808c7eb-986c-4e0e-8892-1612ea155863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cumulated invoice number </value>
      <webElementGuid>721d09b6-dd96-48c4-938c-5d7693b62c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9d1b671-1057-4fdc-bcf4-e7093453578d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>8d49d9cf-1fe8-4f02-a122-a040acf87585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--cumulated_invoice_number_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--cumulated_invoice_number_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--cumulated_invoice_number_transport_request&quot;]</value>
      <webElementGuid>32c2fa6d-9847-4ef4-aaaf-379b5863a509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--cumulated_invoice_number_transport_request']</value>
      <webElementGuid>70443d2d-0270-4838-b772-6b83561b139d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--cumulated_invoice_number_transport_request']/input</value>
      <webElementGuid>434aff31-af1d-4505-b7d4-613a51fc6472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[24]/div/div/input</value>
      <webElementGuid>a20d8668-5e5d-4974-8699-218a73dacc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--cumulated_invoice_number_transport_request' and @name = 'cumulated_invoice_number_transport_request' and @placeholder = 'Cumulated invoice number ' and @type = 'text']</value>
      <webElementGuid>26945bf4-30f3-47d5-bca9-2aad142a09cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
