<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur City</name>
   <tag></tag>
   <elementGuidId>053395a3-2d6f-4d02-a206-59a6ef25f4ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_city_transport_request > #dfc-item--transport-form--exportateur_city_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_city_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d389db8e-79f9-496a-b279-e3106f445bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>0048cddd-91b1-42c8-980c-5404315bacfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_city_transport_request</value>
      <webElementGuid>3517c537-4863-4143-acbf-730ec00ab42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_city_transport_request</value>
      <webElementGuid>c77cc30a-1974-4c2e-8723-fad77e5b5068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur City</value>
      <webElementGuid>7214e4d1-7ac7-4b60-9eb0-825412b028b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6372acf7-1845-407c-a00d-82fca93492bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>b16625a7-08cd-4270-9284-d6afe4fb4faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_city_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_city_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_city_transport_request&quot;]</value>
      <webElementGuid>63d5fee0-b9f2-4ccf-9b7b-d30ed4685a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_city_transport_request']</value>
      <webElementGuid>c0aa8d5f-e42a-4eda-8c1a-b3c28537a594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_city_transport_request']/input</value>
      <webElementGuid>02c898c3-68f4-4a5d-9dc3-5bd8ce35d10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[32]/div/div/input</value>
      <webElementGuid>ee3c1a20-ab89-4410-9591-dc55f417faef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_city_transport_request' and @name = 'exportateur_city_transport_request' and @placeholder = 'Exportateur City' and @type = 'text']</value>
      <webElementGuid>3331ef69-31fb-4530-9af4-b56428160f95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
