<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_By_Term</name>
   <tag></tag>
   <elementGuidId>e1b80111-9ee9-4e6a-a9e2-be2360d948ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;corp&quot;]/app-pricing-list/app-transport-common-list/div/app-list-header-buttons/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>456dee12-6532-4b4a-9202-293e6aeaf526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>818289d5-0809-4250-b55a-0a24607d81a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-star-inserted</value>
      <webElementGuid>5774c45c-399c-4434-9b7c-8ba11f9a32ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by term</value>
      <webElementGuid>cc42d18b-46e7-48a5-8994-453f74e7e6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-pricing-list[@class=&quot;ng-star-inserted&quot;]/app-transport-common-list[1]/div[@class=&quot;content_wrapper app-padding&quot;]/app-list-header-buttons[1]/div[@class=&quot;ag-header-buttons&quot;]/div[@class=&quot;header-buttons&quot;]/input[@class=&quot;form-control ng-star-inserted&quot;]</value>
      <webElementGuid>c00dae49-559e-43bc-8afa-55846d8241d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>c44c0a78-433f-4048-8abc-cfc66ec24c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-pricing-list/app-transport-common-list/div/app-list-header-buttons/div/div/input</value>
      <webElementGuid>25bc8489-c989-43f4-b2e4-da090711aa19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>be9e332e-0413-412a-abe1-facfa3ccdb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search by term']</value>
      <webElementGuid>6774fec2-a957-46e7-a561-4ad527e7b1fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
