<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cumulated SRI number</name>
   <tag></tag>
   <elementGuidId>e49a94bc-cc27-4e9e-9311-dec0c9f86285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--cumulated_sri_number_transport_request > #dfc-item--transport-form--cumulated_sri_number_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--cumulated_sri_number_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a649ecd4-8ac9-4493-8328-da1e232ddb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>f26900d0-a9c9-4f58-9a8a-283c83ece147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--cumulated_sri_number_transport_request</value>
      <webElementGuid>eb606899-0815-4780-b128-eccae99a5889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cumulated_sri_number_transport_request</value>
      <webElementGuid>69524cc1-84e6-4067-b24e-190a7310e1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cumulated SRI number</value>
      <webElementGuid>d376d7a1-4b37-4fdf-914a-97b71dc83355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>035ec234-cfdb-4e88-88d1-216f321d4552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>092063bf-758f-42d3-9d18-369c5163cb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--cumulated_sri_number_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--cumulated_sri_number_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--cumulated_sri_number_transport_request&quot;]</value>
      <webElementGuid>149d8e0a-0237-4124-88cf-5e4dc9ab9127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--cumulated_sri_number_transport_request']</value>
      <webElementGuid>ee6876c7-f448-4ff7-9849-24627b2942c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--cumulated_sri_number_transport_request']/input</value>
      <webElementGuid>ed5a02a9-1bed-4902-b46e-1da9f62abd7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[25]/div/div/input</value>
      <webElementGuid>8fd0a77e-c345-424b-91c1-da490820cdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--cumulated_sri_number_transport_request' and @name = 'cumulated_sri_number_transport_request' and @placeholder = 'Cumulated SRI number' and @type = 'text']</value>
      <webElementGuid>fc75d20b-09c5-4d9b-b371-ca1501b688cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
