<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur name</name>
   <tag></tag>
   <elementGuidId>2b8e60ab-f7fa-431f-9d83-6889aa8bf16d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_name_transport_request > #dfc-item--transport-form--exportateur_name_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_name_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e993b5a3-3f11-495d-b7ab-7be560fc2226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>23b51c78-a433-4419-b2c0-edc528030c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_name_transport_request</value>
      <webElementGuid>81669c64-3107-4d22-a93f-e2afad0869de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_name_transport_request</value>
      <webElementGuid>ed2857af-e5c4-4d17-9d09-3bc7632f5525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur name</value>
      <webElementGuid>5c1e5875-9d00-4d87-bdba-64029ceaf881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7faa0425-54c6-4192-8fef-5626aebd09a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>5ef32347-7abf-46b1-a6d3-83f2f282d7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_name_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_name_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_name_transport_request&quot;]</value>
      <webElementGuid>b7cd7796-10e9-444d-81bb-1a4a573d23c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_name_transport_request']</value>
      <webElementGuid>37f54929-d517-4c3f-864b-e72a358668d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_name_transport_request']/input</value>
      <webElementGuid>011e60ac-5f7c-4481-b1a3-d1de632a3686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[26]/div/div/input</value>
      <webElementGuid>4df02195-e118-4437-88a8-17634fc63929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_name_transport_request' and @name = 'exportateur_name_transport_request' and @placeholder = 'Exportateur name' and @type = 'text']</value>
      <webElementGuid>d76e2e2d-e6fa-461e-8551-adf96d3dd5f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
