<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To Country</name>
   <tag></tag>
   <elementGuidId>38559666-89da-41db-b1b5-e6951f993470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_iso2_country_code_transport_request > #dfc-item--transport-form--bill_to_iso2_country_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_iso2_country_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff4d549c-0ac3-49e6-be48-e8ba38d153a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>ed902f50-3054-4d70-8578-c06d629216ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_iso2_country_code_transport_request</value>
      <webElementGuid>332ce4be-838a-4895-b71f-da12365ec5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_iso2_country_code_transport_request</value>
      <webElementGuid>0e0685d7-9c48-4e76-ba61-09e6c5002b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To Country</value>
      <webElementGuid>a68f65cb-27c5-4c98-b65c-b24cd846bbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec6fc53e-63d6-4e61-bc76-e8f33fbbbe33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>262ae6fb-a8ee-4d27-96d9-2c5734e5e0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_iso2_country_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_iso2_country_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_iso2_country_code_transport_request&quot;]</value>
      <webElementGuid>3d8f357b-d087-47d5-8042-7c828374b193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_iso2_country_code_transport_request']</value>
      <webElementGuid>d714c24b-9f8a-4458-bce5-72afe4d03900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_iso2_country_code_transport_request']/input</value>
      <webElementGuid>c524b200-4cc8-4a4a-9faa-53f08d333267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[13]/div/div/input</value>
      <webElementGuid>79da56a7-f7c2-4830-828c-210848fbed73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_iso2_country_code_transport_request' and @name = 'bill_to_iso2_country_code_transport_request' and @placeholder = 'Bill To Country' and @type = 'text']</value>
      <webElementGuid>21991f02-a5f3-4da2-9f71-a0658dcc5ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
