<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial Number Research</name>
   <tag></tag>
   <elementGuidId>872bc293-9d3c-414b-b69e-1a5268d99467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--serial_number_research_transport_request > #dfc-item--transport-form--serial_number_research_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--serial_number_research_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c87aff58-3b74-4c0b-ad4a-c1200ac137a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>948e4e4b-0c9a-49a7-b6f4-1504d3b4688b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--serial_number_research_transport_request</value>
      <webElementGuid>4d1bcd97-06bd-45cb-9d78-229ed4416554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serial_number_research_transport_request</value>
      <webElementGuid>9cd215d1-78ad-4b95-b4dc-5079e5f7f9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Serial Number Research</value>
      <webElementGuid>3f2dc195-8653-454a-8de4-206d5c3601c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a4b417e-d0d5-4bc4-ab39-fab6d16ff45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ea723c4e-df94-4ba9-bb35-0b958442c95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--serial_number_research_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--serial_number_research_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--serial_number_research_transport_request&quot;]</value>
      <webElementGuid>e96f73e3-be58-414f-a46b-95428aa514da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--serial_number_research_transport_request']</value>
      <webElementGuid>46b2c91b-9240-4e9d-a797-81fef12d8e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--serial_number_research_transport_request']/input</value>
      <webElementGuid>4e9d102d-d431-4ca7-a99f-0430dab760ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[33]/div/div/input</value>
      <webElementGuid>110b41d5-2296-4878-aba8-3d27fff52cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--serial_number_research_transport_request' and @name = 'serial_number_research_transport_request' and @placeholder = 'Serial Number Research' and @type = 'text']</value>
      <webElementGuid>9cbce465-ffd7-43ac-aeb1-0fe1805f0c55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
