<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur Post Code</name>
   <tag></tag>
   <elementGuidId>f979be27-4cec-4a44-a5ba-33f0c2cb1ce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_post_code_transport_request > #dfc-item--transport-form--exportateur_post_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_post_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2727122-126a-4a0d-94b5-1388e53228bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>7a755bec-a97c-484d-8576-50cd83f558d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_post_code_transport_request</value>
      <webElementGuid>6b1b4408-c7cb-40a6-92cb-faef1679ac0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_post_code_transport_request</value>
      <webElementGuid>e52dca3a-ce44-4f61-9a2e-e566056fd3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur Post Code</value>
      <webElementGuid>482abaa8-b1bb-45eb-b806-1b0bda220e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3b9421c-cd59-4979-89c4-4d4357778c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ddd14be0-0deb-4082-ba42-e6e1b102797e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_post_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_post_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_post_code_transport_request&quot;]</value>
      <webElementGuid>b77d7a22-af89-462f-a87a-64d58864fa1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_post_code_transport_request']</value>
      <webElementGuid>fa91a950-792f-4f10-8c0c-bef7cb7fdbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_post_code_transport_request']/input</value>
      <webElementGuid>8edab03d-c22e-4f7f-a154-ec2162dfc36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[33]/div/div/input</value>
      <webElementGuid>345b8850-a37a-4ca0-98a2-dc6180c7c49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_post_code_transport_request' and @name = 'exportateur_post_code_transport_request' and @placeholder = 'Exportateur Post Code' and @type = 'text']</value>
      <webElementGuid>5b31188d-5d17-4777-8385-2256ee245bd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
