<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To Company Code</name>
   <tag></tag>
   <elementGuidId>838aef11-e220-4aec-8d70-0660e594a3af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_company_code_transport_request > #dfc-item--transport-form--bill_to_company_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_company_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34fa2dc8-b18c-4584-87ff-8df40bad3623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>e207885c-d05e-4298-ad8d-6dd100df994a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_company_code_transport_request</value>
      <webElementGuid>44d3619e-9c28-415f-bc43-32b6743f9fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_company_code_transport_request</value>
      <webElementGuid>0890aa43-3fb0-4e36-8e67-c4e19c5d29cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To Company Code</value>
      <webElementGuid>77697435-4ac4-4309-ad5e-3b0b5b51c472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9780924a-0773-4c23-b5c3-5572fcc75e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>e2f6c638-d5d7-4c7a-9a62-0b2087d61029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_company_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_company_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_company_code_transport_request&quot;]</value>
      <webElementGuid>c11f465d-2e7f-47c3-b40a-0656b2a68ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_company_code_transport_request']</value>
      <webElementGuid>1aeee554-3a67-4c74-b0aa-afae5b48bfe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_company_code_transport_request']/input</value>
      <webElementGuid>80a051d4-fb01-48e4-948c-72cd0777ac46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[2]/div/div/input</value>
      <webElementGuid>445820d0-ca76-4a30-854b-3f94871f60ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_company_code_transport_request' and @name = 'bill_to_company_code_transport_request' and @placeholder = 'Bill To Company Code' and @type = 'text']</value>
      <webElementGuid>9898d495-4d84-4701-8f9a-27b7794804f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
