<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transitflag</name>
   <tag></tag>
   <elementGuidId>f5cefa59-b0ab-4dec-abe6-af843d18521a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--transitflag_transport_request > #dfc-item--transport-form--transitflag_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--transitflag_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3107f0b4-02ea-4eed-81c9-ea71f5a24973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>4217ef7c-98a4-4e5f-bbd0-0f7198263348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--transitflag_transport_request</value>
      <webElementGuid>1e66b885-4bb8-4b43-b918-a5a6fd7c6f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transitflag_transport_request</value>
      <webElementGuid>2ab30353-b77d-4538-aaf0-b2d5b2650a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Transitflag</value>
      <webElementGuid>dd3e575d-e7da-43d9-863a-4d91ed2d7f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cda2520a-266d-49ab-b05c-5422898e3249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>0b85dba3-9625-4f7f-91ad-04b16d38cbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--transitflag_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--transitflag_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--transitflag_transport_request&quot;]</value>
      <webElementGuid>1d59bb84-7716-476a-a913-a5fe8df77e4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--transitflag_transport_request']</value>
      <webElementGuid>86981748-77fd-412a-bffd-b9a68e7a211f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--transitflag_transport_request']/input</value>
      <webElementGuid>bb332a86-469e-4c8f-b539-e9abd30e455f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[16]/div/div/input</value>
      <webElementGuid>5d32ec4a-dac3-4bc2-addb-9b1ce65e8576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--transitflag_transport_request' and @name = 'transitflag_transport_request' and @placeholder = 'Transitflag' and @type = 'text']</value>
      <webElementGuid>0e5ec663-fb5e-40f8-994d-61fae6fe1a33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
