<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur Zip Code</name>
   <tag></tag>
   <elementGuidId>31419e6a-fda7-417d-b547-5d06905aec90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_zip_code_transport_request > #dfc-item--transport-form--exportateur_zip_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_zip_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb2c0aa6-78c2-4e81-ad46-a098ad3972f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>ccd0d1fd-1086-4f63-be90-d5b131ef2b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_zip_code_transport_request</value>
      <webElementGuid>403114eb-dfa5-4526-a856-38b9c12bd15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_zip_code_transport_request</value>
      <webElementGuid>dc092a95-f971-4340-a8e1-fd834984759a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur Zip Code </value>
      <webElementGuid>64433424-6bc8-4741-852d-13ec691f940f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>036a9391-d815-478e-aedb-34f2702dd112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>0400fdf7-5aa5-4a22-93f2-79924ddb0d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_zip_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_zip_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_zip_code_transport_request&quot;]</value>
      <webElementGuid>6ea2f900-6556-4760-be51-6b9bf8621c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_zip_code_transport_request']</value>
      <webElementGuid>dfc8a5cc-b1e5-46b4-ac8c-f01b3d504144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_zip_code_transport_request']/input</value>
      <webElementGuid>40b55342-25c5-49a8-bd38-27206f724e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[31]/div/div/input</value>
      <webElementGuid>32b30fb6-edbd-4351-9926-b2d1c036c6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_zip_code_transport_request' and @name = 'exportateur_zip_code_transport_request' and @placeholder = 'Exportateur Zip Code ' and @type = 'text']</value>
      <webElementGuid>cedd049a-a35b-4df4-bb0f-cdc98ed18759</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
