<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Code</name>
   <tag></tag>
   <elementGuidId>e21b18f6-9af0-4500-962a-474013261b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carrier_code_transport_request']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carrier_code_transport_request > #dfc-item--transport-form--carrier_code_transport_request</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08b81f16-2b35-4906-a45d-0103fc025703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>762f5b74-36c9-458a-8b24-6721a640e79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carrier_code_transport_request</value>
      <webElementGuid>854af4fb-17f6-4610-a8ea-c9d08d4be9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrier_code_transport_request</value>
      <webElementGuid>ea3218c9-e5a7-4002-9636-bb2c4c1bf08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier Code</value>
      <webElementGuid>1fe46f98-e4dc-4f23-941f-0d50399fccf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d952c44b-9e39-44ac-8d35-df723cd276e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-star-inserted ng-touched</value>
      <webElementGuid>8e6ac09e-155a-4ef4-ae54-1fff42d277d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carrier_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carrier_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carrier_code_transport_request&quot;]</value>
      <webElementGuid>3ef1eb2d-f1f5-4787-95c2-c832b1796a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carrier_code_transport_request']</value>
      <webElementGuid>f3618b79-bee7-4c5e-b3d2-3041e0941ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carrier_code_transport_request']/input</value>
      <webElementGuid>d96bd44a-bec8-40af-9f74-be272cbca46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[9]/div/div/input</value>
      <webElementGuid>45091430-61e4-420d-affe-5f178c36b188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carrier_code_transport_request' and @name = 'carrier_code_transport_request' and @placeholder = 'Carrier Code' and @type = 'text']</value>
      <webElementGuid>cb08b208-51d3-4a0d-ad21-101d8b6032cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
