<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer_Reference</name>
   <tag></tag>
   <elementGuidId>0c6507fa-53df-42cf-9ed1-c39794baa916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--customerReference']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--customerReference > #dfc-item--transport-form--customerReference</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42b4e0f9-1571-483e-87c8-43bc9fc9384e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>9c381ae0-60e5-4484-aa7c-97e54a8b2c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--customerReference</value>
      <webElementGuid>2d5bd1f3-86e7-4201-9e89-2995b3bb361d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerReference</value>
      <webElementGuid>02b9e12a-f0a6-4c4b-99b5-aedede0af3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Customer Reference</value>
      <webElementGuid>ff95d89c-3f3d-4212-9600-d85e8df02d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>555bc3ce-6928-424c-aaea-04fa34cb7923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>5948aa53-54c4-436d-a49b-6ab28cd6decf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--customerReference&quot;)/div[@id=&quot;dfc-item--transport-form--customerReference&quot;]/input[@id=&quot;dfc-item--transport-form--customerReference&quot;]</value>
      <webElementGuid>d8a50262-eb7d-48c6-a98e-5eada34a8707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--customerReference']</value>
      <webElementGuid>44b88e4d-be2e-4bbf-a3a7-ec2a9972854f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--customerReference']/input</value>
      <webElementGuid>48c95144-e7f8-4c85-9535-69ac1ebae06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[5]/div/div/input</value>
      <webElementGuid>2f03d0a1-7d5a-4adb-b515-43b758315010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--customerReference' and @name = 'customerReference' and @placeholder = 'Customer Reference' and @type = 'text']</value>
      <webElementGuid>6b4bf8b8-bd3d-4c71-b1c2-62b923a50eac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
