<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To Post Code</name>
   <tag></tag>
   <elementGuidId>b27ed7e0-68b0-4a7e-8130-6db467c79e3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_post_code_transport_request > #dfc-item--transport-form--bill_to_post_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_post_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7de7de63-1b6e-4826-84a7-098ccc63db3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>a4bfab96-9568-41e3-95f7-eef3d7ff21c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_post_code_transport_request</value>
      <webElementGuid>4895352b-49b2-43ae-878a-466c57efe61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_post_code_transport_request</value>
      <webElementGuid>56eee3bd-9d5b-455c-84af-8c4bacd87a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To Post Code</value>
      <webElementGuid>f8005a8c-86db-45ba-a4ef-b03b9bfe44d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c290fb1-54bc-42cd-8d79-f75bfbce1995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>1fdbd389-278f-4fa0-b16a-cd115090e5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_post_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_post_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_post_code_transport_request&quot;]</value>
      <webElementGuid>a3b740f7-baf7-4411-be7f-e00b16bdb1bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_post_code_transport_request']</value>
      <webElementGuid>7faa9a59-496c-415e-a53b-3a4457597644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_post_code_transport_request']/input</value>
      <webElementGuid>d8a95dc4-20ae-4ce4-96a4-a451721f27a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[10]/div/div/input</value>
      <webElementGuid>7f3ed4ee-255f-48de-bed1-9803b2fd3ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_post_code_transport_request' and @name = 'bill_to_post_code_transport_request' and @placeholder = 'Bill To Post Code' and @type = 'text']</value>
      <webElementGuid>4d259276-6b64-4e44-a6a5-f8e9a7e401bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
