<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Address 1</name>
   <tag></tag>
   <elementGuidId>c6d36a7a-0f71-478d-bce1-19d10522e0a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carrier_address_1_transport_request > #dfc-item--transport-form--carrier_address_1_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carrier_address_1_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3656bc0-5420-4f0d-ac9a-defbfbcd6f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>257d9524-8a97-4551-8094-e7e18fab1623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carrier_address_1_transport_request</value>
      <webElementGuid>ee702a0b-143d-428d-bd4d-a6adc66b5cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrier_address_1_transport_request</value>
      <webElementGuid>7f0e7361-0805-4fd6-9a1d-4823fdfc7f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier Address 1</value>
      <webElementGuid>41d81b36-75fa-49c1-927b-0491dca4a82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63c0a171-e04e-4cee-831d-423e18314ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>123f4455-b062-40c5-a976-e21e64f043f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carrier_address_1_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carrier_address_1_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carrier_address_1_transport_request&quot;]</value>
      <webElementGuid>b91c276c-2dfc-4979-8677-d4c265164049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carrier_address_1_transport_request']</value>
      <webElementGuid>27b374a7-8df1-4ad3-ad8a-1e81b6497282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carrier_address_1_transport_request']/input</value>
      <webElementGuid>843c5c0b-7db9-486f-8c22-ca6cbd7ad3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[15]/div/div/input</value>
      <webElementGuid>edce0033-8539-4f4d-b0c5-c9dced4e1785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carrier_address_1_transport_request' and @name = 'carrier_address_1_transport_request' and @placeholder = 'Carrier Address 1' and @type = 'text']</value>
      <webElementGuid>ddc3bf00-7ec6-4f87-b908-9acbd04fc1d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
