<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To address 2</name>
   <tag></tag>
   <elementGuidId>38bd1ff9-82bb-4565-978b-b8f7a252f94b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_address_2_transport_request > #dfc-item--transport-form--bill_to_address_2_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_address_2_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48a7d40d-9ea3-4e8a-8545-c722ca14c84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>db1b16b7-fea1-4c3c-b608-6968f0e6d0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_address_2_transport_request</value>
      <webElementGuid>6580071f-cc28-41c0-a3cf-8347f81861d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_address_2_transport_request</value>
      <webElementGuid>ccea9af4-648c-4914-b009-5e443daf8410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To address 2</value>
      <webElementGuid>f13e529b-5ebb-43b8-b066-af2c5d3db93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c39cdb4-7a20-4fc8-9dc6-079e08dacc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>8d72112a-fc8f-40c6-b0e9-3ee1a21f3c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_address_2_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_address_2_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_address_2_transport_request&quot;]</value>
      <webElementGuid>e23ea30c-2880-4579-a7dc-8ba9033f2e3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_address_2_transport_request']</value>
      <webElementGuid>e67c78a7-8e98-478d-90f4-f5cca4307a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_address_2_transport_request']/input</value>
      <webElementGuid>a4dd2ef1-98a8-4ebf-b776-bbe50458c607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[5]/div/div/input</value>
      <webElementGuid>82234ba1-d11e-4ec9-9a71-401b4b43cf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_address_2_transport_request' and @name = 'bill_to_address_2_transport_request' and @placeholder = 'Bill To address 2' and @type = 'text']</value>
      <webElementGuid>94b07a73-40a5-476d-a3eb-54b2e64b72e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
