<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur Address 4</name>
   <tag></tag>
   <elementGuidId>5ed82c5a-5aa9-4106-9d8a-8c26a8b041ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_address_4_transport_request > #dfc-item--transport-form--exportateur_address_4_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_address_4_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10fe623c-ed30-432f-a080-3ca96932419f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>3107197b-ef68-4188-9693-d9c786c81672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_address_4_transport_request</value>
      <webElementGuid>c716f627-037b-4db7-bced-14e129190eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_address_4_transport_request</value>
      <webElementGuid>daab95bc-3426-4eb3-bb20-cb401bb62839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur Address 4</value>
      <webElementGuid>7ae8d065-ab14-41b2-aca8-096152c6f26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fbb33f1f-f52b-4187-bff9-03cf70def0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>19aea2a2-df74-43f5-997f-3b82a25fc9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_address_4_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_address_4_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_address_4_transport_request&quot;]</value>
      <webElementGuid>eed1aca1-5d15-4f56-b479-64ce42be4316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_address_4_transport_request']</value>
      <webElementGuid>4f16c7b4-119f-4be3-8640-393f5c87b2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_address_4_transport_request']/input</value>
      <webElementGuid>ce3c3185-b4a1-4016-b844-5a5100e86e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[30]/div/div/input</value>
      <webElementGuid>e6ccb249-8366-4843-825a-4bb4b18d26c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_address_4_transport_request' and @name = 'exportateur_address_4_transport_request' and @placeholder = 'Exportateur Address 4' and @type = 'text']</value>
      <webElementGuid>f35f4c39-4a48-43f2-98d7-c80c11b20b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
