<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur District</name>
   <tag></tag>
   <elementGuidId>da024524-9022-43c6-98b4-4c0443c01186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_district_transport_request > #dfc-item--transport-form--exportateur_district_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_district_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfe52024-3cc9-41a1-8e8e-ca774af930ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>7d5b30c6-bd85-4511-8674-b1be9d5db15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_district_transport_request</value>
      <webElementGuid>1853d5c7-916f-46ff-9dd5-fd21851c8d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_district_transport_request</value>
      <webElementGuid>de032800-4e7c-4f64-96b9-fbeb9e8b78f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur District </value>
      <webElementGuid>5f763e86-60e9-4eec-aa98-ad055adb8f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d3837ea-2967-483e-b897-fca80c191697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>f5037943-1ab3-4116-a969-3996be1222d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_district_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_district_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_district_transport_request&quot;]</value>
      <webElementGuid>07fb0244-ba6d-4fc9-bec1-a0b3c6c4cff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_district_transport_request']</value>
      <webElementGuid>6a8ec281-cf9c-4e6f-b6e3-529df2690d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_district_transport_request']/input</value>
      <webElementGuid>454cbd56-25f2-4693-b985-f9c235ccb705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[34]/div/div/input</value>
      <webElementGuid>799769a7-354e-401c-a4eb-f8b441639695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_district_transport_request' and @name = 'exportateur_district_transport_request' and @placeholder = 'Exportateur District ' and @type = 'text']</value>
      <webElementGuid>486dd052-8c18-48b1-97fe-78de0f7c31c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
