<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of goods availability</name>
   <tag></tag>
   <elementGuidId>4fcceba5-9079-4ae9-a1a6-26dba782a33f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateOfGoodsAvailability']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dateOfGoodsAvailability</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>084e6b41-186e-4031-8e48-a0b1dbffeb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateOfGoodsAvailability</value>
      <webElementGuid>9384d697-1faf-4d48-857d-1a63aef0af1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2200-02-01</value>
      <webElementGuid>d8a08a80-bf57-47c1-a496-6ef1f03cfa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900-02-01</value>
      <webElementGuid>34dfcf9f-5a30-48dd-b7d4-93711b93e121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dateOfGoodsAvailability</value>
      <webElementGuid>7f9bb651-b029-40e7-b8a3-ec93c02e9669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of goods availability</value>
      <webElementGuid>00f4c19f-702a-4c98-95e7-12042474f1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>cefe0339-a729-4b50-8cbe-495921dc76aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>4c49941b-db0a-4f8f-809f-8e8dc7786ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateOfGoodsAvailability&quot;)</value>
      <webElementGuid>30d6a10a-3655-40b9-a7df-669dbe68ce94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateOfGoodsAvailability']</value>
      <webElementGuid>3b1dd0f1-31b1-44f5-a2a9-962630003f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--dateOfGoodsAvailability']/df-date-form/div/input</value>
      <webElementGuid>51ef05b4-8daa-41c4-b646-b794dc66c39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-date-form/div/input</value>
      <webElementGuid>ec263a71-636f-41bb-82e5-8d1231b7ef2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dateOfGoodsAvailability' and @name = 'dateOfGoodsAvailability' and @placeholder = 'Date of goods availability' and @type = 'date']</value>
      <webElementGuid>bd0cfa5b-ffe7-4a8c-b676-51e56deef4cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
