<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur Code</name>
   <tag></tag>
   <elementGuidId>de5b1b3a-b34c-459c-852c-a9aab09314ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_information_exportateur_code_transport_request > #dfc-item--transport-form--exportateur_information_exportateur_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_information_exportateur_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6eb7d9d3-30d3-4428-8559-5fbe475dd0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>28e92e02-4fab-4e08-8fba-38416fece9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_information_exportateur_code_transport_request</value>
      <webElementGuid>39f66a13-06db-4c5e-a8a1-2f86bd86eadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_information_exportateur_code_transport_request</value>
      <webElementGuid>e1731ab7-8920-412b-b703-4027ba886029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur Code</value>
      <webElementGuid>a6607ed7-0fd2-4bfc-a492-db5ab36f9c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c86d6f98-9a58-4093-8c71-98d5e49ec0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>37fdcf5f-5af1-4014-b484-ea95a23c7bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_information_exportateur_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_information_exportateur_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_information_exportateur_code_transport_request&quot;]</value>
      <webElementGuid>e2b79f0a-2256-4662-b5f7-a407f89feaff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_information_exportateur_code_transport_request']</value>
      <webElementGuid>6c2070ef-40c9-4647-80b2-f0687b4f8b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_information_exportateur_code_transport_request']/input</value>
      <webElementGuid>bac64e39-04f1-42e1-9f00-1f4df55dd622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[25]/div/div/input</value>
      <webElementGuid>af7d2d76-d36b-4b63-89d4-d6b8634d044a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_information_exportateur_code_transport_request' and @name = 'exportateur_information_exportateur_code_transport_request' and @placeholder = 'Exportateur Code' and @type = 'text']</value>
      <webElementGuid>9994db32-d8fc-4448-9d58-d7aaa1eff6c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
