<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Zip Code</name>
   <tag></tag>
   <elementGuidId>24bad5d6-78da-428a-b49c-6076d17d10a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carier_zip_code_transport_request > #dfc-item--transport-form--carier_zip_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carier_zip_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae9676a0-17da-41a3-93a7-edbadd98c231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>f065fece-3e9d-41ee-9131-90320029582c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carier_zip_code_transport_request</value>
      <webElementGuid>24907627-3f2a-4dd6-ba7a-8b1d2674fae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carier_zip_code_transport_request</value>
      <webElementGuid>4a4cf7da-6485-4fb4-8b4a-3ce09263eed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier Zip Code</value>
      <webElementGuid>a1f1b63a-8e0c-4f14-bfd0-a54a29498a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e09364aa-df72-471f-9cc8-f9765918bea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>6bd3884d-9e53-4c4f-9164-a3c3aef07642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carier_zip_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carier_zip_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carier_zip_code_transport_request&quot;]</value>
      <webElementGuid>46f60eee-1112-4a20-9930-2aa723c15f6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carier_zip_code_transport_request']</value>
      <webElementGuid>214abf86-191a-4fd4-a7d9-50099b46bd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carier_zip_code_transport_request']/input</value>
      <webElementGuid>60164f32-5377-43cf-84f3-56436e9bebfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[19]/div/div/input</value>
      <webElementGuid>0f1bc29c-7124-4442-a464-eaa5adb71a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carier_zip_code_transport_request' and @name = 'carier_zip_code_transport_request' and @placeholder = 'Carrier Zip Code' and @type = 'text']</value>
      <webElementGuid>b0988c9f-9a7f-489d-9202-7dd3419d38d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
