<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Incoterm Location</name>
   <tag></tag>
   <elementGuidId>72dd9db1-276e-4d78-911d-da96a4c4dab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--incoterm_location_transport_request > #dfc-item--transport-form--incoterm_location_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--incoterm_location_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55e49676-247f-4b3a-9f9a-d10d4cdd7b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>66ba6ee3-290d-4aab-89ae-f4662083f2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--incoterm_location_transport_request</value>
      <webElementGuid>b93e3044-fb45-453b-a484-b8607ef5596a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>incoterm_location_transport_request</value>
      <webElementGuid>432e9584-ade3-4450-8e4d-08ca685d3970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Incoterm Location</value>
      <webElementGuid>6c813926-baa4-451f-aa66-e5ca7e876666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>865ae11b-0097-4949-9838-40598f510251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>0ed980f3-6620-4583-97b5-c81dd89de212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--incoterm_location_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--incoterm_location_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--incoterm_location_transport_request&quot;]</value>
      <webElementGuid>14ed6781-b847-4ce2-9bba-94155a039e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--incoterm_location_transport_request']</value>
      <webElementGuid>890e6efa-1f8a-48cc-9553-0732c601c299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--incoterm_location_transport_request']/input</value>
      <webElementGuid>296fb6eb-39b3-4743-8e85-66cca0060eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[28]/div/div/input</value>
      <webElementGuid>80bff3cf-1646-4c78-b112-14551d2e2dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--incoterm_location_transport_request' and @name = 'incoterm_location_transport_request' and @placeholder = 'Incoterm Location' and @type = 'text']</value>
      <webElementGuid>52735a88-544d-4bdb-b6eb-0a689435486b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
