<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To_form</name>
   <tag></tag>
   <elementGuidId>b1a3128c-63f0-4fb7-a312-0c8edb174c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;dfc-dyn-root--transport-form--addressDest&quot;]/app-address-picker-form-control//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-dyn-root--transport-form--addressDest > app-address-picker-form-control.ng-star-inserted > div.df-form-control-root.ng-star-inserted > div.df-form-control-item > div.d-flex.ng-star-inserted > div.flex-grow-1 > input.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d7391fa-5d7e-4795-bed2-aab8c152de8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>240ae765-2601-4ca9-8356-2198e26885da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>f76f9be1-184f-43c4-af95-48cb8f641c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7680b10f-04e0-4608-8847-4b66b6e2286c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search addresses</value>
      <webElementGuid>a1947a4c-0d84-4c87-8e1d-a71aa1600928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--transport-form--addressDest&quot;)/app-address-picker-form-control[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;df-form-control-root ng-star-inserted&quot;]/div[@class=&quot;df-form-control-item&quot;]/div[@class=&quot;d-flex ng-star-inserted&quot;]/div[@class=&quot;flex-grow-1&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>f9a20745-78ce-4bf4-8561-8b4127c04c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[9]</value>
      <webElementGuid>9d4feb63-8192-415c-a18b-791a68c92881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--transport-form--addressDest']/app-address-picker-form-control/div/div/div/div/input</value>
      <webElementGuid>5aba804f-eadb-4630-b30e-3c4cc0844d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[35]/div/app-address-picker-form-control/div/div/div/div/input</value>
      <webElementGuid>d241d938-988e-41e5-a3dc-e51cff435c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search addresses']</value>
      <webElementGuid>6d93fa4d-28f5-49ff-a07b-4b05eafa5775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
