<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BC date validated</name>
   <tag></tag>
   <elementGuidId>87bf345c-784b-4eba-91b3-8c8b190550e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bc_date_validated_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bc_date_validated_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52987910-b4fb-4fd8-abfc-0a2ce59d0e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bc_date_validated_transport_request</value>
      <webElementGuid>d8006a60-4d3d-429c-8c15-aa84e46d0342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2200-02-01T00:00:00</value>
      <webElementGuid>b560bd1c-d7a7-4741-89e1-4e8e6a2ebcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900-02-01T00:00:00</value>
      <webElementGuid>e7db8fbc-8f9a-4a12-a86d-f713831bedab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bc_date_validated_transport_request</value>
      <webElementGuid>b32b9649-bdab-4dd5-a8e5-ad2e12d123df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>BC date validated </value>
      <webElementGuid>cb968714-725d-434c-88d2-36a37b4c5c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>78114598-b2c7-4e17-9896-bbb2765ee5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1b1aa4a6-65ca-4a76-8617-8a9f557f938a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bc_date_validated_transport_request&quot;)</value>
      <webElementGuid>8ff54fd5-2ded-4496-8b0d-642476f53a81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bc_date_validated_transport_request']</value>
      <webElementGuid>7875f23b-85b4-4c52-9971-285bc814d0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bc_date_validated_transport_request']/df-date-form/div/input</value>
      <webElementGuid>bf6892da-ed54-4982-8eb2-e34e603a66c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[7]/div/div/df-date-form/div/input</value>
      <webElementGuid>a6cd5cce-5563-4094-b080-22d3b068672e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bc_date_validated_transport_request' and @name = 'bc_date_validated_transport_request' and @placeholder = 'BC date validated ' and @type = 'datetime-local']</value>
      <webElementGuid>1cf75bf3-f2dd-4c9c-9e2e-bc676b94c8f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
