<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PDF Link</name>
   <tag></tag>
   <elementGuidId>79074307-c259-42f4-882b-b2aa2cb007a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--pdf_link_transport_request > #dfc-item--transport-form--pdf_link_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--pdf_link_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c66ff2e-bb46-4a54-9344-25b3aa125a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>aea01c7c-5d64-4cb8-af73-3ae9232635d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--pdf_link_transport_request</value>
      <webElementGuid>3227126a-f530-4dfd-99a8-bdd91f07c8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pdf_link_transport_request</value>
      <webElementGuid>0076f981-5006-40e1-8417-11226f2349ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PDF Link</value>
      <webElementGuid>7474cd11-759a-4a59-bed1-54d47df692fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f855826d-ca5c-4848-8892-9c8a665c6604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>4b6c9c2a-a338-4bf7-900e-5d1ce9d9df10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--pdf_link_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--pdf_link_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--pdf_link_transport_request&quot;]</value>
      <webElementGuid>461d5b53-786d-4bd0-b73f-c99df803d1dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--pdf_link_transport_request']</value>
      <webElementGuid>63acdf41-a935-4f70-b4cd-7d8b4a6b7626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--pdf_link_transport_request']/input</value>
      <webElementGuid>58891f57-cf17-437f-ae41-9452fd7440ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[22]/div/div/input</value>
      <webElementGuid>9b6d352e-fa8e-4bed-90c5-de626e55456e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--pdf_link_transport_request' and @name = 'pdf_link_transport_request' and @placeholder = 'PDF Link' and @type = 'text']</value>
      <webElementGuid>fea4ac30-1309-4905-86ce-6b1949071413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
