<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Message ID</name>
   <tag></tag>
   <elementGuidId>abac417b-9570-4fe4-bc0b-45d7f9554936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--message_id_transport_request > #dfc-item--transport-form--message_id_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--message_id_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4c1d994-c56e-49a6-a33d-6865695bb59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>16a7731b-1943-4799-aaed-54d0df953b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--message_id_transport_request</value>
      <webElementGuid>5ff93e9d-e556-4db4-9865-c3bacc95e849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message_id_transport_request</value>
      <webElementGuid>4d0ba7e9-96fe-4015-b97b-60d024a842ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Message ID</value>
      <webElementGuid>5dee4018-0478-40b7-9c11-8ebffe0c1c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f88bc8e-a820-4d61-b3a3-42277e403c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>a0d1f14e-0d02-4c48-af31-77e07ccc11ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--message_id_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--message_id_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--message_id_transport_request&quot;]</value>
      <webElementGuid>4aae52ee-e766-461f-8d08-2efd00f90894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--message_id_transport_request']</value>
      <webElementGuid>a61528c8-d825-4b1c-a2bc-ff984ea96633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--message_id_transport_request']/input</value>
      <webElementGuid>a1f9ecc4-0edb-43da-a0c1-a2ca9b170b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[21]/div/div/input</value>
      <webElementGuid>84afb50c-0335-4436-8dbb-2e95e26d0f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--message_id_transport_request' and @name = 'message_id_transport_request' and @placeholder = 'Message ID' and @type = 'text']</value>
      <webElementGuid>0b6f1014-7fbb-48d9-924c-50607118942f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
