<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To address 3</name>
   <tag></tag>
   <elementGuidId>974b880d-4987-4116-8b41-10d292605e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_address_3_transport_request > #dfc-item--transport-form--bill_to_address_3_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_address_3_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>814e07a0-f592-4fee-be5c-a674cfa85c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>0b735ccb-8e93-43c9-93b4-d56d035828d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_address_3_transport_request</value>
      <webElementGuid>367f4798-0e9f-4ffb-85ca-849ff625ebe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_address_3_transport_request</value>
      <webElementGuid>9bc45528-aa54-47cc-8c12-737b22c25eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To address 3</value>
      <webElementGuid>4d1d8068-23fa-45b5-a317-ac5c859a37a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fdd32a1-6139-4350-8cf7-06edb1220614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>b2bb83cf-bc51-4abd-94ef-4f2757be194b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_address_3_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_address_3_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_address_3_transport_request&quot;]</value>
      <webElementGuid>893fdd1b-ef07-4339-bf05-158282627ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_address_3_transport_request']</value>
      <webElementGuid>eea660d3-6e46-426f-ab72-98cd2f579052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_address_3_transport_request']/input</value>
      <webElementGuid>bd07854c-8b28-482c-aa3e-ea712d535eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[6]/div/div/input</value>
      <webElementGuid>59d75454-fcd6-43fb-b571-4c8a8f4badc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_address_3_transport_request' and @name = 'bill_to_address_3_transport_request' and @placeholder = 'Bill To address 3' and @type = 'text']</value>
      <webElementGuid>e23b1cbf-d595-4dac-8a37-706e14297793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
