<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type_Of_Shipment</name>
   <tag></tag>
   <elementGuidId>dd79a594-137f-4a14-b3e9-fb4b00aea9ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--type_of_shipment_transport_request']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--type_of_shipment_transport_request > #dfc-item--transport-form--type_of_shipment_transport_request</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd7e616a-0132-49c1-92ac-cf31c60e0d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>d80cd1cd-2ef9-4fce-8e43-46fe32768789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--type_of_shipment_transport_request</value>
      <webElementGuid>4d3a814a-eac6-4f4f-8303-b088f3f7fa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type_of_shipment_transport_request</value>
      <webElementGuid>27b16bac-56f0-4691-8277-b82f550f7024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type of Shipment</value>
      <webElementGuid>d6e312c7-afda-44c4-a8a1-2c0395c5276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2eca9fd8-e240-47b3-a268-2c816d3a7cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-star-inserted ng-touched ng-dirty</value>
      <webElementGuid>cdbf910b-ebf4-489f-bc78-1f240e11c2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--type_of_shipment_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--type_of_shipment_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--type_of_shipment_transport_request&quot;]</value>
      <webElementGuid>16c1ad69-db70-4a0f-86f9-487e661c42dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--type_of_shipment_transport_request']</value>
      <webElementGuid>c66b2e88-4e7e-40c3-9bdd-b31c91dde406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--type_of_shipment_transport_request']/input</value>
      <webElementGuid>baa93e72-6547-45c2-b46a-9cd5d2419aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[10]/div/div/input</value>
      <webElementGuid>51ec711a-d129-49e5-8be8-50209af81ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--type_of_shipment_transport_request' and @name = 'type_of_shipment_transport_request' and @placeholder = 'Type of Shipment' and @type = 'text']</value>
      <webElementGuid>ff557374-1b7e-4fbe-bca0-3ae20db73bd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
