<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier District</name>
   <tag></tag>
   <elementGuidId>8925efa2-e7c6-490a-972f-d19245808991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carrier_district_transport_request > #dfc-item--transport-form--carrier_district_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carrier_district_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eb6c219-91a7-48e5-a9e3-292dd3ed295a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>1de121c5-a777-44a5-aed2-66155ebb8221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carrier_district_transport_request</value>
      <webElementGuid>5ab583de-a644-45b1-b915-2b2dafdbec83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrier_district_transport_request</value>
      <webElementGuid>d49e462a-647c-446a-bd44-9b2c800783c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier District</value>
      <webElementGuid>ab7c7e06-3fe4-4348-98b1-8d26030a4cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b12567c8-8687-4c25-90fe-3d1eb54fcecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>44542401-b69c-4dcd-8a7d-68b545a89106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carrier_district_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carrier_district_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carrier_district_transport_request&quot;]</value>
      <webElementGuid>5aea5934-b056-4469-8c26-4c756aeeb97c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carrier_district_transport_request']</value>
      <webElementGuid>93af95c8-0388-4bbe-8303-02c907de193e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carrier_district_transport_request']/input</value>
      <webElementGuid>98b74b78-2df9-40b6-868e-5de86ae5d373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[22]/div/div/input</value>
      <webElementGuid>a190b4e8-3990-4753-afd3-d999d66846b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carrier_district_transport_request' and @name = 'carrier_district_transport_request' and @placeholder = 'Carrier District' and @type = 'text']</value>
      <webElementGuid>a9fc58c2-b0ac-48b7-a850-02846e7999c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
