<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier City</name>
   <tag></tag>
   <elementGuidId>c1314a7a-81e0-45ed-bf0f-3269d24e0f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carrier_city_transport_request > #dfc-item--transport-form--carrier_city_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carrier_city_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a0f9394-5deb-4b66-8f79-d84e26529726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>23aa3b87-d60e-4d29-bc86-cd025f2ada38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carrier_city_transport_request</value>
      <webElementGuid>28dc7224-dd04-4c62-b57e-f32e3f74d6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrier_city_transport_request</value>
      <webElementGuid>26b11aa2-3790-463a-995e-67bbdf1ab5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier City</value>
      <webElementGuid>1981099a-10cc-4ddf-8749-ce66d0999df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f7e45c8-72de-49ae-ba02-bc6ee1c30b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>ed4b8bfa-082a-4df6-86a5-03fdb856c723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carrier_city_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carrier_city_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carrier_city_transport_request&quot;]</value>
      <webElementGuid>a38780c6-7989-463f-ac6c-c19e859804ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carrier_city_transport_request']</value>
      <webElementGuid>76e90fc8-cf45-4104-8e0f-c0a2a1f0d5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carrier_city_transport_request']/input</value>
      <webElementGuid>b721f470-8582-4bae-98e1-8c02cedef8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[20]/div/div/input</value>
      <webElementGuid>de4ea41f-25ab-4685-9266-fcb1be5f755e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carrier_city_transport_request' and @name = 'carrier_city_transport_request' and @placeholder = 'Carrier City' and @type = 'text']</value>
      <webElementGuid>36e2d818-28ab-40a0-a05e-1419aa1b1e3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
