<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UnitReference</name>
   <tag></tag>
   <elementGuidId>b7dd04e8-9814-42b2-ae43-dff794121f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-unit-content-form--unitReference']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-unit-content-form--unitReference > #dfc-item--transport-unit-content-form--unitReference</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7eb5f5d5-5711-4044-9412-bc098e17f439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>aadcf753-8ad8-48c4-9440-4aacfdfd4332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-unit-content-form--unitReference</value>
      <webElementGuid>46143d42-df52-4414-b7ff-77cea90e8bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unitReference</value>
      <webElementGuid>35c10b15-2acf-4458-ac84-0d40284bf39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>c392ae82-0b5a-4843-a91c-ec4cc4f6d05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55f6ec61-7e85-49e3-a7ea-bbf560612368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>c7f65791-146b-4027-9837-a5221e19e466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-unit-content-form--unitReference&quot;)/div[@id=&quot;dfc-item--transport-unit-content-form--unitReference&quot;]/input[@id=&quot;dfc-item--transport-unit-content-form--unitReference&quot;]</value>
      <webElementGuid>194f01d6-c35c-43d8-b8a2-481690422950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-unit-content-form--unitReference']</value>
      <webElementGuid>879b017a-bba6-4f47-a5b4-0d96b3537dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-unit-content-form--unitReference']/input</value>
      <webElementGuid>6b6a8a48-aeda-41a8-8432-6d8b4c019f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-transport-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[3]/div/div/input</value>
      <webElementGuid>e35b26b1-a4a2-4724-b1f6-ebaf7d85ff1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-unit-content-form--unitReference' and @name = 'unitReference' and @placeholder = 'Reference' and @type = 'text']</value>
      <webElementGuid>b4171cb6-aa81-4805-94f1-5690887a34ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
