<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To Zip Code</name>
   <tag></tag>
   <elementGuidId>467fea2f-0267-4621-86b9-39ac05df26e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_zip_code_transport_request > #dfc-item--transport-form--bill_to_zip_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_zip_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55b86dfa-97b6-4a04-a9fa-6ab32cd93094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>ea0e8e23-ec26-45b3-a1c1-ba6d41823a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_zip_code_transport_request</value>
      <webElementGuid>1882bd5b-41ee-44e2-9343-b6e967a1e2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_zip_code_transport_request</value>
      <webElementGuid>83d9476c-2fc5-45ce-bd6d-c642b3df1459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To Zip Code</value>
      <webElementGuid>de9886b3-b819-4d0a-8c03-5461715d43d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d56e17a3-710a-4921-b782-7f704292888b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>25432a92-11a8-4591-ab4c-11fce3c9f96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_zip_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_zip_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_zip_code_transport_request&quot;]</value>
      <webElementGuid>03f0bb33-8b58-410a-8737-ba3bc4643f1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_zip_code_transport_request']</value>
      <webElementGuid>bf9dc737-b297-4e79-a6be-bd641acf0304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_zip_code_transport_request']/input</value>
      <webElementGuid>58f25ac9-c391-44a4-8e29-e41b093822cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[8]/div/div/input</value>
      <webElementGuid>d6bbb83c-ca0f-4c38-81d7-350133a36bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_zip_code_transport_request' and @name = 'bill_to_zip_code_transport_request' and @placeholder = 'Bill To Zip Code' and @type = 'text']</value>
      <webElementGuid>8b7183db-b0c1-4aba-a092-d27495b64121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
