<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To Admin Sub</name>
   <tag></tag>
   <elementGuidId>e1416ea9-ded2-4c3d-9a7a-ebb1d9a290c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_admin_sub_transport_request > #dfc-item--transport-form--bill_to_admin_sub_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_admin_sub_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>719ebff1-a889-40a7-b9a4-eb5bb6eaf487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>544cf7f2-de28-48d7-a571-d33cbbc8eb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_admin_sub_transport_request</value>
      <webElementGuid>9506d1b8-3106-468d-9062-60b76a853d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_admin_sub_transport_request</value>
      <webElementGuid>3a0f3d08-b322-43a5-9e9f-42dfabc201be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To Admin Sub</value>
      <webElementGuid>84bb5aa5-9c9d-440d-bce9-abe10cf72cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e796a0b3-29be-4fdf-b84f-87c5eaa7b842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>c97fa87d-81f9-4676-9735-5b25a6d6d7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_admin_sub_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_admin_sub_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_admin_sub_transport_request&quot;]</value>
      <webElementGuid>a5ffc70d-262f-4c24-a8bd-aa0913b5c611</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_admin_sub_transport_request']</value>
      <webElementGuid>df6e9d15-dadd-4eaa-9085-9c028b1755bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_admin_sub_transport_request']/input</value>
      <webElementGuid>c1785f7e-8955-46da-bf8d-cdfd97396d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[12]/div/div/input</value>
      <webElementGuid>cd1ec6dc-d5de-468a-9d43-25746b913767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_admin_sub_transport_request' and @name = 'bill_to_admin_sub_transport_request' and @placeholder = 'Bill To Admin Sub' and @type = 'text']</value>
      <webElementGuid>48582f99-00f4-48e7-b0ab-a68c6f55ef7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
