<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Post Code</name>
   <tag></tag>
   <elementGuidId>838a89fa-7374-4775-8590-1889202ea8c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carrier_post_code_transport_request > #dfc-item--transport-form--carrier_post_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carrier_post_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46dabe2b-47b0-4905-af7c-f65c97bf83d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>9da29078-4714-4bd2-a39f-17e913fbfe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carrier_post_code_transport_request</value>
      <webElementGuid>18920925-58a1-4ad2-8423-c631e425be5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrier_post_code_transport_request</value>
      <webElementGuid>e7235604-38b1-4f8b-8764-7c47875c5d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier Post Code</value>
      <webElementGuid>08e3763d-3056-4221-8be1-a21fafc7ef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>086cf7b9-1521-4597-a321-0455013b28f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>064072c0-8ad8-48d5-afff-36a61cb51755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carrier_post_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carrier_post_code_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carrier_post_code_transport_request&quot;]</value>
      <webElementGuid>9dcc5c2d-227a-47d7-b14a-564e06df8e6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carrier_post_code_transport_request']</value>
      <webElementGuid>558a46ea-a125-4fc5-847e-17dc139d8eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carrier_post_code_transport_request']/input</value>
      <webElementGuid>7550806c-c5c0-4454-a468-5ef57f0778c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[21]/div/div/input</value>
      <webElementGuid>58e38aff-059c-4dd8-a815-d968e14635c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carrier_post_code_transport_request' and @name = 'carrier_post_code_transport_request' and @placeholder = 'Carrier Post Code' and @type = 'text']</value>
      <webElementGuid>b55636e3-78c3-47ce-afee-0303e35fe5a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
