<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur AdminSub</name>
   <tag></tag>
   <elementGuidId>3ec236eb-5eb6-4a3a-ad63-a61a480e9d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_adminsub_transport_request > #dfc-item--transport-form--exportateur_adminsub_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_adminsub_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>402d40a3-80f0-492d-baf1-59c6d5723897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>410a691c-3ccc-437a-8900-149028ae5c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_adminsub_transport_request</value>
      <webElementGuid>65cfc3a5-8100-488c-922d-5b974abe3103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_adminsub_transport_request</value>
      <webElementGuid>dd7cecc8-ad33-40d2-a78b-1ca3a9d98e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur AdminSub</value>
      <webElementGuid>13856c46-d144-4940-8692-a2f479cfda79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0546499c-c7d1-400c-8e82-0ceb91c3baff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>f3105a82-d419-4cd9-b089-049a310b3ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_adminsub_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_adminsub_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_adminsub_transport_request&quot;]</value>
      <webElementGuid>e9c4d496-d54a-4e8f-816b-e2e747ce7d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_adminsub_transport_request']</value>
      <webElementGuid>1cdff5ec-7f74-4278-81ca-b139451a06a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_adminsub_transport_request']/input</value>
      <webElementGuid>860cd81d-e468-4f86-8d1a-9bb5e1f34fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[35]/div/div/input</value>
      <webElementGuid>e27742ce-3387-4b85-b68b-305e64d8ba6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_adminsub_transport_request' and @name = 'exportateur_adminsub_transport_request' and @placeholder = 'Exportateur AdminSub' and @type = 'text']</value>
      <webElementGuid>b45f0ee8-0bfc-476e-8da9-528beb65e9df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
