<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exportateur Address 2</name>
   <tag></tag>
   <elementGuidId>6fcd918b-d284-4a60-82d0-5a200945edeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--exportateur_address_2_transport_request > #dfc-item--transport-form--exportateur_address_2_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--exportateur_address_2_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c965662c-294f-4416-ae68-56545dd79053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>473f8703-c877-4367-bbd9-a74704b002cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--exportateur_address_2_transport_request</value>
      <webElementGuid>1e3f0038-ab39-4399-b524-91fa69f09a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exportateur_address_2_transport_request</value>
      <webElementGuid>2a5ce0f0-ad50-412d-8662-fdc5fca4dc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exportateur Address 2</value>
      <webElementGuid>e3edd889-4db1-42e5-8537-68456efc323c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cfb2255-25c4-4035-b7e6-1b42397e45e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>433c9653-d5a2-4b7a-b48a-ddc87be29d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--exportateur_address_2_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--exportateur_address_2_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--exportateur_address_2_transport_request&quot;]</value>
      <webElementGuid>4278d0a7-8005-42bf-abf1-c6829ed72722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--exportateur_address_2_transport_request']</value>
      <webElementGuid>a7078ac3-1394-4b25-bba4-528b5ed652a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--exportateur_address_2_transport_request']/input</value>
      <webElementGuid>2eadc3f5-b12e-404c-b20c-b1e469db2062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[28]/div/div/input</value>
      <webElementGuid>b0ac03e9-12a9-46ba-a482-fb2f9dd57d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--exportateur_address_2_transport_request' and @name = 'exportateur_address_2_transport_request' and @placeholder = 'Exportateur Address 2' and @type = 'text']</value>
      <webElementGuid>1fad3ab4-4a9f-4cf9-b2a0-dda31a367404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
