<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To address 1</name>
   <tag></tag>
   <elementGuidId>447ac2df-e04e-451b-8aa8-a6c33d2473de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_adress_1_transport_request > #dfc-item--transport-form--bill_to_adress_1_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_adress_1_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>199d447f-0a9a-4956-98e4-2c5a066a6a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>8292fd28-99a5-49d7-b526-106b59e62e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_adress_1_transport_request</value>
      <webElementGuid>9bae173d-449a-439a-8678-b0998a7d1a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_adress_1_transport_request</value>
      <webElementGuid>31fb46e7-4f4f-4488-9e18-355db680dca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To address 1</value>
      <webElementGuid>e4133170-5d59-4fbe-8166-36181108eb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3299f749-e9d4-409b-bca8-2b52324672ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>b86f2618-55e6-4f0c-8279-976a5027cfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_adress_1_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_adress_1_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_adress_1_transport_request&quot;]</value>
      <webElementGuid>122555f3-d3e4-4135-a4c6-c8b51bab6926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_adress_1_transport_request']</value>
      <webElementGuid>363c1528-0203-4cb9-9c0f-d13ac434db59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_adress_1_transport_request']/input</value>
      <webElementGuid>c5dede44-3c4a-4c68-9f1f-62cdff0fefb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[4]/div/div/input</value>
      <webElementGuid>329bb5f8-2855-4de8-8a00-442af21b36ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_adress_1_transport_request' and @name = 'bill_to_adress_1_transport_request' and @placeholder = 'Bill To address 1' and @type = 'text']</value>
      <webElementGuid>bbd91158-27ff-4f09-bc10-4bb196c31243</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
