<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Incoterm ID</name>
   <tag></tag>
   <elementGuidId>a67d89f0-c292-4564-b8b4-142cac5a769b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--incoterm_id_transport_request > #dfc-item--transport-form--incoterm_id_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--incoterm_id_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d957646f-4521-4e02-beb1-3eb384cb36f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>986f3888-0e3d-4468-90d5-6718b7c8fcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--incoterm_id_transport_request</value>
      <webElementGuid>cbf99e0a-6006-4575-8af9-c630c4f42e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>incoterm_id_transport_request</value>
      <webElementGuid>8359792e-be89-4b9a-a0d0-88827e27318d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Incoterm ID</value>
      <webElementGuid>f28196af-1841-46c7-9c4c-a701893aa73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2dddda15-79ab-4ea6-b4f3-17d99835af21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>36d08832-66b9-421e-b956-4643a0299161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--incoterm_id_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--incoterm_id_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--incoterm_id_transport_request&quot;]</value>
      <webElementGuid>316b97d0-4c71-47c9-9072-7dc7d7f569e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--incoterm_id_transport_request']</value>
      <webElementGuid>e2efe094-7187-4080-a17f-553648dda67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--incoterm_id_transport_request']/input</value>
      <webElementGuid>ceb58bb1-0451-4f6f-8a6a-f47619f6be3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[27]/div/div/input</value>
      <webElementGuid>f7d735c3-6348-46a1-9338-95e8a356b23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--incoterm_id_transport_request' and @name = 'incoterm_id_transport_request' and @placeholder = 'Incoterm ID' and @type = 'text']</value>
      <webElementGuid>689d0b41-207f-4fe5-85ee-34015f1ff405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
