<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code chargeur connu</name>
   <tag></tag>
   <elementGuidId>cd5224b0-337b-4281-8aa1-84ad0398352f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--code_chargeur_connu_transport_request > #dfc-item--transport-form--code_chargeur_connu_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--code_chargeur_connu_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20d148f3-4133-42f0-aaef-cade440a199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>d93784c0-9436-4390-8d4e-3a6c7d22b32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--code_chargeur_connu_transport_request</value>
      <webElementGuid>2e28236c-2066-4f86-99b2-5c7ab9ac2dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code_chargeur_connu_transport_request</value>
      <webElementGuid>719c4d92-1302-4fc1-a438-fdf7dc9157da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code chargeur connu</value>
      <webElementGuid>6dc73e2d-cb42-48ad-8d3a-3267e126547b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f654b84-53c6-4618-b692-bc0b5fbcb97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>064032ac-7b70-4ea0-9929-8d08bbbf9bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--code_chargeur_connu_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--code_chargeur_connu_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--code_chargeur_connu_transport_request&quot;]</value>
      <webElementGuid>c2fd91af-2c26-44cd-845b-abd0f39f293c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--code_chargeur_connu_transport_request']</value>
      <webElementGuid>d77b97fa-ece5-40b1-a755-af26ab6c0238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--code_chargeur_connu_transport_request']/input</value>
      <webElementGuid>1e69a55a-bfda-4f00-97d2-ddfbfe87095f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/df-form-control[11]/div/div/input</value>
      <webElementGuid>5579c756-d07d-4e4d-a5b8-3dee33c1f2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--code_chargeur_connu_transport_request' and @name = 'code_chargeur_connu_transport_request' and @placeholder = 'Code chargeur connu' and @type = 'text']</value>
      <webElementGuid>84679b3b-577a-465f-a108-03df94d7e33e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
