<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Address 2</name>
   <tag></tag>
   <elementGuidId>abe8f1b0-edb4-42d4-a7ad-c972eb3f9520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--carrier_address_2_transport_request > #dfc-item--transport-form--carrier_address_2_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--carrier_address_2_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f104898-87a7-4362-b755-fc9578eae5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>ddf2a1ab-4927-431d-967c-f670cac8d3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--carrier_address_2_transport_request</value>
      <webElementGuid>572e695c-f5f0-429c-baaf-66e77ba01016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrier_address_2_transport_request</value>
      <webElementGuid>35501056-c249-4fbe-8269-152384c3c116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Carrier Address 2 </value>
      <webElementGuid>00242de5-c804-4a80-8dc0-3ad7b5de0dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df33cb43-f3d6-48bb-a7f3-a37bb606d475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>0708e5c2-d23e-403f-b031-fe2fc826008f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--carrier_address_2_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--carrier_address_2_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--carrier_address_2_transport_request&quot;]</value>
      <webElementGuid>bcc95011-2d69-4867-b5d2-965f1f9e2dae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--carrier_address_2_transport_request']</value>
      <webElementGuid>f24ae081-5174-4947-b787-4d50a39f0d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--carrier_address_2_transport_request']/input</value>
      <webElementGuid>66aa92ad-6550-4edb-a577-cb1a077aae79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[16]/div/div/input</value>
      <webElementGuid>323b4a1d-5eb5-45aa-81b3-d697050ca81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--carrier_address_2_transport_request' and @name = 'carrier_address_2_transport_request' and @placeholder = 'Carrier Address 2 ' and @type = 'text']</value>
      <webElementGuid>421edba4-34a0-40f1-8be8-fb379538a2c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
