<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To City</name>
   <tag></tag>
   <elementGuidId>21baaf43-e148-4051-85d2-6683d522c521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--bill_to_city_transport_request > #dfc-item--transport-form--bill_to_city_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--bill_to_city_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61d5ade0-371f-4491-af31-5ec6f12f9d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>d7b44679-b825-4faa-b672-c5ffcc0035d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--bill_to_city_transport_request</value>
      <webElementGuid>400bd19e-c69b-484c-ab1e-f5600c94ce15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill_to_city_transport_request</value>
      <webElementGuid>c1b2f2b8-b0cf-43ec-a644-4abc2b34429a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bill To City</value>
      <webElementGuid>6c63cf86-8590-4cd2-a7ca-5b6a7d0c92e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67076bde-19b4-42f1-b2fc-a33bd8f106ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>bd72bfad-a0e7-4f2e-8501-d08deb9caed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--bill_to_city_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--bill_to_city_transport_request&quot;]/input[@id=&quot;dfc-item--transport-form--bill_to_city_transport_request&quot;]</value>
      <webElementGuid>2cecf82f-6b3f-413f-95c5-0c2b70d33bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--bill_to_city_transport_request']</value>
      <webElementGuid>d8eab2a2-afa9-43be-93dc-dc3cd75011d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--bill_to_city_transport_request']/input</value>
      <webElementGuid>574367c1-9ca5-49c8-97c0-3e91e7a1ea47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/df-form-control[9]/div/div/input</value>
      <webElementGuid>3c69991f-79ec-4741-b573-33982e79d89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--transport-form--bill_to_city_transport_request' and @name = 'bill_to_city_transport_request' and @placeholder = 'Bill To City' and @type = 'text']</value>
      <webElementGuid>16c24ea7-efb9-4ae6-83cb-1e1232356717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
