<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_EligibleForConsolidation</name>
   <tag></tag>
   <elementGuidId>83e47444-5052-4a4b-806c-bd1c6ce6673b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--transport-form--eligibleForConsolidation--true']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--eligibleForConsolidation--true</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db8d3862-10dc-4f1b-b630-3c7f33944a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>36834e04-196c-4754-9c7b-875b79647d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--eligibleForConsolidation--true</value>
      <webElementGuid>3526dc72-b3c1-46c6-aae9-48892b7d2237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6e5cd92c-18f2-4da3-b1b9-bd30ededcf98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--transport-form--eligibleForConsolidation--true&quot;)</value>
      <webElementGuid>2989dd81-e2d1-4b9c-975e-faac15d290b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--transport-form--eligibleForConsolidation--true']</value>
      <webElementGuid>0711e85e-45bc-417a-98fd-baf3273b150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--eligibleForConsolidation']/div[2]/input</value>
      <webElementGuid>d43fca5a-d014-43fc-8b4a-f6a4767738c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[51]/div/div/div[2]/input</value>
      <webElementGuid>6cbe363e-b27a-4959-802a-98e4989e07e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--transport-form--eligibleForConsolidation--true']</value>
      <webElementGuid>445ef527-9815-43d6-9bf3-98e5ed0c67f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
