<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Ship to code</name>
   <tag></tag>
   <elementGuidId>5febd20a-2215-4507-b879-9d5152744b7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--final_ship_to_code_transport_request > #dfc-item--transport-form--final_ship_to_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--transport-form--final_ship_to_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c247448-f19d-49b3-94c8-8cfaf38ca733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--final_ship_to_code_transport_request</value>
      <webElementGuid>1acb7b46-46d3-49cd-af75-7d8e3bca07ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>final_ship_to_code_transport_request</value>
      <webElementGuid>51097d4d-9d1b-4448-a132-7f16ae8117cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>dbb97f22-4d41-4558-bb80-de4339e7cf20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARE027BEL022ITA031ITA040ITA041ITA044ITA050ITA052</value>
      <webElementGuid>be1d7168-4a91-40e1-aa13-a70acba57166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--final_ship_to_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--final_ship_to_code_transport_request&quot;]/select[@id=&quot;dfc-item--transport-form--final_ship_to_code_transport_request&quot;]</value>
      <webElementGuid>66ec22a9-ce22-4fa7-8b37-611db72da005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--transport-form--final_ship_to_code_transport_request']</value>
      <webElementGuid>10f7e240-d807-4411-ba35-a077b2bf1c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--final_ship_to_code_transport_request']/select</value>
      <webElementGuid>d6c600e9-e777-4be9-9a95-8df5fa13eaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Ship to Code'])[1]/following::select[1]</value>
      <webElementGuid>040f28a7-e9be-4420-b3c5-fef13822d569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='null'])[8]/following::select[1]</value>
      <webElementGuid>0471aa39-e178-4fe8-acb1-825d5e216524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Palette number'])[1]/preceding::select[1]</value>
      <webElementGuid>6f2050df-2738-48e6-8eca-da0e46ad5f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final destination country'])[1]/preceding::select[1]</value>
      <webElementGuid>9c35c327-532e-4769-a2e9-9e989fefcdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>779089b7-8dbc-445e-8c2a-75e4b2b5057a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--transport-form--final_ship_to_code_transport_request' and @name = 'final_ship_to_code_transport_request' and (text() = 'ARE027BEL022ITA031ITA040ITA041ITA044ITA050ITA052' or . = 'ARE027BEL022ITA031ITA040ITA041ITA044ITA050ITA052')]</value>
      <webElementGuid>fc1e1335-5e16-4186-b520-9efb229a2e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
