<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Service_Level</name>
   <tag></tag>
   <elementGuidId>2757df32-2c0c-41d6-9ef1-cfab68475748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--transport-form--typeRequest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--typeRequest > #dfc-item--transport-form--typeRequest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>584c5cef-91af-4469-b31f-4802d584520c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--typeRequest</value>
      <webElementGuid>de6001de-d439-4206-86ad-704cebfb9624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeRequest</value>
      <webElementGuid>bdf371d9-7dc5-41ce-912b-ccb1f1c34a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-invalid ng-star-inserted ng-touched</value>
      <webElementGuid>3ac7ef84-4380-419b-87ab-8d999440650c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STANDARD</value>
      <webElementGuid>d2fe27c0-5950-4e44-af68-4b6c9f9b53a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--typeRequest&quot;)/div[@id=&quot;dfc-item--transport-form--typeRequest&quot;]/select[@id=&quot;dfc-item--transport-form--typeRequest&quot;]</value>
      <webElementGuid>dbf4bebf-ce4a-49f5-8616-6cb25e8c75f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--transport-form--typeRequest']</value>
      <webElementGuid>0df12981-6da0-404c-b245-af85448e3b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--typeRequest']/select</value>
      <webElementGuid>3ce961c6-3789-404b-aa22-37953cf9ade1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service level'])[1]/following::select[1]</value>
      <webElementGuid>aa1758ba-a319-400c-be5e-a5b0dbcb6c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Research'])[1]/following::select[6]</value>
      <webElementGuid>8c53cc5b-8daf-4939-aa70-7bbfc5826abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ce champs est obligatoire'])[2]/preceding::select[1]</value>
      <webElementGuid>7a23a374-7bb0-4fe2-8150-6fbb7c50b4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice currency'])[1]/preceding::select[1]</value>
      <webElementGuid>22938ab1-a20d-407d-be4a-a98e73a8cf03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/df-form-control/div/div/select</value>
      <webElementGuid>ce34daf0-ac7d-42ac-bc1a-d21020037294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--transport-form--typeRequest' and @name = 'typeRequest' and (text() = 'STANDARD' or . = 'STANDARD')]</value>
      <webElementGuid>66d11bc4-0bfc-491a-a1eb-960d69c1769a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
