<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Total Palette number</name>
   <tag></tag>
   <elementGuidId>7046745b-e749-4278-9b90-8860ff4348b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--final_ship_to_code_transport_request > #dfc-item--transport-form--final_ship_to_code_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--transport-form--final_ship_to_code_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0bfa3093-0464-45cc-813f-b10da812699a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--final_ship_to_code_transport_request</value>
      <webElementGuid>b81e59f7-4ac8-4a41-83fa-3e0bd1022b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>final_ship_to_code_transport_request</value>
      <webElementGuid>46a80511-297e-43b1-bc4f-b44bd871ed43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>32aa4e04-2e87-4cf3-ae97-3dde9758ef7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARE027BEL022ITA031ITA040ITA041ITA044ITA050ITA052</value>
      <webElementGuid>8a0fdf29-4bbc-4404-9bd5-ba498854db55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--final_ship_to_code_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--final_ship_to_code_transport_request&quot;]/select[@id=&quot;dfc-item--transport-form--final_ship_to_code_transport_request&quot;]</value>
      <webElementGuid>8d0ef1d1-c0eb-4a04-afe7-f3076404738f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--transport-form--final_ship_to_code_transport_request']</value>
      <webElementGuid>f1d6dc62-46aa-4bcf-889d-3df302fc2220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--final_ship_to_code_transport_request']/select</value>
      <webElementGuid>b44fc17b-6e09-4514-9d65-c6568e6dac7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Ship to Code'])[1]/following::select[1]</value>
      <webElementGuid>84a5ee09-540f-4a8a-9a32-86143f07df1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='null'])[8]/following::select[1]</value>
      <webElementGuid>99c1f51a-858a-4ae4-95d6-66705245c6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Palette number'])[1]/preceding::select[1]</value>
      <webElementGuid>5a407834-fb0e-41ae-8038-44398d553052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final destination country'])[1]/preceding::select[1]</value>
      <webElementGuid>d07e5293-6bb2-4893-b33f-d622eca8ea5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>97975759-aca8-446b-aa8d-567f9e60852e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--transport-form--final_ship_to_code_transport_request' and @name = 'final_ship_to_code_transport_request' and (text() = 'ARE027BEL022ITA031ITA040ITA041ITA044ITA050ITA052' or . = 'ARE027BEL022ITA031ITA040ITA041ITA044ITA050ITA052')]</value>
      <webElementGuid>955b61d4-cdcf-4332-891b-7cb3c6530014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
