<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Final destination country</name>
   <tag></tag>
   <elementGuidId>3e0621f7-a8bc-4f08-9c51-5818055529b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--destination_country_transport_request > #dfc-item--transport-form--destination_country_transport_request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--transport-form--destination_country_transport_request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fbe15ee6-5c6f-49eb-bd5e-7685ada2b2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--destination_country_transport_request</value>
      <webElementGuid>9d80f5d3-97f0-4ce7-bbfa-b11486006d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destination_country_transport_request</value>
      <webElementGuid>a19da790-37f3-4370-9e33-9a86fed4a8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>be6cd43b-5212-46f5-a82b-016edc03011b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BEFIFRGRINITKWLBPAPTQARUUA</value>
      <webElementGuid>f6ede80e-91ea-4cae-9163-4d34deb3f812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--destination_country_transport_request&quot;)/div[@id=&quot;dfc-item--transport-form--destination_country_transport_request&quot;]/select[@id=&quot;dfc-item--transport-form--destination_country_transport_request&quot;]</value>
      <webElementGuid>fa952860-d491-4596-b133-934c436793ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--transport-form--destination_country_transport_request']</value>
      <webElementGuid>bf8ea57f-2a81-4e3f-bb29-8f4d72b037ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--destination_country_transport_request']/select</value>
      <webElementGuid>8f60f1c1-0dda-44f9-be9a-1ab6fe57dbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final destination country'])[1]/following::select[1]</value>
      <webElementGuid>dea3a9f9-d0e8-4ce4-a22e-90244e0d8f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Palette number'])[1]/following::select[1]</value>
      <webElementGuid>08049abc-0457-4298-9d36-f4d1a0f04312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Research'])[1]/preceding::select[1]</value>
      <webElementGuid>1172ac57-f5d0-40b1-b933-165cd5744122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service level'])[1]/preceding::select[6]</value>
      <webElementGuid>7e903163-8019-437b-b6ef-b715c875c721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[32]/div/div/select</value>
      <webElementGuid>66b449c2-8497-43e8-9bea-ea76f35a7538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--transport-form--destination_country_transport_request' and @name = 'destination_country_transport_request' and (text() = 'BEFIFRGRINITKWLBPAPTQARUUA' or . = 'BEFIFRGRINITKWLBPAPTQARUUA')]</value>
      <webElementGuid>6c19a5d3-b636-4b10-8081-dda84b2f856f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
