<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Invoice_Currency</name>
   <tag></tag>
   <elementGuidId>2fb4af77-8212-48cc-bc33-47090de9dd2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dfc-item--transport-form--currencyInvoice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--transport-form--currencyInvoice > #dfc-item--transport-form--currencyInvoice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7fb11f1a-9472-4318-adcf-7605575f5bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--transport-form--currencyInvoice</value>
      <webElementGuid>8c46d422-860f-4fcc-9818-ceceefd0d4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currencyInvoice</value>
      <webElementGuid>341da4dc-bba4-41dc-b3fa-30e544878692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted ng-touched ng-dirty ng-valid</value>
      <webElementGuid>18e6f7e1-5b61-4e52-8505-4a6eb70ef2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AED - United Arab Emirates dirhamAFN - Afghan afghaniALL - Albanian lekAMD - Armenian dramANG - Netherlands Antillean guilderAOA - Angolan kwanzaARS - Argentine pesoAUD - Australian dollarAWG - Aruban florinAZN - Azerbaijani manatBAM - Bosnia and Herzegovina convertible markBBD - Barbadian dollarBDT - Bangladeshi takaBGN - Bulgarian levBHD - Bahraini dinarBIF - Burundian francBMD - Bermudian dollarBND - Brunei dollarBOB - Bolivian bolivianoBRL - Brazilian realBSD - Bahamian dollarBTN - Bhutanese ngultrumBWP - Botswana pulaBYN - Belarusian rubleBZD - Belize dollarCAD - Canadian dollarCDF - Congolese francCHF - Swiss francCLP - Chilean pesoCNY - Chinese yuanCOP - Colombian pesoCRC - Costa Rican colónCUC - Cuban convertible pesoCUP - Cuban pesoCVE - Cape Verdean escudoCZK - Czech korunaDJF - Djiboutian francDKK - Danish kroneDOP - Dominican pesoDZD - Algerian dinarEGP - Egyptian poundERN - Eritrean nakfaETB - Ethiopian birrEUR - EuroFJD - Fijian dollarFKP - Falkland Islands poundGBP - British pound[F]GEL - Georgian lariGGP[G] - Guernsey poundGHS - Ghanaian cediGIP - Gibraltar poundGMD - Gambian dalasiGNF - Guinean francGTQ - Guatemalan quetzalGYD - Guyanese dollarHKD - Hong Kong dollarHNL - Honduran lempiraHRK - Croatian kunaHTG - Haitian gourdeHUF - Hungarian forintIDR - Indonesian rupiahILS - Israeli new shekelIMP[G] - Manx poundINR - Indian rupeeIQD - Iraqi dinarIRR - Iranian rialISK - Icelandic krónaJEP[G] - Jersey poundJMD - Jamaican dollarJOD - Jordanian dinarJPY - Japanese yenKES - Kenyan shillingKGS - Kyrgyzstani somKHR - Cambodian rielKMF - Comorian francKPW - North Korean wonKRW - South Korean wonKWD - Kuwaiti dinarKYD - Cayman Islands dollarKZT - Kazakhstani tengeLAK - Lao kipLBP - Lebanese poundLKR - Sri Lankan rupeeLRD - Liberian dollarLSL - Lesotho lotiLYD - Libyan dinarMAD - Moroccan dirhamMDL - Moldovan leuMGA - Malagasy ariaryMKD - Macedonian denarMMK - Burmese kyatMNT - Mongolian tögrögMOP - Macanese patacaMRO - Mauritanian ouguiyaMRU - Mauritanian ouguiyaMUR - Mauritian rupeeMVR - Maldivian rufiyaaMWK - Malawian kwachaMXN - Mexican pesoMYR - Malaysian ringgitMZN - Mozambican meticalNAD - Namibian dollarNGN - Nigerian nairaNIO - Nicaraguan córdobaNOK - Norwegian kroneNPR - Nepalese rupeeNZD - New Zealand dollarOMR - Omani rialPAB - Panamanian balboaPEN - Peruvian solPGK - Papua New Guinean kinaPHP - Philippine pisoPKR - Pakistani rupeePLN - Polish złotyPRB[G] - Transnistrian rublePYG - Paraguayan guaraníQAR - Qatari riyalRON - Romanian leuRSD - Serbian dinarRUB - Russian rubleRWF - Rwandan francSAR - Saudi riyalSBD - Solomon Islands dollarSCR - Seychellois rupeeSDG - Sudanese poundSEK - Swedish kronaSGD - Singapore dollarSHP - Saint Helena poundSLL - Sierra Leonean leoneSOS - Somali shillingSRD - Surinamese dollarSSP - South Sudanese poundSTD - São Tomé and Príncipe dobraSYP - Syrian poundSZL - Swazi lilangeniTHB - Thai bahtTJS - Tajikistani somoniTMT - Turkmenistan manatTND - Tunisian dinarTOP - Tongan paʻanga[O]TRY - Turkish liraTTD - Trinidad and Tobago dollarTVD[G] - Tuvaluan dollarTWD - New Taiwan dollarTZS - Tanzanian shillingUAH - Ukrainian hryvniaUGX - Ugandan shillingUSD - United States dollarUYU - Uruguayan pesoUZS - Uzbekistani soʻmVEF - Venezuelan bolívarVND - Vietnamese đồngVUV - Vanuatu vatuWST - Samoan tālāXAF - Central African CFA francXCD - Eastern Caribbean dollarXOF - West African CFA francXPF - CFP francYER - Yemeni rialZAR - South African randZMW - Zambian kwacha</value>
      <webElementGuid>5255ba18-f4f8-429d-89ce-c05de538a16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--transport-form--currencyInvoice&quot;)/div[@id=&quot;dfc-item--transport-form--currencyInvoice&quot;]/select[@id=&quot;dfc-item--transport-form--currencyInvoice&quot;]</value>
      <webElementGuid>f1db3bec-37eb-4b42-92d2-8fa553a3b515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dfc-item--transport-form--currencyInvoice']</value>
      <webElementGuid>1815a84d-cade-462b-a9b9-09cdc3dc3399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--transport-form--currencyInvoice']/select</value>
      <webElementGuid>82471e77-356e-43b9-8352-6627596199bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice currency'])[1]/following::select[1]</value>
      <webElementGuid>dc2a4738-6d71-4296-8288-5ac9e1a91b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service level'])[1]/following::select[2]</value>
      <webElementGuid>0c8ccc04-780e-4188-830c-ebbc5eacdffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance'])[1]/preceding::select[1]</value>
      <webElementGuid>c55c2054-4c58-4e3e-b113-8d81fe9a4632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/preceding::select[1]</value>
      <webElementGuid>74d68700-3ea7-4707-bd85-041210d470ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[2]/div/div/select</value>
      <webElementGuid>f3090d40-d709-4863-aba5-67471db2b8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dfc-item--transport-form--currencyInvoice' and @name = 'currencyInvoice' and (text() = 'AED - United Arab Emirates dirhamAFN - Afghan afghaniALL - Albanian lekAMD - Armenian dramANG - Netherlands Antillean guilderAOA - Angolan kwanzaARS - Argentine pesoAUD - Australian dollarAWG - Aruban florinAZN - Azerbaijani manatBAM - Bosnia and Herzegovina convertible markBBD - Barbadian dollarBDT - Bangladeshi takaBGN - Bulgarian levBHD - Bahraini dinarBIF - Burundian francBMD - Bermudian dollarBND - Brunei dollarBOB - Bolivian bolivianoBRL - Brazilian realBSD - Bahamian dollarBTN - Bhutanese ngultrumBWP - Botswana pulaBYN - Belarusian rubleBZD - Belize dollarCAD - Canadian dollarCDF - Congolese francCHF - Swiss francCLP - Chilean pesoCNY - Chinese yuanCOP - Colombian pesoCRC - Costa Rican colónCUC - Cuban convertible pesoCUP - Cuban pesoCVE - Cape Verdean escudoCZK - Czech korunaDJF - Djiboutian francDKK - Danish kroneDOP - Dominican pesoDZD - Algerian dinarEGP - Egyptian poundERN - Eritrean nakfaETB - Ethiopian birrEUR - EuroFJD - Fijian dollarFKP - Falkland Islands poundGBP - British pound[F]GEL - Georgian lariGGP[G] - Guernsey poundGHS - Ghanaian cediGIP - Gibraltar poundGMD - Gambian dalasiGNF - Guinean francGTQ - Guatemalan quetzalGYD - Guyanese dollarHKD - Hong Kong dollarHNL - Honduran lempiraHRK - Croatian kunaHTG - Haitian gourdeHUF - Hungarian forintIDR - Indonesian rupiahILS - Israeli new shekelIMP[G] - Manx poundINR - Indian rupeeIQD - Iraqi dinarIRR - Iranian rialISK - Icelandic krónaJEP[G] - Jersey poundJMD - Jamaican dollarJOD - Jordanian dinarJPY - Japanese yenKES - Kenyan shillingKGS - Kyrgyzstani somKHR - Cambodian rielKMF - Comorian francKPW - North Korean wonKRW - South Korean wonKWD - Kuwaiti dinarKYD - Cayman Islands dollarKZT - Kazakhstani tengeLAK - Lao kipLBP - Lebanese poundLKR - Sri Lankan rupeeLRD - Liberian dollarLSL - Lesotho lotiLYD - Libyan dinarMAD - Moroccan dirhamMDL - Moldovan leuMGA - Malagasy ariaryMKD - Macedonian denarMMK - Burmese kyatMNT - Mongolian tögrögMOP - Macanese patacaMRO - Mauritanian ouguiyaMRU - Mauritanian ouguiyaMUR - Mauritian rupeeMVR - Maldivian rufiyaaMWK - Malawian kwachaMXN - Mexican pesoMYR - Malaysian ringgitMZN - Mozambican meticalNAD - Namibian dollarNGN - Nigerian nairaNIO - Nicaraguan córdobaNOK - Norwegian kroneNPR - Nepalese rupeeNZD - New Zealand dollarOMR - Omani rialPAB - Panamanian balboaPEN - Peruvian solPGK - Papua New Guinean kinaPHP - Philippine pisoPKR - Pakistani rupeePLN - Polish złotyPRB[G] - Transnistrian rublePYG - Paraguayan guaraníQAR - Qatari riyalRON - Romanian leuRSD - Serbian dinarRUB - Russian rubleRWF - Rwandan francSAR - Saudi riyalSBD - Solomon Islands dollarSCR - Seychellois rupeeSDG - Sudanese poundSEK - Swedish kronaSGD - Singapore dollarSHP - Saint Helena poundSLL - Sierra Leonean leoneSOS - Somali shillingSRD - Surinamese dollarSSP - South Sudanese poundSTD - São Tomé and Príncipe dobraSYP - Syrian poundSZL - Swazi lilangeniTHB - Thai bahtTJS - Tajikistani somoniTMT - Turkmenistan manatTND - Tunisian dinarTOP - Tongan paʻanga[O]TRY - Turkish liraTTD - Trinidad and Tobago dollarTVD[G] - Tuvaluan dollarTWD - New Taiwan dollarTZS - Tanzanian shillingUAH - Ukrainian hryvniaUGX - Ugandan shillingUSD - United States dollarUYU - Uruguayan pesoUZS - Uzbekistani soʻmVEF - Venezuelan bolívarVND - Vietnamese đồngVUV - Vanuatu vatuWST - Samoan tālāXAF - Central African CFA francXCD - Eastern Caribbean dollarXOF - West African CFA francXPF - CFP francYER - Yemeni rialZAR - South African randZMW - Zambian kwacha' or . = 'AED - United Arab Emirates dirhamAFN - Afghan afghaniALL - Albanian lekAMD - Armenian dramANG - Netherlands Antillean guilderAOA - Angolan kwanzaARS - Argentine pesoAUD - Australian dollarAWG - Aruban florinAZN - Azerbaijani manatBAM - Bosnia and Herzegovina convertible markBBD - Barbadian dollarBDT - Bangladeshi takaBGN - Bulgarian levBHD - Bahraini dinarBIF - Burundian francBMD - Bermudian dollarBND - Brunei dollarBOB - Bolivian bolivianoBRL - Brazilian realBSD - Bahamian dollarBTN - Bhutanese ngultrumBWP - Botswana pulaBYN - Belarusian rubleBZD - Belize dollarCAD - Canadian dollarCDF - Congolese francCHF - Swiss francCLP - Chilean pesoCNY - Chinese yuanCOP - Colombian pesoCRC - Costa Rican colónCUC - Cuban convertible pesoCUP - Cuban pesoCVE - Cape Verdean escudoCZK - Czech korunaDJF - Djiboutian francDKK - Danish kroneDOP - Dominican pesoDZD - Algerian dinarEGP - Egyptian poundERN - Eritrean nakfaETB - Ethiopian birrEUR - EuroFJD - Fijian dollarFKP - Falkland Islands poundGBP - British pound[F]GEL - Georgian lariGGP[G] - Guernsey poundGHS - Ghanaian cediGIP - Gibraltar poundGMD - Gambian dalasiGNF - Guinean francGTQ - Guatemalan quetzalGYD - Guyanese dollarHKD - Hong Kong dollarHNL - Honduran lempiraHRK - Croatian kunaHTG - Haitian gourdeHUF - Hungarian forintIDR - Indonesian rupiahILS - Israeli new shekelIMP[G] - Manx poundINR - Indian rupeeIQD - Iraqi dinarIRR - Iranian rialISK - Icelandic krónaJEP[G] - Jersey poundJMD - Jamaican dollarJOD - Jordanian dinarJPY - Japanese yenKES - Kenyan shillingKGS - Kyrgyzstani somKHR - Cambodian rielKMF - Comorian francKPW - North Korean wonKRW - South Korean wonKWD - Kuwaiti dinarKYD - Cayman Islands dollarKZT - Kazakhstani tengeLAK - Lao kipLBP - Lebanese poundLKR - Sri Lankan rupeeLRD - Liberian dollarLSL - Lesotho lotiLYD - Libyan dinarMAD - Moroccan dirhamMDL - Moldovan leuMGA - Malagasy ariaryMKD - Macedonian denarMMK - Burmese kyatMNT - Mongolian tögrögMOP - Macanese patacaMRO - Mauritanian ouguiyaMRU - Mauritanian ouguiyaMUR - Mauritian rupeeMVR - Maldivian rufiyaaMWK - Malawian kwachaMXN - Mexican pesoMYR - Malaysian ringgitMZN - Mozambican meticalNAD - Namibian dollarNGN - Nigerian nairaNIO - Nicaraguan córdobaNOK - Norwegian kroneNPR - Nepalese rupeeNZD - New Zealand dollarOMR - Omani rialPAB - Panamanian balboaPEN - Peruvian solPGK - Papua New Guinean kinaPHP - Philippine pisoPKR - Pakistani rupeePLN - Polish złotyPRB[G] - Transnistrian rublePYG - Paraguayan guaraníQAR - Qatari riyalRON - Romanian leuRSD - Serbian dinarRUB - Russian rubleRWF - Rwandan francSAR - Saudi riyalSBD - Solomon Islands dollarSCR - Seychellois rupeeSDG - Sudanese poundSEK - Swedish kronaSGD - Singapore dollarSHP - Saint Helena poundSLL - Sierra Leonean leoneSOS - Somali shillingSRD - Surinamese dollarSSP - South Sudanese poundSTD - São Tomé and Príncipe dobraSYP - Syrian poundSZL - Swazi lilangeniTHB - Thai bahtTJS - Tajikistani somoniTMT - Turkmenistan manatTND - Tunisian dinarTOP - Tongan paʻanga[O]TRY - Turkish liraTTD - Trinidad and Tobago dollarTVD[G] - Tuvaluan dollarTWD - New Taiwan dollarTZS - Tanzanian shillingUAH - Ukrainian hryvniaUGX - Ugandan shillingUSD - United States dollarUYU - Uruguayan pesoUZS - Uzbekistani soʻmVEF - Venezuelan bolívarVND - Vietnamese đồngVUV - Vanuatu vatuWST - Samoan tālāXAF - Central African CFA francXCD - Eastern Caribbean dollarXOF - West African CFA francXPF - CFP francYER - Yemeni rialZAR - South African randZMW - Zambian kwacha')]</value>
      <webElementGuid>b82f4114-21c6-4ee2-9563-425f427a3920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
