<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vignette carrier name</name>
   <tag></tag>
   <elementGuidId>5204c28f-25cc-4afe-977b-e224d94277e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dfc-dyn-root--transport-form--quotes']/app-content-step-pricing//app-quotes-view//div[@id=&quot;quote-view-0header&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vignette.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a49273b3-4f63-42ab-8f16-dffe19fb67a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vignette ng-star-inserted</value>
      <webElementGuid>e9f0264b-10a1-4ab6-98fb-888807f20a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M Baglione (STLSRL) 2  EUR  Transit time : 1 </value>
      <webElementGuid>e3fd5ee1-ff8c-4b90-a9fc-29a1bbfc3378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--transport-form--quotes&quot;)/app-content-step-pricing[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;step-pricing-root ng-star-inserted&quot;]/div[@class=&quot;content ng-star-inserted&quot;]/app-quotes-view[@class=&quot;quotes&quot;]/div[@class=&quot;vignette-container vignette-margin-10 theme-card-plain size-details-form ng-star-inserted&quot;]/div[@class=&quot;vignette ng-star-inserted&quot;]</value>
      <webElementGuid>c95bf5db-10a0-484e-9975-600814ea87e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--transport-form--quotes']/app-content-step-pricing/div/div[2]/app-quotes-view/div/div</value>
      <webElementGuid>dc2b7827-b083-4721-a5d6-50a5735403c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh quotes'])[1]/following::div[3]</value>
      <webElementGuid>c2e7c0bf-1b67-45fa-951d-fa405e0e943d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[5]/following::div[7]</value>
      <webElementGuid>d6fdfe48-ad80-4d0c-b4a2-2c44509c26b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-quotes-view/div/div</value>
      <webElementGuid>dd1f16c1-920e-4cc9-809b-3f6ee71e0594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'M Baglione (STLSRL) 2  EUR  Transit time : 1 ' or . = 'M Baglione (STLSRL) 2  EUR  Transit time : 1 ')]</value>
      <webElementGuid>bb4f0087-5411-4bcd-b6fd-74df316628de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
