<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TypeOfDoc - BC</name>
   <tag></tag>
   <elementGuidId>a059de7e-0c62-4cc6-a1cc-796559fe48ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-documents//div[contains(@class, 'type-doc_wrapper') and .//div[text()[normalize-space() = &quot;BC&quot;]]]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fileDropContainer-147</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f010d746-3f17-479d-82ae-0ab2f799c2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>type-doc_wrapper col-lg-12 col-md-12 col-sm-12 col-xs-12 ng-star-inserted</value>
      <webElementGuid>929291d6-28fc-4497-947f-b6ce460c114f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileDropContainer-147</value>
      <webElementGuid>6e1fdc5c-3764-408f-aa3c-f10fec6a1a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BC  Drag a file here or  Browse  To upload.  ESC-A16309_BC_1.pdf </value>
      <webElementGuid>73c268a0-1401-4ac5-a820-a7bca1399b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileDropContainer-147&quot;)</value>
      <webElementGuid>d3167439-f181-4d3a-ab47-da140f6a0d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fileDropContainer-147']</value>
      <webElementGuid>c0d956de-a36d-46cf-9148-4da6f9062fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-details/div/div/div[2]/div[3]/app-panel-right/app-form-dynamic-panel/div/app-panel-doc-chat/div/div[2]/div/div/app-document-list/div/app-documents/div/div/div</value>
      <webElementGuid>50a8f1f6-be44-4b31-bd0f-be748185a2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents'])[1]/following::div[5]</value>
      <webElementGuid>8f9da1bc-adbd-466f-8036-a7a9c8717014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[4]/following::div[15]</value>
      <webElementGuid>979f0928-7fc9-4da0-b19a-c1472e7d173b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-documents/div/div/div</value>
      <webElementGuid>3af4ae1e-eda7-4bcd-bd67-7c3547d37a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fileDropContainer-147' and (text() = ' BC  Drag a file here or  Browse  To upload.  ESC-A16309_BC_1.pdf ' or . = ' BC  Drag a file here or  Browse  To upload.  ESC-A16309_BC_1.pdf ')]</value>
      <webElementGuid>08dde52c-3693-4285-a562-444a39da4bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
