<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first cell in a row</name>
   <tag></tag>
   <elementGuidId>df0aa731-b850-4d70-9216-de7882e8a1f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ag-grid-angular//span[@class=&quot;ag-cell-value&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b74183f6-dbea-474e-8121-2a5b9af44fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1669021181940</value>
      <webElementGuid>d3c29702-d658-4540-ac83-efafc77e7dee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
