<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multi-execution_automaticAction</name>
   <tag></tag>
   <elementGuidId>fa7506eb-4262-4fa9-9c91-c8c85806b809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;automaticActionConfiguration.multiExecutions&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='automaticActionConfiguration.multiExecutions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f6c1a34-86e4-4686-8e5c-7413fab162ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>92f22a48-22b9-495b-a4ba-864c2f3218d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>automaticActionConfiguration.multiExecutions</value>
      <webElementGuid>662fdc0f-6a7c-4e85-a1b6-e7161a044d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-dirty ng-touched</value>
      <webElementGuid>23b2802f-eec6-489c-9e48-a7fd93acd7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-automatic-actions[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-automatic-actions-detail[1]/div[@class=&quot;global&quot;]/form[@class=&quot;generic-default padding-top-5 ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;form-content col-sm-12 margin-top-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-4 col-xs-12 d-flex-ai-c generic-inputs__style&quot;]/div[@class=&quot;col-md-8&quot;]/input[@class=&quot;ng-valid ng-dirty ng-touched&quot;]</value>
      <webElementGuid>d752bace-5104-42fd-a42f-63579814808e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='automaticActionConfiguration.multiExecutions']</value>
      <webElementGuid>f3042220-43f8-4e3d-a375-275b1eed0acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-automatic-actions/div/app-automatic-actions-detail/div/form/div/div/div/div[4]/div/input</value>
      <webElementGuid>53798314-8bc4-445b-b9ad-04c546e7ab16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>3548c5c3-93a1-4c57-b117-5de15842163c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'automaticActionConfiguration.multiExecutions']</value>
      <webElementGuid>c5aefc39-1553-45d8-8f7e-3b09e5e62469</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
