<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Activated_automaticAction</name>
   <tag></tag>
   <elementGuidId>d9ef3f99-9ea3-4c63-8f8d-76e89e936c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;automaticActionConfiguration.activated&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='automaticActionConfiguration.activated']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d37ae08e-7ceb-4a0b-b91c-8797c1e1dbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0b737921-150c-4e6b-bd0b-375562653205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>automaticActionConfiguration.activated</value>
      <webElementGuid>e5b8e806-c4d2-43a5-b2ec-4814f397eebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6ab929fa-2b3b-4b63-8378-a9832ad77881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-settings-my-company[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content_wrapper&quot;]/div[@class=&quot;panel panel-visible panel-table&quot;]/div[@class=&quot;col-md-12 padding-0&quot;]/app-automatic-actions[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-automatic-actions-detail[1]/div[@class=&quot;global&quot;]/form[@class=&quot;generic-default padding-top-5 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-content col-sm-12 margin-top-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-4 col-xs-12 d-flex-ai-c generic-inputs__style&quot;]/div[@class=&quot;col-md-8&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>e43e8122-36b7-4ba6-a766-77729555c7e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='automaticActionConfiguration.activated']</value>
      <webElementGuid>55207efb-ec4d-4d81-b7cb-8cf6c5ac9e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-automatic-actions/div/app-automatic-actions-detail/div/form/div/div/div/div[3]/div/input</value>
      <webElementGuid>ddb9bf4c-a9e3-428d-8bf0-cdf77df88c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>45654482-1679-4906-9877-e623e05778ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'automaticActionConfiguration.activated']</value>
      <webElementGuid>ba1bd677-bdd5-4c9b-a2b4-6181418b4ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
