<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description Order Priority</name>
   <tag></tag>
   <elementGuidId>081588c9-9704-41a3-9002-9a7271ca1f5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--order-priority-form--description > #dfc-item--order-priority-form--description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--order-priority-form--description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6801ffc-2d2a-4ef9-846e-91c86f14299e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>6e67773a-99a5-41c5-b68e-001bf4636ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--order-priority-form--description</value>
      <webElementGuid>6e5d2da5-06af-4391-9a97-92358093cf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>74c4f9e9-b5eb-4fc3-ad2f-f3438b47fc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>645a4035-c6ba-4975-bef6-27e4c8b49b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c2533ef-4509-4e53-bdee-869272beacea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>691762cf-e1d7-41db-afcc-33f5a3f81352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--order-priority-form--description&quot;)/div[@id=&quot;dfc-item--order-priority-form--description&quot;]/input[@id=&quot;dfc-item--order-priority-form--description&quot;]</value>
      <webElementGuid>c898238a-fa87-4d33-8730-452d5314f7c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--order-priority-form--description']</value>
      <webElementGuid>e1e82167-b1b5-41ed-b18a-9d9a6fa59d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--order-priority-form--description']/input</value>
      <webElementGuid>0acde0b5-4b53-4251-8ad2-0779e3d3e5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/input</value>
      <webElementGuid>e66e9edb-f78b-4812-b411-18ea2024aebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--order-priority-form--description' and @name = 'description' and @placeholder = 'Description' and @type = 'text']</value>
      <webElementGuid>ed1c4bb4-aa02-4abe-a9e9-c100d258bfb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
