<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Activate Order Priority</name>
   <tag></tag>
   <elementGuidId>4dc33078-223f-4869-bc7f-80f279a3568d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--order-priority-form--active--true</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--order-priority-form--active--true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9c9e530-8c11-4eec-ac17-38daa3d2ca0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>298ce9a5-aa95-47d7-8c38-93a4857cbb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--order-priority-form--active--true</value>
      <webElementGuid>6dc4cb9d-210b-4e5d-8d68-220e5d9a4e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9df9f9d7-20b9-46c1-8a2b-c228c883f262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--order-priority-form--active--true&quot;)</value>
      <webElementGuid>a41c523a-9995-4c9e-b9c0-cfe83c32b08d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--order-priority-form--active--true']</value>
      <webElementGuid>1e85685a-53b7-4fcb-816e-32d4b57b2eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--order-priority-form--active']/div/input</value>
      <webElementGuid>1399b6ef-a88c-4849-9d86-e8809c18e82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[2]/div/div/div/input</value>
      <webElementGuid>28494466-aa8e-4e9d-ad95-6377166bfc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--order-priority-form--active--true']</value>
      <webElementGuid>3a14909e-0f68-4b10-b78f-9ccb5dd43df7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
