<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code Order Priority</name>
   <tag></tag>
   <elementGuidId>fc29ba23-c765-4b53-a46f-0c747ae227d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--order-priority-form--code > #dfc-item--order-priority-form--code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--order-priority-form--code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>570af6b1-7675-485c-9ae2-e5d10620f5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>d692d2da-a78b-4bea-be07-81d269027919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--order-priority-form--code</value>
      <webElementGuid>dfe5e0c6-9733-4b34-8d1a-9e61ab6cc794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>9c29635f-0a41-4b81-a75b-bc569c5c5b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>2bca169d-79c5-42ee-9cea-ed469358178c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d87e3ad2-9a20-4cfa-b55c-02c184d593e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>da825c3a-3e70-46a7-a6ff-dbaf5b3b2edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--order-priority-form--code&quot;)/div[@id=&quot;dfc-item--order-priority-form--code&quot;]/input[@id=&quot;dfc-item--order-priority-form--code&quot;]</value>
      <webElementGuid>48efa307-1110-4c0e-94d8-fe961993c66e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--order-priority-form--code']</value>
      <webElementGuid>13c34ba8-9953-4144-b703-ecfc8599dbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--order-priority-form--code']/input</value>
      <webElementGuid>137ec6e2-e5d0-4826-966f-fbc370806628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control/div/div/input</value>
      <webElementGuid>a222afe2-463b-4316-beec-d23df84154fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--order-priority-form--code' and @name = 'code' and @placeholder = 'Code' and @type = 'text']</value>
      <webElementGuid>a0bb997a-e71b-4fa1-9830-01792be1c32d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
