<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference</name>
   <tag></tag>
   <elementGuidId>061dc9dd-85de-4661-917c-f01f3fb720f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-2022-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@aria-label=&quot;Reference Filter Input&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef0937de-fade-4010-a063-4e4b65e0c102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>7a08ca39-bf1b-4182-bcd6-1f5359598283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>26a86a8b-34f3-4eac-9fe1-a00110439fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a11c56c4-a7cd-4d1d-a9e8-1f987f5105d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-2022-input</value>
      <webElementGuid>f5c6e955-3707-4969-9f4b-b27ae556d390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Reference Filter Input</value>
      <webElementGuid>d79457b7-21f9-4803-9e78-da64d0067816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-2022-input&quot;)</value>
      <webElementGuid>fbcff6dd-257b-4afd-8dd3-de11164cb633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-2022-input']</value>
      <webElementGuid>ef70b050-3aa4-4fc7-8f45-42185bd67dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-type-request/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>93341364-9142-4d98-bac5-3ec5db73502d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>932e3f89-3155-4663-8e57-32687d41cf38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-2022-input']</value>
      <webElementGuid>ee631bd4-c440-49be-aefc-9b03ecde5086</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
