<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Breadcrumb - Ref TR</name>
   <tag></tag>
   <elementGuidId>6bae9733-d3bd-4fc2-9838-1036eed1219f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='breadcrumb-tr-reference']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#breadcrumb-tr-reference > a.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>52c4ce30-875c-4453-812c-ddec10827546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>13ca4828-35b9-4da2-88fe-f4e3c95602ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ESC-A16309 (DEMO_04_05_5) </value>
      <webElementGuid>84e8abeb-4d66-4133-9995-ff4955cfe3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb-tr-reference&quot;)/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>2fd8dd57-3392-4159-9bc3-4a6b73774ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='breadcrumb-tr-reference']/a</value>
      <webElementGuid>1fa82180-e159-4cff-a2bb-8bc30dfa4ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ESC-A16309 (DEMO_04_05_5)')]</value>
      <webElementGuid>cc1c647c-9827-4af8-a9cc-a06c8a7395d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[1]</value>
      <webElementGuid>831fedd8-38f1-4875-ab81-4124b1471bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::a[3]</value>
      <webElementGuid>7e8720d0-9ef5-4bd9-9795-470612124001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/preceding::a[1]</value>
      <webElementGuid>1eb0c9aa-7f10-41ca-a4bf-0fdd26e57e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::a[1]</value>
      <webElementGuid>8c6a9acf-ae62-4300-8ce3-847ed6a1d6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESC-A16309 (DEMO_04_05_5)']/parent::*</value>
      <webElementGuid>5334557a-c4e7-48ee-94d4-2376038d972a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]/a</value>
      <webElementGuid>a6c40493-4df2-48bc-9280-4e835a4b2e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' ESC-A16309 (DEMO_04_05_5) ' or . = ' ESC-A16309 (DEMO_04_05_5) ')]</value>
      <webElementGuid>377609d7-378c-4580-a67d-642c75a1883a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
