<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusBar Status Chip</name>
   <tag></tag>
   <elementGuidId>7aa1c95c-2b9e-452a-b141-249764b823e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formStatusBar-chip-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formStatusBar-chip-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9120b10-c5e3-413e-a7b3-48b798587bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formStatusBar-chip-text</value>
      <webElementGuid>fb6782a8-89e5-43b6-93ff-0d43b5b813b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chip ng-star-inserted</value>
      <webElementGuid>5238653a-c628-4084-ac84-eb97ff6cf05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pending </value>
      <webElementGuid>d3b30f28-0b08-48d2-a6da-884da1658625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formStatusBar-chip-text&quot;)</value>
      <webElementGuid>5f805153-a0ab-43ed-8e96-fd5c5574c474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='formStatusBar-chip-text']</value>
      <webElementGuid>9659b8a5-3e30-44ce-872d-27f8269a237c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formStatusBar-chip']/div</value>
      <webElementGuid>63399d68-b115-4f40-9f42-6d291e0b54ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/following::div[9]</value>
      <webElementGuid>d7fd38fe-52bd-429c-98b0-36110aa62e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alerts'])[1]/following::div[9]</value>
      <webElementGuid>b814ad1f-56f5-4b7b-9103-9cf60a811147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate pending or confirm quote file to start process'])[1]/preceding::div[1]</value>
      <webElementGuid>d166ad9e-daea-439a-af77-3f4aae582134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping informations'])[1]/preceding::div[3]</value>
      <webElementGuid>6f76bf25-2d45-4788-baa1-23eda0cbcf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pending']/parent::*</value>
      <webElementGuid>65258626-06af-48d6-9c24-72df2e05e1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-form-statusbar/div/div/div</value>
      <webElementGuid>d4deb9da-5310-46bd-8d9b-58842a03fbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'formStatusBar-chip-text' and (text() = ' Pending ' or . = ' Pending ')]</value>
      <webElementGuid>ab41b169-ae59-47a7-a3e9-715d4a643d93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
