<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prefix</name>
   <tag></tag>
   <elementGuidId>b403f551-a47e-4aa2-ab2e-69d8be7b50ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--document-template-counter-form--prefix > #dfc-item--document-template-counter-form--prefix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--document-template-counter-form--prefix']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>075df078-48ac-4d24-9b44-9d45082b93fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>41cadbf7-b9ef-44ed-982d-a6ce67f4c6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--document-template-counter-form--prefix</value>
      <webElementGuid>7215a873-2b8c-4307-8474-c6fefbd5595e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prefix</value>
      <webElementGuid>f3fd710a-0156-4be8-8998-5454593e73e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Prefix</value>
      <webElementGuid>c4918239-6607-4b90-a461-bcb5d53abc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6795823b-fad3-4684-b939-d8e5f793b001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>a0d00164-afc8-4603-99cc-a127c76ae34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--document-template-counter-form--prefix&quot;)/div[@id=&quot;dfc-item--document-template-counter-form--prefix&quot;]/input[@id=&quot;dfc-item--document-template-counter-form--prefix&quot;]</value>
      <webElementGuid>8d097bb0-bdfb-4081-98b5-4d65597d7784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--document-template-counter-form--prefix']</value>
      <webElementGuid>eca78c44-9902-4156-9e27-d465379f7328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--document-template-counter-form--prefix']/input</value>
      <webElementGuid>53932248-4bd9-418a-ad57-9e16f2cfddcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[3]/div/div/input</value>
      <webElementGuid>b34597f7-9deb-43ae-ab71-77e6f1b797f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--document-template-counter-form--prefix' and @name = 'prefix' and @placeholder = 'Prefix' and @type = 'text']</value>
      <webElementGuid>1d06491a-150a-4c52-a9ef-803769cc2238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
