<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimal number of digits</name>
   <tag></tag>
   <elementGuidId>bfeb472c-f1b4-43a8-a4e5-5dc3f90b9d67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--document-template-counter-form--minDigits > #dfc-item--document-template-counter-form--minDigits</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--document-template-counter-form--minDigits']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbe8b3ef-c7e8-4dc8-8ccc-e9c8f43a1f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>71ed51da-6e73-4c59-adf0-483c470b8ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--document-template-counter-form--minDigits</value>
      <webElementGuid>2169128f-c3d2-4c45-96a0-13b353649653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>minDigits</value>
      <webElementGuid>8379fe0f-fe89-48f2-898f-ae6be44988fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Minimal number of digits</value>
      <webElementGuid>73ec55f4-5ff5-4be0-840f-1bb33d69120e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e44829b5-c6bd-44c5-84ae-fa2c9f185d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>e90e88cf-5bf6-4102-ae4a-8e1c62635f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--document-template-counter-form--minDigits&quot;)/div[@id=&quot;dfc-item--document-template-counter-form--minDigits&quot;]/input[@id=&quot;dfc-item--document-template-counter-form--minDigits&quot;]</value>
      <webElementGuid>7f4f3236-9ded-4de5-8c6a-38e11e5ce02b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--document-template-counter-form--minDigits']</value>
      <webElementGuid>5dafa24e-436b-4158-aea3-3505cdbea0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--document-template-counter-form--minDigits']/input</value>
      <webElementGuid>0a8b8d07-13e3-42ed-a468-4ad15690c974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[4]/div/div/input</value>
      <webElementGuid>1d4b65b7-d17d-4ebc-be52-8add7bd39b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--document-template-counter-form--minDigits' and @name = 'minDigits' and @placeholder = 'Minimal number of digits' and @type = 'number']</value>
      <webElementGuid>a50c2033-3943-4c1b-8d36-0687fcb0364b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
