<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mode CONTINUOUS</name>
   <tag></tag>
   <elementGuidId>bdabd00d-74aa-43a5-b06b-2aa50b7e7462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--document-template-counter-form--mode--CONTINUOUS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--document-template-counter-form--mode--CONTINUOUS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>342b6296-23f7-41b1-9e1c-194ed39f3202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>76fad53a-7305-400a-8a0c-8375f0d0d5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--document-template-counter-form--mode--CONTINUOUS</value>
      <webElementGuid>7d175fa6-3cbc-4761-89a2-11d6a491fe5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-dirty ng-touched</value>
      <webElementGuid>4bc29a55-e786-4543-b911-cf89b47d7aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--document-template-counter-form--mode--CONTINUOUS&quot;)</value>
      <webElementGuid>778fe952-08f0-4752-b5bb-c867be821cd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--document-template-counter-form--mode--CONTINUOUS']</value>
      <webElementGuid>a7be62db-b9a1-4159-a80c-fa2f5b0cc396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--document-template-counter-form--mode']/div[2]/input</value>
      <webElementGuid>9157ff02-03d5-4bf1-a289-4c169f9254e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[6]/div/div/div[2]/input</value>
      <webElementGuid>fe1a2fdf-70ba-4e10-9c8d-f7d6921593b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--document-template-counter-form--mode--CONTINUOUS']</value>
      <webElementGuid>5587be6e-65f2-4c7a-909d-e94f85cd4e61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
