<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mode ANNUAL</name>
   <tag></tag>
   <elementGuidId>fb43ba19-60ee-46a5-9c26-b641735269aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--document-template-counter-form--mode--ANNUAL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--document-template-counter-form--mode--ANNUAL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad2234d1-d197-48cf-8dc6-0626f5bf362a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b9b1aa0d-943c-4a4a-812a-4b7d0e3de73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--document-template-counter-form--mode--ANNUAL</value>
      <webElementGuid>fc0d0f1f-1a17-4c70-afe5-d566062e5f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>fc5142a4-9997-4456-a293-41bd1da96473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-item--document-template-counter-form--mode--ANNUAL&quot;)</value>
      <webElementGuid>080b8b37-e9c5-458a-a366-dee3e6ee70cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--document-template-counter-form--mode--ANNUAL']</value>
      <webElementGuid>07a29871-4a7f-4a19-ab27-00dad5d8a26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--document-template-counter-form--mode']/div/input</value>
      <webElementGuid>e9c60a47-d229-4e71-9504-b104adb6c4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[6]/div/div/div/input</value>
      <webElementGuid>de99a6fd-c75d-4473-9f5e-c4d9c05142b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dfc-item--document-template-counter-form--mode--ANNUAL']</value>
      <webElementGuid>0557c3ee-c01e-4a39-9773-6d0f3f92a0ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
