<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__startNumber</name>
   <tag></tag>
   <elementGuidId>e9ca7986-7556-488f-95ff-b42b14017212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--document-template-counter-form--startNumber > #dfc-item--document-template-counter-form--startNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--document-template-counter-form--startNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8af53b9-b944-457e-ace2-4225ddf60895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>cb38fa80-56be-4cfd-aad8-1d716668c5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--document-template-counter-form--startNumber</value>
      <webElementGuid>2fca4434-846f-46e7-b094-06866c1a364f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startNumber</value>
      <webElementGuid>02a21f59-05a2-40ee-ab94-aa32b0ba7e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start number</value>
      <webElementGuid>a819d69a-fdb8-4457-8c04-580a95e7e259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f5c2527a-6c85-4884-bfdf-7acb69956d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>36b691a8-3977-4ec8-b6ee-3835f2f10a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--document-template-counter-form--startNumber&quot;)/div[@id=&quot;dfc-item--document-template-counter-form--startNumber&quot;]/input[@id=&quot;dfc-item--document-template-counter-form--startNumber&quot;]</value>
      <webElementGuid>47cf5eeb-8c5a-434b-8264-1de3f784776d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--document-template-counter-form--startNumber']</value>
      <webElementGuid>2d713ca2-2214-46f3-8d98-312847380848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--document-template-counter-form--startNumber']/input</value>
      <webElementGuid>966c8f99-ff6e-41db-a578-8a88e059e44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//df-form-control[5]/div/div/input</value>
      <webElementGuid>d7b32456-782f-45d7-9d8f-e6465c47e36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--document-template-counter-form--startNumber' and @name = 'startNumber' and @placeholder = 'Start number' and @type = 'number']</value>
      <webElementGuid>0b447f78-556e-470c-a290-97a488ca73e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
