<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>a4305bfc-361e-4f92-b4b6-2082b60605c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-button-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@class=&quot;fa fa-trash ng-star-inserted&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a51ccc58-f5a9-4177-a5b5-a5c65e4082ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>f8647187-0884-4af4-8912-07a5dd6f5771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-button-2</value>
      <webElementGuid>6e263dd7-0249-468a-a7b3-61bf758a47d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash ng-star-inserted</value>
      <webElementGuid>f1a8f6b9-bae0-4582-b845-69066c1cb27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-button-2&quot;)</value>
      <webElementGuid>1edebc98-3fce-4ff0-88db-cfa80fa3cca3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='header-button-2']</value>
      <webElementGuid>4e03b8f1-4f0a-438d-aa04-7ac54bbd51db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-list-addresses/div/app-list-header-buttons/div/div/div/i[3]</value>
      <webElementGuid>b7d38ad7-c817-41bb-b482-b3a2abccc0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[3]</value>
      <webElementGuid>dbf34ded-c3c9-49b3-8414-f861ac0a1892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Delete' and @id = 'header-button-2']</value>
      <webElementGuid>14f8fc62-c19d-4ffb-ba3c-aad12bc79fd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
