<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View</name>
   <tag></tag>
   <elementGuidId>2612f3e9-38cc-4383-9407-28d9823fde04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='header-button-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-button-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5db45074-891f-45c9-b850-493eb30ff440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Visualiser</value>
      <webElementGuid>d3465e1c-a6a4-4c94-bc39-d890da64b7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-button-0</value>
      <webElementGuid>ef8ed04c-aa4b-40bb-99c8-c9db9a9ce5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit ng-star-inserted</value>
      <webElementGuid>db79dc57-3cc8-4b01-ab1f-a401f5539b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-button-0&quot;)</value>
      <webElementGuid>448ef3e2-66ef-4b9b-a345-2cb41c1955b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='header-button-0']</value>
      <webElementGuid>3887c7d6-ef4d-4cce-98e9-02be27275cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-pricing-list/app-transport-common-list/div/app-list-header-buttons/div/div/div/i</value>
      <webElementGuid>932ee24d-a897-43b7-ba6f-d7ab5edb6417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>bbfaca5f-af54-4e7c-bb69-c3e4f1026ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Visualiser' and @id = 'header-button-0']</value>
      <webElementGuid>a21c705a-9ed0-4887-bcd1-a9c5cb49fc31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
