<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_TR</name>
   <tag></tag>
   <elementGuidId>814d98c0-00f7-4e22-9bd2-cdc42aecb04f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@row-index=(&quot;0&quot;)]//div[@class=&quot;ag-selection-checkbox&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-174-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96d8677e-c573-4ec6-bc26-e1c2ad1f5602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>24d0b8be-2325-475b-ab4f-4dd54984efd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-checkbox-input</value>
      <webElementGuid>76c5cde7-0c2d-450a-b914-f307d9361f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f4a3ae1e-6941-4177-a64c-1bdcea69115b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-174-input</value>
      <webElementGuid>8ae259e3-43fa-493a-b394-ba90cbf45c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Press Space to toggle row selection (unchecked)</value>
      <webElementGuid>b74534eb-4886-42a4-9525-eb3da35da43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9423907f-facb-4da6-a6cb-ab03a4a4d9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-174-input&quot;)</value>
      <webElementGuid>90505d31-95f2-4ff2-81a3-b0282fcb7dc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@class=&quot;ag-selection-checkbox&quot;]</value>
      <webElementGuid>a21df485-1e34-4bfd-a01a-b25d8db2661f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-pricing-list/app-transport-common-list/div/ag-grid-angular/div/div[2]/div[2]/div[3]/div[2]/div/div/div[24]/div[4]/div/div/div/div[2]/input</value>
      <webElementGuid>d3fc573e-2d34-431c-ba6d-0f7fa0cadcd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div[4]/div/div/div/div[2]/input</value>
      <webElementGuid>620cafab-a105-4ad5-996a-9ccb17167cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ag-174-input']</value>
      <webElementGuid>d4038c36-8e8d-4eaa-a6f9-cb3bf834d344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
