<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Users</name>
   <tag></tag>
   <elementGuidId>5c88cc2c-1b27-480e-9a82-e814c8c7cd31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-1310-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ag-grid-angular//input[@aria-label=&quot;Email Filter Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cec094f6-778f-4afe-8da0-9c9f012f04ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>7716a1dc-6294-4b68-b3d3-9129dd9032ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>d139d5e4-65d4-44f9-bfce-de102fe84b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d8c5fba-f2f9-474a-955f-bfd965d5344b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-1310-input</value>
      <webElementGuid>2204807c-90b9-48ed-8b8b-4bcec153c40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email Filter Input</value>
      <webElementGuid>c626e978-d1ac-4709-ac34-8c696ccb32aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-1310-input&quot;)</value>
      <webElementGuid>db2e090b-5ba3-4edc-9727-c0099bf62a00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-1310-input']</value>
      <webElementGuid>00e6ae21-a72c-4dd3-a287-3598bedb6f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-settings-my-company/div/div[2]/div/app-user-list/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div[5]/div/div/div/div[2]/input</value>
      <webElementGuid>0a6a06ba-af76-4655-a71d-35d6bb78094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/input</value>
      <webElementGuid>733623b7-a96e-401b-b309-ebbfe00ce499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-1310-input']</value>
      <webElementGuid>dc0de98a-31d7-4ba6-8547-2cceb951c3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
