<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action Button - Refresh</name>
   <tag></tag>
   <elementGuidId>4f5a19d5-562e-4d69-bb8d-be240a8cfc74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='actionbutton-refresh']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionbutton-refresh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>109cd16f-5441-4709-a1f3-39c3b53f62ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-primary ng-star-inserted</value>
      <webElementGuid>3465b47d-78b9-4ba6-9c68-f02e7b197e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionbutton-refresh</value>
      <webElementGuid>bba311b5-94d2-4086-9c3c-fe64f7cddb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>f4f783cc-d307-463b-aa22-6719628aac18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionbutton-refresh&quot;)</value>
      <webElementGuid>4f16f0e2-62c5-4a02-9b4c-3a6b3614538a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='actionbutton-refresh']</value>
      <webElementGuid>e44fbc06-1877-4a6b-b39a-2674762928ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-header']/app-header/div/app-action-bar/div/div[3]/app-action-buttons/div/div[2]/button</value>
      <webElementGuid>7cdca969-0fb2-458f-a8f8-c63094a1344c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/following::button[1]</value>
      <webElementGuid>b67b84f0-785b-42af-b68d-f9ad25e7f6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidation propositions'])[1]/following::button[2]</value>
      <webElementGuid>d1e97a44-ecac-4501-bfee-4bf22f260075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>c9f7e90a-0248-4b52-8ef1-8da9e0a59211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>f7807f81-720b-4b42-ab8d-02cd28b16eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'actionbutton-refresh' and (text() = 'Refresh' or . = 'Refresh')]</value>
      <webElementGuid>5b9ecfbb-008c-4625-a073-1f6b0019af5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
