<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn open proposition in form</name>
   <tag></tag>
   <elementGuidId>d77eed1d-631f-41d1-bb00-fbde02ec4529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='header-button-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-button-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ee9be04e-d2bb-41df-b752-ee65a1caf0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Open in creation form</value>
      <webElementGuid>474c54a1-238b-48c9-b86a-9df8a90daa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-button-0</value>
      <webElementGuid>ffb36257-eccf-4e48-bdf0-58ac737b3dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-file-text-o ng-star-inserted</value>
      <webElementGuid>1f8f32f4-8315-4cbf-afeb-46abb63ee7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-button-0&quot;)</value>
      <webElementGuid>798edef1-2a74-4c86-8a44-4424262cbb29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='header-button-0']</value>
      <webElementGuid>81989fdf-63a9-4e99-a11f-a4c2e6dc232d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-consolidation-proposition-list/div/div/app-list-header-buttons/div/div/div/i</value>
      <webElementGuid>b814a053-6c47-47c7-ab8d-5a0de71c9808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>f385dfdc-2223-4d50-897a-f4fce0171236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Open in creation form' and @id = 'header-button-0']</value>
      <webElementGuid>c72bed55-1ff3-4b53-89a2-3984e78905e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
