<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First checkbox of list</name>
   <tag></tag>
   <elementGuidId>88013e70-ecd8-4ad7-9ae1-f990487b0432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ag-grid-angular//div[@row-id='0']//div[contains(@col-id, 'trInitials')]//input[contains(@type, 'checkbox')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-952-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d07c7cc2-071e-43c0-9b5d-90257165775b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>90d9489d-2564-4691-9046-b1c7141b482d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-checkbox-input</value>
      <webElementGuid>40e4eda0-ad4f-486b-84ce-10e26916fb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4606b2b8-1f0f-42d0-910a-9c5ecef558ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-952-input</value>
      <webElementGuid>31f1d28f-779b-45fe-8710-a197f954cbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Press Space to toggle row selection (unchecked)</value>
      <webElementGuid>733740d9-32ce-4734-9754-9a207653fc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>69e60a59-862c-472a-a416-77610023abb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-952-input&quot;)</value>
      <webElementGuid>2a06a282-d295-4495-a079-13e5a36af140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-952-input']</value>
      <webElementGuid>a07aae9f-21f3-493f-8099-5060863b7f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-consolidation-proposition-list/div/div/ag-grid-angular/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>73169801-ee9f-4017-86f4-994d773c1f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>473eb8cd-747e-4dd7-bb26-9866e76f112b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ag-952-input']</value>
      <webElementGuid>226019cf-ea5d-4573-8f52-2662be12a8d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
