<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuickFilter - TypeOfShipment (CustomLayout 0)</name>
   <tag></tag>
   <elementGuidId>42c17104-91d7-4daa-b568-d38225c66bb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ag-grid-angular//div[contains(@class, 'ag-header-row') and @aria-rowindex='2']//div[contains(@class, 'ag-header-cell') and @role= 'columnheader' and @aria-colindex= (//div[@role = 'columnheader' and @col-id = 'customLayout_0']/@aria-colindex)]//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-785-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff6b8c51-c585-4474-821a-09fe1051be61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>326162be-bd63-4d41-95c2-0000ee67504f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>0f780d23-7dc8-4ea1-a0da-1562a5aff729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>775e66af-e2a8-4958-91ae-ed09e12da71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-785-input</value>
      <webElementGuid>4e1d8a24-5bc1-4da4-a54a-8f30f477f46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Type of Shipment Filter Input</value>
      <webElementGuid>c2a50cdc-9468-46c7-8364-b08ad42af5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-785-input&quot;)</value>
      <webElementGuid>337f3e01-445f-4595-a2db-dbc22be0d584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-785-input']</value>
      <webElementGuid>06e73755-c277-4276-9761-5c6a7b3f8ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-consolidation-proposition-list/div/div/ag-grid-angular/div/div[2]/div[2]/div/div[2]/div/div[2]/div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>0552d5c1-b82b-4883-b4f9-e3f56491c925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>4edd89cf-f602-4381-ab9f-4510bddc4dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-785-input']</value>
      <webElementGuid>9db8c4de-e2ef-4b11-91f9-7690f3ecad20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
