<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit_Address_From</name>
   <tag></tag>
   <elementGuidId>13309952-d502-42be-a511-7dcccb0d6f0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.btn-icon.fa.fa-pencil.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dfc-dyn-root--transport-form--addressOrigin']/app-address-picker-form-control//i[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>578b04cc-0317-4f1b-ad9f-596ff727890f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon fa fa-pencil cursor-pointer</value>
      <webElementGuid>82ab7b69-61e4-44a9-890c-9bde91f9728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--transport-form--addressOrigin&quot;)/app-address-picker-form-control[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;df-form-control-root ng-star-inserted&quot;]/div[@class=&quot;df-form-control-item&quot;]/div[@class=&quot;address-overview m-fz-s d-flex justify-content-between ng-star-inserted&quot;]/div[@class=&quot;action-buttons ng-star-inserted&quot;]/i[@class=&quot;btn-icon fa fa-pencil cursor-pointer&quot;]</value>
      <webElementGuid>da5ca930-9795-464d-b2af-47124b6a0d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--transport-form--addressOrigin']/app-address-picker-form-control/div/div/div/div[2]/i</value>
      <webElementGuid>a6e5c523-0bda-48a9-b563-cd66beed42a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/i</value>
      <webElementGuid>95eadf25-b462-47f4-916e-f6f9de842a35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
