<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit_Address_To</name>
   <tag></tag>
   <elementGuidId>88eab584-6634-4d7b-88b6-33d2375c7061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.btn-icon.fa.fa-pencil.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dfc-dyn-root--transport-form--addressDest']/app-address-picker-form-control//i[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d8887f72-dab7-4bcc-9733-1c96d6cb4f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon fa fa-pencil cursor-pointer</value>
      <webElementGuid>11e5f127-49e5-4686-9c47-cad0ff813279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-dyn-root--transport-form--addressOrigin&quot;)/app-address-picker-form-control[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;df-form-control-root ng-star-inserted&quot;]/div[@class=&quot;df-form-control-item&quot;]/div[@class=&quot;address-overview m-fz-s d-flex justify-content-between ng-star-inserted&quot;]/div[@class=&quot;action-buttons ng-star-inserted&quot;]/i[@class=&quot;btn-icon fa fa-pencil cursor-pointer&quot;]</value>
      <webElementGuid>05ceb8af-1758-46ec-b606-7ce869508283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-dyn-root--transport-form--addressDest']/app-address-picker-form-control//i[1]</value>
      <webElementGuid>51114dbe-acc9-43e0-b497-a8b5190e0b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/i</value>
      <webElementGuid>e1d52a21-b9c0-49df-ad3e-6169f653eb67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
