<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip_code</name>
   <tag></tag>
   <elementGuidId>e9c42e48-49c8-47a0-b261-749f76ae6d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dfc-item--address-content-form--zipCode > #dfc-item--address-content-form--zipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dfc-item--address-content-form--zipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d373f35f-f843-4f5d-90ac-52b22fe0880e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>(min === 0 &amp;&amp; validity.badInput) &amp;&amp; (  value='');</value>
      <webElementGuid>3ac83930-7d08-4b39-866c-fdac790555a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dfc-item--address-content-form--zipCode</value>
      <webElementGuid>ab3418ed-bba1-4815-9d4b-51b83160edae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>ea399e11-6393-4179-8c57-f8f15a16032d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip code</value>
      <webElementGuid>1a8aedc5-cdec-4899-b5bc-f04ee981a8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13a9197c-a30c-44e3-8815-e1a209bf4fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>78457ff0-9457-4bfe-99f6-1b84ea6ff44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfc-root--address-content-form--zipCode&quot;)/div[@id=&quot;dfc-item--address-content-form--zipCode&quot;]/input[@id=&quot;dfc-item--address-content-form--zipCode&quot;]</value>
      <webElementGuid>7ebde136-a2ca-412f-ae30-1813fd869382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dfc-item--address-content-form--zipCode']</value>
      <webElementGuid>6686b508-54b3-41a4-8ea6-71d287c9c893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dfc-item--address-content-form--zipCode']/input</value>
      <webElementGuid>119ab65b-522a-4fd9-a618-fbf0a9c33602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-unit-form-details/div/mf-dynamic-form/div/form/div/div[2]/div/div/df-form-control[13]/div/div/input</value>
      <webElementGuid>bccd5cb3-3be3-4e1c-8595-2d6405bbbdd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dfc-item--address-content-form--zipCode' and @name = 'zipCode' and @placeholder = 'Zip code' and @type = 'text']</value>
      <webElementGuid>945a7bb4-d4e0-4dfb-86b6-6bf8a8b8ccd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
